### ISSUE TITLE
Hang in shm/test_ucp_tag_xfer.generic_unexp/0

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#1002]
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2455/console
```
15:04:31 [       OK ] shm/test_ucp_tag_xfer.generic_unexp/0 (2211 ms)
15:04:31 [ RUN      ] shm/test_ucp_tag_xfer.contig_exp_sync/0
15:04:31 [     INFO ] 0 79x10^1 25x10^2 7x10^3 3x10^4 3x10^5 3x10^6 3x10^7 
16:17:15 make: *** [test_valgrind] Killed
16:17:15 Build step 'Execute shell' marked build as failure
16:17:15 TAP Reports Processing: START
16:17:15 Looking for TAP results report in workspace using pattern: **/*.tap
16:17:15 Saving reports...
```

**Comment by brminich** [comment]
Another similar hang:
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1801/label=hpc-test-node/console
10:36:40 [ RUN      ] shm/test_ucp_tag_xfer.generic_exp_sync/0
10:36:40 [     INFO ] 0 1581x10^1 500x10^2 158x10^3 50x10^4 15x10^5 5x10^6 3x10^7 

Managed to reproduce locally (just once thogh:( ). The hang is somewhere in disconnect/request test flow.

(gdb) bt
#0  0x00007ffff6b97213 in pthread_spin_lock () from /usr/lib64/libpthread.so.0
#1  0x00007ffff571c9ae in mlx5_poll_cq_1 () from /usr/lib64/libmlx5-rdmav2.so
#2  0x00007ffff783e7d7 in ibv_poll_cq (wc=0x7fffffffd740, num_entries=<optimized out>, cq=<optimized out>) at /usr/include/infiniband/verbs.h:1361
#3  uct_ib_poll_cq (wcs=0x7fffffffd740, count=<synthetic pointer>, cq=<optimized out>) at /labhome/mikhailb/wgit/ucx-tmp/src/uct/ib/base/ib_device.h:239
#4  uct_rc_verbs_iface_poll_tx (iface=0x2cee740) at ib/rc/verbs/rc_verbs_iface.c:72
#5  uct_rc_verbs_iface_progress (arg=0x2cee740) at ib/rc/verbs/rc_verbs_iface.c:96
#6  0x00007ffff782cd1e in ucs_callbackq_dispatch (cbq=0x2ced128, cbq=0x2ced128) at /labhome/mikhailb/wgit/ucx-tmp/src/ucs/datastruct/callbackq.h:263
#7  uct_worker_progress (worker=0x2ced120) at base/uct_md.c:229
#8  0x00007ffff73e8b78 in ucp_worker_progress (worker=worker@entry=0x2cd8aa0) at core/ucp_worker.c:550
#9  0x00007ffff73e4d78 in ucp_ep_destroy (ep=<optimized out>) at core/ucp_ep.c:495
#10 0x000000000059bb97 in release (this=0x2c4ded0) at ./common/test_helpers.h:291
#11 reset (this=0x2c4ded0) at ./common/test_helpers.h:249
#12 ucp_test_base::entity::disconnect (this=0x2c4dea0) at ucp/ucp_test.cc:280
#13 0x000000000057069c in test_ucp_tag::cleanup (this=0x2c4ddc0) at ucp/test_ucp_tag.cc:39
#14 0x0000000000465cb9 in ucs::test_base::TearDownProxy (this=0x2c4ddc0) at common/test.cc:122
#15 0x000000000045af63 in HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x69eec5 "TearDown()", method=<optimized out>, object=<optimized out>) at common/gtest-all.cc:3562
#16 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=object@entry=0x2c4de18, method=<optimized out>, location=location@entry=0x69eec5 "TearDown()") at common/gtest-all.cc:3598
#17 0x000000000044ef5c in testing::Test::Run (this=this@entry=0x2c4de18) at common/gtest-all.cc:3643
#18 0x000000000044f05c in testing::TestInfo::Run (this=0x2bbb580) at common/gtest-all.cc:3812
#19 0x000000000044f1bf in testing::TestCase::Run (this=0x2bada80) at common/gtest-all.cc:3930
#20 0x0000000000453cd7 in testing::internal::UnitTestImpl::RunAllTests (this=this@entry=0x2989760) at common/gtest-all.cc:5802
#21 0x0000000000453fdb in RunAllTests (this=0x2989760) at common/gtest-all.cc:5719
#22 HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=<optimized out>, method=<optimized out>, object=0x2989760) at common/gtest-all.cc:3562
#23 HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=0x6a02b8 "auxiliary test code (environments or event listeners)",
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x453f20 <testing::internal::UnitTestImpl::RunAllTests()>, object=0x2989760) at common/gtest-all.cc:3598
#24 testing::UnitTest::Run (this=<optimized out>) at common/gtest-all.cc:5416
#25 0x000000000040df72 in RUN_ALL_TESTS () at common/gtest.h:20058
#26 main (argc=1, argv=<optimized out>) at common/main.cc:79

**Comment by yosefe** [comment]
need to change all tests to do disconnect in parallel (as i did for some wireup tests) by non-blocking disconnect, and progress all entities.
