### ISSUE TITLE
Is there a way to pre-allocate memory pools in UCX?

### ISSUE THREAD

**Issue by supunkamburugamuve** [openucx/ucx#10097]
We are looking to pre-allocate memory in UCX bounce buffer pools. We are using GPU sends that are allocated from cudaasync memory. UCX uses an internal memory pool as a bounce buffer. Because of the way GPU memory is managed, sometimes UCX pools can fail to allocate at runtime, mainly due to fragmentation. 

We can deal with the main GPU memory allocation failures. But because UCX pools are out of control for us it is hard to deal with it when those allocations fail. It would be ideal if there were a mechanism to pre-allocate these pools.

**Comment by supunkamburugamuve** [comment]
Closing issue.

**Comment by yosefe** [comment]
To follow up, currently pre-allocated memory pools are not supported, but it's something we have considered for future releases.
