### ISSUE TITLE
ERROR mlx5_0: both WC and NC_DEDICATED UAR allocation types  are not supported

### ISSUE THREAD

**Issue by tonycurtis** [openucx/ucx#10180]
### Describe the bug

After building UCX @ github recently started getting errors as in subject line.  Adding `--without-devx`clears them up.

### Steps to Reproduce
- Command line

```
mpirun -n 2 ./a.out
```

- UCX version used (from github branch XX or release YY) + UCX configure flags (can be checked by `ucx_info -v`)

```
# Library version: 1.18.0
# Library path: /lustre/projects/ucx-group/opt/ucx/gcc/git/lib/libucs.so.0
# API headers version: 1.18.0
# Git branch 'master', revision 21c1594
# Configured with: --prefix=/lustre/projects/ucx-group/opt/ucx/gcc/git --with-knem=/opt/knem-1.1.4.90mlnx1 --with-xpmem=/opt/xpmem --enable-cma --without-java --without-go --enable-mt --enable-logging --enable-optimizations --with-valgrind --enable-builtin-memcpy --enable-frame-pointer
```

- **Any UCX environment variables used**

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
   - `cat /etc/issue` or `cat /etc/redhat-release` + `uname -a`

```
fj-debug1[1](~/mpi) cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
fj-debug1[1](~/mpi) uname -a
Linux login1 4.18.0-305.25.1.el8_4.aarch64 #1 SMP Tue Nov 2 21:37:36 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
``
- For RDMA/IB/RoCE related issues:
    - Driver version:
        - `rpm -q rdma-core` or `rpm -q libibverbs`

rdma-core-56mlnx40-56103.versatushpc.aarch64

        - or: MLNX_OFED version `ofed_info -s`
   - HW information from `ibstat` or `ibv_devinfo -vv` command

```
CA 'mlx5_0'
        CA type: MT4123
        Number of ports: 1
        Firmware version: 20.27.2008
        Hardware version: 0
        Node GUID: 0x0c42a103002f436e
        System image GUID: 0x0c42a103002f436e
        Port 1:
                State: Active
                Physical state: LinkUp
                Rate: 100
                Base lid: 110
                LMC: 0
                SM lid: 3
                Capability mask: 0x2651e848
                Port GUID: 0x0c42a103002f436e
                Link layer: InfiniBand
```

**Comment by michal-shalev** [comment]
Hi @tonycurtis, can you please send a log file?
Also, which OFED version are you using? Can you please run `ofed_info -s` and `ofed_info -b` and send the output?

**Comment by tonycurtis** [comment]
[ucxlog.txt](https://github.com/user-attachments/files/17131055/ucxlog.txt)

```
fj-debug1[1](~/mpi) ofed_info -s
MLNX_OFED_LINUX-5.6-1.0.3.3:
```

```
fj-debug1[1](~/mpi) ofed_info -b
Usage: /usr/bin/ofed_info [options]

Options:
    -s       Show package name and version number.
    -n       Show numerical version number only.
    -l       List installed packages details (Default option).
```

`dmesg` has nothing since August

**Comment by michal-shalev** [comment]
@tonycurtis Could you please update OFED and check if the issue persists? 
Additionally, would it be possible for us to gain access to this setup for further debugging?"

**Comment by tonycurtis** [comment]
Here's the relevant parts from configure:

```
checking whether mlx5dv_init_obj is declared... yes
checking whether mlx5dv_create_qp is declared... yes
checking whether mlx5dv_is_supported is declared... yes
checking whether mlx5dv_devx_subscribe_devx_event is declared... yes
checking whether MLX5DV_CQ_INIT_ATTR_MASK_COMPRESSED_CQE is declared... yes
checking whether MLX5DV_CQ_INIT_ATTR_MASK_CQE_SIZE is declared... yes
checking whether MLX5DV_QP_CREATE_ALLOW_SCATTER_TO_CQE is declared... yes
checking whether MLX5DV_UAR_ALLOC_TYPE_BF is declared... yes
checking whether MLX5DV_UAR_ALLOC_TYPE_NC_DEDICATED is declared... no
checking whether mlx5dv_devx_umem_reg_ex is declared... yes
checking for struct mlx5dv_cq.cq_uar... yes
checking whether MLX5DV_OBJ_AH is declared... yes
checking whether MLX5DV_DCTYPE_DCT is declared... yes
checking whether ibv_alloc_td is declared... yes
checking whether MLX5DV_CONTEXT_FLAGS_DEVX is declared... yes
checking whether IBV_LINK_LAYER_INFINIBAND is declared... yes
checking whether IBV_LINK_LAYER_ETHERNET is declared... yes
checking whether IBV_EVENT_GID_CHANGE is declared... yes
```

**Comment by michal-shalev** [comment]
Hi @tonycurtis,
Could you please explain how we can gain access to the Ookami system? 
Also, could you share why updating OFED is not possible on your side?

**Comment by tonycurtis** [comment]
https://access-ci.org/ookami-joins-the-pack/

Can't update because no root access and admins have no plans to update anything at the moment.

**Comment by gleon99** [comment]
@tonycurtis we need SSH access to the nodes to research the issue. How can we get that?
Anyway, our final conclusion might be that using devx with that OFED won't be possible.

**Comment by yosefe** [comment]
IMO we should reduce the log level of "both WC and NC_DEDICATED UAR allocation types are not supported" from ERROR to DIAG/DEBUG, and let UCX disable DevX automatically in this case.

**Comment by tonycurtis** [comment]
Sounds good to me.

**Comment by michal-shalev** [comment]
Hi @tonycurtis @yosefe @artemry-nv 
Following this discussion:
https://github.com/openucx/ucx/pull/10187

**Comment by artemry-nv** [comment]
CC @Artemy-Mellanox
