### ISSUE TITLE
CQ size error

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#1019]
if ud_mlx5 is enabled you get ab error:
```
[1475102411.803692] [softiron-3:22825:0]        ud_mlx5.c:655  UCX  ERROR TX CQE size (128) is not 64
```

**Comment by shamisp** [comment]
I think you missed  ud_mlx5 in #1017

**Comment by yosefe** [comment]
yes, i missed it.
@shamisp can you please also add here the change request regarding overriding MLX5_CQE_SIZE?
Specifically - should we fail if it's already defined, and too small?

**Comment by shamisp** [comment]
Couple of other issue to consider:
* How do we handle the case with pre-defined MLX5_CQE_SIZE. This is something that OFED documentation recommends to do. Moreover on ARM systems with 64B cache line you pretty much have to do it.
* How do we handle the fact that 64 may conflict with inl configuration ?

**Comment by yosefe** [comment]
@shamisp i suggest the following:
if (MLX5_CQE_SIZE is defined) {
  if (large_enough_for_inl) {
    use it
  } else {
    error("invalid value for MLX5_CQE_SIZE ... ")
} else {
  MLX5_CQE_SIZE=max( inl, cache_line)
}

Also, on 64B ARM systems, it's not really needed to set the CQE size to 64b, 128b will also work and the performance difference should be very small.

**Comment by shamisp** [comment]
Sounds very reasonable
