### ISSUE TITLE
Does the UCX support Nividia PXN without extra path when using NVSwitch?

### ISSUE THREAD

**Issue by MoFHeka** [openucx/ucx#10293]
PXN path shown as below:
![message-path-gpu-gpu3](https://github.com/user-attachments/assets/9624b2de-50ff-478b-b520-58155a0c1bf4)

https://developer.nvidia.com/blog/doubling-all2all-performance-with-nvidia-collective-communication-library-2-12/

**Comment by brminich** [comment]
No, UCX currently does not support PXN-like transfers

**Comment by MoFHeka** [comment]
So if I want to implement all-to-all collective communication I better use NCCL?

**Comment by brminich** [comment]
If you assume it will be run in a configuration that benefits from PXN, then yes.
