### ISSUE TITLE
Why ucp_put_nbx/ucp_get-nbx does not support sgl buffer

### ISSUE THREAD

**Issue by super-train** [openucx/ucx#10314]
Hello everyone, I have a question now. Can anyone help me？

When I use ucp_put_nbx or ucp_get-nbx in ucx to perform unilateral operations with rdma, I find that these two interfaces in ucx only support contiguous memory,
Ucp_put_nbx : can only send continuous memory data from the local end;
Ucp_get_nbx : can only receive remote data into continuous local memory;
Why do both interfaces require that the local address must be continuous,

According to the IB specification of RDMA, unilateral operations do not simply require that the destination address be continuous

My current requirement is how to use the UCX interface to perform unilateral operations using RDMA, as the local addresses are discrete 4k pages

Why does the ucp_tag_send_nbx interface support data of type ucp_dt_iov_t * iov

Looking forward to everyone's answers, thank you!

**Comment by super-train** [comment]
@

**Comment by yosefe** [comment]
To follow up on this, UCX supports SGL for ucp_put_nbx and ucp_get_nbx, 
for instance, the following unit test is testing that: 
https://github.com/openucx/ucx/blob/ea791611c02c1e692155ffc936c58fbf189d47fc/test/gtest/ucp/test_ucp_rma.cc#L57
