### ISSUE TITLE
UCX triggers on dummy messages

### ISSUE THREAD

**Issue by vkocheganov** [openucx/ucx#1062]
Two threads on client side: 1st is polling on input messages; 2nd is doing send_tag_nb(…) + progress-loop next to send_tag_nb(…).
After triggering on UCX file descriptor 1st thread makes arm and then progress/probe for messages. 

Piece of polling thread logic:

```
1.  Create UCX Worker()
2.  Arm worker
3.  While (1) {
    a.  epoll_wait(ucx epfd, blocking)
    aa. Arm worker
    b.  do {
        i.  worker_progress()
        ii. msg = probe()
        iii.    if (msg) msg_recv(msg)
    c.  } while (msg);
    d.  goto EPOLL_WAIT
4. }
```

Probe() call often returns NULL, after UCX fd was triggered on event. 

Often means about 700 000 times per second, while about 300 messages of size 1M were sent using UCX during this particular second (using `UCX_TLS=rc UCX_IB_ETH_PAUSE_ON=y UCX_RNDV_THRESH=10000000` parameters).

Setting less granularity of bcopy via `UCX_MAX_BCOPY=500000` fixes this behavior (though is slower).

**Comment by shamisp** [comment]
@yosefe - it wakes up on each completion, right ?

**Comment by yosefe** [comment]
@shamisp no, sometimes it's coalesced. we are investigating this.

**Comment by vkocheganov** [comment]
FYI

There is a big difference (comparing to above case) in placing UCX arm like this:
```
1.  Create UCX Worker()
2.  Arm worker
3.  While (1) {
    a.  epoll_wait(ucx epfd, blocking)
    b.  do {
        i.  worker_progress()
        ii. msg = probe()
        iii.    if (msg) msg_recv(msg) // receive the entire message (2 megabytes for example)
        iv. Arm worker
    c.  } while (msg);
    d.  goto EPOLL_WAIT
4. }
```
In this particular case CPU usage rises up to 98% on customers benchmark for big messages. I believe that the main cause is significant rise in number of dummy messages UCX triggers on. CPU usage when UCX arm placed before second cycle is about 50%. **2 times difference in CPU usage**.

I think it becomes more and more important to make UCX arm logic be more transparent for user, since such simple cases (I described in this comment) can have very dramatic result.

**Comment by vkocheganov** [comment]
By advice of @yosefe  and @shssf I tried following.

In the file `ucx/src/ucp/core/ucp_worker.c` removed `UCT_WAKEUP_TX_COMPLETION` flag in `uct_wakeup_open` call like this:
```
228        status = uct_wakeup_open(iface,
229                                 // UCT_WAKEUP_TX_COMPLETION |
230                                 UCT_WAKEUP_RX_AM |
231                                 UCT_WAKEUP_RX_SIGNALED_AM,
232                                 &wakeup);
```
As I understand this makes worker skip arming of send queue. After these changes **number of dummy messages significantly reduced**. Now there are only 2 or 4 dummy messages in a second. This is very-very good. Thanks.

Following questions still remain:

1. Is there any way to pass control under mentioned flags from UCT to UCP level?
2. Do you have any idea about what type of dummy messages still makes epoll_wait trigger?
