### ISSUE TITLE
hang in the verifier test (task=coll) with rc

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1076]
The following hang was obsereved with 128 ranks but can also be reproduced with 64.
- ompi master branch
- np=64. 8 hosts. ppn=8
- passes with UCX_TLS=dc
- passes with '-mca spml ikrit -mca pml yalla -x MXM_TLS=rc' and 128 ranks
- may be related to https://github.com/openucx/ucx/issues/994

To reproduce:
/hpc/mtr_scrap/users/mtt/scratch/shmem/20161021_030432_32395_103303_vegas08/installs/QOLr/install/bin/oshrun -np 64 -bind-to core -mca btl_openib_warn_default_gid_prefix 0 -display-map -x SHMEM_SYMMETRIC_HEAP_SIZE=128M -mca sshmem_verbs_hca_name mlx5_0:1 -mca btl_openib_if_include mlx5_0:1 -x MXM_RDMA_PORTS=mlx5_0:1 -x UCX_SHM_DEVICES=all -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_ACC_DEVICES=all -mca scoll basic -mca coll_hcoll_enable 0 -mca spml ucx -mca pml ucx -x UCX_TLS=rc --map-by node --mca scoll_basic_barrier_alg 3 --mca scoll_basic_broadcast_alg 0 --mca scoll_basic_collect_alg 2 --mca scoll_basic_reduce_alg 1 /hpc/mtr_scrap/users/mtt/scratch/shmem/20161021_030432_32395_103303_vegas08/installs/QOLr/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour -o5 --task=coll

```
OpenSHMEM Verification Tool ver."1.2.39"
**********************************
* Log file: none
* Host: vegas10
* Output level: 5
* Log level: 0
**********************************

[trace] te..: #00 TEST SUITE: coll (Run oshmem_test COLLECTIVE Transfer test suite.)
[trace] te..: #00 TEST CASE: broadcast32 (shmem_broadcast32(): Copy a data object to a target location on all PEs of the active set.)
[trace] tc..: #00 ...TC: broadcast32 TI #1 result: PASS
[trace] tc..: #00 ...TC: broadcast32 TI #2 result: PASS
[trace] tc..: #00 ...TC: broadcast32 TI #3 result: PASS
[trace] tc..: #00 ...TC: broadcast32 TI #4 result: PASS
[trace] tc..: #00 ...TC: broadcast32 TI #5 result: PASS
[trace] tc..: #00 ...TC: broadcast32 TI #6 result: PASS
[trace] tc..: #00 ...TC: broadcast32 TI #7 result: PASS
PASS   coll       broadcast32    shmem_broadcast32(): Copy a data object to a target location on all PEs of the active set.
[trace] te..: #00 Memory Usage (MB):    before: 71 resident: 1  after: 830 resident: 318        difference: +758 resident: +316
[trace] te..: #00 TEST SUITE: coll (Run oshmem_test COLLECTIVE Transfer test suite.)
[trace] te..: #00 TEST CASE: broadcast64 (shmem_broadcast64(): Copy a data object to a target location on all PEs of the active set.)
[trace] tc..: #00 ...TC: broadcast64 TI #1 result: PASS
[trace] tc..: #00 ...TC: broadcast64 TI #2 result: PASS
[trace] tc..: #00 ...TC: broadcast64 TI #3 result: PASS
[trace] tc..: #00 ...TC: broadcast64 TI #4 result: PASS
[trace] tc..: #00 ...TC: broadcast64 TI #5 result: PASS
[trace] tc..: #00 ...TC: broadcast64 TI #6 result: PASS
<hang>
```

http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/shmem/20161021_030432_32395_103303_vegas08/html/test_stdout_zKmT1m.txt

**Comment by alex-mikheev** [comment]
Fixed in https://github.com/open-mpi/ompi/pull/2452
