### ISSUE TITLE
Failed to receive EP address due to pmix_base_collect_data

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1119]
Setting the pmix_base_collect_data parameter to 0 (which isn't the default in ompi v2.x) makes pml ucx fail with the folliwing errors:

```
Sun Nov 27 16:45:01 2016[1,25]<stddiag>:[vegas26:10897] pml_ucx.c:112 Error: Failed to receive EP address
Sun Nov 27 16:45:01 2016[1,25]<stddiag>:[vegas26:10897] pml_ucx.c:252 Error: Failed to receive worker address from proc: 27
```

The command line to reproduce is (may need to run a few times until it reproduces) :

/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20161127_120011_3151_105938_vegas07/installs/5iml/install/bin/mpirun -np 32 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_SHM_DEVICES=all -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_ACC_DEVICES=all -mca coll_hcoll_enable 0 -x UCX_TLS=dc --map-by node -mca pmix_base_collect_data 0 /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20161127_120011_3151_105938_vegas07/installs/5iml/tests/osu_micro_benchmark/osu-micro-benchmarks-5.0/mpi/collective/osu_allreduce

http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20161127_120011_3151_105938_vegas07/html/test_stdout_RwXy8B.txt

Setting this parameter to 1 makes the test pass.
This reproduces with other benchmarks as well. 

From ompi_info:
MCA pmix base: parameter "pmix_base_collect_data" (current value: "true", data source: default, level: 9 dev/all, type: bool)
Collect all data during modex
Valid values: 0: f|false|disabled|no, 1: t|true|enabled|yes

Open MPI: 2.0.2a1

**Comment by yosefe** [comment]
@artpol84

**Comment by artpol84** [comment]
I think that this is related to the problem that I was tracking from last Tuesday: https://github.com/open-mpi/ompi/pull/2461.

It appears that in case of simultaneous `OOB/tcp` connections there might be a race condition leading to a loss of messages. With direct modex enabled those events are highly likely. In this case some of the direct modex requests are dropped and I was seeing exactly the same picture.

**Comment by artpol84** [comment]
I wonder what algorithm was used, I bet it was `ompi_coll_base_allreduce_intra_recursivedoubling()` as in my case. I'll check it.

**Comment by artpol84** [comment]
Indeed for (at least) 1-byte messages 32-proc allreduce turns into the recursive doubling:
```
(gdb) s
ompi_coll_base_allreduce_intra_recursivedoubling (sbuf=0x7fffe805f000, rbuf=0x7fffd8041000, count=1, dtype=0x6091a0 <ompi_mpi_float>,
    op=0x608980 <ompi_mpi_op_sum>, comm=0x608380 <ompi_mpi_comm_world>, module=0xb60ee0)
    at /labhome/artemp/mtr_scrap/OMPI/2016_11_02_OSHMEM_PMIx/sources/ompi/ompi/mca/coll/base/coll_base_allreduce.c:137
137         char *tmpsend = NULL, *tmprecv = NULL, *tmpswap = NULL, *inplacebuf_free = NULL, *inplacebuf;
(gdb) bt
#0  ompi_coll_base_allreduce_intra_recursivedoubling (sbuf=0x7fffe805f000, rbuf=0x7fffd8041000, count=1, dtype=0x6091a0 <ompi_mpi_float>,
    op=0x608980 <ompi_mpi_op_sum>, comm=0x608380 <ompi_mpi_comm_world>, module=0xb60ee0)
    at /labhome/artemp/mtr_scrap/OMPI/2016_11_02_OSHMEM_PMIx/sources/ompi/ompi/mca/coll/base/coll_base_allreduce.c:137
#1  0x00007fffdb5a8d81 in ompi_coll_tuned_allreduce_intra_dec_fixed (sbuf=0x7fffe805f000, rbuf=0x7fffd8041000, count=1,
    dtype=0x6091a0 <ompi_mpi_float>, op=0x608980 <ompi_mpi_op_sum>, comm=0x608380 <ompi_mpi_comm_world>, module=0xb60ee0)
    at /labhome/artemp/mtr_scrap/OMPI/2016_11_02_OSHMEM_PMIx/sources/ompi/ompi/mca/coll/tuned/coll_tuned_decision_fixed.c:66
#2  0x00007ffff77cc785 in PMPI_Allreduce (sendbuf=0x7fffe805f000, recvbuf=0x7fffd8041000, count=1, datatype=0x6091a0 <ompi_mpi_float>,
    op=0x608980 <ompi_mpi_op_sum>, comm=0x608380 <ompi_mpi_comm_world>) at pallreduce.c:107
#3  0x0000000000401d76 in main (argc=1, argv=0x7fffffffcc08) at osu_allreduce.c:103
```

So it is 99,99% the same problem as  open-mpi/ompi#2461.

**Comment by yosefe** [comment]
waiting for open-mpi/ompi#2477 to merge
