### ISSUE TITLE
mpi_test_suite hang at large scale

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1124]
There is a hang on the mpi_test_suite test when running with the IB transports.

Currently doesn't reproduce on a much smaller scale.

/hpc/local/benchmarks/hpcx_install_Wednesday/hpcx-gcc-redhat7.2/ompi-v2.x/bin/mpirun -np 512 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_SHM_DEVICES=all -x UCX_NET_DEVICES=mlx5_2:1 -x UCX_ACC_DEVICES=all -mca coll_hcoll_enable 0 -x UCX_TLS=ud -mca opal_pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 --map-by node /hpc/scrap/users/mtt/scratch/ucx_ompi/20161125_135850_5895_59251_clx-orion-001/installs/aWGw/tests/mpi-test-suite/ompi-tests/mpi_test_suite/mpi_test_suite -x relaxed -t 'All,^One-sided,^IO,^Environment' -n 300

```
Tue Nov 29 13:28:33 2016[1,0]<stdout>:P2P tests Many-to-one (19/44), comm Halved MPI_COMM_WORLD (6/14), type MPI_SHORT_INT (18/28)
Tue Nov 29 13:28:33 2016[1,0]<stdout>:P2P tests Many-to-one (19/44), comm Halved MPI_COMM_WORLD (6/14), type MPI_2INT (19/28)
Tue Nov 29 13:28:33 2016[1,0]<stdout>:P2P tests Many-to-one (19/44), comm Halved MPI_COMM_WORLD (6/14), type MPI_LONG_DOUBLE_INT (20/28)
Tue Nov 29 13:28:33 2016[1,0]<stdout>:P2P tests Many-to-one (19/44), comm Halved MPI_COMM_WORLD (6/14), type MPI_CONTIGUOUS_INT (21/28)
Tue Nov 29 13:28:34 2016[1,0]<stdout>:P2P tests Many-to-one (19/44), comm Halved MPI_COMM_WORLD (6/14), type MPI_VECTOR_INT (22/28)
Tue Nov 29 13:28:34 2016[1,0]<stdout>:P2P tests Many-to-one (19/44), comm Halved MPI_COMM_WORLD (6/14), type MPI_HVECTOR_INT (23/28)
...hang...
```

ud, rc, rc_x and dc hang.
dc_x fails with 2 ranks on:
```
Tue Nov 29 13:35:20 2016[1,0]<stderr>:[clx-orion-001:4927 :0] ud_mlx5_common.c:63   Assertion `grh_av != NULL' failed
Tue Nov 29 13:35:20 2016[1,1]<stderr>:[clx-orion-002:17407:0] ud_mlx5_common.c:63   Assertion `grh_av != NULL' failed
```
http://e2e-gw.mellanox.com:4080/hpc/scrap/users/mtt/scratch/ucx_ompi/20161125_135850_5895_59251_clx-orion-001/html/test_stdout_qGgucO.txt

ompi v2.x

**Comment by yosefe** [comment]
happens because rx buffers (limit=64k) run out
need to make them inf. by default, and add warning if they run out.
