### ISSUE TITLE
Error on QP with dc_x with the verifier test

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1151]
To reproduce:

env OMPI_MCA_btl_openib_warn_default_gid_prefix=0 SHMEM_SYMMETRIC_HEAP_SIZE=5985M OMPI_MCA_sshmem_verbs_hca_name=mlx5_2:1 OMPI_MCA_btl_openib_if_include=mlx5_2:1 MXM_RDMA_PORTS=mlx5_2:1 UCX_SHM_DEVICES=all UCX_NET_DEVICES=mlx5_2:1 UCX_ACC_DEVICES=all OMPI_MCA_sshmem=sysv OMPI_MCA_spml_ucx_heap_reg_nb=1 OMPI_MCA_scoll=basic OMPI_MCA_coll_hcoll_enable=0 OMPI_MCA_spml=ucx OMPI_MCA_pml=ucx UCX_IB_ADDR_TYPE=ib_local UCX_TLS=dc_x srun --cpu_bind=core -m cyclic --mpi=pmix_v1 -n 1344 --nodes=48 -p orion /hpc/scrap/users/mtt/scratch/shmem/20161209_125323_25502_62195_clx-orion-001/installs/t70_/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour --task=atomic

[1481282983.796568] [clx-orion-001:6134 :0]    ib_mlx5_log.c:111  UCX  FATAL Error on QP 0x1590d wqe[43850]: Local QP operation (synd 0x2 vend 0x68) opcode MASKED_COMPARE_SWAP
==== backtrace ====
0 0x000000000001d87c uct_ib_mlx5_completion_with_err()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/ib/mlx5/ib_mlx5_log.c:109
1 0x000000000001e458 uct_ib_mlx5_check_completion()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/ib/mlx5/ib_mlx5.c:211
2 0x000000000002bbd1 uct_dc_mlx5_poll_tx()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/ib/mlx5/ib_mlx5.inl:32
3 0x000000000002bbd1 uct_dc_mlx5_iface_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/ib/dc/accel/dc_mlx5.c:537
4 0x0000000000016cfe ucs_callbackq_dispatch()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucs/datastruct/callbackq.h:264
5 0x0000000000016cfe uct_worker_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/base/uct_md.c:229
6 0x000000000000c4cd ucp_worker_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/core/ucp_worker.c:603
7 0x000000000000c4cd ucs_async_check_miss()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucs/async/async.h:135
8 0x000000000000c4cd ucp_worker_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/core/ucp_worker.c:604
9 0x0000000000006c5d ucp_atomic_swap32()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/amo/basic_amo.c:115
10 0x0000000000001649 mca_atomic_ucx_cswap()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/oshmem/mca/atomic/ucx/atomic_ucx_cswap.c:37
11 0x000000000004c1e6 pshmem_float_swap()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/oshmem/shmem/c/profile/pshmem_swap.c:64
12 0x0000000000409de5 test_item3()  /hpc/scrap/users/mtt/scratch/shmem/20161209_125323_25502_62195_clx-orion-001/installs/t70_/tests/verifier/tests-mellanox.git/verifier/atomic/osh_atomic_tc5.c:223
13 0x0000000000409de5 osh_atomic_tc5()  /hpc/scrap/users/mtt/scratch/shmem/20161209_125323_25502_62195_clx-orion-001/installs/t70_/tests/verifier/tests-mellanox.git/verifier/atomic/osh_atomic_tc5.c:61
14 0x0000000000406439 __do_exec()  /hpc/scrap/users/mtt/scratch/shmem/20161209_125323_25502_62195_clx-orion-001/installs/t70_/tests/verifier/tests-mellanox.git/verifier/osh_exec.c:283
15 0x0000000000406439 proc_mode_exec()  /hpc/scrap/users/mtt/scratch/shmem/20161209_125323_25502_62195_clx-orion-001/installs/t70_/tests/verifier/tests-mellanox.git/verifier/osh_exec.c:124
16 0x00000000004050be main()  /hpc/scrap/users/mtt/scratch/shmem/20161209_125323_25502_62195_clx-orion-001/installs/t70_/tests/verifier/tests-mellanox.git/verifier/osh_main.c:138
17 0x0000000000021b15 __libc_start_main()  ??:0
18 0x00000000004052d1 _start()  ??:0

http://e2e-gw.mellanox.com:4080/hpc/scrap/users/mtt/scratch/shmem/20161209_125323_25502_62195_clx-orion-001/html/test_stdout_bjuHP6.txt

**Comment by yosefe** [comment]
Fixed, not a UCX issue.
