### ISSUE TITLE
hang on the atest test

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1165]
There is a hang which happens on the atest test with two hosts, ppn=16.
This didn't reproduce on a lower scale.
The last argument to the exec (1000) is the number of iterations and lowering it to 200 makes the test pass.
Hangs on all IB transports.

Command line to reproduce:

$/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20161216_111242_24017_107325_vegas10/installs/Zu5O/install/bin/mpirun -np 32 -H vegas08,vegas11 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_SHM_DEVICES=all -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_ACC_DEVICES=all -mca coll_hcoll_enable 0 -x UCX_IB_ADDR_TYPE=ib_local -x UCX_TLS=rc_x -mca opal_pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20161216_111242_24017_107325_vegas10/installs/Zu5O/tests/atest/atest.git/src/atest -l 1000

**Comment by alinask** [comment]
An updated command line:

 /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20170127_153023_18953_111703_vegas06/installs/AYyv/install/bin/mpirun -np 144 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_SHM_DEVICES=all -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_ACC_DEVICES=all -mca btl_openib_if_include mlx5_0:1 -mca coll_hcoll_enable 0 -x UCX_IB_ADDR_TYPE=ib_local -x UCX_TLS=dc,mm -mca opal_pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20170127_153023_18953_111703_vegas06/installs/AYyv/tests/atest/atest.git/src/atest -l 1000

**Comment by yosefe** [comment]
the test takes a very long time to run, lots (~400k) unexpected message in the test-cross phase.
collectives phase takes ~1hr.

**Comment by yosefe** [comment]
running test-cross completes after 6.3 hours
probably need to optimize tag lookup "scalable tag matching"

**Comment by yosefe** [comment]
passed on [MTT](http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20170218_023419_9884_112868_vegas07) after disabling cross test. 
closing this, will be addressed further by #1147
