### ISSUE TITLE
Failure in  ud/test_ud.connect_iface_sim/1 test

### ISSUE THREAD

**Issue by brminich** [openucx/ucx#1182]
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/505/label=master/console

00:31:40 [ RUN      ] ud/test_ud.connect_iface_sim/1
00:31:40 /var/lib/jenkins/jobs/gh-ucx-pr__NEW/workspace/label/master/contrib/../test/gtest/uct/test_ud.cc:610: Failure
00:31:40 Value of: ep(m_e1)->dest_ep_id
00:31:40   Actual: 16777215
00:31:40 Expected: 0U
00:31:40 Which is: 0

According to the actual value, the root cause is that m_e1 ep had not received neither CONN_REQ nor CONN_REPLY from m_e2 ep. It is worth to increase progression time in the test, like it is done in connect_iface_sim2v2 test.

**Comment by brminich** [comment]
One more UD failure 
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2478/label=hpc-test-node2/console

02:08:27 [ RUN      ] ud/test_ud.crep_ack_drop/0
02:08:28 /scrap/jenkins/scrap/workspace/hpc-ucx-pr/label/hpc-test-node2/contrib/../test/gtest/uct/test_ud.cc:376: Failure
02:08:28 Value of: ep(m_e2, 0)->rx.ooo_pkts.head_sn
02:08:28   Actual: 2
02:08:28 Expected: 3u
02:08:28 Which is: 3

The root cause seem to bound to double CREP/CREQ loss. 500 sec timer is enough for one retransmit only

**Comment by alinask** [comment]
One more:

19:10:13 [ RUN      ] ud/test_ud.crep_drop2/0
19:10:13 /scrap/jenkins/scrap/workspace/hpc-ucx-pr-2/label/hpc-test-node2/contrib/../test/gtest/uct/test_ud.cc:353: Failure
19:10:13 Value of: ep(m_e1, 0)->tx.acked_psn
19:10:13   Actual: 0
19:10:13 Expected: 1
19:10:13 /scrap/jenkins/scrap/workspace/hpc-ucx-pr-2/label/hpc-test-node2/contrib/../test/gtest/uct/test_ud.cc:354: Failure
19:10:13 Value of: ep(m_e1, 0)->tx.psn
19:10:13   Actual: 2
19:10:13 Expected: 3
19:10:13 /scrap/jenkins/scrap/workspace/hpc-ucx-pr-2/label/hpc-test-node2/contrib/../test/gtest/uct/test_ud.cc:355: Failure
19:10:13 Value of: ep(m_e2, 0)->tx.acked_psn
19:10:13   Actual: 0
19:10:13 Expected: 1
19:10:13 /scrap/jenkins/scrap/workspace/hpc-ucx-pr-2/label/hpc-test-node2/contrib/../test/gtest/uct/test_ud.cc:356: Failure
19:10:13 Value of: ep(m_e2, 0)->tx.psn
19:10:13   Actual: 2
19:10:13 Expected: 3
19:10:14 
[  FAILED  ] ud/test_ud.crep_drop2/0, where GetParam() = ud/mlx5_1:1 (263 ms)

http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2488/label=hpc-test-node2/consoleFull
