### ISSUE TITLE
failure in test_ucp_tag_xfer.cc

### ISSUE THREAD

**Issue by brminich** [openucx/ucx#1224]
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr__NEW/624/label=master/consoleFull

9:31:29 [ RUN      ] cmrcx/test_ucp_tag_stats.sync_unexpected/0
19:31:30 /var/lib/jenkins/jobs/gh-ucx-pr__NEW/workspace/label/master/contrib/../test/gtest/ucp/test_ucp_tag_xfer.cc:741: Failure
19:31:30 Expected: (cnt) > (0ul), actual: 0 vs 0

**Comment by brminich** [comment]
When test_run_xfer is invoked with expected false, it does not guarantee that the message will not be expected. It just make a try to send it unexpectedly. 
So unexpected stats tests needs to be corrected.

**Comment by yosefe** [comment]
@brminich so maybe instead of short_progress_loop() in do_xfer(), should wait until unexpected queue is not empty?

**Comment by brminich** [comment]
@yosefe, yes this sounds good, just need to test carefully this change (as it would affect many unit tests)

**Comment by brminich** [comment]
Reproduced here:
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/3144/consoleFull


21:29:03 [ RUN      ] cmrcx/test_ucp_tag_stats.eager_unexpected/0
21:29:04 /var/lib/jenkins/jobs/gh-ucx-pr/workspace/contrib/../test/gtest/ucp/test_ucp_tag_xfer.cc:718: Failure
21:29:04 Expected: (cnt) > (0ul), actual: 0 vs 0
21:29:04 [  FAILED  ] cmrcx/test_ucp_tag_stats.eager_unexpected/0, where GetParam() = \cm,\rc_mlx5 (318 ms)

**Comment by brminich** [comment]
Reporduced here:
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1011/label=master,worker=1/console

22:09:43 [----------] 1 test from cmrcx/test_ucp_tag_stats
22:09:43 [ RUN      ] cmrcx/test_ucp_tag_stats.sync_unexpected/0
22:09:43 /var/lib/jenkins/jobs/gh-ucx-pr/workspace/label/master/worker/1/contrib/../test/gtest/ucp/test_ucp_tag_xfer.cc:881: Failure
22:09:43 Expected: (cnt) > (0ul), actual: 0 vs 0
22:09:44 [  FAILED  ] cmrcx/test_ucp_tag_stats.sync_unexpected/0, where GetParam() = \cm,\rc_mlx5 (442 ms)
22:09:44 [----------] 1 test from cmrcx/test_ucp_tag_stats (442 ms total)
