### ISSUE TITLE
PERF: Parameters handling for ucx_perftest

### ISSUE THREAD

**Issue by shssf** [openucx/ucx#1247]
Currently, the `ucx_perftest` application could use many parameters in batch mode (from files with `-b` command line key). The procedure of these parameters handling assumes accumulative nature. It means that if you don't use a parameter in new line, the value of it might be default one or **previous one** from previous input parameters line.
Example (start the server):
```
ucx_perftest -d mlx5_0:1 -b ./msg_sizes -x rc -t tag_lat -D iov
```
The file msg_sizes:
```
1  -s 0,0,1    -n 200000 -i 8192
2  -s 0,0,2    -n 200000 -i 8192
4  -s 1,1,2    -n 200000 -i 8192
8  -s 2,2,4    -n 200000
16 -s 5,5,6    -n 200000
32 -s 10,10,12 -n 200000
```
The last three lines will be treated as it uses `-i 8192` because previous lines use the parameter.

Also, some parameters has no influence on UCP part of the test.
For example, parameter `-x` above do nothing with UCP part of the test. To limit transports in `ucx_perftest` (UCP part) we have to set `UCX_TLS=rc_x`.
Perhaps it is better to implement setenv() (or kind of it) to align the test user expectations from command line keys.

**Comment by yosefe** [comment]
fixed in perftest run_recurs
