### ISSUE TITLE
long delay/hang in dcx/test_ucp_tag_xfer.iov_exp_sync/0 test

### ISSUE THREAD

**Issue by brminich** [openucx/ucx#1271]
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2765/label=hpc-test-node2/consoleFull#-853622487b816df86-9afc-46eb-984f-1a9a125d73bb

15:12:15 [ RUN      ] dcx/test_ucp_tag_xfer.iov_exp_sync/0
15:12:**15** [     INFO ] 0 79x10^1 25x10^2 7x10^3 3x10^4 3x10^5 3x10^6 3x10^7 make: *** [test_valgrind] Killed
15:12:**30** 
Build step 'Execute shell' marked build as failure
15:12:30 TAP Reports Processing: START
15:12:30 Looking for TAP results report in workspace using pattern: **/*.tap

**Comment by yosefe** [comment]
seems like 5 seconds.. is that considered long?

**Comment by brminich** [comment]
not sure:). Isn't it?
