### ISSUE TITLE
Reverted functionality in hello example

### ISSUE THREAD

**Issue by artpol84** [openucx/ucx#1286]
I think that in https://github.com/openucx/ucx/blob/master/test/examples/ucp_hello_world.c#L467 it should be negation.
Example works anyway, but it looks confusing (at least to me).

**Comment by artpol84** [comment]
Also I've noticed that in OMPI field mask parameter is passed to ucp_init:
https://github.com/open-mpi/ompi/blob/master/ompi/mca/pml/ucx/pml_ucx.c#L133

while there is no such parameter in the hello example which causes following message:
```
ucp_context.c:633  UCX  WARN  empty features set passed to ucp context create
```

**Comment by shssf** [comment]
@artpol84 The variable `server` contains server name string (`char*`). If this variable isn't empty - it means it is client environment. I changed the variable name to avoid confusion.
The second issue - good catch, thank you! Uninitialized variables is always headache

**Comment by artpol84** [comment]
I know about server being a string , I propose to check like 
'NULL == server'
This will emphasize on the string (not binary) nature of server variable which won't be confusing.

**Comment by shssf** [comment]
@yosefe If you approve this I will implement (as I remember it slightly broke UCS code style)
