### ISSUE TITLE
hang on rc in alltoall (IMB) on a large scale

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1288]
To reproduce:

/hpc/local/benchmarks/hpcx_install_Friday/hpcx-gcc-redhat7.2/ompi-v2.x/bin/mpirun -np 2176 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_SHM_DEVICES=all -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_ACC_DEVICES=all -mca btl_openib_if_include mlx5_0:1 -mca coll_hcoll_enable 0 -x UCX_IB_ADDR_TYPE=ib_local -x UCX_TLS=rc,sm -mca opal_pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 --map-by node /hpc/scrap/users/mtt/scratch/ucx_ompi/20170129_173032_2740_79198_clx-hercules-008/installs/A81E/tests/imb/IMB.git/src/IMB-MPI1 -npmin 2176 -iter 1000 -mem 0.9 alltoall

```
Mon Jan 30 14:27:21 2017[1,0]<stdout>:# List of Benchmarks to run:
Mon Jan 30 14:27:21 2017[1,0]<stdout>:
Mon Jan 30 14:27:21 2017[1,0]<stdout>:# Alltoall
Mon Jan 30 14:27:26 2017[1,0]<stdout>:
Mon Jan 30 14:27:26 2017[1,0]<stdout>:#----------------------------------------------------------------
Mon Jan 30 14:27:26 2017[1,0]<stdout>:# Benchmarking Alltoall
Mon Jan 30 14:27:26 2017[1,0]<stdout>:# #processes = 2176
Mon Jan 30 14:27:26 2017[1,0]<stdout>:#----------------------------------------------------------------
Mon Jan 30 14:27:26 2017[1,0]<stdout>:       #bytes #repetitions  t_min[usec]  t_max[usec]  t_avg[usec]
Mon Jan 30 14:27:26 2017[1,0]<stdout>:            0         1000         0.01         0.01         0.01
Mon Jan 30 14:27:27 2017[1,0]<stdout>:            1         1000       593.02       593.48       593.18
Mon Jan 30 14:27:29 2017[1,0]<stdout>:            2         1000       735.83       736.48       736.06
Mon Jan 30 14:27:31 2017[1,0]<stdout>:            4         1000      1186.80      1188.45      1187.18
Mon Jan 30 14:27:34 2017[1,0]<stdout>:            8         1000      2146.08      2148.03      2146.79
Mon Jan 30 14:27:39 2017[1,0]<stdout>:           16         1000      4376.13      4379.25      4377.38
Mon Jan 30 14:27:49 2017[1,0]<stdout>:           32         1000      9181.33      9187.75      9183.88
Mon Jan 30 14:28:00 2017[1,0]<stdout>:           64          439     21497.17     21526.90     21507.86
Mon Jan 30 14:28:11 2017[1,0]<stdout>:          128          179     55358.18     55449.86     55389.85
Mon Jan 30 14:28:16 2017[1,0]<stdout>:          256           12    308789.56    318762.57    313841.50
Mon Jan 30 14:28:21 2017[1,0]<stdout>:          512           12    336763.56    354012.24    346662.89
<...hang...>
```

This is 68 hosts with ppn=32.
The entire run passes with ud and dc (separately) (all IMB benchmarks, not only alltoall).
With rc, the hang can be reproduced when running only alltoall. (passes with np=1000).

**Comment by alex-mikheev** [comment]
I was able to reproduce it on 48 nodes ppn=32

It happens because we run out of TX buffers.  After setting UCX_RC_VERBS_TX_MAX_BUFS=-1 the test completes. The reason why we run out of TX bufs  is TX moderation. Basically there are many connections below the moderation threshold. As a result all tx buf are used but no completions are coming in.

Setting UCX_RC_VERBS_TX_CQ_MODERATION=1 also makes the test pass.

**Comment by alex-mikheev** [comment]
As a workaround UCX_IB_TX_MAX_BUFS=-1 is set to -1. An adapaptive cq moderation  for rc will be developed in the future.
