### ISSUE TITLE
Occasional deadlock in final flush for uct mm endpoints

### ISSUE THREAD

**Issue by LenaO** [openucx/ucx#1304]
In mpich, we detected a occasional (around every 25th run) deadlock in some of our collective tests (with around 10 processes on a shared memory machine). After some deeper analysis I think the problem is in UCX and not in mpich.

I tracked down deadlock to `uct_mm_ep_flush`, which returns `UCS_ERR_NO_RESOURCE` forever.

A deeper analysis brings be to the `uct_mm_progress_fifo_tail` function 

 ``` 
static inline void uct_mm_progress_fifo_tail(uct_mm_iface_t *iface)
{
    /* don't progress the tail every time - release in batches. improves performance */
    if (iface->read_index & iface->fifo_release_factor_mask) {
        return;
    }

    iface->recv_fifo_ctl->tail = iface->read_index;
}
```

Removing the if-condion, solves the problem with the deadlock (but, of course, slows down the performance) -  so I guess a problem here is that (in the last flush) the tail is not updated.

**Comment by yosefe** [comment]
thanks Lena, do you have a command line to reproduce it?
in theory the fact that tail update is once/release_factor, should not make the sender go *completely* out of resources

**Comment by LenaO** [comment]
Hello Yossi,
I will try to find a simple case to reproduce it - at the moment I see it occasionally in some collective tests in mpich (mainly allgather or allgatherv). 
For the moment - I printed out the values for the tail in the case I ran into the deadlock: (hex-numbers), maybe this helps, too. 

```ep->fifo_ctl->head: 0x340 ep->cached_tail: 0x300  iface->read_index: 0x3d6  iface->fifo_release_factor_mask: 0x1f iface->config.fifo_size: 0x40```

**Comment by yosefe** [comment]
@LenaO can you please check if the following fixes the issue:
```
diff --git a/src/uct/sm/mm/mm_iface.c b/src/uct/sm/mm/mm_iface.c
index 85b3805..29e2603 100644
--- a/src/uct/sm/mm/mm_iface.c
+++ b/src/uct/sm/mm/mm_iface.c
@@ -265,11 +265,9 @@ static inline void uct_mm_iface_poll_fifo(uct_mm_iface_t *iface)
 
         /* raise the read_index. */
         iface->read_index++;
-    } else {
-       /* progress the tail when there is nothing to read
-        * to improve latency of receiving a message */
-       uct_mm_progress_fifo_tail(iface);
     }
+
+    uct_mm_progress_fifo_tail(iface);
 }
 
 void uct_mm_iface_progress(void *arg)
```

**Comment by LenaO** [comment]
@yosefe 
Seems to work, I run my test for >1500 Iterations without a deadlock
