### ISSUE TITLE
compile error using arm's gcc

### ISSUE THREAD

**Issue by janjust** [openucx/ucx#1382]
Using ARM-hpc-compiler v1.1

Caveat, I'm running RHEL7.3

> $  gcc --version
> gcc (ARM) 6.1.0
> Copyright (C) 2016 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> $  which gcc
> /opt/arm/gcc-6.1.0_Generic-AArch64_RHEL-7.2_aarch64-linux/bin/gcc

Error:

> make[2]: Entering directory `/hpc/mtr_scrap/users/tomislavj/workspace/arm-workspace/ucx/src/tools/perf'
>   CC       libucxperf_la-libperf.lo
>   CXX      libucxperf_la-uct_tests.lo
> In file included from /labhome/tomislavj/arm-workspace/ucx/src/ucs/sys/math.h:16:0,
>                  from libperf.h:19,
>                  from libperf_int.h:12,
>                  from uct_tests.cc:9:
> /opt/arm/gcc-6.1.0_Generic-AArch64_RHEL-7.2_aarch64-linux/include/c++/6.1.0/math.h:66:12: error: ‘constexpr bool std::isnan(double)’ conflicts with a previous declaration
>  using std::isnan;
>             ^~~~~
> In file included from /usr/include/features.h:375:0,
>                  from /usr/include/sys/uio.h:22,
>                  from libperf.h:16,
>                  from libperf_int.h:12,
>                  from uct_tests.cc:9:
> /usr/include/bits/mathcalls.h:235:1: note: previous declaration ‘int isnan(double)’
>  __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
>  ^
> make[2]: *** [libucxperf_la-uct_tests.lo] Error 1
>

**Comment by gwl-arm** [comment]
Hi janjust,

We are aware of this issue and have a fix ready for our next release of the ARM C/C++ Compiler. A workaround is to pass "-D_GLIBCXX_HAVE_OBSOLETE_ISNAN=1" to your compiler. Depending on the build system, this can usually be achieved by adding it to the CXXFLAGS or CFLAGS environment variable.

Regards,
- George

**Comment by shamisp** [comment]
Tagging @gwl-arm

**Comment by janjust** [comment]
@gwl-arm Thanks!
@shamisp @yosefe This fixes the issue.

**Comment by shamisp** [comment]
Since this is a temporary issue my suggestion it to update the wiki installation page with the workaround.

**Comment by janjust** [comment]
just fyi, need to set CPPFLAGS during config.

**Comment by janjust** [comment]
That, and remember libz needs to be compiled with the same compiler, otherwise it'll fail to find it.

**Comment by shamisp** [comment]
Can you please copy-n-past the command line and I will update the wiki

**Comment by janjust** [comment]
./autogen.sh && ./contrib/configure-release --prefix=$PWD/install CPPFLAGS="-D_GLIBCXX_HAVE_OBSOLETE_ISNAN=1" CFLAGS="-I<path-to>/zlib-1.2.11/install/lib/include" LDFLAGS="-L<path-to>/zlib-1.2.11/install/lib" && make --quiet -j 8 && make install

**Comment by shamisp** [comment]
Hmm, probably you can remove CFLAGS="-I/zlib-1.2.11/install/lib/include" LDFLAGS="-L/zlib-1.2.11/install/lib"

**Comment by janjust** [comment]
then you'll get a config error.

**Comment by shamisp** [comment]
But "-D_GLIBCXX_HAVE_OBSOLETE_ISNAN=1" was supposed to resolve it ? I guess I'm missing something

**Comment by janjust** [comment]
Sorry I misspoke earlier about config.

2 different issues:
1st.
You need zlib compiled with arm's compiler otherwise you'll get a linker failure at: libucm.la (I didn't open an issue for this)

2nd.
You must configure with ISNAN flag otherwise perf will fail to compile.

If you give the correct zlib and the flag, everything is fine.

**Comment by shamisp** [comment]
So the 2nd was solved with workaround proposed by @gwl-arm .

The 1st "solution" looks like a hack, since you already have zlib installed in the deafult system and still you have to create your own copy. @gwl-arm please let me know if it looks familiar.

@janjust can you dump the log for zlib failure. Please double check that you have both RPM and RPM-dev installed. 
Thanks !

**Comment by janjust** [comment]
ah!..Yup, missing -devel pacakge

**Comment by janjust** [comment]
hey, yum search didn't show any differences between arm and x86 machines for zlib...

**Comment by shamisp** [comment]
Does it run now with 
```
./autogen.sh && ./contrib/configure-release --prefix=$PWD/install CPPFLAGS="-D_GLIBCXX_HAVE_OBSOLETE_ISNAN=1" && make --quiet -j 8 && make install
```

**Comment by janjust** [comment]
Yes, like clockwork.

**Comment by shamisp** [comment]
BTW RHEL73 for ARMv8 and x86 is not *exactly* the same (packages and kernels might be a bit different).

**Comment by shamisp** [comment]
Updated https://github.com/openucx/ucx/wiki/OpenMPI-and-OpenSHMEM-installation-with-UCX#ucx-with-arm-hpc-compiler-v11

**Comment by shamisp** [comment]
@gwl-arm For the arm compiler package do we need to add an explicit dependency (with rpm spec) for zlib-devel so it brings (or requires) it automatically ?

**Comment by shamisp** [comment]
@janjust - can you please check the master.  #1401 supposed to fix the zlib issue.

**Comment by janjust** [comment]
@shamisp :+1: Fixed
