### ISSUE TITLE
Timeout in  rc_mlx5/test_uct_ep.disconnect_after_send/0

### ISSUE THREAD

**Issue by alex-mikheev** [openucx/ucx#1389]
53:53 [----------] 1 test from rc_mlx5/test_uct_ep
10:53:53 [ RUN      ] rc_mlx5/test_uct_ep.disconnect_after_send/0
14:08:36 Build timed out (after 200 minutes). Marking the build as failed.
14:08:36 Build was aborted

**Comment by hoopoepg** [comment]
reproduced on RC
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6466/label=hpc-test-node3,worker=3/consoleFull#-853622487b816df86-9afc-46eb-984f-1a9a125d73bb

```
15:02:02 [----------] 1 test from rc/test_uct_ep
15:02:02 [ RUN      ] rc/test_uct_ep.disconnect_after_send/1
17:41:21 
make: *** [test] Terminated
17:41:21 
Build step 'Execute shell' marked build as failure
```
