### ISSUE TITLE
improve perf estimation on RoCE

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#1390]
currently rc_mlx5 bandwidth estimation for 40G RoCE is ~15% lower than actual
need to close the gap in calculation.

**Comment by eladpe** [comment]
show speed on eth port with rc: `UCX_IB_ETH_PAUSE_ON=y ucx_info -t rc_mlx5 -d `
measure bw: `mpirun -np 2 -mca btl tcp,sm,self --map-by node ./src/tools/perf/ucx_perftest -t tag_bw -s 4000000 -n 10000 -w 0`

**Comment by yosefe** [comment]
hostname: r-aa-fatty25
