### ISSUE TITLE
Assertion in udrcx/test_ucp_tag_xfer.iov_exp_truncated/1

### ISSUE THREAD

**Issue by brminich** [openucx/ucx#1538]
Happens in:
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/label=hpc-test-node2,worker=2/3655/consoleFull

12:11:22 [     INFO ] 0 1581x10^1 500x10^2 158x10^3 50x10^4 15x10^5 5x10^6 [hpc-test-node2:11583:0]        rndv.c:379  Assertion `rreq->recv.length != 0' failed

The problem is related to handling of truncated case. It is possible that RNDV RTS message arrives while receiver waits for 0-byte message.  It should be handled ok rather than having an assert.
The problem is most probably a rare case in jenkins testing, because the buffer lengths are random (calculated in test_ucp_tag_xfer::test_xfer).

**Comment by yosefe** [comment]
looks like the assertion should be removed
