### ISSUE TITLE
Document that ucp_rmem_ptr isn't implemented

### ISSUE THREAD

**Issue by stormmq** [openucx/ucx#1582]
I've just spent an hour puzzling why I can't use it...

If the intention is to eventually support the function `ucp_rmem_ptr`, then, perhaps:-

- implement it and return the `ucs_status_t` equivalent of `ENOSYS` for now;
- remove it from the documentation for now
- mark it in big, bold bright letters in the documentation that it isn't implemented

If it should be deprecated, then perhaps implement it to always fail and annotate it as deprecated.

**Comment by shamisp** [comment]
@yosefe I guess we added it for OpenSHMEM and have never had time to implement it, even so we have all the infrastructure in place

**Comment by yosefe** [comment]
duplicates #346

**Comment by shamisp** [comment]
Adding @bbenton 
Shell we remove it and then restore back once we have implementation ?

**Comment by bbenton** [comment]
Yes, I think removing it from the documentation until it's implemented will reduce confusion.
Are there any other documented functions that are not implemented?

**Comment by shamisp** [comment]
@yosefe - what is your take on this ? 
Remove in order to avoid the confusion and restore later on once we have the implementation ready ?

The alternative is to document it explicitly as a not-implemented in UCP.

**Comment by yosefe** [comment]
i think it would be better to remove

**Comment by shamisp** [comment]
Okay. I think we also should remove it for v1.2

**Comment by stormmq** [comment]
OK. I'll adjust my code (a Rust binding for UCX).
