### ISSUE TITLE
v1.2.0 tarball missing configure

### ISSUE THREAD

**Issue by abouteiller** [openucx/ucx#1621]
The tarball does not contain configure. 
One needs to run the autogen, which is not "usual" for a distribution package. 
Running autogen outside of a git repo spits out error messages (see below)

The severity of the issue is low (one can compile the package at the end). 

```
[build@saturn ucx-1.2.0]$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config/m4
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
...
```

**Comment by yosefe** [comment]
@shamisp we need to upload tarball which was created by "make dist"

**Comment by miked-mellanox** [comment]
IMO we should provide src.rpm and tarball as release files.

**Comment by shamisp** [comment]
Agreed. As for now the tarball is auto-generated by github. I have to check if there is a way to overwrite the tarballs. As an alternative, we can upload files to openucx.org

**Comment by yosefe** [comment]
@shamisp here is a configured tarball
[ucx-1.2.2947.tar.gz](https://github.com/openucx/ucx/files/1087586/ucx-1.2.2947.tar.gz)

**Comment by yosefe** [comment]
Added the src.rpm and tarball to https://github.com/openucx/ucx/releases/tag/v1.2.0

**Comment by shamisp** [comment]
Can we rename the fi

**Comment by yosefe** [comment]
fixed
