### ISSUE TITLE
madvise for THP, occasionally returns error

### ISSUE THREAD

**Issue by eladpe** [openucx/ucx#1634]
madvise API that direct the THP behaviour, returns error from time to time. when it happens it can be noticed throughout the entire job run.
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1960

14:34:30 [ RUN      ] shm/test_ucp_wireup.disconnect_nonexistent/1
14:34:30 [1498390470.329132] [jenkins03:4970 :0]        uct_mem.c:151  UCX  ERROR madvise failure status (-1) address(0x3a00000) len(2097152): Invalid argument
14:34:30 [1498390470.391302] [jenkins03:4970 :0]        uct_mem.c:151  UCX  ERROR madvise failure status (-1) address(0x3a00000) len(2097152): Invalid argument
14:34:30 [1498390470.432866] [jenkins03:4970 :0]        uct_mem.c:151  UCX  ERROR madvise failure status (-1) address(0x3a00000) len(2097152): Invalid argument
14:34:30 [1498390470.495591] [jenkins03:4970 :0]        uct_mem.c:151  UCX  ERROR madvise failure status (-1) address(0x3a00000) len(2097152): Invalid argument
14:34:30 [       OK ] shm/test_ucp_wireup.disconnect_nonexistent/1 (662 ms)

**Comment by yosefe** [comment]
fixed by #1636
