### ISSUE TITLE
MLNX OFED should not install UCX into /opt/ucx blindly

### ISSUE THREAD

**Issue by byronyi** [openucx/ucx#1651]
On some platform `/opt` is a shared folder mounted over NFS, and concurrent installations on multiple machines of OFED will fail as `/opt/ucx` is not empty.

**Comment by yosefe** [comment]
agree, we should make the prefix /usr/local by default.
@shamisp @miked-mellanox @alinask pls comment as well

**Comment by miked-mellanox** [comment]
+1, we should have a way to override it from rpmbuild cmd line

**Comment by byronyi** [comment]
For the record I am using Debian right now, so it would be great if you could make it work with all the deb package rules.

**Comment by shamisp** [comment]
@byronyi - yes, we need to add deb support.

**Comment by shamisp** [comment]
👍

**Comment by shamisp** [comment]
@byronyi - It seems the we have the debian rules file and all the rest. 
Do you any particular changes that we have to apply ?

**Comment by byronyi** [comment]
Thanks! You guys are awesome. Can't wait to upgrade to next OFED release (it would be great if you guys could support both Debian and Ubuntu 😄).
