### ISSUE TITLE
1.2.0 distribution tarball

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#1656]
1. The tarball name is ucx-1.2.0 but when it is unpacked it is still ucx-1.2.2947
2. The make dist does not include files from ```doc/doxygen ``` that are used for ```make docs```. Probably we should distribute all files under docs.

**Comment by shamisp** [comment]
UCX doxygen version has to be changed from 1.2 to 1.2.x as the rest of the code

**Comment by shamisp** [comment]
@yosefe I think this one was addressed ?

**Comment by yosefe** [comment]
it was not

**Comment by yosefe** [comment]
ucx version in docs is now auto-generated
