### ISSUE TITLE
enable-debug flag is broken

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1666]
When compiling UCX with the --enable-debug flag, seems that after the following commit, the O2 flag is added (instead of O0) in the makefiles which creates optimizations and therefore eliminates the purpose of this flag. 

```
commit 0e65a305b6e159dffe1c394cd82674e3e17217f1
Merge: 5ec7d9d ceb9cfa
Author: Pavel Shamis / Pasha <shamisp@users.noreply.github.com>
Date:   Mon Jun 5 09:31:24 2017 -0500
 
    Merge pull request #1555 from MattBBaker/topic/configure-cflags
 
    CONFIGURE: Bring in CFLAGS (v1.3) 
```

@MattBBaker Could you please take a look?

**Comment by MattBBaker** [comment]
I'm trying to find where this magic happens. None of the M4 macros sets CFLAGS itself, so it seems like this comes from autotools. Probably a knob that needs to be adjusted in autoconf, though I don't know which. A short term solution is to set CFLAGS="" with --enable-debug.

**Comment by MattBBaker** [comment]
Found it. The macro AC_PROG_CC will set '-O2 -g' in CFLAGS if no user CFLAGS is specified. It should be a quick fix, according to manual adding ': ${CFLAGS=""}' after AC_INIT and before AC_PROG_CC will fix this.
https://www.gnu.org/software/autoconf/manual/autoconf.html

**Comment by MattBBaker** [comment]
Yea, seems dumb. I'll get a PR up later today.

**Comment by alinask** [comment]
@MattBBaker Is this issue fixed? Can we close this?

**Comment by MattBBaker** [comment]
It's in a state of "Works for me". Does the update work for everyone else?

**Comment by alinask** [comment]
Looks like it works for me as well.
Thanks @MattBBaker for fixing this!
