### ISSUE TITLE
failure in dc*/test_uct_event_fd.am 

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1686]
14:24:43 [----------] 1 test from dc_mlx5/test_uct_event_fd
14:24:43 [ RUN      ] dc_mlx5/test_uct_event_fd.am/0
14:24:43 [1499599483.332486] [jenkins03:5408 :0]          dc_ep.c:44   UCX  WARN  ep (0x3273160) is destroyed with 2 outstanding ops
14:24:43 /var/lib/jenkins/jobs/gh-ucx-pr/workspace-4/label/master/worker/3/contrib/../test/gtest/common/test.cc:212: Failure
14:24:43 Failed
14:24:43 Got 1 warnings during the test
14:24:43 [  FAILED  ] dc_mlx5/test_uct_event_fd.am/0, where GetParam() = dc_mlx5/mlx5_0:1 (319 ms)
14:24:43 [----------] 1 test from dc_mlx5/test_uct_event_fd (319 ms total)

http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2092/label=master,worker=3/consoleFull

**Comment by evgeny-leksikov** [comment]
The same for DC:
13:48:24 [----------] 1 test from dc/test_uct_event_fd
13:48:24 [ RUN      ] dc/test_uct_event_fd.am/0
13:48:26 [1499597304.892695] [jenkins03:11642:2]          dc_ep.c:44   UCX  WARN  ep (0x318e550) is destroyed with 1 outstanding ops
13:48:26 /var/lib/jenkins/jobs/gh-ucx-pr/workspace-2/label/master/worker/2/contrib/../test/gtest/common/test.cc:212: Failure
13:48:26 Failed
13:48:26 Got 1 warnings during the test
13:48:26 [  FAILED  ] dc/test_uct_event_fd.am/0, where GetParam() = dc/mlx5_0:1 (1758 ms)
13:48:26 [----------] 1 test from dc/test_uct_event_fd (1758 ms total)
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2090/label=master,worker=2/consoleFull
