### ISSUE TITLE
CFLAGS overwriting by UCX

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#1696]
```
AS_IF([test "x$enable_debug" == xyes],
        [BASE_CFLAGS="-O0 -D_DEBUG $BASE_CFLAGS"],
        [BASE_CFLAGS="-O3 $BASE_CFLAGS"])

```

This a horrible aide force "-Ox" flags from configure script.

**Comment by shamisp** [comment]
@yosefe Are you okay to remove all "-Ox" flags from configure 
I think it is bad idea to have it.

**Comment by hoopoepg** [comment]
added separate option to set optimization level
@yosefe what about close this request?
