### ISSUE TITLE
uct_ib_iface_query() does not recognize 50 Gbit eth speed

### ISSUE THREAD

**Issue by alex-mikheev** [openucx/ucx#1813]
ib_iface.c:749  UCX  ERROR Invalid active_speed on mlx5_0:1: 64
also the function should either return void or callers must check its return value...

**Comment by yosefe** [comment]
@alex-mikheev on which setup did you see 50gbit eth?

**Comment by alex-mikheev** [comment]
clx-zeus-101/clx-zeus-102
