### ISSUE TITLE
[mtt] Error Endpoint timeout was not handled (Eth)

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#1878]
Configuration:
```
MOFED: MLNX_OFED_LINUX-4.1-1.0.2.0
Run details: num_nodes=8 ppn=32(x8)
```

The issue doesn't reproduce with `pml=yalla`.

### osu_micro_benchmark_collective
Full log: http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20170928_023134_28351_10153_clx-orion-049/html/test_stdout_fQvES6.txt

Cmd:
`mpirun -np 2 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output -mca pml ucx -x UCX_NET_DEVICES=mlx5_2:1 -mca btl_openib_if_include mlx5_2:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -x UCX_TLS=ud,sm --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20170928_023134_28351_10153_clx-orion-049/installs/ZTf3/tests/osu_micro_benchmark/osu-micro-benchmarks-5.3.2/mpi/collective/osu_bcast`

Output:
```
--------------------------------------------------------------------------
No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           clx-orion-016
  Local device:         mlx5_2
  Local port:           1
  CPCs attempted:       rdmacm, udcm
--------------------------------------------------------------------------
Thu Sep 28 20:35:50 2017[1,0]<stdout>:
Thu Sep 28 20:35:50 2017[1,0]<stdout>:# OSU MPI Broadcast Latency Test v5.3.2
Thu Sep 28 20:35:50 2017[1,0]<stdout>:# Size       Avg Latency(us)
[mngx-orion-01:18125] 1 more process has sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[mngx-orion-01:18125] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Thu Sep 28 20:40:54 2017[1,0]<stdout>:[1506620454.744787] [clx-orion-016:29714:0]     ucp_worker.c:373  UCX  ERROR Error Endpoint timeout was not handled for ep 0xb2ba40
[clx-orion-016:29714] *** An error occurred in MPI_Bcast
[clx-orion-016:29714] *** reported by process [2534277121,0]
[clx-orion-016:29714] *** on communicator MPI_COMM_WORLD
[clx-orion-016:29714] *** MPI_ERR_OTHER: known error not in list
[clx-orion-016:29714] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[clx-orion-016:29714] ***    and potentially your MPI job)
```

### ibm-tests
Full log: http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20170928_070744_13900_10175_clx-orion-001/html/test_stdout_M_KbQi.txt

Cmd (with `tls=rc`, original was `tls=ud`, behavior is the same):
`$mpirun -np 2 -mca btl_openib_warn_default_gid_prefix 0  --bind-to core --tag-output --timestamp-output -mca pml ucx -x UCX_NET_DEVICES=mlx5_2:1 -mca btl_openib_if_include mlx5_2:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -x UCX_TLS=rc,sm --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20170928_070744_13900_10175_clx-orion-001/installs/UwQp/tests/ibm-tests/ompi-tests/ibm/pt2pt/bsend_usempi`

Output:
```
--------------------------------------------------------------------------
No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           clx-orion-016
  Local device:         mlx5_2
  Local port:           1
  CPCs attempted:       rdmacm, udcm
--------------------------------------------------------------------------
[mngx-orion-01:24024] 1 more process has sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[mngx-orion-01:24024] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Thu Sep 28 21:04:26 2017[1,0]<stddiag>:[clx-orion-016:31121] pml_ucx.c:656 Error: ucx bsend failed: Endpoint timeout
Thu Sep 28 21:04:26 2017[1,0]<stddiag>:[clx-orion-016:31121] pml_ucx.c:750 Error: ucx send failed: No pending message
Thu Sep 28 21:04:26 2017[1,0]<stdout>:[1506621866.483795] [clx-orion-016:31121:0]     ucp_worker.c:373  UCX  ERROR Error Endpoint timeout was not handled for ep 0xb5bb10
[clx-orion-016:31121] *** An error occurred in MPI_Bsend
[clx-orion-016:31121] *** reported by process [2350579713,0]
[clx-orion-016:31121] *** on communicator MPI_COMM_WORLD
[clx-orion-016:31121] *** MPI_ERR_OTHER: known error not in list
[clx-orion-016:31121] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[clx-orion-016:31121] ***    and potentially your MPI job)
```

**Comment by brminich** [comment]
Have you tried to reproduce it? Did not manage to do that. Tried various nodes (including those printing the errors) in the loop

**Comment by amaslenn** [comment]
I did, it reproduced very well so I could reduce NP to 2 and it still reproduced.
Similar issue from today's reports: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/ucx_ompi/20171001_043715_27240_12120_clx-orion-033/html/test_stdout_lSwaqm.txt

**Comment by amaslenn** [comment]
The issue is host dependent, I couldn't reproduce issue from prev comment on random hosts, but it reproduces on the same hosts.
OFED is the same on these hosts:
```sh
pdsh -w "clx-orion-[033-036,061-064]" 'ofed_info | grep OFED-' | dshbak -c
----------------
clx-orion-[033-036,061-064]
----------------
MLNX_OFED_LINUX-4.1-4.1.1.0 (OFED-4.1-4.1.1):
```
But `fw_ver` is different:
```sh
pdsh -w "clx-orion-[033-036,061-064]" 'ibv_devinfo | grep fw_ver' | dshbak -c
----------------
clx-orion-[033-036,061-064]
----------------
        fw_ver:                         16.21.0106
        fw_ver:                         16.21.0106
        fw_ver:                         12.20.1010
        fw_ver:                         12.20.1010
        fw_ver:                         16.21.0106
        fw_ver:                         16.21.0106
```

**Comment by amaslenn** [comment]
Also on Hercules: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/ucx_ompi/20170929_185039_21064_11428_clx-hercules-001/html/test_stdout_N1Kngi.txt
Cmd:
`/hpc/local/benchmarks/hpcx_install_2017-09-29/hpcx-gcc-redhat7.2/ompi-v3.0.x/bin/mpirun -np 1472 -mca btl_openib_warn_default_gid_prefix 0 --debug-daemons --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1,mlx5_1:1 -mca btl_openib_if_include mlx5_0:1,mlx5_1:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -x UCX_TLS=dc,sm --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20170929_185039_21064_11428_clx-hercules-001/installs/6IXY/tests/mpich_tests/mpich-mellanox.git/test/mpi/coll/nbicreduce`

**Comment by brminich** [comment]
Lots of send errors there:
 dc_verbs.c:633  UCX  ERROR Send completion with error on qp 0x226c3: transport retry counter exceeded syndrome 0x81

**Comment by brminich** [comment]
The original issue can't be reproduced with GID_INDEX=3. The issue with dc transport (seen on mlx5_0 and mlx5_1) is most probably a different one, since it is IB and not ETH

**Comment by brminich** [comment]
BTW it hangs with MXM as well:
mpirun -np 16  -mca btl_openib_warn_default_gid_prefix 0 --debug-daemons --bind-to core --tag-output --timestamp-output --display-map -mca pml yalla  -mca btl_openib_if_include mlx5_2:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -x MXM_TLS=ud -x MXM_RDMA_PORTS=mlx5_2:1 --map-by node  /mnt/lustre/users/mtt/scratch/ucx_ompi/20171001_043715_27240_12120_clx-orion-033/installs/FGm0/tests/mpi-small-tests/hpc_tests.git/mpi/misc/ctxalloc 2 1500 100

**Comment by yosefe** [comment]
It happens when using nodes from different leaf switches. We have r-RoCE between the switches, so in order to make the dests pass need to use RoCEv2. Which means UCX_IB_GID_INDEX=3.
With UCX_IB_GID_INDEX=3, the test pass.
We will have OOB solution for this with rdma_cm.

**Comment by miked-mellanox** [comment]
btw, can we scan gid table and always prefer v2?
