### ISSUE TITLE
[mtt] Endpoint timeout was not handled (TLS UD and RC)

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#1881]
Configuration:
```
MOFED: MLNX_OFED_LINUX-4.1-1.0.2.0
OMPI: v3
Hercules x46 nodes
```

Full log: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/ucx_ompi/20170929_185039_21064_11428_clx-hercules-001/html/test_stdout_N1Kngi.txt

Min NP is 31 (originally 1472):
`mpirun -np 31 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1,mlx5_1:1 -mca btl_openib_if_include mlx5_0:1,mlx5_1:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -x UCX_TLS=rc,sm --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20170929_185039_21064_11428_clx-hercules-001/installs/6IXY/tests/mpich_tests/mpich-mellanox.git/test/mpi/coll/nbicreduce`

Output:
```
Sun Oct  1 17:18:44 2017[1,7]<stdout>:[1506867524.064665] [clx-hercules-012:26727:0]     ucp_worker.c:373  UCX  ERROR Error Endpoint timeout was not handled for ep 0xac1510
Sun Oct  1 17:18:44 2017[1,0]<stdout>:[1506867524.637551] [clx-hercules-005:9708 :0]     ucp_worker.c:373  UCX  ERROR Error Endpoint timeout was not handled for ep 0xaa7fa0
Sun Oct  1 17:18:44 2017[1,1]<stdout>:[1506867524.864649] [clx-hercules-006:13248:0]     ucp_worker.c:373  UCX  ERROR Error Endpoint timeout was not handled for ep 0xac1280
Sun Oct  1 17:18:45 2017[1,3]<stdout>:[1506867525.064597] [clx-hercules-008:23244:0]     ucp_worker.c:373  UCX  ERROR Error Endpoint timeout was not handled for ep 0xad2440
Sun Oct  1 17:18:45 2017[1,30]<stdout>:[1506867525.131602] [clx-hercules-065:1754 :0]     ucp_worker.c:373  UCX  ERROR Error Endpoint timeout was not handled for ep 0x9d1e00
```

**Comment by yosefe** [comment]
happened because of setup issue - mlx5_1 was not active on all hosts and mlx5_0,1 were on same subnet
