### ISSUE TITLE
[mtt] hang in several tests with UD/RC_X

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#1909]
Configuration:
```
MOFED: MLNX_OFED_LINUX-4.1-1.0.2.0
OMPI: v3.0.1a1
Hercules: x21 (clx-hercules-[017-018,020-031,050-053,055-057])
```

Detailed log: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/ucx_ompi/20171010_213802_5981_15968_clx-hercules-004/html/test_stdout_dB9fjE.txt

Cmd:
`mpirun -np 364 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output -mca pml ucx-x UCX_NET_DEVICES=mlx5_0:1,mlx5_2:1 -mca btl_openib_if_include mlx5_0:1,mlx5_2:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -x UCX_TLS=rc_x,sm --map-by node -x fca_mpi_fp_sum_forceorder=1 -x fca_mpi_collect_stats=y /mnt/lustre/users/mtt/scratch/ucx_ompi/20171010_213802_5981_15968_clx-hercules-004/installs/JQiG/tests/mpi-small-tests/hpc_tests.git/mpi/misc/fp_sum_test`

Output:
```
Thu Oct 12 10:51:30 2017[1,0]<stdout>:Iteration #0/100 started. Last result is -nan.
Thu Oct 12 10:51:30 2017[1,0]<stdout>:Iteration #1/100 started. Last result is 4084.000000.
```

Min NP can be different, in some cases it hangs with 361, in other NP should be greater.
Affected TLS: `ud` and `rc_x`.

MXM works:
`mpirun -np 362 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output -mca pml yalla -x MXM_RDMA_PORTS=mlx5_0:1,mlx5_2:1 -x UCX_NET_DEVICES=mlx5_0:1,mlx5_2:1 -mca btl_openib_if_include mlx5_0:1,mlx5_2:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -x UCX_TLS=rc_x,sm --map-by node -x fca_mpi_fp_sum_forceorder=1 -x fca_mpi_collect_stats=y /mnt/lustre/users/mtt/scratch/ucx_ompi/20171010_213802_5981_15968_clx-hercules-004/installs/JQiG/tests/mpi-small-tests/hpc_tests.git/mpi/misc/fp_sum_test`

**Comment by amaslenn** [comment]
## mpich_tests_mpi_comm
Orion: x40 (clx-hercules-[001,042,049-050,073,091-101,103-120,122-125,127-128])

Cmd (works OK with `NP=640`):
`mpirun -np 641 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1,mlx5_2:1 -mca btl_openib_if_include mlx5_0:1,mlx5_2:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -x UCX_TLS=ud,sm --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20171015_063922_22180_16827_clx-hercules-001/installs/z4Hw/tests/mpich_tests/mpich-mellanox.git/test/mpi/comm/icsplit`

Works with MXM. UCX + dc/rc also work well.

**Comment by amaslenn** [comment]
## atest
Hercules: x30 (clx-hercules-[001-005,007-008,017,019-021,023-026,029-032,036,038-046,048])
OMPI: 4.0.0a1

Original MTT: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/ucx_ompi/20171014_221929_3103_16763_clx-hercules-074/html/test_stdout_HxiVmD.txt

Cmd (works OK with `NP=480`):
`mpirun -np 481 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1,mlx5_2:1 -mca btl_openib_if_include mlx5_0:1,mlx5_2:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -mca osc ucx -x UCX_TLS=rc_x,sm --map-by node --mca pmix_server_max_wait 8 /mnt/lustre/users/mtt/scratch/ucx_ompi/20171014_221929_3103_16763_clx-hercules-074/installs/SlXf/tests/atest/atest.git/src/atest --test-correctness 1 -t 'Reduce-*-*' --test-cross 0 --test-maxcomm 0 --test-noise 0 --test-slow 0 --nnoise 1 --ncross 10 --slow-sleep 1 --nslow 10 --nmax 10 --test-cross 0`

MXM works, as well as UCX + dc/rc.

**Comment by yosefe** [comment]
is it MLNX_OFED 4.1 GA with Connect-X 5?
it may be possible that a newer driver version has to be used.
Can you try the W/A from https://redmine.mellanox.com/issues/1086254 ?

**Comment by amaslenn** [comment]
@yosefe it is `MLNX_OFED_LINUX-4.1-4.1.1.0`. `mlx5_0` is CX-4, `mlx5_2` is CX-5.
WA helps, I checked all mentioned here command lines, all passed.
