### ISSUE TITLE
how ucx collect the registered memory, which is call by ibv_post_send()?

### ISSUE THREAD

**Issue by tashanzhishi** [openucx/ucx#1925]
in src/uct/ib/rc/verbs/rc_verbs_iface.c
```cpp
static unsigned uct_rc_verbs_iface_progress(void *arg)
{
    uct_rc_verbs_iface_t *iface = arg;
    unsigned count;
    // handle recv_cq
    count = uct_rc_verbs_iface_poll_rx_common(&iface->super);
    if (count > 0) {
        return count;
    }
    // handle send_cq, if recv_cq no event, who call it? memory leak?
    return uct_rc_verbs_iface_poll_tx(iface);
}
```
in ucx, the iface->super->send_cq, recv_cq bind one comp_channel.
in above code, ucx call ibv_poll_cq(send_cq) when epoll_wait find EPOLLIN event, which wakeup by recv_cq. But ibv_post_send can't trigger EPOLLIN event. If one connection only ibv_post_send, how it collect the registered memory consumed by send?

**Comment by yosefe** [comment]
when sending zero-copy (user buffer), each post_send is sent as SIGNALED, which would generate comp_channel event and wake up epoll(EPOLLIN) as well. then it will report send completion to user, which is then allowed to reuse/release the memory.
Does that answer the question?

**Comment by tashanzhishi** [comment]
@yosefe thank you very much, you correct my wrong view.

**Comment by shamisp** [comment]
Can we close this issue ?

**Comment by tashanzhishi** [comment]
@shamisp ok, thanks
