### ISSUE TITLE
UD is selected for AM when running osu_latency on Orion with TLS=rc 

### ISSUE THREAD

**Issue by brminich** [openucx/ucx#1953]
Need to check why UD has better score than RC. 
CMD line:
`mpirun -np 2 --map-by node --bind-to core -mca rmaps_dist_device mlx5_0:1 -mca rmaps_base_mapping_policy dist:span -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1  --report-bindings -x UCX_RC_VERBS_TM_ENABLE=y  -x UCX_TLS=rc  ${HPCX_MPI_TESTS_DIR}/osu-micro-benchmarks-5.3.2/osu_latency`

**Comment by yosefe** [comment]
need to make it so UCX_TLS=rc would use ud only for auxiliary, so even on large scale, when ud is better, rc would still be used - since its user request
