### ISSUE TITLE
[mtt] hang in fp_sum_test

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#1962]
Configuration:
```
MOFED: MLNX_OFED_LINUX-4.1-1.0.2.0
OMPI: 3.0.1a1
Hercules x17 clx-hercules-[001-004,016-019,079-087]
```

MTT report: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/ucx_ompi/20171101_013007_12661_21259_clx-hercules-001/html/test_stdout_kstczm.txt

Cmd:
Load module: `module load hpcx-gcc`
`mpirun -np 273 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1,mlx5_2:1 -mca btl_openib_if_include mlx5_0:1,mlx5_2:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -x UCX_TLS=rc,sm --map-by node -x fca_mpi_fp_sum_forceorder=1 -x fca_mpi_collect_stats=y /mnt/lustre/users/mtt/scratch/ucx_ompi/20171101_013007_12661_21259_clx-hercules-001/installs/AnF1/tests/mpi-small-tests/hpc_tests.git/mpi/misc/fp_sum_test`

Works OK without UCX (`-mca pml ^ucx`) and with MXM (`-mca pml yalla -x MXM_RDMA_PORTS=mlx5_0:1,mlx5_2:1`).

**Comment by yosefe** [comment]
would suggest to also check with direct modex disabled

**Comment by evgeny-leksikov** [comment]
not reproduced after 12 hours loop, @amaslenn could you check mtt logs?

**Comment by amaslenn** [comment]
Latest results look good.
