### ISSUE TITLE
How to install openmpi with ucx?

### ISSUE THREAD

**Issue by ChinouneMehdi** [openucx/ucx#1966]
According to INSTALL file:

> Compiling OpenMPI with UCX library
> ==================================
> 
> The Open MPI package includes two public software layers: MPI and OpenSHMEM.
> UCX support in OpenMPI is not upstream yet, it is work in progress.
> Current work on OpenMPI/UCX integration is ongoing for OpenSHMEM API and can be found here:
> 
> https://github.com/openucx/ompi-mirror/pull/1
> 
> 
> To compile OpenMPI with UCX support:
> 
> # checkout Pull Request
> % git clone https://github.com/openucx/ompi-mirror
> % cd ompi-mirror
> % git fetch origin pull/1/head:pr-1
> % git checkout pr-1

That's repository does not exist!

**Comment by miked-mellanox** [comment]
Thanks, ucx INSTALL file should be updated,you can use ompi master and release branch instead to compile ucx with ompi.
@yosefe plz note

**Comment by ChinouneMehdi** [comment]
I think the README file is also misleading. The first time I read it I thought that ucx depends on the mpi library

>  UCX is a communication library implementing high-performance messaging for MPI/PGAS frameworks
> 
> Quick start
> 
> % export PATH=$PATH:$MPI_HOME/bin
> % ./autogen.sh
> % ./contrib/configure-release --prefix=$PWD/install --with-mpi

**Comment by shamisp** [comment]
Agree. We have to remove MPI dependency in readme, it is only used in regression and it might be misleading. 

We also have to update install instructions. Also you don't have to go with latest. UCX supported in OpenMPI in 2.1 and OpenMPI 3.x tree. Here are addition instructions from FAQ: https://github.com/openucx/ucx/wiki/OpenMPI-and-OpenSHMEM-installation-with-UCX

It also supported by MPICH (3.3a and above)

**Comment by shamisp** [comment]
Adding @bbenton

**Comment by yosefe** [comment]
fixed readme

**Comment by ChinouneMehdi** [comment]
Have you fixed INSTALL file which still contains incorrect information?!
