### ISSUE TITLE
UCX compilation error with CLANG 5

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#2021]
/src/uct/ib/ud/base/ud_iface.c:7:
/src/uct/ib/ud/base/ud_iface.h:198:46: error: taking address of packed member 'queue' of class or structure 'uct_ud_send_skb' may result in an unaligned pointer
      value [-Werror,-Waddress-of-packed-member]
        ucs_queue_push(&iface->tx.res_skbs, &skb->queue);
                                             ^~~~~~~~~~

**Comment by yosefe** [comment]
unaligned pointer should not be a problem in general

**Comment by shamisp** [comment]
It may depend on system configuration. On some systems it may generate runtime warnings.
AFAIK by default C compiler naturally aligns variables for the underlaying arch, unless explicitly “packed” directive is used. In this case no __packed is used.
