### ISSUE TITLE
UCP: ucp_do_am_bcopy_multi drops data on UCS_ERROR_NO_RESOURCE

### ISSUE THREAD

**Issue by MattBBaker** [openucx/ucx#2077]
As several UCP code paths work now (eager send, rendezvous send, maybe stream too?) some bcopy sends can be erroneously skipped. This happens because the datatype is responsible for packing data and updating the offset in the data. Then ucp_do_am_bcopy_multi does the send, reporting an error but failing to reset the offset. The request mechanism then queues the send to try it again, but then it will skip the chunk of data that failed with UCS_ERROR_NO_RESOURCE in the first place.

**Comment by yosefe** [comment]
@MattBBaker  why v1.2.2? isn't this on master?

**Comment by MattBBaker** [comment]
@yosefe you're right. Cleared the 1.2.2.

**Comment by yosefe** [comment]
how can this be reproduced? is it only ugni? can you add small gtest to expose the issue?

**Comment by MattBBaker** [comment]
This is a UGNI SMSG unique problem because there is no way to guarantee ahead of time that the GNI_SmsgSendWTag function used for uct_ep_am_bcopy will succeed before calling pack_cb. So the local side will appear to have resources, call the pack_cb that updates the offset, then fail on GNI_SmsgSendWTag where the remote side is not ready to receive more data. The upper UCP layer assumes that the pack_cb was not called if there was an error, but in this case it is.

**Comment by MattBBaker** [comment]
I've been thinking on the gtest subject, I don't think a gtest can be made unless we make a synthetic uct transport that reports errors to ensure that upper ucp protocols behave in the expected way.

**Comment by yosefe** [comment]
@evgeny-leksikov this is what we discussed, that ucp_dt_pack() should not change the dt state
