### ISSUE TITLE
error handle flow should be invoked before disconnecting

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#2152]
if the err_handle flow is invoked from the main thread, a case where it is invoked after ucp_ep_close_nb may happen.
in this case, during ucp_ep_flush_internal, the UCP_EP_FLAG_FAILED flag isn't set yet and a flush request is created and added to the pending queue. however, unlike the user's requests, when doing pending_purge, the new flush request isn't completed.

**Comment by evgeny-leksikov** [comment]
@alinask do you have a test case for this? I'm not sure I understood.
`ucp_ep_err_pending_purge` calls `ucp_request_complete` in the end which set request state and completion flag unconditionally. So, `ucp_request_check_status` should indicate the error on disconnecting.
The new flush request created by `ucp_ep_flush_internal` is a user request returned by `ucp_ep_close_nb`.
