### ISSUE TITLE
UCP worker can't be initialized with CX5-ROCE out of the box

### ISSUE THREAD

**Issue by evgeny-leksikov** [openucx/ucx#2195]
` rc_iface.c:650  UCX  ERROR Failed to create TM XRQ: No route to host`
`UCX_RC_TM_ENABLE=n` helps

**Comment by yosefe** [comment]
should be fixed in latest MOFED version

**Comment by shamisp** [comment]
At least it has to be documented somewhere in wiki installation notes, including MOFED version, etc.

**Comment by yosefe** [comment]
@evgeny-leksikov was it fixed by new MOFED?

**Comment by evgeny-leksikov** [comment]
Got confirmation, it's fixed in MOFED.

**Comment by shamisp** [comment]
It has to be documented somewhere. Aka MOFED version requirement for UCX
v1.3 release. Also we have to document it in known issues and provide
instructions for an update.

**Comment by brminich** [comment]
@yosefe, should we add this to RN? That HW TM may not work on RoCE with certain MOFED versions?

**Comment by yosefe** [comment]
@brminich yes - pls send to @alinask the required MOFED versions for RN/UM
