### ISSUE TITLE
[mtt] hang in mpi_test_suite with HCOLL

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2222]
Reproduced here: http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/hcol/20180124_143440_15907_139934_jazz17/html/test_stdout_f6C82N.txt

Setup: `jazz x4`

Cmd:
`mpirun -np 112 --bind-to core --map-by node -mca pml ucx -mca btl_openib_warn_default_gid_prefix 0 -mca btl_openib_if_include mlx5_0:1 --timestamp-output -x HCOLL_IB_IF_INCLUDE=mlx5_0:1 -x MXM_RDMA_PORTS=mlx5_0:1 -x HCOLL_ENABLE_MCAST_ALL=0 -x HCOLL_MCAST_NP=6 -x HCOLL_CONTEXT_CACHE_ENABLE=1 -x UCX_SHM_DEVICES=all -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_ACC_DEVICES=all -x HCOLL_ENABLE_SHARP=0 -x HCOLL_ENABLE_TOPOLOGY=0 -x HCOLL_BCOL=ucx_p2p -x HCOLL_SBGP=p2p /hpc/mtr_scrap/users/mtt/scratch/hcol/20180124_143440_15907_139934_jazz17/installs/8gzy/tests/mpi-test-suite/ompi-tests/mpi_test_suite/mpi_test_suite -x relaxed -t 'All,^One-sided,^IO,^Environment' -d 'All,^MPI_LONG_DOUBLE' -n 300`

Disabling `OSC=UCX` and switching `BCOLL` to `mlnx` doesn't help.

Hangs on:
```sh
Sun Jan 28 10:55:05 2018<stdout>:P2P tests Alltoall Issend (27/44), comm MPI_COMM_TYPE_SHARED comm (14/14), type MPI_HINDEXED_INT (25/27)
Sun Jan 28 10:55:05 2018<stdout>:P2P tests Alltoall Issend (27/44), comm MPI_COMM_TYPE_SHARED comm (14/14), type MPI_STRUCT_INT (26/27)
Sun Jan 28 10:55:05 2018<stdout>:P2P tests Alltoall Issend (27/44), comm MPI_COMM_TYPE_SHARED comm (14/14), type MPI_TYPE_MIX (27/27)
Sun Jan 28 10:55:05 2018<stdout>:P2P tests Alltoall Issend (27/44), comm MPI_COMM_TYPE_SHARED comm (14/14), type MPI_TYPE_MIX_ARRAY (28/27)
```

Works well with `-mca pml yalla`. It also works OK with `-mca coll ^hcoll`.
`BCOLL` doesn't matter, it works OK with both `mxm` and `ucx`.

**Comment by hoopoepg** [comment]
issue is in collectives library: no progress call during broadcast

**Comment by yosefe** [comment]
@hoopoepg pls close this issue and open one in hcoll instead
