### ISSUE TITLE
[mtt] mpich_tests_mpi_coll/allgather3 fails with errors with lanes enabled

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2224]
Configuration:
```
OMPI: 3.1.0rc1
Hercules x57 (ppn=32(x57), nodelist=clx-hercules-[001-002,004-013,017-048,065-077])
```

MTT log: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/ucx_ompi/20180126_144916_3762_52828_clx-hercules-001/html/test_stdout_Lg30mn.txt

Cmd:
`mpirun -np 324 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1,mlx5_2:1 -x UCX_IB_GID_INDEX=0 -mca osc ucx -x UCX_TLS=dc_x,sm -x UCX_IB_SL=1 -x UCX_TM_OFFLOAD=n -x UCX_RC_TM_ENABLE=n -x UCX_MAX_EAGER_LANES=3 -x UCX_MAX_RNDV_LANES=3 --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20180126_144916_3762_52828_clx-hercules-001/installs/wahV/tests/mpich_tests/mpich-mellanox.git/test/mpi/coll/allgather3`

Disabling lanes (`-x UCX_MAX_EAGER_LANES=3 -x UCX_MAX_RNDV_LANES=3`) makes test pass.
Works OK with `NP=323` and lanes enabled.

Output:
```sh
...
Sun Jan 28 13:24:05 2018[1,125]<stderr>:vecout[2547713]=2564097
Sun Jan 28 13:24:05 2018[1,125]<stderr>:vecout[2547714]=2564098
Sun Jan 28 13:24:05 2018[1,125]<stderr>:vecout[2547715]=2564099
Sun Jan 28 13:24:05 2018[1,125]<stderr>:vecout[2547716]=2564100
Sun Jan 28 13:24:05 2018[1,125]<stderr>:vecout[2547717]=2564101
Sun Jan 28 13:24:05 2018[1,125]<stderr>:vecout[2547718]=2564102
Sun Jan 28 13:24:05 2018[1,125]<stderr>:vecout[2547719]=2564103
Sun Jan 28 13:24:05 2018[1,125]<stderr>:vecout[2547720]=2564104
Sun Jan 28 13:24:05 2018[1,124]<stderr>:vecout[2547712]=2564096
Sun Jan 28 13:24:05 2018[1,124]<stderr>:vecout[2547713]=2564097
Sun Jan 28 13:24:05 2018[1,124]<stderr>:vecout[2547714]=2564098
Sun Jan 28 13:24:05 2018[1,124]<stderr>:vecout[2547715]=2564099
Sun Jan 28 13:24:05 2018[1,124]<stderr>:vecout[2547716]=2564100
Sun Jan 28 13:24:05 2018[1,124]<stderr>:vecout[2547717]=2564101
Sun Jan 28 13:24:05 2018[1,124]<stderr>:vecout[2547718]=2564102
Sun Jan 28 13:24:05 2018[1,124]<stderr>:vecout[2547719]=2564103
Sun Jan 28 13:24:05 2018[1,124]<stderr>:vecout[2547720]=2564104
Sun Jan 28 13:24:05 2018[1,0]<stdout>: Found 24903680 errors
```

**Comment by hoopoepg** [comment]
there is issue in eager msg ordering

**Comment by hoopoepg** [comment]
fix is in https://github.com/openucx/ucx/pull/2227
