### ISSUE TITLE
ud/test_uct_peer_failure_multiple.test failed

### ISSUE THREAD

**Issue by alex-mikheev** [openucx/ucx#2347]
During jenkins build on hpc-test-node
```
11:01:48 [ RUN      ] ud/test_uct_peer_failure_multiple.test/0
11:01:58 /scrap/jenkins/workspace/hpc-ucx-pr-3/label/hpc-test-node/worker/3/contrib/../test/gtest/common/test.cc:263: Failure
11:01:58 Failed
11:01:58 Got 1 warnings during the test
11:01:58 
[  FAILED  ] ud/test_uct_peer_failure_multiple.test/0, where GetParam() = ud/mlx5_0:1 (10258 ms)
```
May be related to https://github.com/openucx/ucx/issues/1773

**Comment by evgeny-leksikov** [comment]
@alex-mikheev pls provide more info like how it was configured/run/etc do you have a link to whole log?

**Comment by alex-mikheev** [comment]
Full log can be found here:

http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6384/label=hpc-test-node,worker=3/consoleFull

**Comment by evgeny-leksikov** [comment]
Not reproducible durung many hours/days, @yosefe can we close it for now?

**Comment by yosefe** [comment]
not reproduced anymore, closing
