### ISSUE TITLE
[mtt] hang in mpi-small-tests/collmeas with ROCE

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2365]
Configuration
```
OMPI: 3.1.0rc2
Jazz x3 (ppn=28(x3), nodelist=jazz[14,30-31])
```

MTT log: http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180303_030837_117790_143217_jazz14/html/test_stdout_tG3wLg.txt

Reproduction:
`module load hpcx-gcc`
`mpirun -np 2 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_1:1 -x UCX_IB_GID_INDEX=0 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_IB_ETH_PAUSE_ON=y -x UCX_TLS=rc_x,sm -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180303_030837_117790_143217_jazz14/installs/f5Lk/tests/mpi-small-tests/hpc_tests.git/mpi/misc/collmeas`

It hangs on:
```sh
...
Sun Mar  4 16:34:43 2018[1,0]<stderr>:  25165824 &    9161.20 &    9841.45 & Sun Mar  4 16:34:43 2018[1,0]<stderr>:  10521.70 \\
Sun Mar  4 16:34:43 2018[1,0]<stderr>:  33554424 &   14173.09 &   14377.74 &   14582.39 \\
Sun Mar  4 16:34:43 2018[1,0]<stderr>:  33554432 &   14180.65 &   14383.46 &   14586.26 \\
Sun Mar  4 16:34:43 2018[1,0]<stderr>:
Sun Mar  4 16:34:43 2018[1,0]<stderr>:Collective=Allreduce, Communicator=WORLD
Sun Mar  4 16:34:43 2018[1,0]<stderr>:========================================
```

This cmd works well with `ud`.

Original hang with `NP=84`:
```sh
Sat Mar  3 10:37:39 2018[1,0]<stderr>:  33554424 &  191698.57 &  194328.56 &  195209.38 \\
Sat Mar  3 10:37:39 2018[1,0]<stderr>:  33554432 &  190561.24 & Sat Mar  3 10:37:39 2018[1,0]<stderr>: 193695.18 &  194912.92 \\
Sat Mar  3 10:37:39 2018[1,0]<stderr>:
Sat Mar  3 10:37:39 2018[1,0]<stderr>:Collective=Scan, Communicator=WORLD
Sat Mar  3 10:37:39 2018[1,0]<stderr>:===================================
```

This cmd hangs with `ud` on `Sun Mar  4 16:38:00 2018[1,0]<stderr>:Collective=Reduce, Communicator=WORLD`.

**Comment by yosefe** [comment]
works well after setting `-x UCX_IB_GID_INDEX=3 -x UCX_IB_TRAFFIC_CLASS=106` and configuring lossless RoCE
