### ISSUE TITLE
[mtt] mpi-small-tests/perftest is very slow with CUDA 

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2368]
Configuration:
```
OMPI: 3.1.0rc2
Vulcan x2 (ppn=48(x2), nodelist=vulcan[01-02])
```

MTT log: http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180304_000153_35212_143268_vulcan01/html/test_stdout_s4xBgv.txt

Cmd:
`module load hpcx-gcc-cuda`
`module load dev/cuda`
`module load dev/gdrcopy`
`mpirun -np 96 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to hwthread -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_IB_GID_INDEX=0 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc,cuda_copy,gdr_copy -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180304_000153_35212_143268_vulcan01/installs/0N3n/tests/mpi-small-tests/hpc_tests.git/mpi/misc/perftest`

Run took about 3h.

Running without CUDA TLS makes test pass in seconds:
`mpirun -np 96 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to hwthread -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_IB_GID_INDEX=0 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180304_000153_35212_143268_vulcan01/installs/0N3n/tests/mpi-small-tests/hpc_tests.git/mpi/misc/perftest`

**Comment by bureddy** [comment]
should be fixed with https://github.com/openucx/ucx/pull/2375

**Comment by yosefe** [comment]
@amaslenn can you please validate the fix?

**Comment by amaslenn** [comment]
Works well with the latest build.
