### ISSUE TITLE
OpenSHMEM hang, affects both my code and OpenMPI OSHMEM

### ISSUE THREAD

**Issue by tonycurtis** [openucx/ucx#2449]
Hi, I am seeing hangs in the for loop in this example program that came from Quadrics' SHMEM:

[sping.c](https://github.com/tonycurtis/openshmem-examples/blob/master/C/sping.c)

with **_both_** my own OpenSHMEM-on-UCX **_and_** OpenMPI's OSHMEM-on-UCX.  Using UCX from git, master branch, git-pulled and built this morning for the purposes of this issue.

(This whole thing is very confusing, and could be something that the SHMEMs are getting wrong; but I am not sure, and UCX is the common feature here.)

Specifically on IBV cluster locally and also 1 elsewhere.   Sample job has 2 nodes, 8 cores per node.

If I just run as e.g.

`oshrun ./sping 1000`

then the program hangs. 

If I choose 1 transport with required capabilities, e.g.

`export UCX_TLS=dc`

then the program works.

If I give an explicit list of all transports reported by UCX's configure:

```
checking for perl... /usr/bin/perl
configure: Supported transports: ,dc,rc,ud,cm,rdmacm,cma,knem
checking that generated files are newer than configure... done
configure: creating ./config.status
```

`export UCX_TLS=dc,rc,ud,cm,rdmacm,cma,knem`

then the program works.

If I

`export UCX_TLS=all`

then the program hangs.

**Comment by tonycurtis** [comment]
Latest HEAD of github with basic hello world program run on single node with
```
hca_id:	mlx5_0
	transport:			InfiniBand (0)
	fw_ver:				10.16.1066
	node_guid:			001e:6703:00d4:5b1f
	sys_image_guid:			001e:6703:00d4:5b1f
	vendor_id:			0x02c9
	vendor_part_id:			4113
	hw_ver:				0x0
	board_id:			INT0030100001
	phys_port_cnt:			1
	Device ports:
		port:	1
			state:			PORT_ACTIVE (4)
			max_mtu:		4096 (5)
			active_mtu:		4096 (5)
			sm_lid:			162
			port_lid:		79
			port_lmc:		0x00
			link_layer:		InfiniBand
```
 Crunches with
```
[1524756295.188058] [cn-mem:60181:0]         select.c:417  UCX  ERROR no atomic operations on registered memory transport to <no debug data>: Unsupported operation
[1524756295.188143] [cn-mem:60180:0]         select.c:417  UCX  ERROR no atomic operations on registered memory transport to <no debug data>: Unsupported operation
```
if I run with the any or all of the transports reported by UCX's configure
```
export UCX_TLS=dc,rc,ud,cm,rdmacm,cma,knem
```
If I unset UCX_TLS or set it to "all", the program runs.  Is "all" doing something else?  Not seeing this kind of behavior with 1.3.0 release.  Thanks for any help

**Comment by tonycurtis** [comment]
Thanks.  Generally I do not touch UCX_ env. vars. but this was for debugging.   Think it might be a (local) progress issue.

**Comment by shamisp** [comment]
Since many users will not be able to use rc_x/dc_x we should remove those
from the list of required by default. Once emulation layer implemented we
can put those back.
