### ISSUE TITLE
hang in rcx/test_ucp_peer_failure_2pairs.status_after_error/0 on arm

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#2450]
on hpc-arm-hwi01:
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/label=hpc-arm-hwi01,worker=0/6624/console
```
16:04:43 [----------] 1 test from rcx/test_ucp_peer_failure_2pairs
16:04:43 [ RUN      ] rcx/test_ucp_peer_failure_2pairs.status_after_error/0
16:53:48 Build was aborted
16:53:48 TAP Reports Processing: START
16:53:48 Looking for TAP results report in workspace using pattern: **/*.tap
16:53:48 make: *** [test] Terminated
```

**Comment by hoopoepg** [comment]
@yosefe regression is in https://github.com/openucx/ucx/pull/2338, compilation with disabled HAVE_IBV_EXP_RES_DOMAIN resolves issue

**Comment by yosefe** [comment]
@hoopoepg thanks, i will update MOFED version to 4.3-2 to resolve

**Comment by hoopoepg** [comment]
is it MOFED issue?

**Comment by yosefe** [comment]
yes

**Comment by shamisp** [comment]
Should be documented on wiki as a driver requirement

**Comment by yosefe** [comment]
MOFED updated, test passes
