### ISSUE TITLE
UCT: add uGNI support

### ISSUE THREAD

**Issue by miked-mellanox** [openucx/ucx#248]

**Comment by hppritcha** [comment]
@shamisp what sort of help is needed here?

**Comment by shamisp** [comment]
@hppritcha - can we chat ? Generally speaking on the todo list we have support for active messages through SMSG and wire-up through datagram.

**Comment by hppritcha** [comment]
sure, how about morning 8/26?

**Comment by yosefe** [comment]
@MattBBaker  can we close this?

**Comment by MattBBaker** [comment]
Yes.
