### ISSUE TITLE
transport error: Endpoint timeout on ud on a roce fabric

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#2501]
Threre are several failures on a lossless RoCE fabric. Happen on different scales but have the same trace:

```
Tue Apr 10 02:29:25 2018[1,383]<stderr>:[clx-orion-095:15382:0:15382]    ud_iface.c:781  Fatal: transport error: Endpoint timeout
Tue Apr 10 02:29:25 2018[1,83]<stderr>:[clx-orion-112:17829:0:17829]    ud_iface.c:781  Fatal: transport error: Endpoint timeout
Tue Apr 10 02:29:25 2018[1,383]<stderr>:==== backtrace ====
Tue Apr 10 02:29:25 2018[1,383]<stderr>: 0 0x00000000000526e3 uct_ud_iface_dispatch_async_comps_do()  /hpc/local/benchmarks/hpcx_install_2018-04-09/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_iface.c:781
Tue Apr 10 02:29:25 2018[1,383]<stderr>: 1 0x000000000005a258 uct_ud_iface_dispatch_zcopy_comps()  /hpc/local/benchmarks/hpcx_install_2018-04-09/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_iface.h:443
Tue Apr 10 02:29:25 2018[1,383]<stderr>: 2 0x0000000000017b32 ucs_callbackq_dispatch()  /hpc/local/benchmarks/hpcx_install_2018-04-09/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/callbackq.h:208
Tue Apr 10 02:29:25 2018[1,383]<stderr>: 3 0x0000000000003307 mca_pml_ucx_progress()  /hpc/local/benchmarks/hpcx_install_2018-04-09/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/pml/ucx/pml_ucx.c:454
Tue Apr 10 02:29:25 2018[1,383]<stderr>: 4 0x00000000000329fc opal_progress()  /hpc/local/benchmarks/hpcx_install_2018-04-09/src/hpcx-gcc-redhat7.4/ompi/opal/runtime/opal_progress.c:228
Tue Apr 10 02:29:25 2018[1,383]<stderr>: 5 0x0000000000048925 ompi_request_wait_completion()  /hpc/local/benchmarks/hpcx_install_2018-04-09/src/hpcx-gcc-redhat7.4/ompi/ompi/../ompi/request/request.h:413
Tue Apr 10 02:29:25 2018[1,383]<stderr>: 6 0x000000000007c17e ompi_coll_base_bcast_intra_generic()  /hpc/local/benchmarks/hpcx_install_2018-04-09/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/base/coll_base_bcast.c:210
Tue Apr 10 02:29:25 2018[1,383]<stderr>: 7 0x000000000007c5f7 ompi_coll_base_bcast_intra_binomial()  /hpc/local/benchmarks/hpcx_install_2018-04-09/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/base/coll_base_bcast.c:336
Tue Apr 10 02:29:25 2018[1,383]<stderr>: 8 0x00000000000048fc ompi_coll_tuned_bcast_intra_dec_fixed()  /hpc/local/benchmarks/hpcx_install_2018-04-09/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/tuned/coll_tuned_decision_fixed.c:258
Tue Apr 10 02:29:25 2018[1,383]<stderr>: 9 0x000000000005c251 PMPI_Bcast()  /hpc/local/benchmarks/hpcx_install_2018-04-09/src/hpcx-gcc-redhat7.4/ompi/ompi/mpi/c/profile/pbcast.c:111
Tue Apr 10 02:29:25 2018[1,383]<stderr>:10 0x00000000004046ff IMB_basic_input()  ???:0
Tue Apr 10 02:29:25 2018[1,383]<stderr>:11 0x0000000000401f5d main()  ???:0
Tue Apr 10 02:29:25 2018[1,383]<stderr>:12 0x0000000000021c05 __libc_start_main()  ???:0
Tue Apr 10 02:29:25 2018[1,383]<stderr>:13 0x0000000000401df9 _start()  ???:0
Tue Apr 10 02:29:25 2018[1,383]<stderr>:===================
```

Command lines:

• Nodes: orion x14 (ppn=28(x14), nodelist=clx-orion-[090-096,106-112]):

/hpc/local/benchmarks/hpcx_install_2018-04-09/hpcx-gcc-redhat7.4/ompi/bin/mpirun -np 392 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_IB_ETH_PAUSE_ON=y -x UCX_TLS=rc_x,sm -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 -x UCX_IB_TRAFFIC_CLASS=106 -x UCX_IB_GID_INDEX=1 --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20180410_003721_16589_74646_clx-orion-090/installs/Y_iZ/tests/imb/imb/src/IMB-MPI1 -npmin 392 -iter 1000 -mem 0.9

http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20180410_003721_16589_74646_clx-orion-090/html/test_stdout_Akut7L.txt

• Nodes: orion x85 (ppn=28(x85), nodelist=clx-orion-[001-007,009-026,029-088]):

/hpc/local/benchmarks/hpcx_install_2018-04-09/hpcx-gcc-redhat7.4/ompi/bin/mpirun -np 2048 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_IB_ETH_PAUSE_ON=y -x UCX_TLS=all -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 -x UCX_IB_TRAFFIC_CLASS=106 -x UCX_IB_GID_INDEX=1 --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20180410_021211_19489_74653_clx-orion-001/installs/IEmO/tests/npb/NPB3.3.1/NPB3.3-MPI/bin/ft.B.2048

http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20180410_021211_19489_74653_clx-orion-001/html/test_stdout_sRFw64.txt

• Nodes: orion x16 (ppn=28(x16), nodelist=clx-orion-[089-096,105-112]):

/hpc/local/benchmarks/hpcx_install_2018-04-09/hpcx-gcc-redhat7.4/ompi/bin/mpirun -np 448 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_IB_ETH_PAUSE_ON=y -x UCX_TLS=rc_x,sm -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 -x UCX_IB_TRAFFIC_CLASS=106 -x UCX_IB_GID_INDEX=1 --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20180410_080212_31012_74683_clx-orion-089/installs/__57/tests/mpich_tests/mpich-mellanox.git/test/mpi/basic/sendrecv

http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20180410_080212_31012_74683_clx-orion-089/html/test_stdout_yKY52z.txt

Can happen right at the begining of the test or during it.

MLNX_OFED_LINUX-4.3-1.0.1.0

HCA:
```
hca_id: mlx5_2
        transport:                      InfiniBand (0)
        fw_ver:                         12.22.1002
        node_guid:                      e41d:2d03:005c:ff54
        sys_image_guid:                 e41d:2d03:005c:ff54
        vendor_id:                      0x02c9
        vendor_part_id:                 4115
        hw_ver:                         0x0
        board_id:                       MT_2190110032
        phys_port_cnt:                  1
        Device ports:
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             1024 (3)
                        sm_lid:                 0
                        port_lid:               0
                        port_lmc:               0x00
                        link_layer:             Ethernet
```

**Comment by alinask** [comment]
On a slightly smaller scale:

• Nodes: orion x10 (ppn=28(x10), nodelist=clx-orion-[001-002,090-096,098]):

/hpc/local/benchmarks/hpcx_install_2018-04-10/hpcx-gcc-redhat7.4/ompi/bin/mpirun -np 280 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_IB_ETH_PAUSE_ON=y -x UCX_TLS=all -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 -x UCX_IB_TRAFFIC_CLASS=106 -x UCX_IB_GID_INDEX=1 --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20180410_233650_23100_74786_clx-orion-001/installs/jrR3/tests/imb/imb/src/IMB-MPI1 -npmin 280 -iter 1000 -mem 0.9

http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20180410_233650_23100_74786_clx-orion-001/html/test_stdout_eGGRod.txt

May be related to the value of the UCX_IB_GID_INDEX.

**Comment by yosefe** [comment]
need to use UCX_IB_GID_INDEX=3, orion cluster has r-RoCE between leaf switches
