### ISSUE TITLE
[mtt] hang in intel tests with TLS=ud

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2535]
Configuration:
```
OMPI: 3.1.0rc4
vega x48 (ppn=36(x48), nodelist=clx-vega-[001-005,007-030,033-036,050-064])
Job: ucx
```

MTT log: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/ucx_ompi/20180419_014319_12686_77129_clx-vega-001/html/test_stdout_RGEAUj.txt

Cmd:
`mpirun -np 6 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=ud,sm -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20180419_014319_12686_77129_clx-vega-001/installs/IdXH/tests/intel/intel_tests/src/MPI_Waitall_f`

Tests hang with `TLS=ud` only. NP < 6 also works.

**Comment by amaslenn** [comment]
Test passed here: http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180427_072028_12390_3039_vegas25/All_phase-summary.html

**Comment by hoopoepg** [comment]
failed to reproduce on 1000+ launches (about 4 hours) with different NP
it seems issue is not relevant anymore
