### ISSUE TITLE
[mtt] shmem verifier fails with spml=ucx

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2536]
Configuration:
```
OMPI: 3.1.0rc4
Nodes: pvegas x8 (ppn=16(x8), nodelist=vegas[06-07,17,31-34,36])
Job: shmem-ucx
```

MTT log: http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/shmem/20180419_062455_16191_2244_vegas06/html/test_stdout_m2J4YO.txt

Cmd:
`oshrun -np 128 --debug-daemons --display-map --bind-to core -mca oshmem_proc_group_cache_size 10000 -mca btl_openib_warn_default_gid_prefix 0 -report-bindings -mca sshmem_verbs_hca_name mlx5_0:1 -mca btl_openib_if_include mlx5_0:1 -x MXM_RDMA_PORTS=mlx5_0:1 -x UCX_NET_DEVICES=mlx5_0:1 -mca sshmem sysv -mca sshmem_sysv_use_hp 0 -mca coll_hcoll_enable 1 -x HCOLL_POLLING_LEVEL=1 -x HCOLL_ENABLE_MCAST_ALL=0 -x HCOLL_BCOL=basesmuma,ucx_p2p -x HCOLL_SBGP=basesmsocket,p2p -mca spml ucx -mca pml ucx --map-by node -x SHMEM_SYMMETRIC_HEAP_SIZE=1299M /hpc/mtr_scrap/users/mtt/scratch/shmem/20180419_062455_16191_2244_vegas06/installs/1qt6/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour --task=sync`

Output
```sh
[vegas33:10815] MCW rank 85 bound to socket 1[core 10[hwt 0]]: [./././././././.][././B/././././.]
[vegas33:10815] MCW rank 93 bound to socket 1[core 11[hwt 0]]: [./././././././.][./././B/./././.]
[vegas33:10815] MCW rank 101 bound to socket 1[core 12[hwt 0]]: [./././././././.][././././B/././.]

OpenSHMEM Verification Tool ver."1.2.68"
**********************************
* Log file: none
* Host: vegas06
* Output level: 4
* Log level: 0
**********************************

PASS   sync       barrier_all    Barrier All Synchronization Routine.
PASS   sync       wait           Wait Synchronization Routine.
PASS   sync       wait_until     Wait Until Synchronization Routine.
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
oshrun noticed that process rank 64 with PID 6850 on node vegas06 exited on signal 9 (Killed).
--------------------------------------------------------------------------
```

The issue is not reproduced with `-mca spml ^ucx`.

**Comment by yosefe** [comment]
OOM on the server
