### ISSUE TITLE
Usage Documentation: ucx_perftest usage text has no mention of a --batch flag

### ISSUE THREAD

**Issue by stowellm** [openucx/ucx#2633]
The `ucx_perftest` usage text mentions a short flag `-b` which takes a batchfile as input.  Presumably, this is the short version of the `--batch` flag, but it is not documented.  That said, `/usr/share/doc/ucx/perftest/README` only makes reference to a `--batch` flag, not `-b`.

```
# ucx_perftest --help | grep batch
ucx_perftest: invalid option -- '-'
     -D <layout>[,<layout>]    Data layout. Default is "short" in UCT, "contig" in UCP and previous one in batch mode. Second parameter is for receive side in UCP only.
     -b <batchfile> Batch mode. Read and execute tests from a file.

# grep batch /usr/share/doc/ucx/perftest/README 
This is an example of the "batch" configuration files for ucx_perftest.
ucx_perftest --batch msg_pow2 --batch test_types --batch transports <...>
```

This is a request to have the `ucx_perftest` thus inform the user of both short- and long-versions of flags available for use.

**Comment by yosefe** [comment]
actually @shamisp this is your bug in README file :) there is no long `--batch` option..

**Comment by shamisp** [comment]
@yosefe last time I used it, it was there....

**Comment by yosefe** [comment]
@shamisp perftest never had long options, only short. anyway i will fix the README.
