### ISSUE TITLE
ib: possible issue with UD

### ISSUE THREAD

**Issue by hjelmn** [openucx/ucx#2687]
I am trying to use UD through UCT to handle passing connection endpoint information. I can't seem to get it to work. I keep seeing errors of the form:

```
[1529010961.072361] [cn844:41158:0]         ud_inl.h:88   UCX  DATA  iface=0x282b5120 ep=0x28331b70 (0->16777215) no ep resources (psn=2 max_psn=3)
```

I have successfully used DC for this purpose but would like to get UD working for older hardware. Any thoughts.

This is with UCX 1.3.x master. On both Power 9 and ARM Thunder X.

**Comment by hjelmn** [comment]
Will test x86_64 as well. Need to check software availability.

**Comment by shamisp** [comment]
@yosefe - the error looks weird

**Comment by yosefe** [comment]
this is not an error, it means UD cannot send at this moment, need to call uct_worker_progress() on both sides to make it work

**Comment by shamisp** [comment]
hmm, we do have progress thread, right ?

**Comment by hoopoepg** [comment]
progress thread process receives only (it can't process pending send ops)

**Comment by hjelmn** [comment]
I don't see why this would be the case. I see the error on the very first message on the endpoint associated with this tl. I can try adding a loop that calls am_short + worker progress and see if that helps.

**Comment by shamisp** [comment]
@yosefe does post send fails in this case ? Can we return try again ?

**Comment by yosefe** [comment]
this is what we do, @hjelmn you are getting UCS_ERR_NO_RESOURCE right?

**Comment by hjelmn** [comment]
Yup. That is the error.

**Comment by shamisp** [comment]
@hoopoepg I asked about progress thread because @yosefe suggest to progress both sides. The sender send failure does make sense for me. Can we track the resource and return tryagain.

**Comment by shamisp** [comment]
okay, it just got answered :)

**Comment by yosefe** [comment]
is there code in btl ucx to retry in such case?

**Comment by hjelmn** [comment]
Not yet. I wanted to figure out this error before I finish that code. Was really surprised since, as mentioned, no messages had been sent yet. I will add the loop now.

**Comment by hjelmn** [comment]
That was more-or-less the last "bug" in the BTL that needed to be resolved. Will be spending the next couple of days cleaning up the code and testing with MTT then will update my PR for Open MPI.

**Comment by shamisp** [comment]
Awesome. thanks
