### ISSUE TITLE
Question: how to optimize MPI over UCX for small messages?

### ISSUE THREAD

**Issue by vmaffione** [openucx/ucx#2721]
Hi,
  I want to benchmark openmpi over UCX with short messages (8-32 bytes).

My MPI program uses two nodes A and B, with two simple test scenarios: (1) A sends messages in a very tight loop (`MPI_Send()`) and B receives messages (`MPI_recv`) in a very tight loop; (2) ping-pong, where A calls `MPI_Send()` and `MPI_Recv()` in a tight loop and B does the opposite.

Is there any way I can configure UCX and or openmpi to maximize the message rate for (1) and number of ping pong transactions per second for (2)? Or should I use different `MPI_Send()/MPI_Recv()` variants?

My current numbers are about 8 Mops for (1) and 600 Kops for (2).

Thanks!

**Comment by brminich** [comment]
Hello,
For such benchmarks UCX should select the most optimal parameters by default.
BTW, do you want to optimize OMPI/UCX for your particular benchmarks or you want to create a benchmark which would show good values?

For message rate I'd use non-blocking MPI calls (`MPI_Isend/MPI_Irecv`), like osu_bw and osu_mbw_mr do. 
(2) sounds like a typical ping-pong available in OSU or IMB MPI benchmarks

What is your command line and HW details? (to better understand whether provided numbers are good or not)

**Comment by yosefe** [comment]
@vmaffione the performance numbers you see look reasonable for the system. On newer NIC (ConnectX4/5 for example) we could expect better message rates.

**Comment by yosefe** [comment]
MPI_Send/MPI_Recv (blocking) usually work best since there is no extra overhead of allocating and waiting for a request.

**Comment by vmaffione** [comment]
That makes sense, thanks. In any case I think that MPI_Send over UCX (over ibverbs) does not wait for the transmission to complete before returning, but only queues to the SQ. Am I correct?

**Comment by brminich** [comment]
Yes, it should be this way for the message range you specified. However UCX may wait for transmission completion for relatively big message sizes.

**Comment by shamisp** [comment]
I was about to point out that it really depends on the underlaying network + message size. In most case the small message is copied to a bouncing buffer (or network device memory) and completed in place. A.k.a. user memory buffer is re-usable and it is valid to mark the message as completed. Larger messages in the case of blocking send can be blocked and in this case MPI_Send will be relatively slow when compared to non-blocking sends.

**Comment by vmaffione** [comment]
Thanks. I'm only interested in small messages (<32 bytes), and over ibverbs. I guess in this case UCX uses inline send which saves the latency of a DMA transaction on the sender side.

So you are saying that UCX decides which send/receive strategy to use depending on the message size. Are the size threshold(s) static (per backend) or dynamic? Where can I see the thresholds in the code (or within configuration parameters)?

**Comment by vmaffione** [comment]
I have an additional question on UCX over ibverbs. How does UCX decide the type of QP to use, e.g. RC, UC or UD? What type of queue do you think it is used in my scenario?
Thanks for the help

**Comment by vmaffione** [comment]
Thanks for the help! It seems UCX does not support UC, I can only choose "rc" (which apparently corresponds to RC or UD).
Is there any reason for this limitation?

**Comment by shamisp** [comment]
@vmaffione we don't support it mostly because we don't have a use case for UC. 
Why would we want to have unreliable connected transport ? It does not scale with number of connections + you have to manage reliability in software.

**Comment by vmaffione** [comment]
Thanks @shamisp ! I am just curious, I'm not suggesting the use of UC.
Forgive me for my limited of knowledge on ibverbs mode, but... my understanding is that both UC and RC do not scale with the number of nodes, because you need a pair of QPs for each couple of nodes at least. On the other hand, UD scales because you need one (or O(1)) QPs per node.
So RC is non-scalable and reliable, and UD is scalable and unreliable. UC would be excluded because is non-scalable and unreliable, which is a lose-lose.

In any case it is still not clear to me whether UCX actually uses RC or UD, because the documentation for `UCX_TLS=rc` states "transport used is RC or UD". But which one is actually chosen?

**Comment by brminich** [comment]
You need to specify `UCX_TLS=ud` to use UD transport. With `rc` you will always have RC QPs

**Comment by vmaffione** [comment]
That worked, thanks.
But then maybe the documentation is outdated? The `ud` transport is not reported as an option.
This is the filtered output of `ucx_info -f`
````
#
# Comma-separated list of transports to use. The order is not meaningful.
# In addition it's possible to use a combination of the following aliases:
#  - all    : use all the available transports.
#  - sm/shm : all shared memory transports.
#  - mm     : shared memory transports - only memory mappers.
#  - ugni   : ugni_rdma and ugni_udt.
#  - ib     : all infiniband transports.
#  - rc     : rc and ud.
#  - rc_x   : rc with accelerated verbs and ud.
#  - ud_x   : ud with accelerated verbs.
#  - dc_x   : dc with accelerated verbs.
#  Using a \ prefix before a transport name treats it as an explicit transport name
#  and disables aliasing.
# 
#
# Syntax: comma-separated list of: string
#
UCX_TLS=all
````
and the `ud` option is missing.

**Comment by brminich** [comment]
Yes, looks like documentation needs to be fixed. Thanks for reporting it

**Comment by yosefe** [comment]
The transports listed in this help message are aliases: "In addition it's possible to use a combination of the following aliases"
"ud" is a real transport name, not an alias, which can be shown by "ucx_info -d"

**Comment by shamisp** [comment]
@yosefe from usability perspective it would be nice to list all the available transport on the platform. Can we leverage the transport list that is returned by ucx_info ?

**Comment by brminich** [comment]
Also, `rc` is not an `rc or ud` now, because ud is used for wireup only (auxiliary)

**Comment by shamisp** [comment]
@brminich you confused me with the last statement ...

**Comment by brminich** [comment]
Now `rc` is an alias which means that `rc` will be used as transport and `ud` will be used for wireup process only (we added this restriction a while ago). So, `ud` is not used for payload, therefore `rc` does not mean `rc or ud` anymore

**Comment by vmaffione** [comment]
Can someone please point me at the code that backs MPI_Send() over UCX?
I'm quite lost in the code...

**Comment by yosefe** [comment]
https://github.com/open-mpi/ompi/blob/master/ompi/mca/pml/ucx/pml_ucx.c#L771

**Comment by vmaffione** [comment]
thanks
