### ISSUE TITLE
Deadlock with UCX_RC_VERBS_TX_CQ_LEN=1

### ISSUE THREAD

**Issue by vmaffione** [openucx/ucx#2727]
Hi,
  I'm doing some very simple experiments with MPI over UCX (see #2721).
I observe deadlock when setting `UCX_RC_VERBS_TX_CQ_LEN=1`, and this is an allowed configuration.
I'm not interested in such a configuration, but maybe you should prevent that?

Separate question: I'm interested to the `UCX_UD_VERBS_TX_CQ_MODERATION` parameter, but I'm not sure about its meaning. This is the description:
````
#
# Number of send WQEs for which completion is requested.
#
# Syntax: unsigned integer
#
UCX_UD_VERBS_TX_CQ_MODERATION=64
````
I see two possible meanings:
  (1) 64 is the maximum number of outstanding send WQEs for which completion is requested (out of `UCX_RC_VERBS_TX_QUEUE_LEN`). But in this case how do you decide which WQEs to mark and which not to mark?
  (2) One WQE every 64 is marked to report completion.
Which one is correct?

**Comment by yosefe** [comment]
@vmaffione the configuration is intended mostly for debugging/tuning and hence there is no check that it is workable, only some sanity checks.
The meaning is (1)
The WQEs are marked once per TX_CQ_MODERATION, or if it's zero-copy or RMA/AMO operation

**Comment by vmaffione** [comment]
@yosefe  Did you mean that meaning is (2) (i.e. one WQE marked every 64)?

**Comment by yosefe** [comment]
Sorry for the confusion,
The meaning of UCX_RC_VERBS_TX_CQ_LEN is (1)
The meaning of UCX_UD_VERBS_TX_CQ_MODERATION is (2)

**Comment by vmaffione** [comment]
No worries, thanks.
The meaning of `UCX_RC_VERBS_TX_CQ_LEN` is clear from the documentation, btw.
You may want to clarify the meaning of `UCX_UD_VERBS_TX_CQ_MODERATION`, as it is a bit unclear imho.
