### ISSUE TITLE
Gtest communication failure due to "error: struct has size 0 in C, size 1 in C++" with armclang

### ISSUE THREAD

**Issue by nSircombe** [openucx/ucx#2741]
The structure ibv_exp_res_domain in /src/uct/ib/base/ib_verbs.h is empty.

When compiling the test suite with armclang this throws an error since empty structures are not permitted in C++.
Adding 'int :0;' into the struct as a work-around does not help, since the behaviour of a struct with no named member is undefined, and in clang, generates the same error as an empty struct.

Adding a named 'char' into the structure (as GCC appears to https://gcc.gnu.org/onlinedocs/gcc/Empty-Structures.html) allows the commutation to progress to completion, but the test suite fails on 'test_datatype.queue_iter', 'Segmentation fault: address not mapped to object'.

**Comment by shamisp** [comment]
How we didn't catch this one in regression ? I would expect that any testing with inbox driver would step on this issue.

**Comment by yosefe** [comment]
we are setting x86 testing machine for upstream, we can make it run clang (but not arm-clang) compilation too.

**Comment by shamisp** [comment]
I would expect that you will see similar error with regular clang on any platform.

**Comment by yosefe** [comment]
@nSircombe it should be already fixed, by #2743

**Comment by nSircombe** [comment]
Yep, now compiles without issue, but fails during the test with the same issue I saw when I padded out the empty struct with a char.
Segfaults in the test_datatype.queue_iter test.

**Comment by yosefe** [comment]
opened #2928
