### ISSUE TITLE
Frequency read by UCS on x86 doesn't match actual CPU frequency

### ISSUE THREAD

**Issue by rzambre** [openucx/ucx#2792]
`ucs_arch_get_clocks_per_sec()` in `src/ucs/arch/x86_64/cpu.c` reads the frequency using the CPU model instead of information from cpuinfo. This is incorrect when the user changes the frequency of the CPU to something other than the base frequency of the CPU. The correct CPU frequency will be read only from `ucs_get_cpuinfo_clock_freq` when the CPU frequency is different from the base frequency.

**Comment by yosefe** [comment]
@rzambre AFAIK for modern x86 models, the tsc frequency does not change when CPU clock is changed, it always uses the base frequency

**Comment by shamisp** [comment]
@yosefe they had issues with some cores where tsc changes with frequency. This is the reason why OpenMPI does not use it.

**Comment by yosefe** [comment]
is there constant_tsc flag for this CPU? maybe the fix should be to check for this flag in cpuid

**Comment by shamisp** [comment]
@yosefe Not going to help. It was a bug in hardware. OpenMPI moved to get_clocktime on ALL x86.

**Comment by yosefe** [comment]
So can we check for the specific CPU model/revision(s) which have this bug?

**Comment by shamisp** [comment]
@yosefe not going to work... :-) Most reasonable approach for x86 is the one that ibv_perftest is using.

**Comment by yosefe** [comment]
why is it not going to work?

**Comment by shamisp** [comment]
There is no public information on the subject.

**Comment by shamisp** [comment]
@yosefe so... what do we want to do about this

**Comment by yosefe** [comment]
need more details/justification to what is being fixed and why

**Comment by shamisp** [comment]
https://github.com/open-mpi/ompi/issues/3847
https://github.com/open-mpi/ompi/issues/3003

**Comment by yosefe** [comment]
maybe we could have 2 flavors of timer: 
- accurate clock_gettime - for perftest
- inaccurate and fast - for ud SW reliability

**Comment by shamisp** [comment]
Overall - sounds like a good idea to me. 
clock_gettime is pretty fast on x86 unless you have static build, which most like will lead to system call.
