### ISSUE TITLE
No unsignaled WQEs for puts?

### ISSUE THREAD

**Issue by rzambre** [openucx/ucx#2815]
This is more of a question than an issue: from https://github.com/openucx/ucx/blob/master/src/uct/ib/rc/accel/rc_mlx5_common.h#L579-L614
I see that the WQEs are always signaled for puts but signaling is moderated for active messages (every 64 WQEs). What was the design motivation behind moderating signaling only for active messages not for puts?

**Comment by yosefe** [comment]
efficient shmem_quiet()

**Comment by shamisp** [comment]
okay. Maybe for UCT level we should provide an option to disable this ?

**Comment by yosefe** [comment]
for UCT users?
would UCP set it always?

**Comment by shamisp** [comment]
for UCT user and benchmarks.
UCP - this is good question....Maybe we should make it optional as well. It really depends on programming model. For shmem style quite it is easier to count acks.If you use barrier for synchronization, there is no need for acks.

**Comment by yosefe** [comment]
@rzambre @shamisp can you provide more details about the benchmark you are running? is it ucx_perftest? we want to look into optimizing this.

**Comment by rzambre** [comment]
@yosefe yes, it was the ucx_perftest benchmark. You can see the difference with `-t put_bw` and `-t am_bw`

**Comment by shamisp** [comment]
@rzambre I remember you did some benchmarking showing that after some threshold ```put_bw``` is always going through "retry" flow. AKA you have to pull CQ before you actually can post WQE.

**Comment by rzambre** [comment]
Yes, I had just used print statements in the benchmarks to verify. I had put a `printf("%d\n", m_send_b_count);` at https://github.com/openucx/ucx/blob/master/src/tools/perf/uct_tests.cc#L279. After a certain number of posts, the printf statement will show `status == UCS_ERR_NO_RESOURCE` after every post.
