### ISSUE TITLE
How to check the ucp_ep connection status?

### ISSUE THREAD

**Issue by jiguanglizipao** [openucx/ucx#2893]
I want to free the ucp_ep when the peer is crashed or disconnected but I don't find any interface can check the ucp_ep connection status. Whether I missed? How to implement it if not?

**Comment by yosefe** [comment]
if something was sent on the ep, the request may complete with error
also, it's possible to set error handler on the endpoint which will be called in case of peer failure

**Comment by yosefe** [comment]
@jiguanglizipao i don't see in the code above where is the ep released..

**Comment by evgeny-leksikov** [comment]
Also need to set `ucp_ep_params_t::err_mode = UCP_ERR_HANDLING_MODE_PEER` on ep creation to detect peer failure with `ucp_ep_params_t::err_handler`

**Comment by jiguanglizipao** [comment]
@yosefe I want to check the connection status after `ucp_worker_progress` because the `while (request->completed == 0) ucp_worker_progress(worker);` is a endless loop.

**Comment by jiguanglizipao** [comment]
The err_handler seems work.
Thank you @yosefe @evgeny-leksikov .
