### ISSUE TITLE
shmem_verifier fail on arm

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#2923]
```
module load hpcx-gcc
oshrun -np 42 -mca btl self --bind-to core -mca oshmem_proc_group_cache_size 10000 \
-report-bindings -mca btl_openib_if_include mlx5_0:1 -x UCX_NET_DEVICES=mlx5_0:1 \
-mca sshmem ucx -mca coll '^hcoll' -mca spml ucx -mca pml ucx --map-by node \
-x SHMEM_SYMMETRIC_HEAP_SIZE=1164M \
/hpc/mtr_scrap/users/mtt/scratch/shmem/20181002_232037_61903_7871_hpc-arm-*/installs/4BYz/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour --task=data:put_blocking
```

**Comment by yosefe** [comment]
@amaslenn FYI

**Comment by shamisp** [comment]
I need a bit more details about the test itself. I the memory is updated by
some other PE ?

**Comment by yosefe** [comment]
looks like we have to add datatype to shmem API

**Comment by shamisp** [comment]
@yosefe I'm not sure if the test is SHMEM compliant. 1.4 suggest to use shmem_wait for local memory poll.

**Comment by manjugv** [comment]
@shamisp In the test that Yossi is mentioning, the local data is read by shmem_int_get operation. Why is it not complaint then ? I'm I missing something.

**Comment by yosefe** [comment]
agree with @manjugv , out UCX implementation of shmem_get/put is not compliant, it does not access memory with the right granularity (which should be according to data-type , in this case - int)

**Comment by shamisp** [comment]
it looks like you poll on the date with shmem_get while the address is updated by remote PE ? Do you expect atomic update ? if so, why ?

**Comment by yosefe** [comment]
i would expect shmem_get() for basic types to see consistent data

**Comment by shamisp** [comment]
@yosefe SHMEM spec does not define single copy operations. x86 and arm defines those on arch level but it is not obvious how it is maps to CCI, PCIe, NIC/HCA and other interconnects.

**Comment by shamisp** [comment]
Regardless, I still want to understand the memcpy issue

**Comment by yosefe** [comment]
after chat with @shamisp we concluded that the test is not spec-compliant since it relies on shmem_get to wait for memroy update, which does not provide atomicity guarantee (need to use shmem_atomic_fetch or shmem_wait_until, for example)

**Comment by manjugv** [comment]
@yosefe @shamisp I'm not sure how shmem_atomic_fetch will help.

**Comment by shamisp** [comment]
@manjugv it will help. Implementation wise it will go through HCA loopback.

**Comment by manjugv** [comment]
@shamisp But, you are mixing atomic with non-atomic operation. I will IM you :)

**Comment by shamisp** [comment]
@manjugv - valid point. My assumption was that everything is replaced with AMOs.

**Comment by yosefe** [comment]
ok , so will replace it all with shmem_test or wait_until

**Comment by shamisp** [comment]
@yosefe @manjugv BTW, while in this particular shmem_test/wait_until will work it does not really resolve the issue. There is no guarantee that PCIe or IB will do single copy from the NIC to memory.

**Comment by yosefe** [comment]
@sameerkm if shmem_test/wait_until wouldn't work, then it should be fixed in SHMEM library, not the test

**Comment by manjugv** [comment]
@shamisp I'm not sure what issue we are referring anymore. :) However, I don't think the test requires single copy guarantees.

**Comment by shamisp** [comment]
@manjugv memory model discussion.
