### ISSUE TITLE
Malloc hooks failure on Arm/TX2

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#2939]
Latest master:

```
[ RUN      ] malloc_hook.dlopen
[     INFO ] Loading /home/ucx/build/test/gtest/ucm/test_dlopen/.libs/libdlopen_test_do_load.so
[     INFO ] Loading /home/ucx/build/test/gtest/ucm/test_dlopen/.libs/libdlopen_test_do_mmap.so
../../../test/gtest/ucm/malloc_hook.cc:976: Failure
Expected: ((uintptr_t)lib) != ((uintptr_t)__null), actual: 0 vs 0
```

**Comment by shamisp** [comment]
Apparently it is not built at all.

If --enable-gtest specified it is built and it is passing the test.
Otherwise the file is not created at all.

Since it is not consistent with the rest for gtests, which do not require explicit enable flag, I would suggest to fix the makefiles.

**Comment by yosefe** [comment]
basically this is oncorrect usage, but @hoopoepg  can you pls to fix "make test" target to fail if --enable-gtest was not specified

**Comment by shamisp** [comment]
@yosefe 
If --enable-gtest is required, we should fail. As for now it is inconsistent and confusing.

**Comment by hoopoepg** [comment]
on the way: https://github.com/openucx/ucx/pull/2941
