### ISSUE TITLE
Assertion failure (worker->inprogress == 0) when ucp_worker_progress is called from server accept callback

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [openucx/ucx#2946]
I'm seeing this 
```
ucp_worker.c:1395 UCX Assertion `worker->inprogress++ == 0' failed
```
issue with on a program that has a server listen for connections and calls `ucp_worker_progress` in the `accept_callback`  function that is passed as a listen parameter. Is this valid use of `ucp_worker_progress`? 
I see that @yosefe has fixed a [bug](https://github.com/openucx/ucx/issues/607) with a similar error message but I don't the error is related. 

I set the worker thread mode to thread_multiple but that doesn't seem to help. My main thread is busy polling on a condition that is set by accept callback after it progresses past the call to `ucp_worker_progress()`. Which thread is executing the `accept_callback`? Is it the pthread created in tcp uct? If yes, is my program invalid? Can you provide suggestions on what else I can try?

Thanks in advance.

**Comment by yosefe** [comment]
ucp_worker_progress is not allowed to be called from callbacks

**Comment by Akshay-Venkatesh** [comment]
Thanks for the quick response @yosefe. I'll change the usage in the program.

**Comment by yosefe** [comment]
@Akshay-Venkatesh thanks, can we close this?

**Comment by shamisp** [comment]
@yosefe do we have this document somewhere ?

**Comment by Akshay-Venkatesh** [comment]
@yosefe Sorry for the delay. Didn't see the notification. Please go ahead and close.

**Comment by Akshay-Venkatesh** [comment]
@yosefe I forgot to ask -- are other ucp communication calls allowed inside the callback? or is the requirement that no ucp calls be made from within callback functions?

**Comment by yosefe** [comment]
communication calls are allowed, but not progress calls
