### ISSUE TITLE
Failure to create ibv_context with dc_x/rc_x and 126 ppn

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#2963]
- lots of hwthreads/node.
- MOFED 4.4 and UCX 1.4 (from the MOFED distro)
- Open MPI 3.1.2.  

When running 126 or more MPI ranks/node:
 ```
/home/hpp/ompi/examples@cn805:~/ompi/examples> ((v3.1.2))mpirun -np 126 --bind-to hwthread --mca btl ^openib ./ring_c
[1539724919.792899] [cn805:206805:0]      ib_device.c:227  UCX  ERROR ibv_open_device(mlx5_3) failed: Cannot allocate memory
[1539724919.820865] [cn805:206837:0]      ib_device.c:227  UCX  ERROR ibv_open_device(mlx5_3) failed: Cannot allocate memory
```

Setting UCX_TLS to dc or rc - the problem vanishes.
Setting it to dc_x or rc_x the problem reappears.

**Comment by hoopoepg** [comment]
not sure about ring_c, but I run another application:
```
[09:40:24;sergeyo@jazz28:/labhome/sergeyo]$ ~/local/ompi/bin/mpirun --oversubscribe -np 146 -x UCX_NET_DEVICES=mlx5_0:1 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll ^hcoll -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc_x --map-by core roce-repro
Wed Oct 17 09:40:35 2018[1,0]<stdout>:iteration 0
Wed Oct 17 09:40:46 2018[1,0]<stdout>:iteration 276
...
```
are there more details about environment?

**Comment by yosefe** [comment]
according to latest note from Howard, "we now think this is a Open MPI bug"

**Comment by jithinjosepkl** [comment]
We are seeing this issue with  OpenMPI 4.0 and UCX 1.4.0. Setting UCX_TLS=rc fixes the issue.

Do we know the corresponding OpenMPI issue that Howard is referring to ("according to latest note from Howard, "we now think this is a Open MPI bug"")?

**Comment by jithinjosepkl** [comment]
@hoopoepg , I had these already "-mca btl ^vader,tcp,openib".  UCX_TLS=rc fixes the issue though.
```
./openmpi-4.0.0.install/bin/mpirun -np 60 --hostfile ~/hostfile -mca pml ucx --mca btl ^vader,tcp,openib -x UCX_NET_DEVICES=mlx5_0:1  -x UCX_IB_PKEY=0x0003 -x UCX_TLS=rc ./osu-micro-benchmarks-5.5-ompi/mpi/pt2pt/osu_mbw_mr
```

**Comment by shamisp** [comment]
@yosefe - should be reopen this ? Not sure how it can be OpenMPI bug. Just in case, I would suggest disable uct btl with ^uct.

**Comment by jithinjosepkl** [comment]
Btw, I confirm that this happens with MPICH (3.3) +UCX (1.4.0) as well. Please let me know if you need any additional details.

**Comment by shamisp** [comment]
It would be nice to introduce some unit test that will hit this flow. We do have machines with a lot of cores. With tx2 you can get to 224.

**Comment by jithinjosepkl** [comment]
Noticed these error logs in dmesg when I got the "Cannot allocate memory" error (Hoping this will give some hints.)

```
[17507.989873] mlx5_0:alloc_and_map_wc:2477:(pid 108172): UAR alloc failed
[17507.991290] mlx5_core 0002:00:02.0: mlx5_cmd_check:771:(pid 108167): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)
```

Corresponding UCX runtime error is:
```
ib_device.c:227  UCX  ERROR ibv_open_device(mlx5_0) failed: Cannot allocate memory
```

**Comment by yosefe** [comment]
@jithinjosepkl can you post the output of `ibv_devinfo -v` ? Probably on SRIOV there is a lower on number of UARs (max_device_ctx)

**Comment by jithinjosepkl** [comment]
Thanks @yosefe. Indeed, it was set to 60.

```
[jijos@jijos-01 ~]$ ibv_devinfo -v  | grep ctx
        max_device_ctx:                 60
```

That explains the "cannot allocate memory" errors while running more than 60 ranks per node (with UCX_TLS=rc).

But curious why it failed for lesser than 60 ranks per node, and worked when UCX_TLS=rc was set? Does UCX internally create more than one context per rank (probably for different transports)?

**Comment by yosefe** [comment]
@jithinjosepkl the accelerated verbs transports (dc_x/rc_x) allocate a "resource domain" context, in addition to the verbs context. The resource domain consumes a single global UAR which is used by all process, and is also accounted into the limit imposed by "max_device_ctx".
Using UCX_TLS=rc selects the "regular" RC transport, not the accelerated one, which does not allocate a resource domain.
So you should be able to run 59 processes per node without UCX_TLS, and 60 with UCX_TLS=tc

**Comment by shamisp** [comment]
@yosefe can we document it somewhere on wiki ?
