### ISSUE TITLE
Any way to get which thread is calling ucp_send_callback_t?

### ISSUE THREAD

**Issue by rzambre** [openucx/ucx#2992]
If I have multiple threads calling independent `ucp_tag_send_nb` (i.e. on completely separate endpoints), and the send call returns in an outstanding request, is there a way for me to find out which thread is calling the send callback?

The goal is to have a max number of outstanding requests per thread. So, in the send callback I would want to decrement the outstanding-requests counter of the thread that is calling the send callback. I tried using a `ucp_request_init_callback_t` in which I store the thread_id in a request struct but the stored thread_id in the request struct is always 0 even when thread_1 calls the send callback. So, an orthogonal question would be: when is the `ucp_request_init_callback_t` function called?

**Comment by brminich** [comment]
In what thread do you call `ucp_worker_progress` function? This one should invoke comp callbacks.   

As for request_init callback, it is invoked only once at the very beginning. You need to reset/reinit all the needed fields, before to release it back to UCX. Below is the relevant documentation:
```
 /**
  * Pointer to a routine that is used for the request initialization.
  * This function will be called only on the very first time a request memory
  * is initialized, and may not be called again if a request is reused.
  * If a request should be reset before the next reuse, it can be done before
  * calling @ref ucp_request_free.
  *
```
You can check usage example [here](https://github.com/openucx/ucx/blob/0c86fc0e44d67636118702302b2330692b0c3c62/test/examples/ucp_hello_world.c#L210)

**Comment by rzambre** [comment]
Thank you, @brminich. A couple of follow-up questions.

(1) I can call `omp_get_thread_num` inside the callback and decrement the respective thread's counter of outstanding requests. But this works only when each thread has its own UCP worker. When the multiple threads have their own UCP endpoint but share the the UCP worker, the above approach cannot work since thread i could be reading thread j's completions. In this case, is there a way to propagate or derive tag information of the request being completed (I am setting the tag of the request to the thread id)?

(2) Within which function exactly is the request_init callback called? Is it during `ucp_worker_create` or is it during a nonblocking call such as `ucp_tag_send_nb`?

**Comment by rzambre** [comment]
If the request_init is being called on a chunk basis as opposed to a per-request basis, then it wouldn't be possible to propagate correct tag information for a future `ucp_tag_send_nb`, correct? If the `ucp_tag_send_nb` of thread_i results in chunk allocation of request objects, then thread_i doesn't know which thread will be calling `ucp_tag_send_nb` next and hence wouldn't know what tag information to insert in the user part of the request. This is for multiple threads with their own UCP endpoint within a shared UCP worker.

**Comment by brminich** [comment]
I meant that every time you get a request from `ucp_tag_send_nb` function, you'd need to save a tag in your part of the request, like below:
```
my_req = ucp_tag_send_nb(..., tag,...);
my_req->tag = tag;
```

**Comment by rzambre** [comment]
Got it, makes sense. Thank you!
