### ISSUE TITLE
Query supported features at UCP layer

### ISSUE THREAD

**Issue by minsii** [openucx/ucx#2994]
Hello, we are adding the atomics feature into MPICH/CH4/UCX. 

We found that, on `mlx4` platform, the `UCP_FEATURE_AMO32` feature is not supported. If adding both `UCP_FEATURE_AMO32 | UCP_FEATURE_AMO64` at `ucp_init`, then `ucp_ep_create` fails with error `UCS_ERR_UNREACHABLE`. 

To ensure our code can run on platform that may or may not support atomic or a subset of the atomic features, we will need to detect which feature is supported at runtime. I have found a related discussion at https://elist.ornl.gov/mailman/htdig/ucx-group/2018-May/000689.html, which suggests the `uct_iface_query ` API. However, at MPICH layer we do not know which transport is being used.

It would be great if UCP can expose such information. Here are some possible options:
1. `ucp_init` internally skips any unsupported feature, and returns `rejected feature` to us. Thus, we can disable related routine (e.g., disable any 32bit atomic code if `AMO32` has been rejected)
2. UCP introduces a query API that can return a list of supported features for the current transport. Then, we can call it before `ucp_init` and only set supported features at `ucp_init` time.

Could you please let us know if there is already a similar feature in UCP or any of the above options would work. Thanks !

**Comment by pavanbalaji** [comment]
Thanks, @yosefe.  But perhaps the request here should be considered for all features, rather than just the atomic32 feature, but rather for any feature.  Unless there’s a commitment that every single feature is going to be supported on every hardware (potentially through software emulation), which is probably unrealistic, I think a query or fallback functionality, similar to what Min suggested, would be useful.

**Comment by shamisp** [comment]
@pavanbalaji I think the goal from now and going on to cover all the gaps with the emulation layer.

**Comment by shamisp** [comment]
@pavanbalaji It will show up in v1.5.0.

We branched v1.4.x in August way before the emulation was introduced. 
The good news - we plan to branch for 1.5.x shortly after 1.4.0 release.

Target release date for 1.5.0 is end of November / beginning of December.

**Comment by minsii** [comment]
@shamisp @yosefe I have one more question about the emulation layer for atomics in v1.5.0. According to the UCX 1.4 spec and source code of 1.4 release, an atomic operation is valid only when meet all the following conditions (please correct me if any of my assumption is wrong):
- Data size is 4 or 8 bytes
- Remote address is aligned with data size
- The combination of <datatype, op> can only be: <integer, add>, <integer, logic>, <integer, bitwise>, <any type, cswap>, <any type, swap>, or <any type, fetch (i.e., add with value 0)>

With the emulation layer, will UCX eventually remove all the above limitations ? For example, will `atomic swap with 1 char data` become valid ?

**Comment by yosefe** [comment]
@minsii  the emulation layer (which is already part of UCX v1.5.0) is not designed to remove these limitations, since it's more of an API specification limitation. The reason it's currently defined this way is to be compliant with OpenSHMEM specification, which defines only 4/8 byte atomics.
is there a need to have also 1-byte (or other) atomics in UCX?

**Comment by minsii** [comment]
In MPI standard, we do not have bytes-limitation for RMA atomics, but we limit the basic datatypes that can be used for each atomic operation. For 1-byte example, we support `cswap with byte type`. For larger bytes example, we support `add with arbitrary count of integers (or floating point)`. 

I do not think UCX have to support all MPI-supported atomics in the emulation layer, instead, we would like to query the hardware atomic support of the underlying network. The use case would be, the MPI user tells us which atomic operations they will use (i.e., through MPI info). Then we will know whether MPI can handle all user-required atomics through network hardware. If yes, we can use network atomics, otherwise we have to fallback to active message with CPU-based atomic mechanism in MPI.

**Comment by shamisp** [comment]
@minsii are you asking about atomics supported by underlaying network devices or UCX ? UCX implements emulation layer (over active messages) which virtually can enable any atomic supported by underlaying CPU architecture ?

@yosefe I think for MPI_Info it might be useful to expose some of the underlaying capabilities (in hardware), emulation etc. We talked about this in early days of UCX.

**Comment by minsii** [comment]
@shamisp I was asking the atomics support/limitation in UCX since I am implementing MPICH's RMA atomics on top of UCX, thus we have to rely on the atomics semantics defined by UCX. 

However, based on the above conversation, I am a little concerned about the emulation strategy in UCX. As you mentioned, the emulation layer can eventually support all atomics. But all of them have to go through active message for atomicity, eventually losing performance (I assume UCX cannot guarantee the atomicity between `op1` and `op2` if `op1` is sent as network atomic and `opt2` is sent via active message). 

The way we think in MPICH is that, we want to provide fast hardware atomics as much as possible (e.g., when user only requires a subset of atomics which can all be supported by the network hardware). Thus, what we really want is that UCX can expose the underlying hardware atomics support to us.

**Comment by shamisp** [comment]
@minsii You are right to be concerned. It is even more complicated - once emulation was enabled, it must be enabled for all PEs, which we may not have control over. 

@yosefe I don't remember how do we deal with this today ? I guess once emulation is enabled or HW offloads are disabled ?

@minsii during initialization we let the user pass a configuration argument (similar to MPI info) that let's request specific atomic operations. For now it only lists 32 and 64bit ops: https://github.com/openucx/ucx/blob/master/src/ucp/api/ucp.h#L137
We can extend the list to specific ops such that MPI can pass it down and based on this we will try to figure out if emulation has to be enabled or disabled.  The next question - is this something that defined globally during MPI init or it is different for each MPI window ?

We also can try to do it other way around and expose what is emulated and what is not. Does MPI allow user to query what operations are natively supported ?

**Comment by shamisp** [comment]
@minsii so, what we have today does not fit well with MPICH. We allow user to pass the information about AMOs during library initilization only. For MPICH you need something like this but on memory region (rkey) granularity. In theory , it can be done. The challenge is that all PEs accessing this region have to agree on the same path...

**Comment by minsii** [comment]
@shamisp maybe we can consider an alternative option:
- At UCX init time, MPICH tells UCX that only enable native atomics. Then UCX needs to return the list of enabled atomics (`ucx_enabled_atomics`).
- At MPICH window creation time, MPICH chooses native atomics (i.e., using UCP AMO API) or active message (i.e., using send/recv) for that window by comparing user info with `ucx_enabled_atomics`.

In this way, UCX still configures AMOs only at initialization, and we only need the list of enabled atomics as return value (or through other query API). What do you think ?

**Comment by minsii** [comment]
@shamisp Good point. We do also see similar situation in MPICH/OFI stack that both MPICH and OFI have their own internal active message. In MPICH, we disable OFI's progress thread, and let MPICH's progress engine to make progress for both layers' active messages.

**Comment by yosefe** [comment]
@shamisp @minsii the problem now is that UCX API atomics are following OpenSHMEM specification, rather than MPI RMA. Today, IMHO the way to go is to use UCX atomics for a particular MPI window if we know they are only going to be 32/64 bit, and fallback to active messages (on top of ucp_tag API) otherwise.
@shamisp We should think about extending UCX to support general atomics to fit MPI needs.

**Comment by minsii** [comment]
@yosefe Thanks for the suggestion. I have similar plan that we can temporarily add UCP-based atomics in MPICH/UCX following this approach. This routine is enabled/disabled based on the conditions as required by UCX1.4. 

> Data size is 4 or 8 bytes
Remote address is aligned with data size
The combination of <datatype, op> can only be: <integer, add>, <integer, logic>, <integer, bitwise>, <any type, cswap>, <any type, swap>, or <any type, fetch (i.e., add with value 0)>

We hope a future UCX release can fully expose the underlying hardware support thus fits our needs.
