### ISSUE TITLE
ucx_perftest building is BROKEN

### ISSUE THREAD

**Issue by jengelh** [openucx/ucx#300]
commit 6777d78e2923c3dccd73942e48a02190960c4aab
```
$ ./configure --disable-static && make V=1
[...]
# CC      perftest.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I../../.. -O3 -g -Wall -Werror -msse4.1 -mavx -I/home/abuild/rpmbuild/BUILD/ucx/src -I/home/abuild/rpmbuild/BUILD/ucx/src ./perftest.c -c  -fPIC -DPIC -o .libs/perftest.o
# CCLD    libucxperf.la
libtool: link: gcc perftest.o -o .libs/ucx_perftest  ./.libs/libucxperf.a /home/abuild/rpmbuild/BUILD/ucx/src/ucp/.libs/libucp.so /home/abuild/rpmbuild/BUILD/ucx/src/uct/.libs/libuct.so /home/abuild/rpmbuild/BUILD/ucx/src/ucs/.libs/libucs.so -lm -lpthread -lrt -ldl -Wl,-rpath -Wl,/usr/lib64
gcc: error: perftest.o: No such file or directory
Makefile:894: recipe for target 'ucx_perftest' failed
```

**Comment by yosefe** [comment]
on which distro/arch?

**Comment by jengelh** [comment]
openSUSE 13.2 x86_64, but this does not play a role because this behavior is across all distros AFAIU.
The point is that your Makefile illegally relies on the presence of `./perftest.o`, which may be absent.

**Comment by yosefe** [comment]
i see, it tries to take perftest.o from current directory, but it's created by libtool in .libs

**Comment by jengelh** [comment]
Well, you cannot rely on .libs/perftest.o either, because that may be absent too if --disable-shared is used. You must only use perftest.lo.
