### ISSUE TITLE
AUR package added for UCX

### ISSUE THREAD

**Issue by vmaffione** [openucx/ucx#3004]
If it can be of any interest, I just created an AUR package for Archlinux https://aur.archlinux.org/packages/openucx/

**Comment by shamisp** [comment]
@vmaffione - thanks for doing this ! please let us know if you see any issues.

**Comment by vmaffione** [comment]
Sure. I did this because it's the only way I could find to make openmpi work over Infiniband.
The old "openib" openmpi backend does not work on Arch.
