### ISSUE TITLE
Querying max number of entities in UCP?

### ISSUE THREAD

**Issue by rzambre** [openucx/ucx#3066]
This is a question: is there a way to query the maximum number of UCP workers or UCP contexts I can create instead of finding out the limit programmatically? This could be useful when the UCX user needs to create a pool of resources during initialization.

**Comment by yosefe** [comment]
currently there is no such way. there are many limitations on number of workers, which depend on how many devices and transports are used per worker, amount of memory in the system, size of buffer pools in the transports, and much more. Usually we aim to support at least one worker per CPU logical core on the currently supported platforms.
