### ISSUE TITLE
[mtt] segfault in un_contiguous on Allgatherv 'MPI_DOUBLE_INT' test

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#3075]
Configuration
```
OMPI: 4.1.0a1
MOFED: MLNX_OFED_LINUX-4.4-2.0.7.0
Module: hpcx-gcc (2018-11-29)
Test module: mtt-tests/hpcx-gcc
Nodes: hercules x92 (ppn=32(x92), nodelist=clx-hercules-[037-128])
```

MTT log: http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20181130_102613_4654_241190_clx-hercules-037/html/test_stdout_V1n5bT.txt

Test fails on `Allgatherv 'MPI_DOUBLE_INT' with 1000 iterations`. Test passes with NP<=2040, or with NP=2041 and reduced number of iterations. Looks like test issue.

Original cmd:
`mpirun -np 2944 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_2:1,mlx5_3:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc,self,sm -x UCX_IB_SL=1 -x UCX_RC_TM_ENABLE=n -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 -x UCX_MAX_EAGER_LANES=3 -x UCX_MAX_RNDV_LANES=3 -x UCX_IB_TRAFFIC_CLASS=106 -x UCX_IB_GID_INDEX=auto --map-by node /hpc/local/benchmarks/hpcx_install_2018-11-29/mtt-tests-gcc/installs/DJlZ/tests/mpi-small-tests/hpc_tests.git/mpi/misc/un_contiguous`

Output:
```sh
Fri Nov 30 12:19:40 2018[1,0]<stdout>:Testing Allgatherv 'MPI_DOUBLE_INT' with 1000 iterationsFri Nov 30 12:19:48 2018[1,1656]<stderr>:[clx-hercules-037:16466:0:16466] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x106e0)
Fri Nov 30 12:19:48 2018[1,1748]<stderr>:[clx-hercules-037:16467:0:16467] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x106e0)Fri Nov 30 12:19:48 2018[1,1645]<stderr>:[clx-hercules-118:22998:0:22998] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x106e0)
Fri Nov 30 12:19:48 2018[1,1650]<stderr>:[clx-hercules-123:24179:0:24179] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x106e0)
...
Fri Nov 30 12:19:48 2018[1,95]<stderr>:/hpc/local/benchmarks/hpcx_install_2018-11-29/mtt-tests-gcc/installs/DJlZ/tests/mpi-small-tests/hpc_tests.git/mpi/misc/un_contiguous.c: [ double_int_fill() ]
Fri Nov 30 12:19:48 2018[1,95]<stderr>:      ...
Fri Nov 30 12:19:48 2018[1,809]<stderr>:       37 {
Fri Nov 30 12:19:48 2018[1,809]<stderr>:       38 	mpi_double_int_t *di = p;
Fri Nov 30 12:19:48 2018[1,809]<stderr>:       39 	di->d = seed % 10000;
Fri Nov 30 12:19:48 2018[1,809]<stderr>:==>    40 	di->i = (seed * 17) % 10000;
Fri Nov 30 12:19:48 2018[1,809]<stderr>:       41 }
```

**Comment by hoopoepg** [comment]
out-of-memory issue

**Comment by yosefe** [comment]
@hoopoepg how can out-of-memory cause segfault? AFAIK OOM killer sends SIGKILL?

**Comment by hoopoepg** [comment]
@yosefe test is failed to allocate memory and crashed on access to NULL pointer

**Comment by yosefe** [comment]
@hoopoepg weird, why would allocation fail? AFAIK it should go to swap or invoke OOM killer if memory is locked/pinned. Hard to believe virtual memory is limited only 61GB..
see https://www.quora.com/What-are-the-possible-ways-malloc-might-fail-Consider-malloc-code-doesnt-have-any-bugs

**Comment by hoopoepg** [comment]
no, in case if requested more than available memory (RAM + SWAP) malloc returns NULL

**Comment by hoopoepg** [comment]
at least corruption stack points to test itself where is invalid memory access which means failed to allocate memory

**Comment by yosefe** [comment]
if `dtypes = calloc(10, sizeof *dtypes);` had returned NULL, i would expect segfault to occur at a small address
but in fact the segfault is at 0x106e0
```
Fri Nov 30 12:19:48 2018[1,1650]<stderr>:[clx-hercules-123:24179:0:24179] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x106e0)
```

**Comment by yosefe** [comment]
if `calloc(total_count * size, extent);` returned NULL, why is the segfault at 0x106e0 and not 0?

**Comment by hoopoepg** [comment]
it seems it failed to map buffer to memory (no free RAM available)

**Comment by yosefe** [comment]
does the test pass on a machine with more memory?

**Comment by hoopoepg** [comment]
hercules has 256Gb of memory, have you better system? :)

**Comment by yosefe** [comment]
sounds good, does it pass on hercules?

**Comment by hoopoepg** [comment]
memory required **(np * iterations * rand * datatype)** of memory per rank. it works fine on 2041- ranks, but after some np limit it fails

**Comment by hoopoepg** [comment]
@amaslenn let's limit np to 2041
