### ISSUE TITLE
Trouble building UCX (error utilizing binutils)

### ISSUE THREAD

**Issue by sasuke79** [openucx/ucx#3094]
I am trying to build UCX from source using gcc7 + binutils 2.27. Whenever I run `make`, I get the following:

In file included from debug/debug.c:31:0:
/apps/default/include/bfd.h:6588:3: error: expected specifier-qualifier-list before 'ENUM_BITFIELD'
   ENUM_BITFIELD (bfd_format) format : 3;
   ^~~~~~~~~~~~~
/apps/default/include/bfd.h: In function 'bfd_set_cacheable':
/apps/default/include/bfd.h:6860:7: error: 'bfd {aka struct bfd}' has no member named 'cacheable'
   abfd->cacheable = val;
       ^~
debug/debug.c: In function 'load_file':
/apps/default/include/bfd.h:518:41: error: 'bfd {aka struct bfd}' has no member named 'flags'
 #define bfd_get_file_flags(abfd) ((abfd)->flags)
                                         ^
debug/debug.c:200:10: note: in expansion of macro 'bfd_get_file_flags'
     if ((bfd_get_file_flags(file->abfd) & HAS_SYMS) == 0) {
          ^~~~~~~~~~~~~~~~~~
make[2]: *** [debug/libucs_la-debug.lo] Error 1
make[2]: Leaving directory `/scratch/build/ucx-1.4.0/src/ucs'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/scratch/build/ucx-1.4.0'
make: *** [all] Error 2

Is there a particular version of binutils that must be used?

**Comment by yosefe** [comment]
Does your binutils compile with gcc7 (without UCX)?

**Comment by sasuke79** [comment]
It does. All unit tests pass as well.

**Comment by yosefe** [comment]
@sasuke79 i've tried with gcc 7.1.1 and binutils 2.27-28.fc26 (on fedora 26) and got no errors. Did you build  binutils from source? How did you point UCX to /apps/default/include/bfd.h?
