### ISSUE TITLE
Send completion error with OpenMPI 3.1.2 UCX PML

### ISSUE THREAD

**Issue by ca-taylor** [openucx/ucx#3130]
I'm getting the errors below a few minutes into a 3840-task (i.e. rank) OpenMPI run with the following.

export OMPI_MCA_pml="ucx"
export OMPI_MCA_pml_ucx_verbose=100
export OMPI_MCA_btl="^vader,tcp,openib"
export UCX_RC_VERBS_FC_ENABLE=n

Note that I get the error with or without FC enable.  That was just my naive attempt to change something.   

I may cross post this to the OpenMPI user list but it seems more like a UCX problem than a OpenMPI problem.

[1547217255.226204] [c25a-s35:21592:0] rc_verbs_iface.c:69   UCX  ERROR Send completion with error: local length error
[1547217255.226772] [c25a-s35:21592:0]      uct_iface.c:328  UCX  ERROR Error Endpoint timeout was not handled for ep 0xce31430
[1547217255.228075] [c34b-s22:27211:0] rc_verbs_iface.c:69   UCX  ERROR Send completion with error: local length error
[1547217255.229784] [c25a-s22:18696:0] rc_verbs_iface.c:69   UCX  ERROR Send completion with error: local length error
[1547217255.230103] [c25a-s22:18696:0]      uct_iface.c:328  UCX  ERROR Error Endpoint timeout was not handled for ep 0x3196530

On the OpenMPI side, there are no UCX PML errors until this...

[c40a-s3:263417:0] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x2ab619e98ca8)
==== backtrace ====
    0  /lib64/libucs.so.0(+0x134a0) [0x2ab38bf194a0]
    1  /lib64/libucs.so.0(+0x13912) [0x2ab38bf19912]
    2  /home/desika.narayanan/gizmo_runs/simba/m50n1024/gizmo_simba/GIZMO() [0x44a355]
    3  /home/desika.narayanan/gizmo_runs/simba/m50n1024/gizmo_simba/GIZMO() [0x44a395]
    4  /home/desika.narayanan/gizmo_runs/simba/m50n1024/gizmo_simba/GIZMO() [0x44a395]
    5  /home/desika.narayanan/gizmo_runs/simba/m50n1024/gizmo_simba/GIZMO() [0x44a395]
    6  /home/desika.narayanan/gizmo_runs/simba/m50n1024/gizmo_simba/GIZMO() [0x44a754]
    7  /home/desika.narayanan/gizmo_runs/simba/m50n1024/gizmo_simba/GIZMO() [0x44a395]
    8  /home/desika.narayanan/gizmo_runs/simba/m50n1024/gizmo_simba/GIZMO() [0x44a395]
    9  /home/desika.narayanan/gizmo_runs/simba/m50n1024/gizmo_simba/GIZMO() [0x44a754]
   10  /home/desika.narayanan/gizmo_runs/simba/m50n1024/gizmo_simba/GIZMO() [0x44a395]

but it is not clear whether the above is cause or effect.

**Comment by ca-taylor** [comment]
I should have added...

RHEL 7.5
OpenMPI 3.1.2
ucx 1.2.2 (native RH).
The application is gizmo (Astronomical simulation code).
Mellanox IB fabric with a mix of mlx4 and mlx5 (mostly mlx4)
with native RH IB stack (no MOFED).

**Comment by brminich** [comment]
Can you please also post a command line? Do you specify any UCX env vars?

**Comment by ca-taylor** [comment]
The app run command looks like this...

export OMPI_MCA_pml="ucx"
export OMPI_MCA_pml_ucx_verbose=100
export OMPI_MCA_btl="^vader,tcp,openib"
export UCX_LOG_LEVEL=DEBUG
export UCX_LOG_FILE=/ufrc/narayanan/desika.narayanan/ucx.log

DATADIR=$SLURM_SUBMIT_DIR
cd $DATADIR/gizmo_simba
srun --mpi=pmix_v2  $DATADIR/gizmo_simba/GIZMO $DATADIR/m50n1024.param   1 > $DATADIR/LOG

**Comment by yosefe** [comment]
@ca-taylor this UCX version is pretty old.. any chance you can try out [v1.5.0-rc1](https://github.com/openucx/ucx/releases/tag/v1.5.0-rc1)?

**Comment by ca-taylor** [comment]
> this UCX version is pretty old.. any chance you can try out v1.5.0-rc1?

Agreed.  We are in the process of upgrading to the 1.4.0 build in EPEL.   If that doesn't help I'll build our own 1.5.0-rc1 RPM.

**Comment by ca-taylor** [comment]
After upgrading to the 1.4.0 build in EPEL, the "local length" errors seem to have gone away.  The application deadlocks at an MPI_barrier() call but there are no complaints from UCX or the OpenMPI ucx PML so that is probably a different issue.

Thanks for the suggestion.
