### ISSUE TITLE
fix ucx_info help message

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#3147]
https://bugzilla.redhat.com/show_bug.cgi?id=1667548

**Comment by shamisp** [comment]
"access denied" on the link.

**Comment by yosefe** [comment]
Do you have RH bugzilla account?

**Comment by shamisp** [comment]
```
You are not authorized to access bug #1573775.

Most likely the bug has been restricted for internal development processes and we cannot grant access.
```

**Comment by shamisp** [comment]
I was about to tag 1.5.0 RC2. If you think that turnaround time on this one is short, we can wait.

**Comment by shamisp** [comment]
Can somebody copy-n-paste the error report since it is not accessible. Otherwise it is not clear what we have to review.
