### ISSUE TITLE
ucx_info: unexpected backquote in cuda output

### ISSUE THREAD

**Issue by tonycurtis** [openucx/ucx#3158]
UCX github master @ 84ab04f950a3efbf138eb9963c32c6a8dd44570c

```
$ ucx_info -d
...
...
# Memory domain: cuda_ipc
#            component: cuda_ipc`
#             register: <= 1g, cost: 0 nsec
#           remote key: 96 bytes
...
...
```

Looks like a stray backquote on the "component" line

**Comment by tonycurtis** [comment]
Couldn't find what caused it yet...

**Comment by tonycurtis** [comment]
Hmm, looks like UCX is just reporting verbatim what the cuda_ipc MD is telling it.  Could well be an issue in CUDA.

Close and ignore.

**Comment by tonycurtis** [comment]
Hmm, looks like UCX is just reporting verbatim what the cuda_ipc MD is telling it.  Could well be an issue in CUDA.

Or is it the memcpy() in uct_md_query() and a NUL-termination problem?

**Comment by yosefe** [comment]
it's probably because component name is limited to 8, which is exactly the length of "cuda_ipc", so it does not include the NULL terminator

**Comment by tonycurtis** [comment]
Component name wasn't long enough, fixed
