### ISSUE TITLE
gdrcopy location and libraries needed by ucx_info

### ISSUE THREAD

**Issue by tonycurtis** [openucx/ucx#3198]
I was testing UCX git master @ b598220b4b78f26885d816630ae7a3d7abf139d7 on a machine with GPUs and gdrcopy installed.

```shell
$ configure ... --with-cuda=/opt/cuda/10 --with-gdrcopy=/opt/gdrcopy ...
```

The `/opt/gdrcopy` path isn't propagated so `ucx_info` complains

```shell
/opt/ucx/git/bin/ucx_info: error while loading shared libraries: libgdrapi.so.1: cannot open shared object file: No such file or directory
```

Is the intention that `LD_LIBRARY_PATH` should provide link info for CUDA and gdrcopy?

**Comment by bureddy** [comment]
@tonycurtis can you please check with latest master.  This should have fixed with @yosefe 's recent loadable modules

**Comment by tonycurtis** [comment]
I built UCX github@master —with-cuda=/path/etc and there are no errors when running ucx_info.  However, if the CUDA and gdrcopy library paths are subsequently missing from LD_LIBRARY_PATH, those transports don’t get reported by ucx_info -d.

tony

**Comment by bureddy** [comment]
@tonycurtis This is expected as cuda/gdrcopy uct libs are not build with "rpath"  to cuda/gdrcopy install libs.
@yosefe  please advise.

**Comment by yosefe** [comment]
currently ucx does not add rpath to avoid dependency on a specific filesystem location.
the intention is that LD_LIBRARY_PATH would be used

**Comment by tonycurtis** [comment]
> On Feb 20, 2019, at 8:49 AM, Yossi Itigin <notifications@github.com> wrote:
> 
> currently ucx does not add rpath to avoid dependency on a specific filesystem location.
> the intention is that LD_LIBRARY_PATH would be used
> 

OK, I can live with that…
thanks
tony

**Comment by bureddy** [comment]
@yosefe @tonycurtis  can we close this?

**Comment by tonycurtis** [comment]
+1
