### ISSUE TITLE
UCX memory hooks with static linking

### ISSUE THREAD

**Issue by AdamSimpson** [openucx/ucx#3210]
I recently ran into an issue with an application, compiled against OpenMPI with UCX support, that manifested itself as a segfault during GPU aware MPI function calls(`MPI_Isend` in this particular case). The issue was caused by the application statically linking `libcudart`, which caused the UCX `cudaMalloc` memory hook to not be registered correctly, leading UCX to treat the GPU memory as CPU memory. Is it possible for UCX to detect such situations and handle them more gracefully? If that's not so easy perhaps this requirement could be better documented?

**Comment by bureddy** [comment]
@AdamSimpson can you try  "-x UCX_MEMTYPE_CACHE=n"  ?

**Comment by AdamSimpson** [comment]
@bureddy, thanks that appears to work as well. For this particular case we're able to force the use of dynamic `libcudart` so it's no longer an issue in that sense. 

I mostly wanted to open a bug in an attempt to save others the trouble of trying to track down this issue in the future :)

**Comment by shamisp** [comment]
This is something that must be documented in FAQ. Probably we have to have separate warning for staticky linked apps. @yossefe ?

**Comment by AdamSimpson** [comment]
I should mention that this app wasn't fully statically linked either, I believe just `libcudart` was static. The application used CMake as the build system which by default seems to prefer using `libcudart_static.a`, if it's available.

**Comment by shamisp** [comment]
Tagging @yosefe

**Comment by yosefe** [comment]
@bureddy are we testing today in UCM that cuda memory hooks actually work (the same way we test regular malloc hooks)?

**Comment by bureddy** [comment]
@yosefe yes, we are testing cuda hooks (https://github.com/openucx/ucx/blob/master/test/gtest/ucm/cuda_hooks.cc)

the cuda symbols should have replaced with ucm hooks even if it is statically linked.  will try a repro.

**Comment by shamisp** [comment]
@bureddy unless it is inlined or something ...

**Comment by AdamSimpson** [comment]
Here is a minimal reproducer:

**gpu_aware.c**
```
#include <stdio.h>
#include <stdlib.h>
#include <cuda_runtime.h>
#include <mpi.h>
 
int main( int argc, char** argv )
{
    MPI_Init (&argc, &argv);
 
    int direct;
    int rank, size;
    int *h_buff = NULL;
    int *d_rank = NULL;
    int *d_buff = NULL;
    size_t bytes;
    int i;
 
    // Get MPI rank and size
    MPI_Comm_rank (MPI_COMM_WORLD, &rank);
    MPI_Comm_size (MPI_COMM_WORLD, &size);
 
    // Allocate host and device buffers and copy rank value to GPU
    bytes = size*sizeof(int);
    h_buff = (int*)malloc(bytes);
    cudaMalloc((void**)&d_buff, bytes);
    cudaMalloc((void**)&d_rank, sizeof(int));
    cudaMemcpy(d_rank, &rank, sizeof(int), cudaMemcpyHostToDevice);
 
    // Preform Allgather using device buffer
    MPI_Allgather(d_rank, 1, MPI_INT, d_buff, 1, MPI_INT, MPI_COMM_WORLD);
 
    // Check that the GPU buffer is correct
    cudaMemcpy(h_buff, d_buff, bytes, cudaMemcpyDeviceToHost);
    for(i=0; i<size; i++){
        if(h_buff[i] != i) {
            printf ("Alltoall Failed!\n");
            exit (EXIT_FAILURE);
        }
    }
    if(rank==0)
        printf("Success!\n");
 
    // Clean up
    free(h_buff);
    cudaFree(d_buff);
    cudaFree(d_rank);
    MPI_Finalize();
 
    return 0;
}
```

**compile static**
```
$ mpicc -I/usr/local/cuda/include gpu_aware.c /usr/local/cuda/lib64/libcudart_static.a -lrt -ldl -o static.out
```

**run with failure**
```
$ mpirun -np 2 --mca btl ^openib --mca pml ucx ./static.out
Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x7fe434600200)
==== backtrace ====
    0  /usr/lib/libucs.so.0(+0x21df0) [0x7fe468e98df0]
    1  /usr/lib/libucs.so.0(+0x22064) [0x7fe468e99064]
    2  /lib/x86_64-linux-gnu/libc.so.6(+0x14e005) [0x7fe47b570005]
    3  /usr/lib/libucp.so.0(ucp_dt_pack+0xea) [0x7fe4690d1bea]
    4  /usr/lib/libucp.so.0(+0x2bb08) [0x7fe4690dfb08]
    5  /usr/lib/libuct.so.0(uct_mm_ep_am_bcopy+0xf8) [0x7fe45f55ca48]
    6  /usr/lib/libucp.so.0(+0x48a1d) [0x7fe4690fca1d]
    7  /usr/lib/libucp.so.0(+0x2c297) [0x7fe4690e0297]
    8  /usr/lib/libucp.so.0(ucp_tag_send_nbr+0x236) [0x7fe4690f0416]
    9  /usr/local/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_send+0xd2) [0x7fe46b1db832]
   10  /usr/local/lib/libmpi.so.40(ompi_coll_base_sendrecv_actual+0xd9) [0x7fe47bab0d79]
   11  /usr/local/lib/libmpi.so.40(ompi_coll_base_allgather_intra_two_procs+0xab) [0x7fe47baaff6b]
   12  /usr/local/lib/libmpi.so.40(MPI_Allgather+0x11e) [0x7fe47ba6a42e]
   13  ./static.out() [0x4034de]
   14  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fe47b442830]
   15  ./static.out() [0x403319]
...
```
**compile dynamic**
```
$ mpicc -I/usr/local/cuda/include gpu_aware.c -L/usr/local/cuda/lib64 -lcudart -lrt -ldl -o dynamic.out
```

**run with success**
```
mpirun -np 2 --mca btl ^openib --mca pml ucx ./dynamic.out 
Success!
```
