### ISSUE TITLE
Segfault with OpenMPI 4.0.0: address not mapped

### ISSUE THREAD

**Issue by jw292** [openucx/ucx#3213]
I get a segfault running with OpenMPI 4.0.0 on ARM TX2 cluster.

```[arm18:30953:0:30953] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x40015b1ce9c0)
==== backtrace ====
    0  /home/j/DEBUG/lib/libucs.so.0(+0x23f14) [0x400006a1df14]
    1  /home/j/DEBUG/lib/libucs.so.0(+0x22ad4) [0x400006a1cad4]
    2  linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x4000000204f0]
    3  eagle_25.yml() [0x40f110]
    4  eagle_25.yml() [0x40d9e4]
    5  eagle_25.yml() [0x438134]
    6  eagle_25.yml() [0x439ff4]
    7  eagle_25.yml() [0x4064fc]
    8  /lib64/libc.so.6(__libc_start_main+0xec) [0x400004ecb870]
    9  eagle_25.yml() [0x404c68]
```

I see the above segfault with 

* HPCX/UCX v1.4.0 + OpenMPI 4.0.0
* OpenUCX v1.6.0 + OpenMPI 4.0.0

However the code works with

* HPCX/UCX v1.4.0 + OpenMPI 3.1.2a
* OpenUCX v1.6.0 + OpenMPI 3.1.3

The code also works also works with OpenMPI 4.0.0 if I use openib instead of UCX e.g. 

   mpirun --mca btl_openib_allow_ib 1

**Comment by yosefe** [comment]
@jw292 is it possible to point to or attach the code/binary of the failing application (eagle_25.yml)?

**Comment by jw292** [comment]
The code is developed by Durham University (and others).   You can download from the group's Gitlab site: https://gitlab.cosma.dur.ac.uk/swift/swiftsim

I built with OpenMPI 4.0.0 (compiled with armclang)

```
./configure --prefix=$HOME/SWIFT \
    --enable-mpi \
    --enable-debug \
    --disable-hand-vec \
    --with-hdf5=/path/to/hdf5 \
    --with-gsl=/path/to/gsl \
    --with-tbbmalloc=/path/to/tbb/ \
    --with-arm-fftw=/opt/arm/armpl-19.0.0_ThunderX2CN99_SUSE-12_arm-hpc-compiler_19.0_aarch64-linux \
    CC=mpicc \
    LDFLAGS="-mcpu=native -armpl" \
    CFLAGS="-mcpu=native -armpl"
```

To run the code I used :

```
mpirun -np 8 -npernode 2 --report-bindings --bind-to socket --mca btl ^openib  $HOME/SWIFT/bin/swift_mpi --cosmology --hydro --self-gravity --stars -v 1 --threads=32 --pin -n 1024 eagle_25.yml
```

If instead you run with openib, then the code works

```
mpirun -np 8 -npernode 2 --report-bindings --bind-to socket --mca btl ^ucx --mca btl_openib_allow_ib 1   $HOME/SWIFT/bin/swift_mpi --cosmology --hydro --self-gravity --stars -v 1 --threads=32 --pin -n 1024 eagle_25.yml
```
Or alternatively build with OpenMPI v3 and that works too.  Let me know if you need more info.

**Comment by hoopoepg** [comment]
@jw292 what are configuration flags for arm-fftw module?
and what source and version of fftw was used?

**Comment by hoopoepg** [comment]
@jw292 hi
we tried to reproduce crash but without success. but I found some strange in your command line: when you run OMPI over openib you set command line ```--mca btl ^ucx``` which is incorrect, you should set ```--mca pml ^ucx``` instead. could you try to run your experiment using pml ucx and add switches ```--mca opal_common_ucx_opal_mem_hooks 1 -x UCX_MEM_MMAP_HOOK_MODE=none``` ?

thank you

**Comment by yosefe** [comment]
@jw292 ping

**Comment by yosefe** [comment]
closing due to no response from issue author
