### ISSUE TITLE
dc_mlx5.c:1252 UCX  ERROR error modifying DCT to RTR: Invalid argument

### ISSUE THREAD

**Issue by bartoldeman** [openucx/ucx#3245]
Using all self-compiled UCX 1.5.0rc1, 1.5.0, master using rdma-core 21 and 22, openmpi 3.1.2 using the UCX pml. dc_mlx5 transport is enabled. I am getting this error while trying to run a simple MPI Hello World program (even with `mpiexec -n 1 hello`):
```
dc_mlx5.c:1244 UCX  ERROR error modifying DCT to RTR: Invalid argument
pml_ucx.c:208 Error: Failed to create UCP worker
Hello world, rank 0 out of 1 processors
```
(so it does run after the error messages) Where would this come from? The same binaries work without error another cluster with an older CentOS (7.5 vs 7.6) and older hardware (ConnectX-4 vs ConnectX-5). Both use the 'inbox' kernel drivers. It works ok on both clusters with `UCX_TLS=rc`.

Differences:
working cluster: CentOS 7.5,
```
modinfo mlx5_core
filename:       /lib/modules/3.10.0-862.14.4.el7.x86_64/kernel/drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko
...
```
lspci
```
04:00.0 Infiniband controller: Mellanox Technologies MT27700 Family [ConnectX-4]
        Subsystem: Mellanox Technologies Device 0013
        Physical Slot: 0-4
        Flags: bus master, fast devsel, latency 0, IRQ 24, NUMA node 0
        Memory at 90000000 (64-bit, prefetchable) [size=32M]
        Expansion ROM at 94700000 [disabled] [size=1M]
        Capabilities: <access denied>
        Kernel driver in use: mlx5_core
        Kernel modules: mlx5_core
```

non-working cluster: CentOS 7.6,
modinfo mlx5_core
```
filename:       /lib/modules/3.10.0-957.5.1.el7.x86_64/kernel/drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko.xz
...
```
lspci:
```
5e:00.0 Infiniband controller: Mellanox Technologies MT27800 Family [ConnectX-5, PCIe 3.0]
        Subsystem: Mellanox Technologies Device 0027
        Flags: bus master, fast devsel, latency 0, IRQ 46, NUMA node 0
        Memory at ba000000 (64-bit, prefetchable) [size=32M]
        Expansion ROM at b8800000 [disabled] [size=1M]
        Capabilities: <access denied>
        Kernel driver in use: mlx5_core
        Kernel modules: mlx5_core
```

I could ask the admins to downgrade a node to CentOS 7.5 to see if it helps -- I remember UCX was working fine without these errors, and with the same binaries, before.

**Comment by bartoldeman** [comment]
@Artemy-Mellanox wrote that the kernel used here does not support dc_mlx5 in any case.
I found out that in both situations dc_mlx5 cannot be used, but in the newer CentOS kernel ucx_info misdetects that dc_mlx5 is available and tries to use it:

older
```
$ uname -r
3.10.0-862.14.4.el7.x86_64
$ ucx_info -d | grep Transport
#   Transport: self
#   Transport: tcp
#   Transport: rc
#   Transport: rc_mlx5
#   Transport: ud
#   Transport: ud_mlx5
#   Transport: cm
#   Transport: mm
#   Transport: mm
#   Transport: cma
```
newer:
```
$ uname -r
3.10.0-957.5.1.el7.x86_64
$ ucx_info -d | grep Transport
#   Transport: self
#   Transport: tcp
#   Transport: rc
#   Transport: rc_mlx5
#   Transport: dc_mlx5
#   Transport: ud
#   Transport: ud_mlx5
#   Transport: cm
#   Transport: mm
#   Transport: mm
#   Transport: cma
```
so I can simply list all transports except dc_mlx5 in UCX_TLS (that is `UCX_TLS=self,tcp,rc,rc_mlx5,ud,ud_mlx5,cm,mm,cma`).

So the question remains then why dc_mlx5 support is misdetected.

**Comment by bartoldeman** [comment]
@Artemy-Mellanox sent me a patch yesterday and I confirmed that it works by no longer misdetecting dc_mlx5. I guess this issue will be closed automatically once the patch makes it way into git.

**Comment by yosefe** [comment]
Fixed in master
