### ISSUE TITLE
Help to debug GPU issue

### ISSUE THREAD

**Issue by dimaleks** [openucx/ucx#3268]
Hello!

I have a problem and I'm stuck with it for a few days now.
I'm using master branch UCX 59a6f045ae39 with OMPI 4.0.1 on a machine with 1 socket and 4 V100 GPUs connected by NVlink.
osu_latency benchmark for Device to Device works fine and seems reasonable fast.
My own small simple example runs fine too.

However, when I compile and run my large code, I can't get UCX to work with GPU memory.
It seems that UCX treats the CUDA pointer and tries to use CPU path for the exchange as I get an error like this:
`[1551197569.692606] [barry:28085:0]         cma_ep.c:113  UCX  ERROR process_vm_readv delivered 0 instead of 160928, error message Bad address`

Seems that `process_vm_readv` shouldn't be called here at all.

On the other hand running with `mpirun --mca btl smcuda,self --mca pml ^ucx` looks working, no errors occur and the output is as expected.

I tried setting `UCX_LOG_LEVEL` to higher values, but I don't know what I should be looking at. What could be a debugging strategy in this case? Any chance to understand why UCX chooses one path but not another?

Thank you!

**Comment by yosefe** [comment]
@dimaleks is it possible that in the code, memory is allocated before the call to MPI_Init()?

**Comment by dimaleks** [comment]
I saw that this situation may be problematic in another issue, and made sure MPI_Init() is called first.

**Comment by bureddy** [comment]
@dimaleks can you check with -x UCX_MEMTYPE_CACHE=n.
currently we have know issues with  uda mem type cache if 
      - cuda allocations are done before MPI_init 
      - if application link to libcudart statically.

**Comment by dimaleks** [comment]
Hi @bureddy 
Thanks very much, looks like the code's working with that variable set!
I'm using CMake, and by default it links cudart_static, I was not aware this is problematic.

Are there any performance or other implications with UCX_MEMTYPE_CACHE=n ?

**Comment by bureddy** [comment]
This issue is reported just recently : https://github.com/openucx/ucx/issues/3210

UCX_MEMTYPE_CACHE=y is optimization to save the cost of pointer type checking with cudacudaPointerGetAttributes() which could be 0.2 - 0.5us.
