### ISSUE TITLE
fetch-and-add instead of cswap for header update in MM active messages

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#328]
Note from @sameerkm : apparently for power platform it is preferable to use fadd instead of cswap. This is something that we have to test.

**Comment by yosefe** [comment]
The algorithm depends on cswap. If we want to use fadd, need to modify it, potentially making it less optimal.

**Comment by shamisp** [comment]
Less optimal for x86_64 but more optimal for Power8. So, there is a chance that we would have to move it to UCS and make it platform depended. We would have to evaluate on both platforms and decide.

**Comment by yosefe** [comment]
after talk with IBM, seems we can keep the existing algorithm, just add optimized cswap for power
