### ISSUE TITLE
Question: UCX on Cray Shasta / Slingshot

### ISSUE THREAD

**Issue by angainor** [openucx/ucx#3306]
Does anyone know if UCX in its current implementation is going to work on the new Cray architecture? If not, are there plans for such implementation? It might be a naive question, but I can not find any info whether Shasta uses uGNI, and whether UCX is compatible with it.

**Comment by yosefe** [comment]
UCX supports current Cray arch, namely Gemini and Aries. UCX is intended to continue and support new generations, and it could be tested once they become available.

**Comment by angainor** [comment]
@yosefe Great, thanks for the info!
