### ISSUE TITLE
Is it safe to share single ucs_mpool_t across multi iface

### ISSUE THREAD

**Issue by yuq** [openucx/ucx#3362]
Hi, I find in cuda TLs that there's one ucs_mpool_t for each iface, so guess if could use one ucs_mpool_t for all cuda iface. I can't see there's mutex lock when get/put from/to this pool, so it's not thread safe. So seem it depends on the answer of the following question:
1. will multi iface be in multi threads?
2. does one iface only resides in signle thread?

**Comment by brminich** [comment]
multi-threading is implemented on UCP level. Either separate worker/s is used for each thread (which means separate iface) or single worker is shared by several threads (and in this case every UCP API call, including progress, is guarded by worker lock).
So, in general it is not safe to use the same mpool for all ifaces.

**Comment by yuq** [comment]
OK, thanks for the answer.

**Comment by yosefe** [comment]
it's possible to share mpool on different iface instances if they are on the same UCT worker. In this case, UCP thread safety model will cover this. Currently there is infrastructure for sharing iface resources on a worker: uct_worker_tl_data_get/uct_worker_tl_data_put
