### ISSUE TITLE
cuda-aware example fails

### ISSUE THREAD

**Issue by robertsawko** [openucx/ucx#3386]
Hi,

I am testing NVIDIA cuda-aware Jacobi from [here](https://github.com/NVIDIA-developer-blog/code-samples/tree/master/posts/cuda-aware-mpi-example) on a P8+4xP100 cluster.

I have compiled my own ucx version 1.5.0:
```bash
$ucx_info -v
# UCT version=1.5.0 revision 4185bbd
# configured with: --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/gpfs/paragon/local/apps/dev//compiler/gcc/6.4/ucx/1.5.0-cuda --enable-mt --without-java --with-cuda=/gpfs/paragon/local/apps/cuda/9.2 --disable-doxygen-doc --with-knem=/opt/knem-1.1.2.90mlnx2

```

I followed this up with openmpi 3.1.2 specifying `--with-ucx` and `--with-cuda`.

Then I modify NVIDIA example to account for local rank environmental variable and run both tests:
```bash
bsub << EOF
#BSUB -n 4
#BSUB -q $QUEUE
#BSUB -x
#BSUB -R "span[ptile=4]"
#BSUB -gpu "num=4"

ulimit -s 10240
mpirun -report-bindings \\
    -map-by ppr:2:socket -bind-to core \\
    ./bin/jacobi_cuda_aware_mpi -t 4 1
EOF
```

Unfortunately cuda-aware variant segfaults:
```
[pge422:41447:0:41447] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x10024be1140)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
==== backtrace ====
 0 0x0000000000075a58 group_register()  mca_base_var_group.c:0
 1 0x00000000000771b4 mca_base_framework_register()  ???:0
 2 0x00000000000773a0 mca_base_framework_open()  ???:0
 3 0x0000000000006fdc mca_pml_cm_component_open()  pml_cm_component.c:0
 4 0x000000000006863c mca_base_framework_components_open()  ???:0
 5 0x0000000000111e54 mca_pml_base_open()  pml_base_frame.c:0
 6 0x0000000000077464 mca_base_framework_open()  ???:0
 7 0x000000000006baa8 ompi_mpi_init()  ???:0
 8 0x00000000000a6330 MPI_Init()  ???:0
 9 0x0000000010002984 Initialize()  ???:0
10 0x0000000010001a50 main()  ???:0
11 0x0000000000024700 generic_start_main.isra.0()  libc-start.c:0
12 0x00000000000248f4 __libc_start_main()  ???:0
===================
```

Please advise.

**Comment by bureddy** [comment]
@robertsawko  I could not repro it on my setup p9 + 4xV100
```

[root@ibm-p9-012 src]#ucx_info -v
# UCT version=1.5.0 revision 4185bbd
# configured with: --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/mnt/nfsshare/users/devendar/ucx-fix/install --with-cuda=/usr/local/cuda/
[root@ibm-p9-012 src]# ompi_info --version
Open MPI v3.1.3a1

```

```
[root@ibm-p9-012 src]# mpirun  -np 4 -map-by ppr:2:socket -bind-to core  --allow-run-as-root -mca btl_openib_warn_default_gid_prefix 0 --report-bindings  ../bin/jacobi_cuda_normal_mpi -t 4 1
[ibm-p9-012:15477] MCW rank 0 bound to socket 0[core 0[hwt 0-3]]: [BBBB/..../..../..../..../..../..../..../..../..../..../..../..../..../..../....][..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../....]
[ibm-p9-012:15477] MCW rank 1 bound to socket 0[core 1[hwt 0-3]]: [..../BBBB/..../..../..../..../..../..../..../..../..../..../..../..../..../....][..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../....]
[ibm-p9-012:15477] MCW rank 2 bound to socket 1[core 16[hwt 0-3]]: [..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../....][BBBB/..../..../..../..../..../..../..../..../..../..../..../..../..../..../....]
[ibm-p9-012:15477] MCW rank 3 bound to socket 1[core 17[hwt 0-3]]: [..../..../..../..../..../..../..../..../..../..../..../..../..../..../..../....][..../BBBB/..../..../..../..../..../..../..../..../..../..../..../..../..../....]
Topology size: 4 x 1
Local domain size (current node): 4096 x 4096
Global domain size (all nodes): 16384 x 4096
Starting Jacobi run with 4 processes using "Tesla V100-SXM2-16GB" GPUs (ECC enabled: 4 / 4):
Iteration: 0 - Residue: 0.250000
Iteration: 100 - Residue: 0.002397
Iteration: 200 - Residue: 0.001204
Iteration: 300 - Residue: 0.000804
Iteration: 400 - Residue: 0.000603
Iteration: 500 - Residue: 0.000483
Iteration: 600 - Residue: 0.000402
Iteration: 700 - Residue: 0.000345
Iteration: 800 - Residue: 0.000302
Iteration: 900 - Residue: 0.000269
Stopped after 1000 iterations with residue 0.000242
Total Jacobi run time: 0.9625 sec.
Average per-process communication time: 0.0766 sec.
Measured lattice updates: 69.68 GLU/s (total), 17.42 GLU/s (per process)
Measured FLOPS: 348.39 GFLOPS (total), 87.10 GFLOPS (per process)
Measured device bandwidth: 4.46 TB/s (total), 1.11 TB/s (per process)
```

From your  backtrace,  ooks like some basic MPI startup issue during MPI_Init.  Did you run any sanity tests with your MPI build?

**Comment by robertsawko** [comment]
Yes, I think you must be right even the IMB doesn't run on this. Checking my compilation now...

Part of the reason why I am doing this is to learn how this is supposed to work. Do I need `gdrcopy` in UCX to make it faster?

**Comment by robertsawko** [comment]
Hmm, I cannot see what I have done wrong. I went back and rebuilt with 3.1.3:

```
Open MPI configuration:
-----------------------
Version: 3.1.3
Build MPI C bindings: yes
Build MPI C++ bindings (deprecated): no
Build MPI Fortran bindings: mpif.h, use mpi
MPI Build Java bindings (experimental): no
Build Open SHMEM support: yes
Debug build: no
Platform file: (none)

Miscellaneous
-----------------------
CUDA support: yes
PMIx support: internal
 
Transports
-----------------------
Cisco usNIC: no
Cray uGNI (Gemini/Aries): no
Intel Omnipath (PSM2): no
Intel SCIF: no
Intel TrueScale (PSM): no
Mellanox MXM: yes
Open UCX: yes
OpenFabrics Libfabric: no
OpenFabrics Verbs: yes
Portals4: no
Shared memory/copy in+copy out: yes                                                                                             [3/8361]
Shared memory/Linux CMA: yes
Shared memory/Linux KNEM: yes
Shared memory/XPMEM: no
TCP: yes
 
Resource Managers
-----------------------
Cray Alps: no
Grid Engine: no
LSF: yes
Moab: no
Slurm: yes
ssh/rsh: yes
Torque: no
 
OMPIO File Systems
-----------------------
Generic Unix FS: yes
Lustre: no
PVFS2/OrangeFS: no
```
and I cannot see any error appearing in the compilation.

**Comment by robertsawko** [comment]
No, I am sorry. I seem to be confused. My test script was wrong. I have now retrated all changes and confirm that Intel Memory Benchmark works ok, so sanity check is passed. Sorry for  the confusion.

**Comment by robertsawko** [comment]
So after testing a little bit more it seems to be me that my affinity setting is the culprit. After removing all `map-by` all examples seem to work. I still get the UCX warning about memory at the end and the results are poor in the sense that cuda-aware Jacobi is slower. I also randomly got that error for normal-mpi  and rank 8

```
It appears as if there is not enough space for mpirun: Forwarding signal 18 to job
ared_mem_cuda_pool.pge418 (the shared-memory backing
file). It is likely that your MPI job will now either abort or experience
performance degradation.

  Local host:  pge418
  Space Requested: 134217736 B
  Space Available: 1875968 B
--------------------------------------------------------------------------
[pge418:57483] create_and_attach: unable to create shared memory BTL coordinating strucure :: size 134217728
[pge418:57486:0:57486] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x1000c7e4658
```

**Comment by bureddy** [comment]
@robertsawko gdrcopy improves the  latency of the small messages.   
Can you get UCX warning coming at the end? This might be related to testcase if memory is not free before MPI_Finalize. You can ignore them or silence with UCX_LOG_LEVEL=error.

is  normal-mpi  means without UCX?

**Comment by robertsawko** [comment]
Thanks, I am going to inspect the code from NVIDIA a bit closer today and try to find this memory that is not being freed. I cannot find any other warning other than the one I sent above about being unable to create "shared memory byte transfer layer"? This happens only on "normal-mpi" when I've got more than one socket/numa.

By the way this code is I believe what driven [this post](https://devblogs.nvidia.com/benchmarking-cuda-aware-mpi/).

> is normal-mpi means without UCX?

No, all my runs are with UCX/1.5.0 but the normal-mpi jacobi code simpy explicitly allocated host memory and this is what gets sent. The cuda aware one sends GPU memory.

**Comment by robertsawko** [comment]
The exact wording of the warning I get is this:
```
[1552951307.968931] [pge418:56294:0]  memtype_cache.c:137  UCX  WARN  destroying inuse address:0x3fff5a018000
```

**Comment by bureddy** [comment]
@robertsawko Yes, this warning is because of cuda memory allocated is not freed before MPI_Finalize. this is harmless you can ignore if you want.

Regarding,  "shared memory byte transfer layer" error,  Looks like it openmpi sm BTL smcuda component init issue because of tmp space on your system.  don't need to initialize BTLs component when using UCX.  can you try ` "-mca pml ucx -mca btl ^smcuda,openib "`

**Comment by robertsawko** [comment]
Sorry, I am too slow for this...

I have tried by fixing btl and it works although it's slower than the normal-mpi version. So I assume it's the classic power issue that you need to fix the binding. I add `-map-by` and it segfaults.

Also, I am realising now that I must have messed something with the configuration after all but I am not sure what it is.

When I do `ucx_info -b` I see
```
...
#define HAVE_CUDA                 0
...
```
But when I configure I see:

```
checking cuda.h usability... yes 
checking cuda.h presence... yes 
checking for cuda.h... yes 
checking for cuPointerGetAttribute in -lcuda ... yes 
checking cuda_runtime.h usability... yes 
checking cuda_runtime.h presence... yes 
checking for cuda_runtime.h... yes 
checking for cuPointerGetAttribute in -lcuda ... (cached) yes 
checking gdrapi.h usability... no
checking gdrapi.h presence... no
checking for gdrapi.h... no
configure: WARNING: GDR_COPY not found
configure: ROCm path was not specified. Guessing ...
```

which is why I initially thought that UCX with cuda-awareness built fine.

**Comment by robertsawko** [comment]
I clearly am doing something wrong so I would appreciate a second pair of eyes looking over it. Here's my compilation script that I submit as a batch job.

```bash
../ucx-${VERSION}/contrib/configure-release \\
    --prefix=$INSTALL_DIR \\
    --enable-optimizations \\
    --disable-debug \\
    --disable-params-check \\
    --with-avx \\
    --enable-mt \\
    --without-java \\
    --with-cuda=$CUDA_ROOT \\
    --disable-doxygen-doc \\
    --with-knem=\${KNEM_DIR} \\
    && make -j16 && rm -rf $INSTALL_DIR && make install
```
And associated log
[build-ucx-1.5.0.txt](https://github.com/openucx/ucx/files/2989396/build-ucx-1.5.0.txt). Sorry to dump it on you like this.

**Comment by bureddy** [comment]
Build looks fine.   can you get "ucx_info -d" output?

Regarding the performance,  what is your topology (nvidia-smi topo -m) ? how many nodes, cores you are running?

**Comment by robertsawko** [comment]
> Build looks fine. can you get "ucx_info -d" output?

Can I ask why do you say this? Is `ucx_info -b` not a diagnostic here?

> Regarding the performance, what is your topology (nvidia-smi topo -m) ? how many nodes, cores you are running?

```
          GPU0   GPU1    GPU2    GPU3    mlx5_0  mlx5_1  CPU Affinity
GPU0     X  NV2 SYS SYS SYS SYS 0-63
GPU1    NV2  X  SYS SYS SYS SYS 0-63
GPU2    SYS SYS  X  NV2 NODE    NODE    64-127
GPU3    SYS SYS NV2  X  NODE    NODE    64-127
mlx5_0  SYS SYS NODE    NODE     X  PIX
mlx5_1  SYS SYS NODE    NODE    PIX  X
```
Is that readable? The formatting is slightly broken when I copy this over.

I run 2, 4, 8 rank tests. We have run tests on MareNostrum P9 and PizDaint (different topologies, I know), and cuda-aware was consistently better. Sometimes by very little.

I forgot about this quirk of this cluster: the double infiniband fabric. I wonder if this is "correctly" wired up. It seems from `nvidia-topo -m` that they are attached only to one socket. Am I reading this right?

**Comment by bureddy** [comment]
I checked ucx 1-.5.0 and it dont seen any discrepancy with ucx_info -b.  is there any chance ucx_info is from system default ucx_info instead of your build one?

```
ucx_info -b | grep CUDA
#define HAVE_CUDA                 1
#define HAVE_CUDA_H               1
#define HAVE_CUDA_RUNTIME_H       1
#define UCX_CONFIGURE_FLAGS       "--enable-gtest --with-valgrind --enable-profiling --enable-frame-pointer --enable-stats --enable-memtrack --enable-fault-injection --enable-debug-data --enable-mt --prefix=/.autodirect/mtrswgwork/devendar/workspace/CUDA/ucx/install --enable-debug --with-cuda --with-gdrcopy --with-mpi" 
```
You have  poor performing links in the topology,   
          1.  intra-node two GPUs communicating to other two over QPI.  UCX currently does fragmented cudacpy which is not good.
          2. Yes both NICs are on same scoket.  GPUDirect RDMA performance from GPU0 and GPU1 will be too bad.

Can you try with 4 ranks (2 ranks/node) with devices GPU2 and GPU3. use option CUDA_VISIBLE_DEVICES=2,3

**Comment by robertsawko** [comment]
Thanks, I think we're onto something here, but this looks quite confusing to me. I am splitting into sections, sorry.
 
### UCX version
> is there any chance ucx_info is from system default ucx_info instead of your build one?

I don't think so. System ucx does this:
```bash
$ /opt/ucx/bin/ucx_info -v 
# UCT version=1.2.2947
# configured with: --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check
$ /opt/ucx/bin/ucx_info -b | grep -i cuda

# I mean no output!
```
This UCX is very old and I had issues with it. You helped me with it in the past actually by advising to upgrade, which I did. The sysadmins haven't updated system one so I keep my own in Lmod hierarchy. I've got several versions of it as there are other users and I don't want to interfere with their production runs. This is the one I am testing right now:

```bash
ucx_info -v
# UCT version=1.5.0 revision 4185bbd
# configured with: --prefix=/gpfs/paragon/local/apps/dev//compiler/gcc/6.4/ucx/1.5.0-cuda --enable-optimizations --disable-debug --disable-params-check --with-avx --enable-mt --without-java --with-cuda=/gpfs/paragon/local/apps/cuda/9.2 --disable-doxygen-doc --with-knem=/opt/knem-1.1.2.90mlnx

$ ucx_info -b | grep -i cuda
#define HAVE_CUDA                 0
```
To me, this looks contradictory. Is it possible this is a separate bug? About reporting? On P9 though it works fine and I see what I expect.
```
#define HAVE_CUDA                 1
#define HAVE_CUDA_H               1
#define HAVE_CUDA_RUNTIME_H       1
``` 

### Links in the topology
>  intra-node two GPUs communicating to other two over QPI.

QPI? You don't mean [this](https://en.wikipedia.org/wiki/Intel_QuickPath_Interconnect)? This is a `ppc64le` machine

> UCX currently does fragmented cudacpy which is not good.

Could you just send me a link or a document I can have a look. I don't understand what *fragmented* cuda copy means.

> Yes both NICs are on same scoket. GPUDirect RDMA performance from GPU0 and GPU1 will be too bad.

Yes, I mentioned this to our sysadmins several times. I will try to raise it though their official enhancement request system... Can you point me to anything that could give me an idea of how much performance we're losing because of this?

### Tests with CUDA_VISIBLE_DEVICES

This is very awkward to script as I think I also want to keep all ranks on the second socket. I wrote some scripting to generate the rankfiles though and submitted the benchmark. The cluster is very busy right now so they still haven't gone through. When I get results I will post it.

### Acknowledgement

Thanks for your help, I really appreciate it. It has been quite insightful for me already.

**Comment by robertsawko** [comment]
This is what I submitted for CUDA-aware:

```bash
rank=0
core=0
rm rankfile.2 2> /dev/null
for h in ${LSB_HOSTS};
do
    echo rank $rank=$h slot=1:${core} >> rankfile.2
    rank=$(($rank+1))
    core=$((($core+1) % 2))
done

export CUDA_VISIBLE_DEVICES=2,3
mpirun -report-bindings \
    -rf rankfile.2 \
    -mca pml ucx -mca btl ^smcuda,openib \
    ./bin/jacobi_cuda_aware_mpi -fs -t 2 1

...
# Result
Average per-process communication time: 0.1197 sec
```

Normal MPI

```bash
mpirun -report-bindings \
    ./bin/jacobi_cuda_normal_mpi -fs -t 2 1
...
# Result
Average per-process communication time: 0.0524 sec
```

The 4 and 8 still haven't gone through, but this is already symptomaic of my problem. It's 2x slower!

**Comment by bureddy** [comment]
Is  both cases (Normal and CUDA aware) are running with same bindings ( CUDA_VISIBLE_DEVICES=2,3  and -rf rankfile.2)? if not, can you try it.
BTW, is there any possibility get access to the setup?

**Comment by robertsawko** [comment]
### Tests

Yes, everything is run with pre-generated rankfile and `CUDA_VISIBLE_DEVICES=2,3`. Here's the output in tabular form for communication time:

|ranks|hosts|cuda-aware|normal|
|-------|--------|----------------|---------|
|2|1|0.1197|0.0470|
|4|2|0.2302|0.0830|
|8|4|-|0.1095|0.1095|

On other clusters we tried (with different MPIs) the same test is consistently better for `cuda-aware`. Here normal is like 2x faster. 8 ranks of cuda aware segfaults, somewhat randomly with:

```
[pge420:120904] MCW rank 0 bound to socket 1[core 8[hwt 0-7]]: [......../......../......../......../......../......../......../........][BBBBBBBB/......../....
[pge420:120904] MCW rank 1 bound to socket 1[core 9[hwt 0-7]]: [......../......../......../......../......../......../......../........][......../BBBBBBBB/....
[pge118:40964] MCW rank 2 bound to socket 1[core 8[hwt 0-7]]: [......../......../......../......../......../......../......../........][BBBBBBBB/......../.....
[pge118:40964] MCW rank 3 bound to socket 1[core 9[hwt 0-7]]: [......../......../......../......../......../......../......../........][......../BBBBBBBB/.....
[pge108:74217] MCW rank 4 bound to socket 1[core 8[hwt 0-7]]: [......../......../......../......../......../......../......../........][BBBBBBBB/......../.....
[pge108:74217] MCW rank 5 bound to socket 1[core 9[hwt 0-7]]: [......../......../......../......../......../......../......../........][......../BBBBBBBB/.....
[pge130:109378] MCW rank 6 bound to socket 1[core 8[hwt 0-7]]: [......../......../......../......../......../......../......../........][BBBBBBBB/......../....
[pge130:109378] MCW rank 7 bound to socket 1[core 9[hwt 0-7]]: [......../......../......../......../......../......../......../........][......../BBBBBBBB/....
[pge108:74222:0:74222] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x1003cde1140)
==== backtrace ====
 0 0x0000000000075718 group_register()  mca_base_var_group.c:0
 1 0x0000000000076e74 mca_base_framework_register()  ???:0
 2 0x0000000000077060 mca_base_framework_open()  ???:0
 3 0x000000000006baec ompi_mpi_init()  ???:0
 4 0x00000000000a6430 MPI_Init()  ???:0
 5 0x0000000010002984 Initialize()  ???:0
 6 0x0000000010001a50 main()  ???:0
 7 0x0000000000024700 generic_start_main.isra.0()  libc-start.c:0
 8 0x00000000000248f4 __libc_start_main()  ???:0
===================
```

### Access

> BTW, is there any possibility get access to the setup?

Do you mean like get a login session? I agree it would be easier, but these are not systems managed by us. I will ask today.

Meanwhile, I can probably offer a Webex session with a screenshare, I could send you my details and we could arrange it.

**Comment by robertsawko** [comment]
@bureddy , let me know how you want to proceed. I have sent you a Linkedin message as I couldn't locate your work email on the Internet (probably a good thing). For now I can only offer a webex session sometime in the week, but we could try to get you a debug account too, but apparently it's a but I was told webex with shared screen is the preference. I have reasonably free week ahead so could be very flexible. Thanks.

**Comment by bureddy** [comment]
@robertsawko based on our offline discussion, were you able to check performance with GPUDirectRDMA module?
Do you still have any issues? if not can we close this?

**Comment by robertsawko** [comment]
Do you mind waiting a little with this? I am still asking for the kernel modules to be installed... it's not a cluster we manage so things take time. I think they are reviewing wether the whole OFED stack needs updating. Thanks.

**Comment by bureddy** [comment]
@robertsawko Sure.

**Comment by robertsawko** [comment]
@bureddy progress!

The sysadmins have installed `nv_peer_mem` for memory and I am currently testing it. Unfortunately just straight recompilation of an OSU benchmark didn't seem to have done anything. Sometimes the benchmark works and sometimes it produces a core dump. I am attaching a working and non working tests below. 

Few questions:
 * do I need to recompile ucx and openmpi consistently on the nodes that contain the the module?
 * does the `nv_peer_mem` cover inter or intra node comms or both?

[test-failed.txt](https://github.com/openucx/ucx/files/3320952/test-failed.txt)
[test-success.txt](https://github.com/openucx/ucx/files/3320953/test-success.txt)

**Comment by robertsawko** [comment]
I've been also looking through the new issues and this problem looks awfully similar to this one #3550 but the core dump occurs somewhat randomly.

**Comment by bureddy** [comment]
@robertsawko 
you don't need to recompile ucx and openmpi.  UCX figure it out if module is loaded or not during runtime.
nv_peer_mem will improve the performance of inter node case where IB communication is used.

Looks like crash is while initializing the CUDA context in the benchmark.  It seems more of CUDA setup issue than UCX. do you see any stale process hanging on the GPU when you see this. check  section " Processes: " in nvidia-smi output

**Comment by robertsawko** [comment]
Yes, this might be a completely separate issue we are debugging here... I am seeing this random crash on any node with or without the `nv_peer_mem` module.

I have been checking `nvidia-smi` process section and I cannot see any processes there. Also, I know I am using the nodes in exclusive mode so I should be the only person touching these gpus. I think there might be a ganglia monitoring application running in there and I wonder if it's not causing some issues. I also occasionally see `irq/555-nvidia` or `irq/39-nvidia` processes when I `top`.

**Comment by robertsawko** [comment]
A colleague of mine also gave me an idea here that maybe the system is just outdated too much and the kernel-driver combination is no longer supported:
```
$uname -a
Linux pge330 3.10.0-514.el7.ppc64le #1 SMP Wed Oct 19 11:27:06 EDT 2016 ppc64le ppc64le ppc64le GNU/Linux
$nvidia-smi 
Tue Jun 25 16:46:44 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
```
Is that a possibility? I've been playing in an interactive mode running same application time after time with no consistency. Sometimes segfault sometimes ok. What do you think about this?

**Comment by bureddy** [comment]
what is your cuda version? You can check compatibility for your runtime with driver here : https://docs.nvidia.com/deploy/cuda-compatibility/

**Comment by yosefe** [comment]
@robertsawko ping

**Comment by robertsawko** [comment]
I am really sorry guys. This dropped under my radar due to a mix of commitment and fulfilled holiday plans. I will definitely test it over the next week and get back to you.

**Comment by eric-haibin-lin** [comment]
Any update on this?

**Comment by robertsawko** [comment]
Just to confirm. This is now working on the latest version of UCX and OpenMPI. Thanks.
