### ISSUE TITLE
CUDA/ROCM Managed memory behavior with and w/o memtype cache

### ISSUE THREAD

**Issue by bureddy** [openucx/ucx#3391]
we have a change in behavior for MANAGED memory with and w/o MEM_TYPE Cache.  When mem type cache is enabled, we are detecting MANAGED and non-MANAGED correctly .  But with cache off,  CUDA/ROCM  MDs mem_type_owned() returns true if memory is CUDA/ROCM.  In case of managed memory it returns FALSE and memory is treated as HOST.  

We need to discuss on how to handle this? one way is to change UCT API mem_type_owned() to return mem_type id instead of true/false.  (or) add a another MD to own MANAGED memory.

 @Akshay-Venkatesh @yuq @yosefe

**Comment by Akshay-Venkatesh** [comment]
Ideally, what mem_type_owned() returns shouldn't depends on whether mem_type cache is turned on/off. Should we be discussing how to decouple that?

**Comment by bureddy** [comment]
@Akshay-Venkatesh mem_type_owned() return value is not depending on mem_type cache is on/off.  
Problem is MANAGED memory is treated as 
      - MANAGED  memory with mem_type cache is ON.  
      - HOST memory with mem_type cache is OFF

**Comment by jakirkham** [comment]
@bureddy, is this issue still live? Noticed your xref'd PR was merged. Unclear if there was more to do here or not.

**Comment by bureddy** [comment]
Issue is fixed.

**Comment by jakirkham** [comment]
Thanks for confirming. Is this in a release? If so, which one?

**Comment by bureddy** [comment]
its in 1.7.x
