### ISSUE TITLE
dc_x / ODP tests can take ~20m to complete (instead of few seconds)

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#3409]
when fixed, neet to revert https://github.com/openucx/ucx/pull/3406

**Comment by yosefe** [comment]
https://redmine.mellanox.com/issues/1723591 (Mellanox internal link)

**Comment by dmitrygladkov** [comment]
ok to close?

**Comment by yosefe** [comment]
fixed passing min_rnr_timer in modify_dct
