### ISSUE TITLE
ucx_perftest -t ucp_add hangs

### ISSUE THREAD

**Issue by lyu** [openucx/ucx#3471]
Starting from 5f2eabc, the `ucp_add` test of `ucx_perftest` hangs on our ConnectX-5 cluster. The put and get tests work fine, and I haven't tried other atomic ops.

Stack trace shows that it is stuck in the `ucp_worker_flush` at the end of the test.

**Comment by yosefe** [comment]
@lyu #3457 should fix the issue should for rc/dc transport

**Comment by lyu** [comment]
@yosefe The problem is gone. Thank you!
Closing.
