### ISSUE TITLE
Building UCX with CUDA and NumaCtl

### ISSUE THREAD

**Issue by moravveji** [openucx/ucx#3494]
Dear developers,

I am hoping to build UCX with CUDA/10.1 and NumaCtl on a CentOS 7.5 compute nodes of our cluster. Our nodes have 4xP100 Nvidia GPUs, and are connected via the InfiniBand fabric. My intention is very close to the post #3386. 

I get an error with the "configure-release" step as the following:
```
CC       algorithm/libucs_la-crc.lo
gcc: error: unrecognized command line option '--with-cuda=/software/CUDA/10.1.105'
gcc: error: unrecognized command line option '--with-numa=/software/numactl/2.0.11-GCCcore-6.4.0'
gcc: error: unrecognized command line option '--with-avx'
gcc: error: unrecognized command line option '--without-java/lib/ucx"'
make[2]: *** [algorithm/libucs_la-crc.lo] Error 1
make[2]: Leaving directory `/work/UCX/from-source/ucx/src/ucs'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/work/UCX/from-source/ucx'
make: *** [all] Error 2
```

Here is the relevant part of my compile script:
```
export opt_prefix="--prefix=${dir_inst}"
export opt_cuda="--with-cuda=${EBROOTCUDA}"
export opt_numa="--with-numa=${dir_numa}"  # "--disable-numa"
export opt_optim="--enable-optimizations"
export opt_debug="--disable-debug"
export opt_params="--disable-params-check"
export opt_avx="--with-avx"
export opt_mt="--enable-mt"
export opt_java="--without-java"
export options="${opt_prefix} ${opt_cuda} ${opt_numa} \
${opt_optim} ${opt_debug} ${opt_params} ${opt_avx} ${opt_mt} ${opt_java}"

cd ${dir_src}

./autogen.sh
[[ $? -eq 0 ]] || (echo "Error: ./autogen.sh failed"; exit 1)

./contrib/configure-release "${options}"
[[ $? -eq 0 ]] || (echo "Error: configure-release failed"; exit 1)

make -j1
[[ $? -eq 0 ]] || (echo "Error: make failed"; exit 1)
```

Do you have any idea if I am making any mistake somewhere, which I cannot spot?
I presume that the --with-avx, --with-cuda and --with-numa options must be passed to the "configure-release" step; however, the configure fails to accept my offering!

I will be grateful to hear your feedback.

Kind regards,
Ehsan

**Comment by yosefe** [comment]
@moravveji  looks like the --with arguments are passed to gcc for some reason..
can you pls post the first few lines of config.log? it should show the expanded ./configure command

**Comment by moravveji** [comment]
Alright. Here it goes ...
`  $ /easybuild/work/UCX/from-source/ucx/contrib/../configure --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/UCX-1.4-GCC-6.4.0-2.28   --enable-optimizations --disable-debug --disable-params-check  --enable-mt `

Clearly, three of the cmd-args are passed twice, whereas few others have not even been parsed to the configure. Furthermore, in the entire config.log file, I found no trace of "--with-cuda", "--with-avx" and "--with-numa".
Thanks for your swift follow up!

**Comment by yosefe** [comment]
@moravveji can you try using ./configure instead of ./contrib/configure-release?

**Comment by moravveji** [comment]
Sure.
`
  CC       libucm_cuda_la-cudamem.lo
  CCLD     libucm_cuda.la
make[3]: Leaving directory `/easybuild/work/UCX/from-source/ucx/src/ucm/cuda'
Making all in rocm
make[3]: Entering directory `/easybuild/work/UCX/from-source/ucx/src/ucm/rocm'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/easybuild/work/UCX/from-source/ucx/src/ucm/rocm'
make[2]: Leaving directory `/easybuild/work/UCX/from-source/ucx/src/ucm'
Making all in src/ucs
make[2]: Entering directory `/easybuild/work/UCX/from-source/ucx/src/ucs'
  CC       algorithm/libucs_la-crc.lo
gcc: error: /lib/ucx": No such file or directory
make[2]: *** [algorithm/libucs_la-crc.lo] Error 1
make[2]: Leaving directory `/easybuild/work/UCX/from-source/ucx/src/ucs'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/easybuild/work/UCX/from-source/ucx'
make: *** [all] Error 2
`

And the begin of the config.log looks like this:
` $ ./configure --prefix=/data/leuven/sys/x0090231/UCX-1.4-GCC-6.4.0-2.28   --enable-optimizations --disable-debug --disable-params-check  --enable-mt`

**Comment by moravveji** [comment]
Any updates on my issues above?

**Comment by yosefe** [comment]
@moravveji sorry for late response, unfortunately config.log is not enough to identify the problem. can you pls upload also:
1. config.status
1. the output of `make V=1`
1. The full build script (maybe it's setting any environment variables such as CFLAGS?)

Regarding "how to link against libpthread.so" - seems like there is some issue with `--enable-mt`, hopefully the log files should give hint what went wrong.

**Comment by amaslenn** [comment]
@moravveji and if you are using easybuild, could you please share which UCX config you use (looks like this one: https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/u/UCX/UCX-1.3.1-GCCcore-6.4.0.eb) and what modifications you make to it (since it doesn't contain any CUDA specific options by default)?

**Comment by moravveji** [comment]
Thanks gusy for your helps. I managed to fix my build for v.1.4, and I'm now gonna try the latest one 1.5.1 and see whether the same script works or not. 
Closing this ticket.
