### ISSUE TITLE
include file not installed

### ISSUE THREAD

**Issue by lionkov** [openucx/ucx#356]
ucs/datastruct/queue_types.h (included by ucp/api/ucp.h)

**Comment by shamisp** [comment]
@yosefe Shell we add ucp.h hello world test like we have for UCT ?

**Comment by yosefe** [comment]
@lionkov on my system it is installed, see: https://github.com/openucx/ucx/blob/master/src/ucs/Makefile.am#L42
maybe you have an old version / need to rerun automake?

**Comment by lionkov** [comment]
It working now.
