### ISSUE TITLE
CUDA/IB local protection error on inter-socket access

### ISSUE THREAD

**Issue by spickartz** [openucx/ucx#3564]
I am trying to run the `osu_bw` Benchmark on CUDA device memory between two multi-GPU multi-HCA NUMA nodes.

If I set the environment variables

- `CUDA_VISIBLE_DEVICES`
- `CUDA_DEVICE_ORDER`
- `UCX_NET_DEVICES`

such that a combination of an HCA and a GPU on two different sockets is used, I get the following error from the verbs layer:

```
$ mpirun -mca pml ucx -x CUDA_VISIBLE_DEVICES=0 -x CUDA_DEVICE_ORDER=PCI_BUS_ID -x UCX_NET_DEVICES=mlx5_0:1  -n 2 ./osu_bw D D
[...]
# OSU MPI-CUDA Bandwidth Test v5.6.1
# Send Buffer on DEVICE (D) and Receive Buffer on DEVICE (D)
# Size      Bandwidth (MB/s)
mlx5:  got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
0000000d 00000000 00000000 00000000
00000000 02005104 0a00061e 000164d2
rc_verbs_iface.c:67   send completion with error: local protection error

src/ucs/../../../src/ucs/debug/assert.c: [ ucs_fatal_error_message() ]
      ...
       33     }
       34
       35     ucs_handle_error(message_buf);
==>    36     abort();
       37 }
       38
       39 void ucs_fatal_error_format(const char *file, unsigned line,

==== backtrace (tid:  29607) ====
 0 0x000000000001e590 ucs_fatal_error_message()  src/ucs/debug/assert.c:36
 1 0x0000000000022d6b ucs_log_default_handler()  src/ucs/debug/log.c:140
 2 0x0000000000022e84 ucs_log_dispatch()  src/ucs/debug/log.c:193
 3 0x000000000002915d uct_rc_verbs_iface_poll_tx()  src/uct/ib/rc/verbs/rc_verbs_iface.c:106
 4 0x000000000002915d uct_rc_verbs_iface_progress()  src/uct/ib/rc/verbs/rc_verbs_iface.c:134
 5 0x00000000000262ca ucs_callbackq_dispatch()  src/ucs/datastruct/callbackq.h:211
 6 0x00000000000262ca uct_worker_progress()  src/uct/api/uct.h:1926
 7 0x00000000000262ca ucp_worker_progress()  src/ucp/core/ucp_worker.c:1644
 8 0x0000000000003a57 mca_pml_ucx_progress()  ???:0
 9 0x0000000000036bbc opal_progress()  ???:0
10 0x000000000005430d ompi_request_default_wait_all()  ???:0
11 0x0000000000097def MPI_Waitall()  ???:0
12 0x000000000040242e main()  work/osu-micro-benchmarks-5.6.1-ompi/mpi/pt2pt/osu_bw.c:127
13 0x0000000000022445 __libc_start_main()  ???:0
14 0x0000000000402602 _start()  ???:0
=================================
```

If II call (please note: `UCX_NET_DEVICES=mlx5_1:1`)
```
mpirun -mca pml ucx -x CUDA_VISIBLE_DEVICES=0 -x CUDA_DEVICE_ORDER=PCI_BUS_ID -x UCX_NET_DEVICES=mlx5_1:1  -n 2 ./osu_bw D D
```
or (please note: `CUDA_VISIBLE_DEVICES=3`)
```
mpirun -mca pml ucx -x CUDA_VISIBLE_DEVICES=3 -x CUDA_DEVICE_ORDER=PCI_BUS_ID -x UCX_NET_DEVICES=mlx5_0:1  -n 2 ./osu_bw D D
```
instead, the benchmark succeeds.

I am using the current master (`f5e004195e6d1efb0ce877ee6cf54a3b7a2875a8`) of the UCX library and OpenMPI 4.0.1.

So my questions are:

1. Is this setup not supposed to be supported by UCX or am I doing something wrong here?
2. If not supported, are there any means for performing an appropriate error handling within UCX or on a layer above?

Thanks in advance!

**Comment by bureddy** [comment]
@spickartz  can you get output of `nvidia-smi topo -m` ?

**Comment by spickartz** [comment]
Sure, I get:
```
$ nvidia-smi topo -m
	GPU0	GPU1	GPU2	GPU3	mlx5_0	mlx5_1	CPU Affinity
GPU0	 X 	NV2	NV2	NV2	PIX	SYS	0-19,40-59
GPU1	NV2	 X 	NV2	NV2	PIX	SYS	0-19,40-59
GPU2	NV2	NV2	 X 	NV2	SYS	PIX	20-39,60-79
GPU3	NV2	NV2	NV2	 X 	SYS	PIX	20-39,60-79
mlx5_0	PIX	PIX	SYS	SYS	 X 	SYS
mlx5_1	SYS	SYS	PIX	PIX	SYS	 X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe switches (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing a single PCIe switch
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by bureddy** [comment]
@spickartz  I do not have exact same setup. I tried and i couldn't see same behavior on some other multi-GPU multi-HCA NUMA setup.

Can you check few more things?
1.  is nv_peer_mem module loaded?` /etc/init.d/nv_peer_mem status `
2.  what is the version of nv_peer_mem?  `cat /sys/kernel/mm/memory_peers/nv_mem/version`
3. MOFED version?  `ofed_info -s`
4. can you build UCX debug version and upload verbose log run with `-x UCX_LOG_LEVEL=data`

**Comment by spickartz** [comment]
@bureddy here is what I found out:
> 
> Can you check few more things?
> 
> 1. is nv_peer_mem module loaded?`/etc/init.d/nv_peer_mem status`
This script is not installed on our systems but `lsmod` shows that it is loaded:
```
$ lsmod | grep nv_peer_mem
nv_peer_mem            13163  0
nvidia              17601141  92 nv_peer_mem,nvidia_uvm
ib_core               294554  12 rdma_cm,ib_cm,iw_cm,nv_peer_mem,mlx4_ib,mlx5_ib,ib_ucm,ib_umad,ib_uverbs,rdma_ucm,ib_ipoib
```
> 2. what is the version of nv_peer_mem?  `cat /sys/kernel/mm/memory_peers/nv_mem/version`
```
$ cat /sys/kernel/mm/memory_peers/nv_mem/version
1.0-7
```
> 3. MOFED version?  `ofed_info -s`
```
$ ofed_info -s
OFED-internal-4.5-1.0.1:
```
> 4. can you build UCX debug version and upload verbose log run with `-x UCX_LOG_LEVEL=data`

I will provide this in the following comment as this gets quite long.

**Comment by spickartz** [comment]
If I understand the CUDA GPUDirect documentation correctly ([https://docs.nvidia.com/cuda/gpudirect-rdma/index.html](https://docs.nvidia.com/cuda/gpudirect-rdma/index.html)):
>Finally, the third situation, where the path traverses a QPI/HT link, may be extremely performance-limited or even not work reliably.

then I assume this communication path is not necessarily supported. Or am I misunderstanding the documentation at this point?

**Comment by spickartz** [comment]
The root-cause of this issue has been found on our system. The problem was enabled ACS (Access Control Services) for PCIe devices within the BIOS (see also [https://ftpw.supermicro.com.tw/support/faqs/faq.cfm?faq=20732](https://ftpw.supermicro.com.tw/support/faqs/faq.cfm?faq=20732)).

If ACS is disabled, the protection error does not occur anymore. Does the UCX library provide any error handling that could be used by upper layers to circumvent this problem?

**Comment by bureddy** [comment]
@spickartz Good to know that issue got resolved.  My earlier experience is that ACS should get you poor performance but not the protection error.   In general ACS should have enabled in all GPU environments as this also affects GPU-GPU P2P performance.  Any sanity tests like (ibperf or cuda utilities) should have exposed this.

I would consider this as no issue in UCX for now.

**Comment by spickartz** [comment]
@bureddy Thanks for the feedback. I would close the issue then. However, is anything planed that would enable an error handling by upper layers?

**Comment by bureddy** [comment]
@spickartz not in plan for now.

**Comment by shamisp** [comment]
@bureddy - can we identify this misconfiguration from user space by reading some proc ? If it is exposed to user space we can add some check during initialization and report warning to user about system misconfiguration.

**Comment by bureddy** [comment]
@shamisp I don't see any proc entry for this to read in userspace.  AFAIK only way is to parse "lspci -vvv" output. but, this requires root permissions.  It seems NVIDIA also do not have any kind of handling for this in their tools.

**Comment by miked-mellanox** [comment]
maybe we should have FAQ entry on this or in README

**Comment by shamisp** [comment]
@spickartz if it is not programmatically exposed to user space, there is not much we can do about detecting this. We can document the symptoms and workaround on Wiki as @miked-mellanox suggested.

**Comment by spickartz** [comment]
@shamisp Sounds reasonable to me. In that case, I guess the issue can be closed. Or do you want to leave it open until an appropriate hint is given in the documentation?

Thanks a lot for your support!

**Comment by bureddy** [comment]
Added FAQ entry here : https://github.com/openucx/ucx/wiki/NVIDIA-GPU-Support

**Comment by shamisp** [comment]
Can you please add reference to the main page
https://github.com/openucx/ucx/wiki
otherwise it is hard to find IMHO.
