### ISSUE TITLE
Inaccurate UCX_NUM_EPS causes hangs in multi-worker setups

### ISSUE THREAD

**Issue by lyu** [openucx/ucx#3574]
UCX: master HEAD

Test program: [ucx_num_eps_stuck.cpp](https://gist.github.com/lyu/9a1eaed1afb0390961fc9a41dd49f350)

In short, this program creates several threads, then each thread creates several workers and finally it connect some of the workers by creating endpoints. This problem was discovered when we were experimenting with some communication pipelining code.

To reproduce: compile the program with UCX flags and `-fopenmp`, then on the same machine, run
```
./ucx_num_eps_stuck
```
and
```
./ucx_num_eps_stuck $HOSTNAME
```

The issue may not be reproduced every time but should have a fairly high chance of happening. To resolve the issue, set `UCX_NUM_EPS` to a relatively large number like 128.

This problem can also be reproduced from two nodes connected by ConnectX-5 NICs. If not, simply increase the number of threads or the number of workers per thread so that there are more endpoints in the program.

**Comment by yosefe** [comment]
Reproduced also with the SW versions above, on MLNX_OFED 4.5, with the command:
```
$ /mpirun -x UCX_NET_DEVICES=mlx5_2:1 -np 2 --map-by node ./NPmpi --pert 0 --integrity --repeats 2 --start 262144
Doing a message integrity check instead of measuring performance
Using a constant number of 2 transmissions
NOTE: Be leary of timings that are close to the clock accuracy.

      Clock resolution ~   1.000 nsecs      Clock accuracy ~  40.000 nsecs

Start testing with 1 trials for each message size
  1: 262.144 KB         2 times -->          0 failures
  2: 393.216 KB         2 times -->          0 failures
  3: 524.288 KB         2 times -->     524288 failures
  4: 786.432 KB         2 times -->     786432 failures
  5:   1.049 MB         2 times -->    1048576 failures
  6:   1.573 MB         2 times -->    1572864 failures
  7:   2.097 MB         2 times -->          0 failures
  8:   3.146 MB         2 times -->          0 failures
  9:   4.194 MB         2 times -->          0 failures
 10:   6.291 MB         2 times -->    6291456 failures
 11:   8.389 MB         2 times -->    8388608 failures

Completed with        max bandwidth    2.111 Gbps        7.862 msecs latency


```

**Comment by yosefe** [comment]
@lyu sorry for late response, the issue is that the target worker is flushed while there is no progress on the sender workers. as a result the wireup process cannot complete so the flush does not complete.
it does not happen with large `UCX_NUM_EPS`, because it forces usage of dc transport which does not require wireup process.

The test should be fixed like this:
```diff
--- ucx_num_eps_stuck.cpp.orig	2019-06-09 14:12:50.686211200 +0300
+++ ucx_num_eps_stuck.cpp	2019-06-09 14:16:00.081928000 +0300
@@ -36,7 +36,8 @@ void flush_callback(void *request, ucs_s
 }
 
 
-ucs_status_t wait_ucp_request(ucp_worker_h worker, void* request)
+ucs_status_t wait_ucp_request(ucp_worker_h worker, void* request,
+                              ucp_worker_h *extra_wrks = NULL, int nwrks = 0)
 {
     if (request == NULL) {
         return UCS_OK;
@@ -46,6 +47,9 @@ ucs_status_t wait_ucp_request(ucp_worker
         ucs_status_t status;
         do {
             ucp_worker_progress(worker);
+            for (int i = 0; i < nwrks; ++i) {
+                ucp_worker_progress(extra_wrks[i]);
+            }
             status = ucp_request_check_status(request);
         } while (status == UCS_INPROGRESS);
         ucp_request_free(request);
@@ -61,10 +65,10 @@ ucs_status_t flush_ep(ucp_worker_h worke
 }
 
 
-ucs_status_t flush_worker(ucp_worker_h worker)
+ucs_status_t flush_worker(ucp_worker_h worker, ucp_worker_h *extra_wrks, int nrwks)
 {
     void* request = ucp_worker_flush_nb(worker, 0, flush_callback);
-    return wait_ucp_request(worker, request);
+    return wait_ucp_request(worker, request, extra_wrks, nrwks);
 }
 
 
@@ -193,7 +197,7 @@ void run_server(ucp_worker_h wrkr, ucp_a
         #pragma omp barrier
         #pragma omp master
         {
-            ucp_worker_flush(wrkr);
+            flush_worker(wrkr, wks, N_WORKERS);
             socket_barrier(conn_skt);
         }
 
@@ -279,7 +283,7 @@ void run_client(ucp_worker_h wrkr, ucp_a
         #pragma omp barrier
         #pragma omp master
         {
-            ucp_worker_flush(wrkr);
+            flush_worker(wrkr, wks, N_WORKERS);
             socket_barrier(conn_skt);
         }
 
```

**Comment by lyu** [comment]
@yosefe Thank you for the explanation!

I am still relatively new to this and I don't know anything about the wireup process (couldn't find anything in the UCX specs), so please bear with me if I do some thing that makes no sense.

Let's call the worker I created before entering the parallel region the "default worker".

I want to solve this wireup issue as I create the new thread-local workers (and their associated endpoints),  so I tried to flush the default worker immediately after I create the endpoints, and progress the newly created thread-local worker in the flush routine kind like what your solution does (Option 2 below). This solution doesn't work, strange.

But then I tried to flush the newly created thread-local worker and progress the default worker, and the problem is gone (Option 1 below). I have no idea what's going on.

```diff
@@ -36,7 +36,8 @@ void flush_callback(void *request, ucs_status_t status)
 }
 
 
-ucs_status_t wait_ucp_request(ucp_worker_h worker, void* request)
+ucs_status_t wait_ucp_request(ucp_worker_h worker, void* request,
+                              ucp_worker_h new_worker = NULL, const int flag = 0)
 {
     if (request == NULL) {
         return UCS_OK;
@@ -46,6 +47,9 @@ ucs_status_t wait_ucp_request(ucp_worker_h worker, void* request)
         ucs_status_t status;
         do {
             ucp_worker_progress(worker);
+            if (flag != 0) {
+                ucp_worker_progress(new_worker);
+            }
             status = ucp_request_check_status(request);
         } while (status == UCS_INPROGRESS);
         ucp_request_free(request);
@@ -61,10 +65,10 @@ ucs_status_t flush_ep(ucp_worker_h worker, ucp_ep_h ep)
 }
 
 
-ucs_status_t flush_worker(ucp_worker_h worker)
+ucs_status_t flush_worker(ucp_worker_h worker, ucp_worker_h new_worker, int flag)
 {
     void* request = ucp_worker_flush_nb(worker, 0, flush_callback);
-    return wait_ucp_request(worker, request);
+    return wait_ucp_request(worker, request, new_worker, flag);
 }
 
 
@@ -181,19 +185,21 @@ void run_server(ucp_worker_h wrkr, ucp_address_t* wrkr_addr, const size_t wrkr_a
 
         for (int i = 0; i < N_WORKERS; i++) {
             ucp_worker_create(ucp_ctx, &wkp, &wks[i]);
-        }
-
-        for (int i = 0; i < N_WORKERS; i++) {
             epp.address = wrkr_addr;
             ucp_ep_create(wks[i], &epp, &eps[i][0]);
             epp.address = client_wrkr_addr;
             ucp_ep_create(wks[i], &epp, &eps[i][1]);
+
+            // Option 1: This works
+            flush_worker(wks[i], wrkr, 1);
+            // Option 2: This doesn't work
+            // flush_worker(wrkr, wks[i], 1);
         }
 
         #pragma omp barrier
         #pragma omp master
         {
-            ucp_worker_flush(wrkr);
+            flush_worker(wrkr, NULL, 0);
             socket_barrier(conn_skt);
         }
 
@@ -267,19 +273,21 @@ void run_client(ucp_worker_h wrkr, ucp_address_t* wrkr_addr, const size_t wrkr_a
 
         for (int i = 0; i < N_WORKERS; i++) {
             ucp_worker_create(ucp_ctx, &wkp, &wks[i]);
-        }
-
-        for (int i = 0; i < N_WORKERS; i++) {
             epp.address = wrkr_addr;
             ucp_ep_create(wks[i], &epp, &eps[i][0]);
             epp.address = server_wrkr_addr;
             ucp_ep_create(wks[i], &epp, &eps[i][1]);
+
+            // Option 1: This works
+            flush_worker(wks[i], wrkr, 1);
+            // Option 2: This doesn't work
+            // flush_worker(wrkr, wks[i], 1);
         }
 
         #pragma omp barrier
         #pragma omp master
         {
-            ucp_worker_flush(wrkr);
+            flush_worker(wrkr, NULL, 0);
             socket_barrier(conn_skt);
         }
```

I am doing this for OSSS-UCX (create a new worker for each SHMEM context) and discovered this issue because the program hangs if I create new contexts and then try to flush the default context. Obviously I do not want to progress every single worker that I have allocated everytime I flush the default context, so I want to solve this problem as I create the contexts/workers. So at this point I have two questions:
 - Is this wireup issue a one-time thing? Meaning, if I have progressed/flushed whatever I should progress/flush, then can I forget about this issue and assume all the workers are completely independent of each other?
 - Could you please explain my new solutions' behavior? Is option 1 the right way to solve the problem?

Thank you again for you help!

**Comment by yosefe** [comment]
@lyu option2 doesn't work because you are progressing only one of the non-default workers (wks[i[) while flushing the default worker. possibly one of the other threads is not currently progressing its non-default worker.
option1 is ok because wks[i] is connecting only to the default worker so it's ok to progress only both of them while flushing it.
as general rule, need to flush all workers in the process while waiting for something to complete to avoid such deadlocks.
regarding "Is this wireup issue a one-time thing?" - yes, when flush the endpoint or the initiating worker it's complete. however, it should be possible to avoid the flush during init, by making sure all wait operation progress all workers.

**Comment by lyu** [comment]
@yosefe Thanks! Closing.
