### ISSUE TITLE
Failure in mlx5

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#360]
----------] 8 tests from rc_mlx5/uct_p2p_am_test
[ RUN      ] rc_mlx5/uct_p2p_am_test.am_short/0
[     INFO ] 8 235 3000x{8..235} nocomp 45 
[       OK ] rc_mlx5/uct_p2p_am_test.am_short/0 (3232 ms)
[ RUN      ] rc_mlx5/uct_p2p_am_test.am_short/1
[     INFO ] 8 235 3000x{8..235} nocomp 45 [:37665:0] Caught signal 11 (Segmentation fault)

I will send full log in email

**Comment by yosefe** [comment]
should be fixed as part of #320
