### ISSUE TITLE
How does openucx fuse with the sheepdog?

### ISSUE THREAD

**Issue by fantastic2085** [openucx/ucx#3664]

**Comment by petro-rudenko** [comment]
Sheepdog is a distributed file system, that seems to use accelio library:
https://github.com/sheepdog/sheepdog/blob/6b3aa035564fcc9271f00698f0acf756b92bcd98/sheep/request.c#L1111

Accelio is not actively maintained anymore. If you're a sheepdog developer and want to use openucx  - would be glad to help.

**Comment by fantastic2085** [comment]
Thank you!
