### ISSUE TITLE
If UCX is based on Linux kernel TCP/IP for sending and receiving data, how does it provide accelerated performance?

### ISSUE THREAD

**Issue by fantastic2085** [openucx/ucx#3665]

**Comment by yosefe** [comment]
@fantastic2085 UCX also supports high-speed RDMA networks (such as Infiniband and RoCE) in addition to TCP/IP.

**Comment by shamisp** [comment]
It also leverages shared memory communication (sysv, knem, cma, xpmem) whenever possible. The library autodetects available transports and uses most optimal channel/s (potentially more than one) for communication. As @yosefe we also support ROCE over ethernet which is supported by variety ethernet adapters.

**Comment by fantastic2085** [comment]
Thank you very much!
