### ISSUE TITLE
UCX programs hang when compiled with -fsanitize=address

### ISSUE THREAD

**Issue by tonycurtis** [openucx/ucx#3676]
git master @ 462e0240e544678a9d28bf48a59230a513767da4

When compiled with `-fsanitize=address`, programs linked with UCX hang on start, even a vanilla `main() { return 0; }` that doesn't even call UCX

Works with 1.x releases

**Comment by shamisp** [comment]
@tonycurtis what about 1.6.0-rc1 ?

**Comment by tonycurtis** [comment]
1.6.0-rc1 works too

**Comment by tonycurtis** [comment]
#3681 works for me
