### ISSUE TITLE
ROCm unit tests not working

### ISSUE THREAD

**Issue by stanleytsang-amd** [openucx/ucx#3722]
It appears as though since commit 6bd16ca I am unable to run the rocm-specific unit tests.  Calling the gtest executable with --gtest_filter="*rocm*" produces zero cases run.  In earlier commits the filter works.

I think the merge in 6bd16ca accidentally removed the test case instantiation for rocm in test/gtest/uct/test_md.cc - it is a merge for PR #3348, and you can see in PR 3348 the entry for rocm in test_md.cc is still there in line 538.  I have confirmed in f6629a4 I can still run the rocm unit tests as noted above.

If the change in the merge was intentional, please advise how to run the rocm-specific unit tests.  Thank you.

**Comment by yuq** [comment]
It's expected, because we haven't implemented ROCM memory alloc in the test yet. In order to run rocm tests, we need to implement it first.

**Comment by rkothako** [comment]
Hi @yuq 
Please update once the ROCm tests are implemented.
Thank you.

**Comment by paklui** [comment]
#4376

**Comment by paklui** [comment]
#4376

**Comment by paklui** [comment]
The gtest for rocm appears to be enabled again by #4376 I am able to run the gtest now.
@stanleytsang-amd , do you think we can close this issue?
Here's the (incomplete) log:
[Uploading log.gtest.daytona32.191111_003510.txt…]()

**Comment by paklui** [comment]
I see from #4376 , the rocm gtest has been enabled again.
Running the command like this generates some runs. 
[log.gtest.daytona32.191114_185244.txt](https://github.com/openucx/ucx/files/3849324/log.gtest.daytona32.191114_185244.txt)
[out.gtest.daytona32-list.txt](https://github.com/openucx/ucx/files/3849325/out.gtest.daytona32-list.txt)

``
ucx/test/gtest/gtest --gtest_filter=*rocm*
``
@stanleytsang-amd , seems like the ROCm unit tests is working. I guess we can close this issue.

**Comment by stanleytsang-amd** [comment]
> I see from #4376 , the rocm gtest has been enabled again.
> Running the command like this generates some runs.
> log.gtest.daytona32.191114_185244.txt
> out.gtest.daytona32-list.txt
> ucx/test/gtest/gtest --gtest_filter=*rocm*
> @stanleytsang-amd , seems like the ROCm unit tests is working. I guess we can close this issue.

Agreed.  Closing
