### ISSUE TITLE
Drop outdated line referencing NCCL

### ISSUE THREAD

**Issue by jakirkham** [openucx/ucx#3747]
When talking with @Akshay-Venkatesh offline, we determined [this line referencing NCCL]( https://github.com/openucx/ucx/blob/35ca8df88d7335bcc899fa40ea094b6ecfc2a23a/config/m4/gdrcopy.m4#L31 ) is leftover. If that's true, it would be good to drop it.

**Comment by bureddy** [comment]
it's my bad.  
PR: https://github.com/openucx/ucx/pull/3749

**Comment by jakirkham** [comment]
Ah that makes more sense. Thanks @bureddy! 😄

**Comment by yosefe** [comment]
Fixed by #3749
