### ISSUE TITLE
UCX build against rdma-core fails in TCP UCT

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#3785]
UCX master against RDMA-CORE master

```
make 
Making all in .
make[1]: Entering directory `ucx/build.release.rdmacore/src/uct'
  CC       tcp/libuct_la-tcp_net.lo
In file included from 
ucx/build.release.rdmacore/../src/uct/ib/base/ib_device.h:10:0,
                 from ../../../src/uct/tcp/tcp_net.c:14:
ucx/build.release.rdmacore/../src/uct/ib/base/ib_verbs.h:272:14: fatal error: infiniband/tm_types.h: No such file or directory
 #    include <infiniband/tm_types.h>
              ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by shamisp** [comment]
Why TCP TL needs include from RDMA-CORE to function ! This is really wrong...

**Comment by shamisp** [comment]
No `-I` is passed , so obviously it fails

**Comment by dmitrygladkov** [comment]
> Why TCP TL needs include from RDMA-CORE to function ! This is really wrong...

TCP needs it to calculate IPoIB header size (only if `HAVE_IB` defined). TCP uses constants like `UCT_IB_LRH_LEN`, `UCT_IB_GRH_LEN` and etc for this

**Comment by shamisp** [comment]
Well, it breaks TCP code because now you have to pass include pass for `infiniband/tm_types.h`

**Comment by shamisp** [comment]
Seems like this include is only required for BW estimate... Way too much hassle. I would use some static number once IPoIB is detected.

**Comment by shamisp** [comment]
And the other question - this is something that we should be easy to catch in CI build ...

**Comment by yosefe** [comment]
@shamisp which rdma-core version do you have? 
we have 25.0 (latest master) in CI

**Comment by yosefe** [comment]
@Artemy-Mellanox looks like something is wrong with HW_TM macros from configure
We try to include infiniband/tm_types.h even though it does not exist
@shamisp Even if we remove this from TCP, IB will fail to compile anyway
