### ISSUE TITLE
segfault with MPICH + UCX 1.6.0 and malloc hooks

### ISSUE THREAD

**Issue by raffenet** [openucx/ucx#3831]
How to reproduce:
MPICH master: https://github.com/pmodels/mpich
> ./autogen.sh
> ./configure --with-device=ch4:ucx --with-ch4-netmod-ucx-args=am-only --enable-g=dbg --disable-fast --with-ucx=<path/to/ucx-1.6.0> --prefix=<path/to/install>
> make -j install
> cd test/mpi/threads/pt2pt
> make multisend2
> mpiexec -n 4 ./multisend2

Segfaults go away if malloc hooks are disabled with `UCX_MEM_EVENTS=n`.

**Comment by hoopoepg** [comment]
@raffenet could you copy backtrace here?
thank you

**Comment by raffenet** [comment]
[backtrace.txt](https://github.com/openucx/ucx/files/3359833/backtrace.txt)

**Comment by hoopoepg** [comment]
hi @raffenet 
could you try to test this PR: https://github.com/openucx/ucx/pull/3836

thank you
