### ISSUE TITLE
Invalid value of canonical build

### ISSUE THREAD

**Issue by gaby7646** [openucx/ucx#3871]
Hi there!. I'm configuring `openmpi-4.0.1` before to installing it. I did `sudo ./configure --prefix= /usr/local` and I obtain the following error:
`*** Startup tests`
`checking build system type ../usr/local`
`configure:error:invalid value of canonical build`

**Comment by hiroyuki-sato** [comment]
Hello, @gaby7646 

Could you try `./configure --prefix=/usr/local`
You don't need space between `=` and `/`

**Comment by gaby7646** [comment]
Thanks!

**Comment by shamisp** [comment]
I guess we can close this one
