### ISSUE TITLE
[Q] epoll keyword in comments.

### ISSUE THREAD

**Issue by hiroyuki-sato** [openucx/ucx#3900]
Hello, @dmitrygx 

As you know, we eliminate epoll function in many files.
Does this comment are still correct or should we fix it?

Best regards.

```C
src/ucs/async/async.h
56: * @param mode            Either to use signals or epoll threads to wait.

src/ucs/async/async_fwd.h
109: * @param mode            Either to use signals or epoll threads to wait.

src/uct/tcp/tcp.h
20:/* How many events to wait for in epoll_wait */
```

**Comment by dmitrygx** [comment]
Hello @hiroyuki-sato 

Yes, they are no longer valid
Do you mind preparing a PR to fix it? Thank you!

**Comment by hiroyuki-sato** [comment]
Hello, @dmitrygx . Thank you for your reply.

Created PR #3901. 
Please take a look when you get a chance.
