### ISSUE TITLE
autogen.sh fails on AS_IF in v1.6.0 configury

### ISSUE THREAD

**Issue by naughtont3** [openucx/ucx#3940]
When running `autogen.sh` from a v1.6.0 Git tag I get an error on `AS_IF` (see below), but the same setup works fine for v1.5.1 and earlier with same Autotools/setup.

Note, I found  #3540 that appears to be related to this topic, but that was closed and not exactly sure how it would fix the problem.  I used same Autotools setup w/ and w/o pkg-config on older v1.5.1 and v1.5.0 UCX tags and the `autogen.sh` was fine.

I did quick tests across UCX tags:
   - v1.5.0
   - v1.5.1
   - v1.6.0

And used three possibly Autotool configurations (setup details at end):
   1. All system installed version
   2. Self Autotools   (minus pkg-config, b/c that's my normal setup)
   3. Self Autotools w/ Self pkg-config

The only difference between System and Self autotool versions is in Automake:
   - System at automake-1.15
   - Self   at automake-1.15.1

I get a regression when running 'autogen.sh' from Git clone of UCX v1.6.0.

v1.6.0:
  - WORKS: git-ucx-tag-1-6-0 All system Autotools (1)
  - **FAILS**: git-ucx-tag-1-6-0 SELF autotools, SYS pkg-config (2)
  - **FAILS**: git-ucx-tag-1-6-0 SELF autotools, SELF pkg-config (3)

v1.5.1:
  - WORKS: git-ucx-tag-1-5-1 All system Autotools (1)
  - WORKS: git-ucx-tag-1-5-1 SELF autotools, SYS pkg-config (2)
  - WORKS: git-ucx-tag-1-5-1 SELF autotools, SELF pkg-config (3)

v1.5.0:
  - WORKS: git-ucx-tag-1-5-0 All system Autotools (1)
  - WORKS: git-ucx-tag-1-5-0 SELF autotools, SYS pkg-config (2)
  - WORKS: git-ucx-tag-1-5-0 SELF autotools, SELF pkg-config (3)

The only remaining variable would be that my Automake v1.15.1 is causing the problem compared to v1.15 (seems odd), but something is odd.  

What has changed in the UCX configury that causes the `autogen.sh` to fail?

```
beaker:$ git clone -b v1.6.0 https://github.com/openucx/ucx.git ucx-git-tag-rel160
beaker:$ cd ucx-git-tag-rel160/
beaker:$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config/m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'config/m4'.
libtoolize: copying file 'config/m4/libtool.m4'
libtoolize: copying file 'config/m4/ltoptions.m4'
libtoolize: copying file 'config/m4/ltsugar.m4'
libtoolize: copying file 'config/m4/ltversion.m4'
libtoolize: copying file 'config/m4/lt~obsolete.m4'
autoreconf: running: /home/tjn/local/gnu/bin/autoconf
configure.ac:33: error: possibly undefined macro: AS_IF
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:34: error: possibly undefined macro: AC_SUBST
configure.ac:137: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:236: error: possibly undefined macro: AC_DEFINE
configure:26931: error: possibly undefined macro: AC_MSG_WARN
autoreconf: /home/tjn/local/gnu/bin/autoconf failed with exit status: 1
beaker:$
```

Setup 1: System Autotools (1):
 - m4: m4 (GNU M4) 1.4.17
 - autoconf: autoconf (GNU Autoconf) 2.69
 - automake: automake (GNU automake) 1.15
 - libtoolize: libtoolize (GNU libtool) 2.4.6
 - pkg-config: 0.29.1
 - PATHS:
   /usr/bin/m4
   /usr/bin/autoconf
   /usr/bin/automake
   /usr/bin/libtoolize
   /usr/bin/pkg-config

Setup 2: SELF Autotools w/ System pkg-config (2):
 - m4: m4 (GNU M4) 1.4.17
 - autoconf: autoconf (GNU Autoconf) 2.69
 - automake: automake (GNU automake) 1.15.1         <== Newer
 - libtool: libtool (GNU libtool) 2.4.6
 - libtoolize: libtoolize (GNU libtool) 2.4.6
 - pkg-config: 0.29.1                               <== SYS  install
 - PATHS:
   /home/3t4/local/gnu/bin/m4
   /home/3t4/local/gnu/bin/autoconf
   /home/3t4/local/gnu/bin/automake
   /home/3t4/local/gnu/bin/libtool
   /home/3t4/local/gnu/bin/libtoolize
   /usr/bin/pkg-config

Setup 3: SELF Autotools w/ SELF pkg-config (3):
 - m4: m4 (GNU M4) 1.4.17
 - autoconf: autoconf (GNU Autoconf) 2.69
 - automake: automake (GNU automake) 1.15.1        <== Newer
 - libtool: libtool (GNU libtool) 2.4.6
 - libtoolize: libtoolize (GNU libtool) 2.4.6
 - pkg-config: 0.29.1                              <== TJN install
 - PATHS:
   /home/3t4/local/gnu/bin/m4
   /home/3t4/local/gnu/bin/autoconf
   /home/3t4/local/gnu/bin/automake
   /home/3t4/local/gnu/bin/libtool
   /home/3t4/local/gnu/bin/libtoolize
   /home/3t4/local/gnu/TESTING/pkg-config-0.29.1/_install/bin/pkg-config

**Comment by yosefe** [comment]
looks like missing pkg-config

**Comment by yosefe** [comment]
probably the self autotools is not picking up neither system not self pkg-config because they have different installation prefix
what is the result of `grep  pkg.m4 aclocal.m4` in UCX directory, after running autogen?

**Comment by naughtont3** [comment]
@yosefe  In all my `FAILS` cases the `aclocal.m4` does not include any mention of `pkg.m4`.  However, if I create a 4th setup as you suggested where `pkg-config` is at the same installation prefix (so paths are the same for Autotools) I get the mention of `pkg.m4`.   

Note, this only occurs in the ucx-1.6.0 tree and is new compared to <= v1.5.1, where I do not see the `pkg.m4` checked.  So it looks like a check is being made on `pkg-config` (`PKG_MACROS_VERSION`) in ucx-1.6.0.  The goofed `pkg-config` paths for my installation are what caused the problem.  If the "self" installed pkg-configs & other autotool friends are in same install prefix all is fine.  (So that's what was meant by the broken pkg-config install.) :-)

OK, so I think I understand the difference in the configury now (PKG_MACROS_VERSION) and how to resolve in my local install.   Thanks!

**Comment by naughtont3** [comment]
Adding info for last test to ticket trails...

```
beaker:ucx-git-tag-rel160$ show-dev-tools.sh --showpaths
*********************
*** Tool Paths    ***
*********************
   /tmp/UCX_TESTS/env4/gnu/bin/m4
   /tmp/UCX_TESTS/env4/gnu/bin/autoconf
   /tmp/UCX_TESTS/env4/gnu/bin/automake
   /tmp/UCX_TESTS/env4/gnu/bin/libtool
   /tmp/UCX_TESTS/env4/gnu/bin/libtoolize
   /tmp/UCX_TESTS/env4/gnu/bin/pkg-config
   /usr/bin/make
   /usr/bin/cmake
   /usr/bin/flex
   /usr/bin/bison
   /usr/bin/gcc
   /usr/bin/g++
   /usr/bin/git
   /usr/bin/vim
   /usr/bin/ctags
   /usr/bin/rsync
   /usr/bin/strace
   /usr/bin/genisoimage

*********************
*** Tool Versions ***
*********************
m4: m4 (GNU M4) 1.4.17
autoconf: autoconf (GNU Autoconf) 2.69
automake: automake (GNU automake) 1.15.1
libtool: libtool (GNU libtool) 2.4.6
libtoolize: libtoolize (GNU libtool) 2.4.6
pkg-config: 0.29.1
make: GNU Make 4.1
cmake: cmake version 3.5.1
flex: flex 2.6.0
bison: bison (GNU Bison) 3.0.4
gcc: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
g++: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
git: git version 2.7.4
vim: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 07 2019 15:35:43)
ctags: Exuberant Ctags 5.9~svn20110310, Copyright (C) 1996-2009 Darren Hiebert
rsync: rsync  version 3.1.1  protocol version 31
strace: strace -- version 4.11
genisoimage: genisoimage 1.1.11 (Linux)

beaker:ucx-git-tag-rel160$
beaker:ucx-git-tag-rel160$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config/m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
autoreconf: running: /tmp/UCX_TESTS/env4/gnu/bin/autoconf
autoreconf: running: /tmp/UCX_TESTS/env4/gnu/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
autoreconf: Leaving directory `.'
beaker: ucx-git-tag-rel160$  echo $?
0
beaker: ucx-git-tag-rel160$ grep pkg.m4 aclocal.m4
dnl pkg.m4 - Macros to locate and utilise pkg-config.   -*- Autoconf -*-
dnl of pkg.m4 when generating configure.
    [m4_fatal([pkg.m4 version $1 or higher is required but ]PKG_MACROS_VERSION[ found])])
beaker: ucx-git-tag-rel160$
```

**Comment by yosefe** [comment]
pkg.m4 deps removed in UCX master and v1.6.x

**Comment by naughtont3** [comment]
Ref #4027
