### ISSUE TITLE
Add a 'void *' application cookie to ucp request

### ISSUE THREAD

**Issue by tjcw** [openucx/ucx#3951]
I need to pass a 'void * cookie' from the site of an active message call, to the callback function which runs in the client when the active message is complete. This 'void *' would be used to carry application context to the callback.
I think the right way to do this would be to add a 'void *' to the ucp request type, and add 2 functions to set and get this field. Code using this function would then look like
```
ucs_status_ptr_t sstatus=ucp_am_send_nb(.., application_callback, ..) ;
ucp_set_cookie(sstatus, application_context_pointer) ; 
..
void application_callback(void *request, ucs_status_t status)
{
  void *application_context_ptr = ucp_get_cookie(request) ; 
  ..
}

```
I'll work on a code change and PR for this, but I'd appreciate comments on the design.

**Comment by shamisp** [comment]
@snyjm-18 FYI

**Comment by yosefe** [comment]
@tjcw can we close this ?

**Comment by tjcw** [comment]
Yes. Closing.
