### ISSUE TITLE
ucp active message with iovec

### ISSUE THREAD

**Issue by tjcw** [openucx/ucx#3954]
I'm making a ucp active message call with an ucp_dt_iov_t paramater (2 elements). I'm assuming that the internals of UCX flattens the ucp_dt_iov_t on the way to the server and passes the address of the first byte of the flattened structure, and the total length, to the active message function; but this does not seem to be what the server receives. The length is what I expect, but the data is not what I expect.
Am I right in my assumption about what I should receive in the server ?
Client code is
```
    TRACE_FORMAT("send->meta connection_id=%u scr_ep=%u hdr_bytes=%lu bytes=%lu",
        send->meta.connection_id,send->meta.src_ep,send->meta.hdr_bytes,send->meta.bytes) ;
    ucp_dt_iov_t iovec[2] ;
    iovec[0].buffer = &send->meta;
    iovec[0].length = send->meta.metaSize();
    iovec[1].buffer = payload ;
    iovec[1].length = length ;
    TRACE_FORMAT("iovec lengths=(%lu,%lu) buffers=(%p,%p)", iovec[0].length, iovec[1].length, iovec[0].buffer, iovec[1].buffer) ;
	  TRACE_FORMAT("Making active message call dispatch=%d", _mcast_dispatch) ;
          ucs_status_ptr_t sstatus=ucp_am_send_nb(dest,_mcast_dispatch, iovec, 2, ucp_dt_make_iov(), UCXsendMcastDone, 0) ;
```
server code is
```
template <bool T_AM, bool T_Pipe>
  inline ucs_status_t UCXNativeInterfaceP2P<T_AM, T_Pipe>::dispatch_mcast
    (
        void *cookie,
        void *header,
        size_t length,
        ucp_ep_h reply_ep,
        unsigned flags
     )        /**< OUT: receive structure, only needed if non-NULL */
  {
    TRACE_FN_ENTER();

    TRACE_FORMAT("cookie=%p header=%p length=%lu reply_ep=%p flags=0x%08x", cookie, header, length, reply_ep, flags) ;

    UCXNativeInterfaceP2P<T_AM, T_Pipe> *p2p_ni = (UCXNativeInterfaceP2P<T_AM, T_Pipe> *)cookie;
    multicast_metadata_t *meta = (multicast_metadata_t *) header;
    TRACE_FORMAT("meta connection_id=%u src_ep=%u hdr_bytes=%lu bytes=%lu",meta->connection_id, meta->src_ep, meta->hdr_bytes, meta->bytes) ;
```
and the trace I get is
```
[1,1]<stderr>:multicast_over_send():752 .. iovec lengths=(32,0) buffers=(0x1f1bc300,(nil))
[1,1]<stderr>:multicast_over_send():746 .. send->meta connection_id=1 scr_ep=1 hdr_bytes=16 bytes=0
[1,0]<stderr>:> dispatch_mcast() [../../adapter/ucx/NativeInterface.h:1041]
[1,0]<stderr>:dispatch_mcast():1043 .. cookie=0x2f58bd60 header=0x200023292030 length=32 reply_ep=(nil) flags=0x00000001
[1,0]<stderr>:dispatch_mcast():1047 .. meta connection_id=2896101377 src_ep=1 hdr_bytes=0 bytes=274877744200
```

**Comment by tjcw** [comment]
In some special cases of my active message call, iovec[1].length is zero. I have special-cased the client code for this
```
	  if ( iovec[1].length == 0 )
	    {
              sstatus=ucp_am_send_nb(dest,_mcast_dispatch, iovec[0].buffer, iovec[0].length, ucp_dt_make_contig(1), UCXsendMcastDone, 0) ;
```
and in this case the data appearing at the server is what I expect. So there is something going on that I don't expect with ucp_dt_make_iov .

**Comment by snyjm-18** [comment]
Yes, you are correct in your assumption. Have you run the ucp_am gtest? Could you let me know the results?

**Comment by snyjm-18** [comment]
I tried sending a struct similar to that which you sent, and got a correct result. Hopefully the gtest on your system will expose the issue.

**Comment by tjcw** [comment]
I think the problem is that ucp_am_send_nb doesn't make a copy of the ucp_dt_iov_t array. In my case, the ucp_dt_iov_t[2] is a local variable on the caller's stack, and it seems that by the time the ucp active message runtime refers to it, some parts have been reused for other purposes by the caller.
I will run the ucp_am gtest on my system.

**Comment by tjcw** [comment]
Yes, I have confirmed that this is the problem. 'gtest --gtest-filter=*ucp_am*' runs cleanly, but when I change the test to
```
        sstatus = ucp_am_send_nb(receiver().ep(), 0,
                                 iovec, 2, ucp_dt_make_iov(),
                                 (ucp_send_callback_t) ucs_empty_function, 0);
        iovec[0].buffer = NULL ;
        iovec[1].buffer = NULL ;
        wait(sstatus);
```
I get a segmentation violation in the internals of libucs.so, at libucs.so.0(+0x2c308) .
So it looks like ucx requires the 'iovec' to be in storage which is stable until the completion callback is driven.
Is it possible to remove this restriction ?

**Comment by snyjm-18** [comment]
Because it is a nb call, the iovec is not available for reuse until the completion callback is called. I do not believe there is a way to remove this restriction. @yosefe or @shamisp might be able to add more context as this is not an issue specific to AMs.

**Comment by shamisp** [comment]
Is the request to cache the iovec structure itself ? Are you allocating it on stack or something ?

**Comment by snyjm-18** [comment]
When I had to do something similar, I dynamically allocated the memory or used a memory pool and then attached it to the request and then freed/released it in the completion callback.

**Comment by shamisp** [comment]
I would expect that this is something that is cached on the user level (MPI request?)

**Comment by tjcw** [comment]
I have found a suitable structure that I can extend to hold the iovec, and now things are working. Closing.
