### ISSUE TITLE
[Q] futex, Does TODO use pthread_cond mean?

### ISSUE THREAD

**Issue by hiroyuki-sato** [openucx/ucx#3959]
I found the message `TODO use pthread_cond` message in `src/ucs/async/async.c`.
Does this mean that OpenUCX want to replace `futext` to `pthread_cond` on Linux?

I'm looking for `futex` alternative because macOS doesn't support it.
Fortunately, `pthread_cond_wait` and some functions available on macOS.

```
config/m4/sysdep.m4
280:AC_CHECK_HEADERS([linux/futex.h])

src/ucs/async/async.c
521:            /* TODO use pthread_cond / futex to reduce CPU usage while waiting

src/ucs/stats/stats.c
22:#include <linux/futex.h>
93:ucs_sys_futex(volatile void *addr1, int op, int val1, struct timespec *timeout,
96:    return syscall(SYS_futex, addr1, op, val1, timeout, uaddr2, val3);
502:        ucs_sys_futex(&ucs_stats_context.flags, FUTEX_WAIT, flags, ptime, NULL, 0);
619:        ucs_sys_futex(&ucs_stats_context.flags, FUTEX_WAKE, 1, NULL, NULL, 0);
hsato-mbp13:ucx hsato$ rg -i futex
config/m4/sysdep.m4
280:AC_CHECK_HEADERS([linux/futex.h])

src/ucs/async/async.c
521:            /* TODO use pthread_cond / futex to reduce CPU usage while waiting

src/ucs/stats/stats.c
22:#include <linux/futex.h>
93:ucs_sys_futex(volatile void *addr1, int op, int val1, struct timespec *timeout,
96:    return syscall(SYS_futex, addr1, op, val1, timeout, uaddr2, val3);
502:        ucs_sys_futex(&ucs_stats_context.flags, FUTEX_WAIT, flags, ptime, NULL, 0);
619:        ucs_sys_futex(&ucs_stats_context.flags, FUTEX_WAKE, 1, NULL, NULL, 0);
```

**Comment by yosefe** [comment]
@hiroyuki-sato it means we could potentially use either futex of pthread_cond. since we now care about FreeBSD and MacOS, it will probably be pthread_cond and not futex.

**Comment by hiroyuki-sato** [comment]
Hello, @yosefe. Thank you for your comment.

I got it
* Linux -> `futex`
* FreeBSD, macOS -> `pthread_cond` or something.

I'll talk @kostikbel  about implementation.
@kostikbel, Could you cooperate with me when I porting futex alternative?

**Comment by yosefe** [comment]
@hiroyuki-sato if we can make it work with pthread_cond, better use it on Linux as well ..

**Comment by hiroyuki-sato** [comment]
@yosefe Those functions are available on macOS and FreeBSD too.
(I looked up FreeBSD and macOS manual)

I'll try to replace `futex` using `pthread_cond`.

* pthread_cond_destroy
* pthread_cond_init
* pthread_cond_signal
* pthread_cond_timedwait
* pthread_cond_wait

**Comment by kostikbel** [comment]
See https://github.com/kostikbel/ucx/commits/freebsd, commit Futexes are only available on Linux.
I did not tested it for known reasons.

**Comment by hiroyuki-sato** [comment]
Hello, @kostikbel. Thank you for your reply.
I found [this commit](https://github.com/kostikbel/ucx/commit/6ea631a30987253e793a6f410e4d817dcd735c85)
I'll take a look later.

For avoiding duplicate works, we need to share macOS/FreeBSD specific issues.
I'll prepare it.

**Comment by kostikbel** [comment]
Just look at the freebsd branch, and perhaps base your work on it and not on the ucx/master.  I am trying to push all of this into mainstream as soon as I can given that the work is background.

**Comment by hiroyuki-sato** [comment]
@kostikbel Thank you for your comment. I'll take a look at your branch.

I'm developing macOS porting on this branch.
https://github.com/hiroyuki-sato/ucx/tree/osx_fixes
I create PR as soon as possible if a modification relates to a Linux platform.
But, I don't create a PR about macOS(and FreeBSD) specific, because I'm not sure whether those changes are properly or not yet.

**Comment by hiroyuki-sato** [comment]
Hello, @kostikbel 

What do you think to create a new PR on this branch?
https://github.com/hiroyuki-sato/ucx/commit/82697be73aa3a6a11fa457e234d8d3c744d8a8d6

It based on your change.
As @yosefe's comment, I change from futex to pthread_cond.

Please let me know if create a new PR for yourself. Or, Should I change something.
(Commit message and so on.)

**Comment by kostikbel** [comment]
I will create the push request later today, myself.

**Comment by hiroyuki-sato** [comment]
@kostikbel Thank you!

**Comment by hiroyuki-sato** [comment]
PR #4002 is created. I'll close this issue after merge.

**Comment by hiroyuki-sato** [comment]
#4002 has been merged!
