### ISSUE TITLE
Error incompatible types when assigning to type ‘gdr_mh_t’ from type ‘int’ while building UCX

### ISSUE THREAD

**Issue by afernandezody** [openucx/ucx#4019]
Hello,
I'm trying to install UCX in order to facilitate CUDA+MPI jobs. I'm using a configuration with OFED (4.17-1-rc2) and an Ethernet card. After installing CUDA and gdrcopy, I'm trying to build UCX (1.6.0) with:
```
./configure --prefix=/usr/local/ucx-cuda-install --with-cuda=/usr/local/cuda-10.1  --with-gdrcopy=/home/ody/gdrcopy --disable-numa
sudo make install
```
However, I'm getting the following error message:    
```
cuda/gdr_copy/gdr_copy_md.c: In function ‘uct_gdr_copy_mem_reg_internal’:
cuda/gdr_copy/gdr_copy_md.c:109:22: error: incompatible types when assigning to type ‘gdr_mh_t’ from type ‘int’
         mem_hndl->mh = 0;
                      ^
make[1]: *** [cuda/gdr_copy/libuct_la-gdr_copy_md.lo] Error 1
make[1]: Leaving directory `/home/ody/ucx-1.5.2/src/uct'
make: *** [install-recursive] Error 1
```

The error seems to be related to gdrcopy. Any suggestion on what is going on or how to troubleshoot it? Thanks.

**Comment by dmitrygx** [comment]
@afernandezody Hello!

Thank you for reporting this to us!
This is related to UCT/CUDA/GDR_COPY transport.
It has been already fixed in the master branch - #3964.
Please, let me know if this fixes the compilation issue reported by you

**Comment by afernandezody** [comment]
Hi @dmitrygx,
Thank you for the feedback. Is there any timeline on the release of 1.6.1 or 1.7.0? The release schedule on the website indicates August for 1.7.0. I tried the master branch but it has fewer components than the stable release, and lacks the 'configure' file.

**Comment by dmitrygx** [comment]
@yosefe @shamisp could help us with the release schedule?

@afernandezody is it possible to use v1.6.x branch?
BTW, pls try to run ./autogen before configuring master

**Comment by shamisp** [comment]
I think we will have 1.6.1 release out before 1.7.0. On master you have all the same components as in 1.6.x tree. If you download the code directly from git you have to run autogen.sh to generate configure.

**Comment by afernandezody** [comment]
Hi. I tried the master and 1.6.x branches but got the following error message.
```
gdr_copy_ep.c: In function 'uct_gdr_copy_ep_put_short':
gdr_copy_ep.c:45:9: error: implicit declaration of function 'gdr_copy_to_bar' [-Werror=implicit-function-declaration]
         ret = gdr_copy_to_bar(gdr_copy_key->bar_ptr + bar_offset, buffer, length);
         ^
gdr_copy_ep.c: In function 'uct_gdr_copy_ep_get_short':
gdr_copy_ep.c:68:9: error: implicit declaration of function 'gdr_copy_from_bar' [-Werror=implicit-function-declaration]
         ret = gdr_copy_from_bar(buffer, gdr_copy_key->bar_ptr + bar_offset, length);
         ^
cc1: all warnings being treated as errors
make[3]: *** [libuct_cuda_gdrcopy_la-gdr_copy_ep.lo] Error 1
make[3]: Leaving directory `/home/ody/ucx-master/src/uct/cuda/gdr_copy'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/home/ody/ucx-master/src/uct/cuda'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/ody/ucx-master/src/uct'
make: *** [install-recursive] Error 1
```
Although not the same, it looks like related to the previous error. Thanks.

**Comment by bureddy** [comment]
@afernandezody It looks like you have installed  "master" branch of gdrcopy on your setup, which have API change and UCX is not adapted to it yet. Can you please install latest release version (v1.3) of gdrcopy (https://github.com/NVIDIA/gdrcopy/tree/v1.3)

**Comment by afernandezody** [comment]
Hi @bureddy,
The version of gdrcopy v1.3 that I was able to download is 1+ years old and giving me errors during compilation. The error is connected to libgdrapi.so.1.2, and I believe that you commented on it (https://github.com/NVIDIA/gdrcopy-build failure on power PC #27) although I'm not using PowerPC.

**Comment by bureddy** [comment]
@afernandezody 
it seems above reference issue link is incorrect. I guess you are referring https://github.com/NVIDIA/gdrcopy/issues/27 
Can you open an issue in gdrcopy github with build error and your CPU model details?

**Comment by afernandezody** [comment]
Correct. I didn't post the link to the specific issue but to the website. Let me work on the other ticket.
