### ISSUE TITLE
uct_ep_create_connected() undefined

### ISSUE THREAD

**Issue by mmikailov** [openucx/ucx#4020]
Dear Sir/Madam:

When trying to build OpenMPI 4.0.1 with UCX I get:
../../../opal/.libs/libopen-pal.so: undefined reference to `uct_ep_create_connected'

I have already successfully installed UCX before trying to build OpenMPI 4.0.1.

I can not find uct_ep_create_connected () function definition anywhere

.Anyone's help is greatly appreciated.

Thanks,
-Mike

**Comment by shamisp** [comment]
Mike,
What is the configure cmd and where ucx is installed ?

**Comment by mmikailov** [comment]
Thank you for the quick reply. Here it is:
./configure --with-ucx=/projects/mikem/applications/ucx --enable-mpi-cxx --enable-orterun-prefix-by-default \ 
--enable-openib-rdmacm-ibaddr --enable-static --prefix=/projects/mikem/applications/openmpi4 --enable-mpi-fortran \
--with-x --with-sge 2>&1 | tee ../configure.log

UCX is installed under: /projects/mikem/applications/ucx
I also run the below commands before configure:
export PKG_CONFIG_PATH=/projects/mikem/applications/ucx/lib/pkgconfig:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=/projects/mikem/applications/ucx/lib:$LD_LIBRARY_PATH
export ucx_CFLAGS="-I/projects/mikem/applications/ucx/include"
export ucx_LIBS="-L/projects/mikem/applications/ucx/lib"

Your any further help is appreciated.

Thanks,
-Mike

**Comment by yosefe** [comment]
@mmikailov can you pls follow the instructions on https://github.com/openucx/ucx/wiki/OpenMPI-and-OpenSHMEM-installation-with-UCX#openmpi-and-openshmem-installation to disable OpenMPI's btl/uct compilation?

**Comment by mmikailov** [comment]
Thank you very much! Done!

**Comment by shamisp** [comment]
I guess we can close this one.

**Comment by mmikailov** [comment]
Yes, thank you very much for the great support!
