### ISSUE TITLE
BUILD/xpmem: pkg.m4 dependency

### ISSUE THREAD

**Issue by raffenet** [openucx/ucx#4021]
This dependency was removed from the ugni configure, but still exists for xpmem. https://github.com/openucx/ucx/blob/8e9d28d1ba1c94f230ab65a6e5b67840dacc1a08/src/uct/sm/mm/xpmem/configure.m4#L16

**Comment by shamisp** [comment]
@raffenet I suggest to go ahead and update this configure based on Yossi's example
