### ISSUE TITLE
UCX on EL 7.5 and EL 7.6

### ISSUE THREAD

**Issue by ca-taylor** [openucx/ucx#4059]
We'd like to upgrade to EL 7.6.  All of our current hosts are running EL 7.5 with ucx-1.4.0.  That works fine with various builds of OpenMPI on our Mellanox (connect-IB, connectX-4, connectX-5) fabric.

However, if we upgrade any of our hosts to EL 7.6 and install the same ucx 1.4.0 (built on an EL 7.6 host), and try to run an existing app (OpenMPI 3.1.0 in this case but I've tried others) we get the following backtrace.

```
[c1a-s24:27738:0:27738]    ud_iface.c:780  Fatal: transport error: Endpoint timeout
==== backtrace ====
    0  /lib64/libucs.so.0(ucs_fatal_error+0xf7) [0x2b0bc0dcc8b7]
    1  /lib64/libuct.so.0(uct_ud_iface_dispatch_async_comps_do+0x128) [0x2b0bc0b94c78]
    2  /lib64/libuct.so.0(+0x29b18) [0x2b0bc0b98b18]
    3  /lib64/libucp.so.0(ucp_worker_progress+0x22) [0x2b0bbe7958e2]
    4  /apps/mpi/intel/2018.1.163/openmpi/3.1.0/lib64/libmpi.so.40(mca_pml_ucx_progress+0x14) [0x2b0bbb1e9f74]
    5  /apps/mpi/intel/2018.1.163/openmpi/3.1.0/lib64/libopen-pal.so.40(opal_progress+0x24) [0x2b0bbed83424]
    6  /apps/mpi/intel/2018.1.163/openmpi/3.1.0/lib64/libmpi.so.40(ompi_request_default_wait+0xb8) [0x2b0bbb0968a8]
    7  /apps/mpi/intel/2018.1.163/openmpi/3.1.0/lib64/libmpi.so.40(ompi_coll_base_sendrecv_actual+0xc4) [0x2b0bbb0f9544]
    8  /apps/mpi/intel/2018.1.163/openmpi/3.1.0/lib64/libmpi.so.40(ompi_coll_base_allgather_intra_recursivedoubling+0x13a) [0x2b0bbb0f7c2a]
    9  /apps/mpi/intel/2018.1.163/openmpi/3.1.0/lib64/libmpi.so.40(PMPI_Allgather+0x80) [0x2b0bbb0aa840]
   10  /ufrc/ufhpc/chasman/mufasa/gizmo-mufasa/./GIZMO() [0x4c0e2b]
   11  /ufrc/ufhpc/chasman/mufasa/gizmo-mufasa/./GIZMO() [0x41b71f]
   12  /ufrc/ufhpc/chasman/mufasa/gizmo-mufasa/./GIZMO() [0x410a35]
   13  /ufrc/ufhpc/chasman/mufasa/gizmo-mufasa/./GIZMO() [0x41f7aa]
   14  /ufrc/ufhpc/chasman/mufasa/gizmo-mufasa/./GIZMO() [0x406807]
   15  /usr/lib64/libc.so.6(__libc_start_main+0xf5) [0x2b0bbb959495]
   16  /ufrc/ufhpc/chasman/mufasa/gizmo-mufasa/./GIZMO() [0x4060a9]
===================

```
The same thing happens with ucx 1.5.2.  In short, it appears that ucx built on EL 7.5 and ucx built on  EL 7.6 are incompatible.   Is this expected?

Also, should we expect ucx 1.5.2 to be backward compatible with ucx 1.4.0?   I looked for a compatibility matrix but did not find one.

**Comment by ca-taylor** [comment]
This looks similar to,
    https://github.com/openucx/ucx/issues/2685
which references an internal Mellanox ticket and says was fixed.

If so, what was the fix and how do we get it?

**Comment by brminich** [comment]
It also similar to #3087.
Can you please check whether #3090 fixes the issue? (it should be included starting from UCX 1.6)

**Comment by ca-taylor** [comment]
> It also similar to #3087.
> Can you please check whether #3090 fixes the issue? (it should be included starting from UCX 1.6)

Thanks.  I'll give 1.6 a try and post back.

**Comment by ca-taylor** [comment]
Indeed, 1.6 appears to work on both EL7.5 and EL7.6 with existing binaries compiled against ucx 1.4.0.   
Thanks!

**Comment by shamisp** [comment]
I guess we can close this one .

**Comment by ca-taylor** [comment]
> I guess we can close this one .

Yes.  My testing is not very thorough yet but if it turns out that there is still an issue, I will come back and re-open this but I don't think that is going to happen.
