### ISSUE TITLE
Binary portability (OpenMPI + UCX)

### ISSUE THREAD

**Issue by tbiedert** [openucx/ucx#4081]
How portable would a binary distribution of OpenMPI + UCX be (on Linux)?

I guess the dynamic module loading helps, but in the case of CUDA-aware MPI with potentially RDMA, to what degree does it rely on specific versions of MOFED/OFED or CUDA for instance?  

Thanks!

**Comment by yosefe** [comment]
if the application is build over MPI interface, it's binary portability is by OpenMPI rules, which is AFAIK for a major release version (e.g OpenMPI 4.0 should be compatible with OpenMPI 4.1)

**Comment by yosefe** [comment]
Also, a binary build of OpenMPI+UCX is generally NOT compatible across different versions of Cuda and OFED.

**Comment by tbiedert** [comment]
Ok, thanks!  I'm actually talking about the portability of OpenMPI+UCX itself.  So compile both on system A, and use both on system B.

So we basically depend on binary compatibility of CUDA and OFED?

**Comment by yosefe** [comment]
yes
OFED and rdma-core are supposed to be backward compatible but to be on the safe side i would not mix different versions
Cuda - maybe @Akshay-Venkatesh or @spotluri can tell

**Comment by spotluri** [comment]
CUDA driver provides binary backwards compatiblity, UCX only uses CUDA driver API, So, should be OK to reuse on systems with newer CUDA drivers. 
https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility

**Comment by Akshay-Venkatesh** [comment]
> UCX only uses CUDA driver API, So, should be OK to reuse on systems with newer CUDA drivers

@spotluri This is mostly true. There are a few calls runtime calls also made from some of the cuda components.

**Comment by shamisp** [comment]
Can we close ?
