### ISSUE TITLE
Loss in performance as core count increases

### ISSUE THREAD

**Issue by afernandezody** [openucx/ucx#4102]
Hello,
I'm combining UCX 1.6.0 with OpenMPI (4.0.1) in clusters created with instances from AWS. I have no issue compiling and building everything. The jobs run fine but the performance is just not there. Small clusters (72 cores) exhibit the expected performance but increasing the core count (288) leads to performance deterioration (around 20%) versus standard clusters, which use BTL components. The loss in performance is pretty consistent across different benchmarks and I have tried the usual flags (e.g. --mca btl ^vader,tcp,openib,uct), which make no difference. I was wondering if anyone has noticed similar performance in a cloud environment or what could be the root of the behavior. Thanks.

**Comment by yosefe** [comment]
@afernandezody i guess the transports in use are TCP and shared memory?
Can you provide one example of a benchmark and number of cores where you see the most difference vs BTL components (command line, number of nodes, and number of cores per node)?
thank you!

**Comment by yosefe** [comment]
thanks , it seems mostly related to TCP performance then. adding @dmitrygx

**Comment by dmitrygx** [comment]
@afernandezody do you have those benchmarks available for free?

**Comment by yosefe** [comment]
i guess it's https://www.nas.nasa.gov/publications/npb.html

**Comment by dmitrygx** [comment]
> i guess it's https://www.nas.nasa.gov/publications/npb.html

> This is NPB https://www.nas.nasa.gov/publications/npb.html

@yosefe @shamisp thank you!
