### ISSUE TITLE
incorrect UCS_PTR_STATUS(request) behavior

### ISSUE THREAD

**Issue by bureddy** [openucx/ucx#4128]
`(UCS_PTR_STATUS(request) == UCS_OK)` check is ~failing~ false positive if last byte of the inprogress request object address bits are 0. 

```
(gdb) n
84              if (UCS_PTR_STATUS(self->reply) == UCS_OK) {
(gdb) p self->reply
$1 = (void *) 0x1689a00
(gdb) p ((ucs_status_t)(intptr_t)(self->reply))
$2 = UCS_OK
(gdb) p ((ucs_status_t)(intptr_t)(0x1689a00))
$3 = UCS_OK
```

**Comment by shamisp** [comment]
This is really cool bug ! I guess it casts to short because of enum.

**Comment by yosefe** [comment]
@bureddy the expected usage is to check `UCS_PTR_IS_ERR(self->reply)` before doing UCS_PTR_STATUS(_ptr)
even if the enum was full in, we could have a 32-bit aligned ptr

**Comment by bureddy** [comment]
@yosefe  If that is the case, we have used it wrongly in some places. for example,
https://github.com/openucx/ucx/blob/master/test/examples/ucp_hello_world.c#L208

Not sure if this is valid usage. for example,  in ucp_hello_world.c, it is checked UCS_PTR_IS_ERR before UCS_PTR_STATUS. but resulted in a error because request is not progressed.
https://github.com/openucx/ucx/blob/master/test/examples/ucp_hello_world.c#L208

```
Assertion `address_count <= 64' failed


/scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-gpu/worker/1/contrib/../src/ucs/debug/assert.c: [ ucs_fatal_error_message() ]
      ...
       30     }
       31 
       32     ucs_handle_error(message_buf);
==>    33     abort();
       34 }
       35 
       36 void ucs_fatal_error_format(const char *file, unsigned line,

==== backtrace (tid:  16929) ====
 0 0x0000000000050a31 ucs_fatal_error_message()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-gpu/worker/1/contrib/../src/ucs/debug/assert.c:33
 1 0x0000000000050bb6 ucs_fatal_error_format()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-gpu/worker/1/contrib/../src/ucs/debug/assert.c:49
 2 0x000000000006c4f8 ucp_address_unpack()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-gpu/worker/1/contrib/../src/ucp/wireup/address.c:811
 3 0x000000000001a173 ucp_ep_create_api_to_worker_addr()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-gpu/worker/1/contrib/../src/ucp/core/ucp_ep.c:550
 4 0x000000000001a6f3 ucp_ep_create()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-gpu/worker/1/contrib/../src/ucp/core/ucp_ep.c:639
 5 0x00000000004027c9 run_ucx_server()  ucp_hello_world.c:0
 6 0x00000000004029a0 run_test()  ucp_hello_world.c:0
 7 0x0000000000402e7a main()  ???:0
 8 0x0000000000021c05 __libc_start_main()  ???:0
 9 0x0000000000401959 _start()  ???:0
=================================
```

**Comment by bureddy** [comment]
https://github.com/openucx/ucx/issues/3849

**Comment by yosefe** [comment]
@bureddy where did you see this error? but https://github.com/openucx/ucx/blob/master/test/examples/ucp_hello_world.c#L208 does check UCS_PTR_IS_ERR a few lines before...

**Comment by bureddy** [comment]
I see this in jenkins of my WIP PR: https://github.com/openucx/ucx/pull/4123 , where I have added few fields in ucp_request struct which changed the size of struct from 232 Bytes to 256 Bytes.  Because of this alignment now I see more user requests ptr are 256B aligned.
jenkins log:  http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/label=hpc-test-node-gpu,worker=1//12153/console

I tried https://github.com/openucx/ucx/pull/4123/commits/c61a03ca62406d030afeff37fe5e95de77ab23b4  in that PR to workaround this issue.

I can even reproduce this issue easily w/o this PR by simply adding some padding bytes in request object.


```

201     request = ucp_tag_send_nb(server_ep, msg, msg_len,
202                               ucp_dt_make_contig(1), tag,
203                               send_handler);
204     if (UCS_PTR_IS_ERR(request)) {
205         fprintf(stderr, "unable to send UCX address message\n");
206         free(msg);
207         goto err_ep;
208     } else if (UCS_PTR_STATUS(request) != UCS_OK) {
209         wait(ucp_worker, request);
210         request->completed = 0; /* Reset request state before recycling it */
211         ucp_request_release(request);
212     }
213
```

In the above code,  got request ptr with 256B aligned ptr,   UCS_PTR_IS_ERR(request) check at line 204 is  false, then UCS_PTR_STATUS check at line 208 is also false.

**Comment by shamisp** [comment]
> @bureddy the expected usage is to check `UCS_PTR_IS_ERR(self->reply)` before doing UCS_PTR_STATUS(_ptr)
> even if the enum was full int, we could have a 32-bit aligned ptr

@yosefe I don't think we explicitly document this. In UCP.H we have some examples how to check request status but I think we should explicitly state this.

**Comment by yosefe** [comment]
@shamisp agree. I want to change ucp.h that we should check for NULL, since comparing to UCS_OK 1st could be misleading. Maybe even dedicate a small text section for this.
