### ISSUE TITLE
COMPILER_OPTION macro in configure.m4 is broken

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#4129]
building ucx with `--enable-optimizations` does not really enable cpu optimizations, since the optimization flags are not added to BASE_CFLAGS/BASE_CXXFLAGS

Also, need to rename this macro to COMPILER_ARCH_OPTION or similar

**Comment by hoopoepg** [comment]
@yosefe I will look

**Comment by yosefe** [comment]
@hoopoepg thanks, but no need - i have patch to fix it (not submitted yet), will ask u to review ..

**Comment by yosefe** [comment]
fixed by #4157
