### ISSUE TITLE
Cannot build with gdr_copy on v1.6.x branch

### ISSUE THREAD

**Issue by chhu** [openucx/ucx#4201]
Hi,
Compiled latest gdr_copy from nvidia repo with master from ucx and was happy that everything worked. Then I was not so happy to see that UCX API changed so it cannot compile against ompi master. That forced me to go back to v1.6.x branch, now gdr_copy does complain because of new API... How can I resolve this? What version of gdr_copy do I need to check out to be compatible with v1.6.x?
Thanks!

**Comment by brminich** [comment]
Can you please try to disable building UCT btl  by adding `--enable-mca-no-build=btl-uct` to your configure? 

Described here: https://github.com/openucx/ucx/wiki/OpenMPI-and-OpenSHMEM-installation-with-UCX

**Comment by chhu** [comment]
That did work indeed. 
Thanks!!
