### ISSUE TITLE
[Q] spinlock using __sync_bool_compare_and_swap implementation 

### ISSUE THREAD

**Issue by hiroyuki-sato** [openucx/ucx#4208]
Hello, @dmitrygx 

As we discussed [before](https://github.com/openucx/ucx/issues/3928#issuecomment-513706788), I'm trying to implement `pthread_spinlock` alternative, because macOS doesn't support it.
This branch is the `__sync_bool_compare_and_swap` implementation.
https://github.com/hiroyuki-sato/ucx/commit/32f853e346cf52c97d3dc7cfb6818604444d2d84

Could you check this change when you get a chance?
I don't create PR for a while. 

Best regards.

**Comment by dmitrygx** [comment]
Hello @hiroyuki-sato 

Posted comments to use UCS alternatives (wrappers) for atomic compare-and-swap and fence operations instead

**Comment by hiroyuki-sato** [comment]
Hello, @dmitrygx. Thank you for your reply. I'll fix it.

P.S.
I realized that compare-and-swap and progress64 spinlock are easy to test on macOS and Linux.
`os_unfair_lock` work on macOS only. So, It is hard to test on both platforms.

P.S2
I'm not sure yet but, [progress64](https://github.com/hiroyuki-sato/ucx/blob/topic/use-progress64/src/ucs/type/spinlock.h) spinlock failed on gtest. I'll investigate it later.
