### ISSUE TITLE
Linker error when building 1.6.1

### ISSUE THREAD

**Issue by jakirkham** [openucx/ucx#4218]
Am able to build 1.5.1 without issues. However when trying to build 1.6.0 and more recently 1.6.1, have ran into build issues. Appears there is some sort of linker error, but am unclear on the cause or how to fix it. Here's the [build log]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=74876&view=logs&jobId=90682b30-d652-55a6-6545-e470106c30b8 ) from the changes in PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/19 ). Also here's [the build script]( https://github.com/conda-forge/ucx-split-feedstock/blob/51664397134e62f679f4990ab49b7ae02c9994f1/recipe/install_ucx.sh ) used.

**Comment by yosefe** [comment]
@jakirkham can you please change "make VERBOSE=1" to "make V=1" so we can see the full link command?

**Comment by yosefe** [comment]
@jakirkham seems like linker flags for nested convenience libraries are not passed by libtool. Also the path seems very long "_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p"

is it possible to make it shorter?

**Comment by jakirkham** [comment]
Hmm...is that something I'm actually able to affect or is that more internal to UCX's build process?

The path length is made quite long intentionally to ensure the binaries are relocatable. IOW the path can be replaced easily when a user installs this package somewhere else on their own system.

What I find interesting is these problems did not exist in 1.5.1. For instance here is [a recent build of 1.5.1]( https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_build/results?buildId=74869 ), which passes. We've only [changed the version]( https://github.com/conda-forge/ucx-split-feedstock/pull/19/files ).

**Comment by jakirkham** [comment]
cc @Akshay-Venkatesh

**Comment by yosefe** [comment]
the change in v1.6 is that we added new test (test_link_map) which uses libtool convenience libraries.

**Comment by jakirkham** [comment]
Ah ok. Thanks for spelling that out.

Does this require `.la` files (libtool archive files)?

**Comment by yosefe** [comment]
yes
we tell libtool to use libucp.la, and it should also pick up its dependencies (libucs, libuct). for some reason on that system the dependencies are not picked by libtool

**Comment by jakirkham** [comment]
We typically strip libtool `.la` files from packages. Is it possible for us to just disable this test? I think it's just going to point out we don't provide `.la` files.

**Comment by yosefe** [comment]
these are .la files which are not park of packages, but used internally during UCX build process..
@jakirkham can you pls check if changing top_builddir to abs_top_builddir in https://github.com/openucx/ucx/blob/master/test/apps/Makefile.am#L36 helps?

**Comment by jakirkham** [comment]
I see.

That's a good lead. Gave it a try. Unfortunately it's [still failing]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=75334 ). Here's [the patch]( https://github.com/conda-forge/ucx-split-feedstock/blob/fafedc58b4e85aabc4960b2194605575e93f8333/recipe/fixes_4218.patch ) used in the build.

**Comment by yosefe** [comment]
@jakirkham is it possible to recreate the build environment outside of Azure CI to debug this?
Or alternatively can we pull all intermediate build files from Azure to inspect them? Specifically, i'd like to see libucp.la and libtool script

BTW seems like there is a typo in libibverbs rpm name here:
https://github.com/conda-forge/ucx-split-feedstock/blob/51664397134e62f679f4990ab49b7ae02c9994f1/.azure-pipelines/build_steps.sh#L34

**Comment by jakirkham** [comment]
Yeah if you clone my branch, you can run `python build-locally.py` and this will run the build on your machine. It builds within a Docker container (so you will need Docker installed). The container is left around after the build (even if it fails) so you can inspect it more closely.

Ah thanks for catching that. Will submit a fix. 🙂

**Comment by yosefe** [comment]
@jakirkham I see this issue too. Can you try with this patch in UCX:
```
diff --git a/configure.ac b/configure.ac
index bbb3f51..781b1eb 100644
--- a/configure.ac
+++ b/configure.ac
@@ -82,6 +82,13 @@ AC_FUNC_STRERROR_R
 AC_PATH_TOOL([PKG_CONFIG], [pkg-config], [pkg-config])
 
 
+#
+# Force link_all_deplibs=yes for libtool, otherwise it will not
+# link agains dependency libs
+#
+link_all_deplibs=yes
+
+
 #
 # Check if 'ln' supports creating relative links
 #
```

**Comment by jakirkham** [comment]
Should I be using both patches or can I drop [the other one]( https://github.com/openucx/ucx/issues/4218#issuecomment-535078115 )?

**Comment by yosefe** [comment]
drop the previous one

**Comment by jakirkham** [comment]
Looks that [fails too]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=75576 ). Let me know if there are more flags you'd like me to set to provide more info in these logs.

**Comment by yosefe** [comment]
@jakirkham are you pulling UCX from github repo or from dist tarball? if the latter, need to re-run ./autogen.sh

**Comment by jakirkham** [comment]
Of course. Thanks for the reminder. Will retry and report back.

**Comment by jakirkham** [comment]
Yep, [the `configure.ac` patch works]( https://github.com/openucx/ucx/issues/4218#issuecomment-535572106 ). Thanks for putting that together, @yosefe! 😄

**Comment by jakirkham** [comment]
@yosefe, I went ahead and submitted your patch as PR ( https://github.com/openucx/ucx/pull/4279 ) and gave you credit. Hope that is ok. :)
