### ISSUE TITLE
Clarify message context documentation

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#4228]
See my notes here https://github.com/openucx/ucx/pull/4180

**Comment by tonycurtis** [comment]
uct_def.h


> 
> * If UCT_CB_PARAM_FLAG_DESC flag is enabled, then data is part of a descriptor
> * which includes the user-defined rx_headroom, and the callback may return
> * UCS_INPROGRESS and hold on to that descriptor. Otherwise, the data can't be
> * used outside the callback. If needed, the data must be copied-out.


If the UCT_CB_PARAM_FLAG_DESC flag is enabled, then the data is part of a descriptor
that includes the user-defined rx_headroom, and the callback may return
UCS_INPROGRESS and hold on to that descriptor.  Otherwise, the data can't be used outside of the callback.
If needed, the data must be copied out.

“May return” implies other value(s) might be returned - should they be enumerated?

> more fragments of the message yet to be delivered.

Are yet to be…

> * @param [inout] context Storage for a per-message user-defined context. For      
> *      
> * example, it can be initialized to a user-defined value      
> * @retval UCS_OK - descriptor was consumed, and can be released      
> * when the first fragment arrives with the flag


Is “it” the storage or the context?

> No need to initialize the value in case of single      
> * fragment message 

In case of -> if the message is a single fragment

Tony

**Comment by brminich** [comment]
It is storage for the context. UCT provides a storage where UCP keeps message context.
UCP sets it to some value when the first fragment arrives, and then uses it for assembling the message when the rest of fragments arrive

**Comment by brminich** [comment]
@shamisp clarification that the message is sent by a single call looks important to me.
@tonycurtis, do you have edits to the description proposed by @shamisp? 
The final text would be :
```
Storage for a per-message user-defined context. In this context, the message is defined by the sender side as single call
to uct_ep_tag_eager_short/bcopy/zcopy. On the transport level the message can be fragmented and delivered to the target
over multiple fragments. The fragments will preserve the original order of the message. Each fragment will result in
invocation of the above callback. The user can use UCT_CB_PARAM_FLAG_FIRST to identify the first fragment, allocate 
context object and use the context as token that is set by user and passed to subsequents callbacks of the same message.
The user is responsible for allocation and release of the context.

@note No need to allocate the context in case of single fragment message (i.e. @a flags contains 
      @ref UCT_CB_PARAM_FLAG_FIRST, but does not contain @ref UCT_CB_PARAM_FLAG_MORE).
```

**Comment by shamisp** [comment]
@brminich looks good to me.

**Comment by tonycurtis** [comment]
> On Sep 27, 2019, at 7:18 AM, Mikhail Brinskiy <notifications@github.com> wrote:
> 
> @shamisp <https://github.com/shamisp> clarification that the message is sent by a single call looks important to me.
> @tonycurtis <https://github.com/tonycurtis>, do you have edits to the description proposed by @shamisp <https://github.com/shamisp>?
> The final text would be :
> 
> Storage for a per-message user-defined context. In this context, the message is defined by the sender side as single call
> to uct_ep_tag_eager_short/bcopy/zcopy. On the transport level the message can be fragmented and delivered to the target
> over multiple fragments. The fragments will preserve the original order of the message. Each fragment will result in
> invocation of the above callback. The user can use UCT_CB_PARAM_FLAG_FIRST to identify the first fragment, allocate 
> context object and use the context as token that is set by user and passed to subsequents callbacks of the same message.
> The user is responsible for allocation and release of the context.
> 
> @note No need to allocate the context in case of single fragment message (i.e. @a flags contains 
>       @ref UCT_CB_PARAM_FLAG_FIRST, but does not contain @ref UCT_CB_PARAM_FLAG_MORE).
I'd just add articles/plural-fix in:

… allocate the context object and use the context as a token…by the user… subsequent … 

… in the case of a single … 

Otherwise fine!
Tony

**Comment by brminich** [comment]
#4238

**Comment by shamisp** [comment]
Fixed
