### ISSUE TITLE
Could not get ucp_rkey_ptr to work with mapped global/static variables

### ISSUE THREAD

**Issue by lyu** [openucx/ucx#4230]
UCX: master branch

Test program: [test_ucp_rkey_ptr.cpp](https://gist.github.com/lyu/be7510c2860d853db13c1f738fe36dc5)

In OpenSHMEM all the global/static variables must be remotely accessible. While we were able to map them by mapping the .data and .bss sections using ucp_mem_map and have them exposed to the network, we could not get valid pointers to these variables using ucp_rkey_ptr, even within the same process.

The test program linked above attempts to get pointers for both heap-allocated objects and registered global objects, and the latter fails.

Sample output:
```
** .data + .bss sections: [0x404100 ~ 0x404250]
** Initialized global variable @ 0x404238
** Uninitialized global variable (BSS) @ 0x404240

Heap allocated @ 0x2aaaaacc0000
.data mapped @ 0x404100

ucp_rkey_ptr returned pointer for heap data: 0x2aaab019f008... Works!
Cannot get .data pointer: Destination is unreachable
```

Even if I make sure the .data section is page-aligned
```
** .data + .bss sections: [0x205000 ~ 0x205250]
** Initialized global variable @ 0x205130
** Uninitialized global variable (BSS) @ 0x205138

Heap allocated @ 0x2aaaaacc0000
.data mapped @ 0x205000

ucp_rkey_ptr returned pointer for heap data: 0x2aaab019f008... Works!
Cannot get .data pointer: Destination is unreachable
```

Am I doing something wrong? Thank you!

**Comment by brminich** [comment]
That is not supported by UCX.  
`ucp_rkey_ptr` works for the allocated shared memory only.

**Comment by lyu** [comment]
Thanks! Closing.
