### ISSUE TITLE
Possible to get user information in callback of ucp_tag_recv_nb before it returns?

### ISSUE THREAD

**Issue by rzambre** [openucx/ucx#4235]
Occasionally, I notice that the callback of `ucp_tag_recv_nb` gets called before `ucp_tag_recv_nb` returns. In such cases, is there any way to access any "user information" related to the operation? For example, when I have multiple UCP workers that use the same callback for receives on all UCP workers, I would like to know which worker was used for the operation that the callback is associated with. So my "user information" here is the index of the worker used for the operation.

Is it possible to find the worker index in the callback with the current API?

**Comment by brminich** [comment]
Please check discussion in #4187. With the current API it is not so easy. You may use some specific var/flag indicating whether your request info was filled. Then you would be able to distinguish immediate and regular completions

**Comment by rzambre** [comment]
Hmm, I am able to detect whether or not the completion is immediate or regular. What I need is some information about the operation being completed in the completion callback. Anyways, I read through the discussion in the issue and it seems like it is not straightforward to get this kind of information with the current API without some additional overheads.

To get my user-information about which UCP worker was used for this operation, I could use different callbacks, each hardcoded with the worker index in its body. But maintaining such a code is not sustainable especially when I can have workers in the order of hundreds. For this particular problem where I just need to know the index of the worker used for the operation, it would've been nice if I could specify the index as an argument into the callback function. But I am not sure if such an extension to the API would accommodate for all kinds of situations.

**Comment by shamisp** [comment]
Are you trying to map worker to MPI session from the Callback  ? I’m just trying to figure out what is the high level issue that we are trying to resolve ?

**Comment by rzambre** [comment]
@shamisp In our experimental MPICH version, we are maintaining a pool of UCP workers (each worker could map to different MPI objects -- could be MPI sessions, MPI communicators, MPI windows, or anything else). Each worker is associated with a cache of MPI requests. So, during the creation and freeing of an MPI request, we use the cache of the worker used for the operation of that request. One of the places where we have to create an MPI request is when the completion callback of `ucp_tag_recv_nb` is executed before the program returns from `ucp_tag_recv_nb` (https://github.com/pmodels/mpich/blob/master/src/mpid/ch4/netmod/ucx/ucx_recv.h#L26). In these cases, we need to know which worker was used for the `ucp_tag_recv_nb`.

**Comment by shamisp** [comment]
Why do you create request ? Is this unexpected message ?

**Comment by rzambre** [comment]
The logic is not related to handling unexpected messages. Actually, I am not sure why we create a request there.

@raffenet would we break anything if we switch to always creating the request after `ucp_tag_recv_nb` returns?

**Comment by rzambre** [comment]
There might be a way we can rework logic in MPICH to prevent the creation of a Request in the callback, which would get rid of our need for user-information in the callback. So I'll close this issue for now.
