### ISSUE TITLE
Error in ucs_socket_send_nb results in an infinite loop

### ISSUE THREAD

**Issue by madsbk** [openucx/ucx#4243]
As far as I can see, [`uct_tcp_ep_send()`](https://github.com/openucx/ucx/blob/master/src/uct/tcp/tcp_ep.c#L491) translate any error returned by [`ucs_socket_send_nb()`](https://github.com/openucx/ucx/blob/a5225ac407f8939c85d57ab9c190eba9fe43767a/src/ucs/sys/sock.h#L143) as a zero progress count.

Thus, when [`ucs_socket_handle_io_error`](https://github.com/openucx/ucx/blob/master/src/ucs/sys/sock.c#L217) returns `UCS_ERR_IO_ERROR` it is interpreted as _no progress_ and the system goes into an infinite loop where it keeps trying to send on the broken socket.

cc @Akshay-Venkatesh

**Comment by dmitrygx** [comment]
> As far as I can see, uct_tcp_ep_send() translate any error returned by ucs_socket_send_nb() as a zero progress count.

@madsbk yes, you're right
Unfortunately, we don't have an error handling enabled in UCT/TCP

> Thus, when ucs_socket_handle_io_error returns UCS_ERR_IO_ERROR it is interpreted as no progress and the system goes into an infinite loop where it keeps trying to send on the broken socket.

btw, even if we enable error handling when sending data from AM functions (when we may return an error to a user), we still don't a way to report an error from `uct_iface_progress()` when progressing user's data that weren't sent thru AM function

**Comment by madsbk** [comment]
Is it possible to _flag_ the send message as finished/canceled so it won't be scheduled again?

**Comment by dmitrygx** [comment]
> Is it possible to _flag_ the send message as finished/canceled so it won't be scheduled again?

yes, it is possible - we should close a broken socket as communications are impossible anymore to not handle events from `epoll_wait()` for it as they just report us about an error on a fd
but, this UCT Endpoint is non-operational anymore and should be closed by a user

**Comment by dmitrygx** [comment]
@madsbk is it possible to fetch and test #4248 PR in order to evaluate the solution with your application? thank you in advance!

**Comment by shamisp** [comment]
@dmitrygx - this is true not just TCP. This is generally necessary for FT support. We should be able to detect and close EP that entered error state for whatever reason.

**Comment by dmitrygx** [comment]
@shamisp we have plans on error handling support enabling in TCP, but for now, I think it would good to just close a TCP socket for a given EP to avoid receiving `EPOLLOUT`/`EPOLLIN` events on that socket from `epoll_wait()`  - this is what #4248 PR does

**Comment by shamisp** [comment]
@dmitrygx makes sense.

**Comment by dmitrygx** [comment]
@madsbk can you confirm whether it fixes your application or not?

**Comment by madsbk** [comment]
> @madsbk can you confirm whether it fixes your application or not?

It works, thanks!
