### ISSUE TITLE
Message rate depends on number of messages?

### ISSUE THREAD

**Issue by rzambre** [openucx/ucx#4280]
I am trying to understand the behavior of UCX for `ucp_get_nbi`. The graph is the message rate (average of at least 3 trials) reported by an OSU_MBW_MR -style benchmark with 16 process pairs using windows of `MPI_Get-MPI_Win_flush`. Each window is 64 `MPI_Get`s (8 bytes) followed by an `MPI_Win_flush`.  On the x-axis I am just varying the number of messages between each process-pair. Ideally, the number of messages should not matter, that is, the graph should have a straight line. In this graph, there is no warmup before I start measuring. If I include a warmup of 1 million messages before I start measuring, the graph is a straight line.

(1) What overheads are present when I send very few messages that get amortized over larger number of messages?
(2) Why does the average message rate behave irregularly after 8K messages? It also gets noisier after that point. Does it have to do with how requests are handled internally by UCX?

This is with `ucx-1.5.0` using `UCX_NET_DEVICES=mlx5_0:1` and `UCX_TLS=rc_mlx5,rc` on MPICH `master`.

![get_message_rate_versus_messages](https://user-images.githubusercontent.com/15037603/66687722-48d1fd80-ec49-11e9-9bec-4b2fff752562.png)

**Comment by rzambre** [comment]
If you need any more information or the microbenchmark, please let me know.

**Comment by brminich** [comment]
The performance drop at 8KB can be explained by switching to another protocol (e.g. bcopy to zcopy).
For get operations the threshold is 16K. Since you see the drop starting at 8K, I'd assume that SW RMA emulation is used instead of real RDMA (we use 8K segments for active messages).  
Can you please collect UCX debug traces by setting UCX_LOG_LEVEL=trace? You'd need to build debug UCX version for that. When collecting traces, please run just 1 iteration and use 1 pair. Also is it possible to use newer UCX - 1.6.0 or master? It is always better to debug using latest available release.
BTW, do you see the same behavior with Open MPI using `osc ucx`?

**Comment by rzambre** [comment]
@brminich note that the x-axis is not the message size. The x-axis is just the number of messages. Each message is 8 bytes. So for each message, UCX would be using the same `short` protocol.

I can check with UCX-1.6.0 to see if this issue still exists.

**Comment by brminich** [comment]
oh, right. What is the message rate when warmup is done?

**Comment by rzambre** [comment]
Here is the same graph as above which also includes a line with a `warmup` of 1 million messages. In the case of `warmup`, the initial incline is not present, stating that there is some overhead occurring for the first messages. But the `warmup` still includes the drop around 4k messages.

![get_message_rate_versus_messages_with_and_without_warmup](https://user-images.githubusercontent.com/15037603/66772213-cda75c00-ee81-11e9-8abb-dbdc243fd6fb.png)

**Comment by rzambre** [comment]
Also, the reason why the performance `without warmup` is important is that applications typically do not have any notion of warmup in their runs. They might finish before the underlying mechanisms have "warmed up" and would hence observe slow performance.

**Comment by evgeny-leksikov** [comment]
@rzambre I think you can get some better numbers increasing these parameters:
```
ucx_info -c  | grep LEN | grep _RC_
UCX_RC_VERBS_TX_QUEUE_LEN=256
UCX_RC_VERBS_RX_QUEUE_LEN=4095
UCX_RC_VERBS_TX_CQ_LEN=4096
UCX_RC_MLX5_TX_QUEUE_LEN=256
UCX_RC_MLX5_RX_QUEUE_LEN=4095
UCX_RC_MLX5_TX_CQ_LEN=4096
```
