### ISSUE TITLE
[Q] How to get the received nbytes by ucp_tag_recv_nb() when it completes immediately

### ISSUE THREAD

**Issue by madsbk** [openucx/ucx#4289]
Is it possible to get the number of bytes received by `ucp_tag_recv_nb()` when the return status is `UCS_OK` i.e. `ucp_tag_recv_nb()` completes immediately without calling the callback function.

In my callback function I check if the `ucp_tag_recv_info_t.length` is as expected but how to do that when `ucp_tag_recv_nb()` completes immediately?

Notice that `ucp_tag_recv_nb()` returns `UCS_OK` even when `ucp_tag_recv_nb()` haven't received the full `count*datatype`.

**Comment by yosefe** [comment]
because of this, for tag_recv_nb, the callback is called also for immediate completion

**Comment by madsbk** [comment]
I see thanks! 
I confused the semantic of `ucp_tag_send_nb()` with `ucp_tag_recv_nb()`.
