### ISSUE TITLE
API/ABI compatibility between build variants

### ISSUE THREAD

**Issue by jakirkham** [openucx/ucx#4300]
Am curious from a building/packaging perspective how the API/ABI is affected by different compilations. For instance if CUDA is disabled/enabled, how does that affect the API/ABI available for other libraries to link against? Though this could be asked for other options as well. Asking as I'd like to know if other libraries built against UCX should be tracking/depending on these options somehow. Or if these other libraries will be the same regardless what features of UCX were enabled/disabled at build time.

**Comment by yosefe** [comment]
UCX API/ABI does not depend on ./configure result such as cuda on/off detection

**Comment by shamisp** [comment]
Since the question was addressed, I will go ahead and close the ticket

**Comment by jakirkham** [comment]
Thanks!
