### ISSUE TITLE
[Q] Is it legal to fork after initialization?

### ISSUE THREAD

**Issue by madsbk** [openucx/ucx#4325]
After creating `ucp_context_h` and `ucp_worker_h`, is it legal to fork the process? If yes, what is the semantic? Is it as if they were created separately?

What about forking after calls to `ucp_ep_create()` and `ucp_listener_create()`?

cc @pentschev

**Comment by yosefe** [comment]
@madsbk it's OK to fork as long as no RDMA or UCX API are used in the child process

**Comment by madsbk** [comment]
Thanks for the clarification!

**Comment by bistack** [comment]
@yosefe Hi. Is it possible that chid process cleans up env and then re-connects new ucx RDMA connections?

**Comment by yosefe** [comment]
> @yosefe Hi. Is it possible that chid process cleans up env and then re-connects new ucx RDMA connections?

it may work, but it's not officially supported/tested at the moment.

**Comment by bistack** [comment]
@yosefe Thanks. We had tried once without success. A big problem was that we did not understand the ucx code. Is there some demo code? Maybe we could try second times.

**Comment by gsanchezgallegos** [comment]
Any updates? What works for me was making the connections after fork. Trying to close the conections before forking did not work.
