### ISSUE TITLE
UCM/CUDA: failure in ucm_cudafree_dispatch_events when there is no context

### ISSUE THREAD

**Issue by pentschev** [openucx/ucx#4367]
When `cudaFree` is called, `ucm_cudafree_dispatch_events` will call `cuMemGetAddressRange` to attempt to find the base pointer and its size. If there's no CUDA context set in the thread, the call to `cuMemGetAddressRange` will fail and consequently the assertion https://github.com/openucx/ucx/blob/master/src/ucm/cuda/cudamem.c#L117 as well.

For a bit more context on when this issue happens, it may happen with UCX-Py when the application has multiple threads that may be doing any generic work and Python happens to call the garbage collector which will run in the current thread. However, this thread may not have a CUDA context set, as it could after all not be doing any CUDA work.

When the CUDA runtime API is used, it will automatically set the primary CUDA context, so a call to `cudaFree` would work even when no context is set. This raises two questions:

1. Should that assertion only happen if the `cuMemGetAddressRange` call succeeds?
1. I'm assuming UCX is using the returned size to do some internal control, as it is set to 1 when that fails. Could we just continue when the call fails (no assertion) and downgrade the warning to trace/debug or some other log level to allow the application to run cleanly?

I've seen this error when there's no context set, but I think a failure for any other reason would manifest the same way.

cc @quasiben @madsbk for visibility

**Comment by bureddy** [comment]
@pentschev I think assertion should be only when cuMemGetAddressRange
And also I think we can downgrade the warning

**Comment by pentschev** [comment]
Thanks for the reply @bureddy. I opened https://github.com/openucx/ucx/pull/4374 to address this.
