### ISSUE TITLE
Can mempool of ucx manage cuda memory?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [openucx/ucx#4368]
These days  I want to mange cuda memory in my code, and I find that ucx has implemented mempool,  but I can't make sure whether ucx's mempool can manage cuda memory or not due to too many code file in ucx project. So can mempool of ucx manage cuda memory, and can you give me some instructions to help me manage cuda memory in ucx?

**Comment by yosefe** [comment]
it's not possible because mpool metadata is also on the backing storage

**Comment by Keepmoving-ZXY** [comment]
ok, and does rcache can manage cuda memory of different gpu devices?

**Comment by yosefe** [comment]
> ok, and does rcache can manage cuda memory of different gpu devices?

Yes

**Comment by Keepmoving-ZXY** [comment]
thank you, I have a detailed watch to rcache.

**Comment by Keepmoving-ZXY** [comment]
Does `ucp_mem_map` can allocate cuda memory
