### ISSUE TITLE
Remove UCX_TLS rc alias or rename rc TL to rcv

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#4390]
So, I checked few people outside of Mellanox about their understanding what "rc" in UCX_TLS actually means. As expected, nobody had an idea that rc is an alias that silently enables rc_mlx5. The actual name for rc transport is rc_v and not rc. My suggestion is to remove rc alias and map it back to an actual rc TL.  Alternative is rename rc TL to rcv.

**Comment by yosefe** [comment]
We can rename "rc" transport to "rc_verbs" and "rc" alias will enable both.
This will prevent situation where users who are not aware of mlx5/verbs difference will select "rc" transport, and will get worse performance.

**Comment by shamisp** [comment]
Rename to rc -> rc_verbs transport works for me.

**Comment by shamisp** [comment]
BTW, the same goes for UD.

**Comment by yosefe** [comment]
> BTW, the same goes for UD.

Of course.

**Comment by quasiben** [comment]
something to be aware of @pentschev
