### ISSUE TITLE
cudaHostRegister invalid argument in uct_cuda_copy_mem_reg

### ISSUE THREAD

**Issue by Sergei-Lebedev** [openucx/ucx#4393]
ucp_mem_map fails to register cuda memory. 
The exact error:
```
cuda_copy_md.c:86   UCX  ERROR cudaHostRegister(address, length, 0x01) is failed. ret:invalid argument
ucp_mm.c:121  UCX  ERROR failed to register address 0x7fb473081000 length 4915200 on md[0]=cuda_cpy: Input/output error
```
uct_cuda_copy_mem_reg first checks memory type and then if it's not a host pointer it calls cudaHostRegister. But cudaHostRegister in turn works only for host memory and it doesn't make sense to pass cuda pointer to it, probably that's why ucx prints "invalid argument" error.

**Comment by Sergei-Lebedev** [comment]
UPD: there are no errors If memtype cache is disabled

**Comment by dmitrygx** [comment]
@Sergei-Lebedev could you share `params` that you pass as an argument, please?

**Comment by bureddy** [comment]
@Sergei-Lebedev the check(https://github.com/openucx/ucx/blob/master/src/uct/cuda/cuda_copy/cuda_copy_md.c#L76)  is to prevent double registration. cuPointerGetAttribute() return CU_MEMORYTYPE_HOST only if the memory is already registered or allocated with cudaMallocHost(0 which is already registered.

if memory is allocated with malloc() and friends, then cuPointerGetAttribute() return NULL

**Comment by bureddy** [comment]
> UPD: there are no errors If memtype cache is disabled

look like memtype cache not detected the type correctly 
 for ucp_mem_map memory https://github.com/openucx/ucx/blob/master/src/ucp/core/ucp_mm.c#L329

**Comment by dmitrygx** [comment]
> look like memtype cache not detected the type correctly

@bureddy yes, this is a case
we have a fix for this
