### ISSUE TITLE
bug: pending request should have been flushed

### ISSUE THREAD

**Issue by angainor** [openucx/ucx#4482]
In my benchmark code I quite often see the following bug reported by UCX 1.6.1:

```
[login-1-1:145512:2:145517]      ucp_ep.c:648  Bug: pending request 0x2ac4fc01a828 on ep 0x2ac5670fc000 should have been flushed
[login-1-1:145512:0:145515]      ucp_ep.c:648  Bug: pending request 0x2ac504018ce8 on ep 0x2ac56707c000 should have been flushed
[login-1-1:145512:1:145514]      ucp_ep.c:648  Bug: pending request 0x2ac500019ce8 on ep 0x2ac5670bc000 should have been flushed
==== backtrace (tid: 145514) ====
 0 0x000000000001e250 ucs_fatal_error_message()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucs/debug/assert.c:36
 1 0x000000000001e3b6 ucs_fatal_error_format()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucs/debug/assert.c:52
 2 0x00000000000120ab ucp_destroyed_ep_pending_purge()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucp/core/ucp_ep.c:648
 3 0x00000000000122a6 uct_mm_ep_abriter_purge_cb()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/uct/sm/mm/base/mm_ep.c:401
 4 0x0000000000017f09 ucs_arbiter_group_purge()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucs/datastruct/arbiter.c:151
 5 0x000000000001232d uct_mm_ep_pending_purge()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/uct/sm/mm/base/mm_ep.c:415
 6 0x000000000001218d uct_ep_pending_purge()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/uct/api/uct.h:2186
 7 0x000000000001218d ucp_ep_cleanup_lanes()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucp/core/ucp_ep.c:669
 8 0x00000000000120c8 ucp_ep_destroy_internal()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucp/core/ucp_ep.c:654
 9 0x000000000001fe19 ucp_worker_destroy_eps()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucp/core/ucp_worker.c:1551
10 0x000000000001fe19 ucp_worker_destroy()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucp/core/ucp_worker.c:1560
11 0x00000000004046a9 main._omp_fn.0()  ghex_p2p_bi_cb_avail_mt.cpp:0
12 0x000000000001687e gomp_thread_start()  /cluster/work/users/vegarde/build/GCCcore/8.3.0/system-system/gcc-8.3.0/stage3_obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/team.c:120
13 0x0000000000007dd5 start_thread()  pthread_create.c:0
14 0x00000000000fe02d __clone()  ???:0
```
This is a multi-threaded benchmark, in which two ranks with `nthr` threads both send and receive messages to/from each other. Each thread keeps `inflight` messages posted at a time. Each rank  submits in total roughly `nmesg` send and recv requests, and when the ranks notice that they have sent and received at least `nmesg`, they exit the loop. Then, they flush the worker, synchronize on a simple barrier, and finalize.

What probably triggers the above bug message is the fact that I do not cancel any pending requests - neither send, nor receive. So there might be uncompleted messages posted at the time when I destroy the worker. 

I report the above because the message says `Bug`. But I also wonder, am I obliged to post equal number of matching send and recv requests and complete (or cancel) all before I finalize UCX?

Thanks!

**Comment by yosefe** [comment]
@angainor all outstanding requests must be completed before destroying the worker

**Comment by angainor** [comment]
@yosefe Thanks! This might be difficult in some situations in practice. Is there some way to cancel all posted requests? The problem is that when using the callback interface I currently don't keep track of the returned requests, and only free them in the callback itself. So when threads submit a bunch of requests, I currently have no means to cancel them before I quit.

**Comment by yosefe** [comment]
@angainor currently there is no such option, because it will add more overhead for cases where a user does not have leftover requests. I think it makes sense that the application would track the requests in such case, similar to the requirement to free() all pointers that one would malloc()..

**Comment by angainor** [comment]
@yosefe OK, thanks for the clarification. Could you also clarify how the `ucp_worker_flush_nb` works exactly? If two peers each submit a different number both matching, and non-matching send_tag and recv_tag requests, what will be the outcome of a flush? I suspect I do not full understand what it does.. 

btw, I see now that I get the above 'bug' message when running within one compute node. I do not see it when using two compute nodes linked with IB.

**Comment by yosefe** [comment]
@angainor the effect of ucp_worker_flush_nb() on send/recv requests is undefined. It only guarantees both local and remote completion of RMA and AMO operations.

**Comment by angainor** [comment]
ah! that explains a lot! thanks!
