### ISSUE TITLE
disable connection between different roce versions

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#4512]
UCX/ib selects gid index automatically with highest roce version
in some case peers can use different roce version on diff. devices so they can't send packets to each other
for example on hpc-test-node2 between mlx4_0:2 and mlx5_0 (which mlx5_0:2 has IP address)

https://gist.githubusercontent.com/mellanox-github/8bf930b14e303e4176e1e758f3799e81/raw/a7e4faea3dc7a8ad6754b67a42389d1fa520ee11/hpc-test-node-legacy_W1
https://gist.githubusercontent.com/mellanox-github/8bf930b14e303e4176e1e758f3799e81/raw/186ead1a057ca6a8d5b1663f927708a6e3020d97/hpc-test-node-legacy_W0

**Comment by shamisp** [comment]
another good reason to introduce wire protocol.

**Comment by alinask** [comment]
Fixed in https://github.com/openucx/ucx/pull/4688
