### ISSUE TITLE
Error in perftest

### ISSUE THREAD

**Issue by afernandezody** [openucx/ucx#4518]
Hello,
I'm getting errors in perftest during UCXv1.6.1 installation. The only new element is that CUDA is v10.2 (10.2.89.444.33.01). Could this be causing the issue or is it something else? The OS is ALinux, gdrcopy is v1.3, and compilation/build is pretty standard (`./configure --prefix=/usr/local/ucx-cuda-install --with-cuda=/usr/local/cuda-10.2  --with-gdrcopy=/home/ec2-user/gdrcopy; sudo make -j 4 install`).
Thanks.
P.S. Also tried 1.6.0
![error_perftest](https://user-images.githubusercontent.com/44442767/69759895-22045380-1131-11ea-9bb7-4d5c3bb824af.png)

**Comment by afernandezody** [comment]
It seems that the problem is caused by Alinux2 as switching back to CentOS seems to be the error.

**Comment by yosefe** [comment]
looks like openmp is not supported by the compiler

**Comment by afernandezody** [comment]
Hi @yosefe,
Thanks. Sometimes it's hard to figure out the twists of ALinux; they have gcc 7.1.2 but why did they leave openmp out? Anyway, I'm closing this ticket (as it's not a UCX problem) and will open one in the ALinux forum.
P.S. I didn't label the thread as "bug," at least not intentionally.
