### ISSUE TITLE
AZP CI fails when running on direct pushes

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#4538]
### Describe the bug
AZP CI is triggered by both PRs and direct pushes to the master and release branches. A "Codestyle commit title" check expects `System.PullRequest.TargetBranch` to be set while it is not.

### Steps to Reproduce
Trigger AZP CI in a branch manually or push commits directly so it will be triggered automatically. Example: https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=2930.

**Comment by yosefe** [comment]
@amaslenn  there should not be direct pushes to master and release branches.. did you see that happen?

**Comment by amaslenn** [comment]
No, I haven't seen any direct pushed. But once commit is merged it triggers `push` event and AZP runs on this merged commit.
