### ISSUE TITLE
Problem of "offset" in ucp_do_am_bcopy_multi

### ISSUE THREAD

**Issue by apachexm** [openucx/ucx#4600]
When UCX_RNDV_THRESH=inf, ucp_do_am_bcopy_multi() will be used to transfer long tag message. In ucp_do_am_bcopy_multi() function, req->send.state.dt.offset will be updated after a successful pack_first() or pack_middle() callback.

But in some UCT am_bcopy implementations, such as uct_tcp_ep_am_bcopy() or uct_ugni_smsg_ep_am_bcopy(), am_bcopy may failed with NO_RESOURCE return code after pack_cb() because data transfer cannot start when the device is busy. Thus in such condition, when returning to ucp_do_am_bcopy_multi(), the req may be added to pending queue or retried, but the req->send.state.dt.offset has been set to a wrong value.

one line code below will solve the problem, I think.  (in file proto_am.inl)

if (ucs_unlikely(packed_len < 0)) {
    req->send.state.dt.offset = offset;
    /* original code block */
}

**Comment by bureddy** [comment]
known issue https://github.com/openucx/ucx/issues/2077
