### ISSUE TITLE
Question/Request for comments: Flaw in MT support?

### ISSUE THREAD

**Issue by artpol84** [openucx/ucx#4609]
### Problem description

Consider the following example,

```C
typedef struct { ... } req_internal_t;
// This is the request size passed to ucp_init()
typedef struct {
    req_internal_t x
} my_ucx_req_t; 

void cbfunc(void *request, ucs_status_t status)
{
    my_ucx_req_t *req = (my_ucx_req_t *)request;
    internal_complete(&req->x);
}

void my_ucx_put(...)
{
    my_ucx_req_t *req = ucp_put_nb( ..., cbfunc);
    ...
    // if req is not UCS_OK and not an error
    internal_init(req->x);
}
```

In the single threaded case, the order of operations is always correct:

| Thread1  |
| ------------- |
| `req = ucp_put_nb(...,cbfunc)`  | 
| `internal_init(&req->x)` |
| `ucp_worker_progress()` -> `cbfunc()` | 

However, in a multi-threaded case, it is possible for `ucp_worker_progress()` to be called on another thread:

| Thread1  | Thread2 |
| ------------- | ------------- |
| `req = ucp_put_nb(...,cbfunc)`  |  |
|  | `ucp_worker_progress()` -> `cbfunc()`  |
| `internal_init(&req->x)` | | 

As a workaround, an external locking can be used to ensure request initialization atomicity:

| Thread1  | Thread2 |
| ------------- | ------------- |
| `lock(my_mutex)`  |  |
| `req = ucp_put_nb(...,cbfunc)`  |  |
| `internal_init(&req->x)` | | 
| `unlock(my_mutex)`  |  |
|| `lock(my_mutex)`  |
|  | `ucp_worker_progress()` -> `cbfunc()`  |
| | `unlock(my_mutex)`  |

But that defeats the purpose of internal UCX locking.

### Possible solutions

I can think of 3 ways to ensure the atomicity of the request initialization.

1. Introducing an mt-versions of all operations that may return request that have additional `init_cb` and `init_data` arguments
```C
ucs_status_ptr_t ucp_put_nb_mt(ucp_ep_h ep, const void *buffer, size_t length,
                            uint64_t remote_addr, ucp_rkey_h rkey,
                            ucp_send_callback_t cb,
                            ucp_req_init_callback_t init_cb, void *init_data)
```
2. Same as (1), but pass `init_cb` to `ucp_init()` thus only need to provide the initialization blob to the operation:
```C
ucs_status_ptr_t ucp_put_nb_mt(ucp_ep_h ep, const void *buffer, size_t length,
                            uint64_t remote_addr, ucp_rkey_h rkey,
                            ucp_send_callback_t cb,
                            void *init_data)
```
3. Introduce `ucp_req_initialized()` function to defer the completion callback invocation until user is ready to handle it. To maintain backward compatibility, the old/new mode should be selected at UCP init or at worker creation time.
```C
void my_ucx_put(...)
{
    my_ucx_req_t *req = ucp_put_nb( ..., cbfunc);
    ...
    // if req is not UCS_OK and not an error
    internal_init(req->x);
    ucp_req_initialized(req);
}
```
In this case if ucx will complete the request before `internal_init()` it would need to defer the completion report and call it as part of `ucp_req_initialized()`.

| Thread1  | Thread2 |
| ------------- | ------------- |
| `req = ucp_put_nb(...,cbfunc)`  |  |
|  | `ucp_worker_progress()` -> `mark_req_complete()`  |
| `internal_init(&req->x)` | | 
| `ucp_req_initialized(req)` -> `cbfunc()` | | 

### P.S.

Real example: OMPI/pml/ucx, the `mca_pml_ucx_start` function [[link](https://github.com/open-mpi/ompi/blob/master/ompi/mca/pml/ucx/pml_ucx.c#L1019:L1059)].
The sequential/expected order of operations is as follows:
1. The request is returned by UCX in [[line 1020](https://github.com/open-mpi/ompi/blob/master/ompi/mca/pml/ucx/pml_ucx.c#L1020)] or [[line 1030](https://github.com/open-mpi/ompi/blob/master/ompi/mca/pml/ucx/pml_ucx.c#L1030)].
2. The initialization is completed in [[line 1056](https://github.com/open-mpi/ompi/blob/master/ompi/mca/pml/ucx/pml_ucx.c#L1056)] by setting `req_complete_cb_data` field to `preq` (I assume, persistent request pointer).
3. The `req_complete_cb_data` field is later used in the [[completion callback ](https://github.com/open-mpi/ompi/blob/master/ompi/mca/pml/ucx/pml_ucx_request.c#L99)].

If the UCP progress will happen on another thread between steps (1) and (2) it is possible, that the callback (3) will be invoked as part of that progress and will have uninitialized `req_complete_cb_data`.

**Comment by artpol84** [comment]
@yosefe, @karasevb, @jladd-mlnx FYI

**Comment by yosefe** [comment]
#4187

**Comment by angainor** [comment]
@artpol84 FYI, for now we ended up locking all calls to UCX and initializing the library with `UCS_THREAD_MODE_SERIALIZED`. 

btw., @yosefe is there a significant difference between this and `UCS_THREAD_MODE_SINGLE`? If we anyway have to lock calls to UCX, is it OK if I compile without multithreading and use external locks?

**Comment by artpol84** [comment]
> OK if I compile without multithreading and use external locks?

Yes, we use it that way in multiple codes.

**Comment by yosefe** [comment]
> btw., @yosefe is there a significant difference between this and `UCS_THREAD_MODE_SINGLE`? If we anyway have to lock calls to UCX, is it OK if I compile without multithreading and use external locks?

UCS_THREAD_MODE_SINGLE and UCS_THREAD_MODE_SERIALIZED is mostly the same, except UCS_THREAD_MODE_SERIAZIED also forces BlueFlame flush. And for your use case, this is also the right thing to do.
