### ISSUE TITLE
Failure to Compile Sockaddr - Undefined Reference Symbol Error With ICC/ICPC IPO

### ISSUE THREAD

**Issue by EmmaJaneBonestell** [openucx/ucx#4624]
### Describe the bug
Enabling IPO/interprocedural optimization/link time optimization with ICC/ICPC results in an unresolved/undefined reference symbol error for sockaddr. Using "-flto" in gcc does not produce this error. Appears to be related to libstdc++. 
```
make[2]: Entering directory '/opt/ucx/ucxbuild/build/test/apps'
Making all in sockaddr
make[3]: Entering directory '/opt/ucx/ucxbuild/build/test/apps/sockaddr'
  CXX      sa-sa_base.o
  CXX      sa-sa_main.o
  CXX      sa-sa_tcp.o
  CXX      sa-sa_util.o
  CXXLD    sa
ipo: error #11021: unresolved _ZNSt14_Function_base12_M_max_alignE
        Referenced in /tmp/ipo_icpcYJnRpy.o
ipo: error #11021: unresolved _ZNSt14_Function_base11_M_max_sizeE
        Referenced in /tmp/ipo_icpcYJnRpy.o
icpc: error #10014: problem during multi-file optimization compilation (code 1)
make[3]: *** [Makefile:508: sa] Error 1
make[3]: Leaving directory '/opt/ucx/ucxbuild/build/test/apps/sockaddr'
make[2]: *** [Makefile:750: all-recursive] Error 1
make[2]: Leaving directory '/opt/ucx/ucxbuild/build/test/apps'
make[1]: *** [Makefile:734: all-recursive] Error 1
make[1]: Leaving directory '/opt/ucx/ucxbuild/build'
make: *** [Makefile:600: all] Error 2
```

### Steps to Reproduce
- Command line: 
```
./configure CC=icc CXX=icpc LD=xild AR=xiar CFLAGS="-ipo"
make
```
- UCX version used: Tested on git master, 1.6.1, and 1.7.0-rc1 
- UCX configure flags: `./configure CC=icc CXX=icpc LD=xild AR=xiar CFLAGS="-ipo"` 
I am using more flags than this, but this is enough to get the error. 

### Setup and versions
- OS version: Ubuntu 19.10
- CPU architecture: x86_64
- ICC Version: 19.1.0.166 20191121

### Additional information

- Configure result - config.log (attached)
[config.log](https://github.com/openucx/ucx/files/4004122/config.log)
- Make result - builducx.txt
[builducx.txt](https://github.com/openucx/ucx/files/4004136/builducx.txt)
 (attached)

**Comment by hoopoepg** [comment]
hi @EmmaJaneBonestell 

thank you for bug report

did you try to use older ICC? could it be regression in ICC?
we will try to reproduce it in our environment

**Comment by EmmaJaneBonestell** [comment]
While I did try it with different c standard libraries, I haven't tried an older ICC version -- I will check the previous version within the next day or two and let you know if it's a problem with ICC, in which case, I will submit a bug report to them.

**Comment by EmmaJaneBonestell** [comment]
@hoopoepg 

After testing, it does appear to be a regression in the 2020 version.

I tested the final releases of the 2019 and 2018 editions, and it compiled just fine with the "-ipo" flag set. I noticed the compiled sa file did not even contain the std::_Function_base::_M_max* symbols according to nm. 

Of course removing the "-g" flags from the sockaddr makefiles results in a successful compilation on the 2020 edition, but I'm not sure how this would affect ucx or if it would even be functional still.

Not sure how much you can do for this problem, so I will report it to Intel (not that they have the best reputation for fixing bugs).

**Comment by hoopoepg** [comment]
@EmmaJaneBonestell thank you for the update
we will look at this issue too after our environment is ready (it takes time)

thank you again

**Comment by hoopoepg** [comment]
we reproduced this issue even without UCX building (using simple reproducer). It seems this is issue in ICC 2020. Closing issue for now

**Comment by EmmaJaneBonestell** [comment]
Intel doesn't admit the regression (for no particular reason); Not necessarily ideal, but for anyone else that comes across this, it can be made to compile by adding -Wl,-E to the makefile for sockaddr, without having to remove -g, -Werror, etc. (Though an ipo_out.optrpt will still show it did not perform whole-program optimizations as previous versions of the Intel compiler will say they did).

**Comment by EmmaJaneBonestell** [comment]
While probably not suitable for adding to ucx, for anyone who comes across this:

I've finally found that including the following from the std_function.h resolves the issue when using icpc with any #include <functional> call, and allows for full IPO to take place vs. ignoring the symbol. **In addition to including the following, you must compile the object using the "-ansi" flag, and the flag _must_ appear after a -std=gnu++foo flag.** 

#include <functional>
class _Undefined_class;
union _Nocopy_types
  {
    void*       _M_object;
    const void* _M_const_object;
    void (*_M_function_pointer)();
    void (_Undefined_class::*_M_member_pointer)();
  };
#ifdef _M_max_size
#undef _M_max_size
#endif
#ifdef _M_max_align
#undef _M_max_align
#endif
static const std::size_t _M_max_size = sizeof(_Nocopy_types);
static const std::size_t _M_max_align = __alignof__(_Nocopy_types);
