### ISSUE TITLE
osu build issue

### ISSUE THREAD

**Issue by kayog96** [openucx/ucx#4689]
I am getting this error while building OSU microbenchmark for ROCm: WARNING: unrecognized options: --enable-rocm, --with-rocm.

I am running this command for building OSU:
./configure --enable-rocm --with-rocm=/opt/rocm CC=$OMPI_DIR/usr/bin/mpic++ CXX=$OMPI_DIR/usr/bin/mpicxx LDFLAGS="-L$OMPI_DIR/lib/ -lmpi -L/opt/rocm/lib/ -lhip_hcc" CPPFLAGS="-std=c++11" 

Also, i am having doubt that without doing any changes specific to ROCm in configure.ac file, you are just building a default version of OSU.

If not, can you please tell me what are the changes you have done to make OSU specific for ROCm.

Thanks.

**Comment by dmitrygx** [comment]
@kayog96 thanks for reporting the issue
but are you sure that the issue should be reported to OpenUCX community? Should it be reported to OSU instead?
