### ISSUE TITLE
when compile from source,can't find "numa.h"  though i have set head file path by "LDFLAGS.."

### ISSUE THREAD

**Issue by jsboer** [openucx/ucx#4774]
### Describe the bug

```
checking for numa.h... no
configure: error: NUMA headers not found. Please reconfigure with --disable-numa.  Warning: this may have negative impact on library performance. It is better to install libnuma-devel package
```

"### Steps to Reproduce
1.cd ucx
  ./autogen.sh
 mkdir build
 cd build
2. set some env:
```
export C_INCLUDE_PATH=-I/home/jrf/tools/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/
export CPLUS_INCLUDE_PATH=-I/home/jrf/tools/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/
export OBJC_INCLUDE_PATH=-I/home/jrf/tools/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/
export LDFLAGS=-I/home/jrf/tools/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/
 ../configure --prefix=/home/jrf/tools/ucx
```
and then
```
../configure --prefix=/home/jrf/tools/ucx
```
what should i do ?

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
Linux mu01 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.5.1804 (Core)

**Comment by jsboer** [comment]
I’m sorry,i should check the "./configure -h"carefully,it tell me everything
```
 CC          C compiler command
  CFLAGS      C compiler flags
  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
  LIBS        libraries to pass to the linker, e.g. -l<library>
  CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
              you have headers in a nonstandard directory <include dir>
  CPP         C preprocessor
  CXX         C++ compiler command
  CXXFLAGS    C++ compiler flags
  CCAS        assembler compiler command (defaults to CC)
  CCASFLAGS   assembler compiler flags (defaults to CFLAGS)
  LT_SYS_LIBRARY_PATH
              User-defined run-time library search path.
  CXXCPP      C++ preprocessor
  DOXYGEN_PAPER_SIZE
              a4wide (default), a4, letter, legal or executive
  MPICC       MPI C compiler command
  MPIRUN      MPI launch command
```

**Comment by tonycurtis** [comment]
> On Feb 14, 2020, at 4:59 AM, jsboer <notifications@github.com> wrote:
> 
> Describe the bug
> 
> checking for numa.h... no
> configure: error: NUMA headers not found. Please reconfigure with --disable-numa.  Warning: this may have negative impact on library performance. It is better to install libnuma-devel package
> "### Steps to Reproduce
> 1.cd ucx
> ./autogen.sh
> mkdir build
> cd build
> 2. set some env:
> 
> export C_INCLUDE_PATH=-I/home/jrf/tools/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/
> export CPLUS_INCLUDE_PATH=-I/home/jrf/tools/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/
> export OBJC_INCLUDE_PATH=-I/home/jrf/tools/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/
> export LDFLAGS=-I/home/jrf/tools/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/
>  ../configure --prefix=/home/jrf/tools/ucx

numactl=$HOME/opt/numactl/2.0.13

CFLAGS="-I$numactl/include"
LDFLAGS="-L$numactl/lib -Wl,-rpath,$numactl/lib"
export CFLAGS LDFLAGS

Worked for me

Tony

**Comment by jsboer** [comment]
@tonycurtis tthank you very much!
