### ISSUE TITLE
Can ucx packaged in rpm format?

### ISSUE THREAD

**Issue by lytofd** [openucx/ucx#4827]
As title said, so we can install ucx by command such as rpm -i xxx.
Can ucx support this way?

**Comment by yosefe** [comment]
Yes, the contrib/buildrpm.sh script can produce UCX rpm, you can also download SRC RPM of latest release: https://github.com/openucx/ucx/releases/download/v1.7.0/ucx-1.7.0-1.fc30.src.rpm

**Comment by lytofd** [comment]
> Yes, the contrib/buildrpm.sh script can produce UCX rpm, you can also download SRC RPM of latest release: https://github.com/openucx/ucx/releases/download/v1.7.0/ucx-1.7.0-1.fc30.src.rpm

thanks

**Comment by shamisp** [comment]
@lytofd I guess we can close this for now. Feel free to re-open if it does not work for you.
