### ISSUE TITLE
"Warning: UCX is unable to handle VM_UNMAP event" with UCX 1.7.0 and Open MPI 4.0.3

### ISSUE THREAD

**Issue by mkre** [openucx/ucx#4866]
### Describe the bug
We started seeing the error message
```
common_ucx.c:149  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
```
as we are Open MPI 4.0.3 with UCX 1.7.0. We are hesitating to apply the proposed workaround (`--mca opal_common_ucx_opal_mem_hooks 1`) as we are not sure about possible negative consequences and would rather understand the root cause of the issue. Note that we have MOFED 4.6 installed, but we are explicitly using an UCX 1.7.0 distribution via `$LD_LIBRARY_PATH`. 

Note that we seem to be getting the same message when using Open MPI 4.0.2 built against HCOLL, but _not_ when using Open MPI 4.0.2 built _without_ HCOLL. Maybe this helps to track down the issue.

### Steps to Reproduce
- Command line: `mpirun -np 2 ./a.out`
- UCX version used: UCX 1.7.0
- UCX configure flags:
```
--prefix=/usr/local/hudson/workspace/ucx-linux-glibc2.17/build/1.7.0/install --disable-optimizations --enable-logging --disable-debug --disable-assertions --disable-params-check --with-verbs=/home/test/.gradle/caches/cda/tpls/mofed-4.0-linux-x86_64/usr --with-rdmacm=/home/test/.gradle/caches/cda/tpls/mofed-4.0-linux-x86_64/usr --with-knem=/home/test/.gradle/caches/cda/tpls/mofed-4.0-linux-x86_64/opt/knem-1.1.2.90mlnx2 --without-java --with-rc --with-ud --with-dc --with-cm --with-mlx5-dv --with-dm
```
- Any UCX environment variables used: `UCX_TLS=self,sm,ud`

### Setup and versions
- OS version: CentOS 7.6
- CPU architecture: x86_64
- MLNX_OFED version: 4.6

### Additional information (depending on the issue)
- OpenMPI version: 4.0.3
- Open MPI configure flags: 
```
'--prefix=/usr/local/jenkins/workspace/openmpi-linux/build/4.0.3/install' '--with-usnic' '--enable-mpi-fortran=none' '--disable-oshmem' '--with-package-string=Simcenter STAR-CCM+ Open MPI distribution' '--disable-show-load-errors-by-default' '--with-psm=/home/test/.gradle/caches/cda/tpls/mofed-2.1-linux-x86_64/usr' '--with-psm2=/home/test/.gradle/caches/cda/tpls/intel_opa-10.2-linux-x86_64' '--with-psm2-libdir=/home/test/.gradle/caches/cda/tpls/intel_opa-10.2-linux-x86_64/lib64' '--with-ucx=/home/test/.gradle/caches/cda/tpls/ucx-1.7.0-mofed-1.5-linux-x86_64-Release-libc2_12-gnu7_1_0' '--with-mxm=/home/test/.gradle/caches/cda/tpls/mofed-2.1-linux-x86_64/opt/mellanox/mxm/' '--with-knem=/home/test/.gradle/caches/cda/tpls/mofed-2.1-linux-x86_64/opt/knem-1.1.90mlnx2' '--with-ofi=/home/test/.gradle/caches/cda/tpls/libfabric-1.8.0-linux-x86_64-Release-libc2_12-gnu7_1_0' '--with-verbs=/home/test/.gradle/caches/cda/tpls/mofed-2.1-linux-x86_64/usr' '--enable-ipv6' '--with-tm=/home/test/.gradle/caches/cda/tpls/torque-4.2.10-linux-x86_64' '--with-singularity=/home/test/.gradle/caches/cda/tpls/singularity-2.6.1-linux-x86_64' '--with-slurm' '--with-sge' '--with-lsf=/home/test/.gradle/caches/cda/tpls/lsf-10.1-linux-x86_64' '--with-lustre=/home/test/.gradle/caches/cda/tpls/lustre-2.8-linux-x86_64' '--with-pvfs2=/home/test/.gradle/caches/cda/tpls/orangefs-2.8.4-linux-x86_64' '--with-hcoll=/usr/local/jenkins/workspace/openmpi-linux/hcoll-4.4'
```
- Output of `ucx_info -d`: [ucx_info-d.txt](https://github.com/openucx/ucx/files/4318784/ucx_info-d.txt)
- Configure result - config.log: [config.log](https://github.com/openucx/ucx/files/4318782/config.log)
- Log file - configure UCX with "--enable-logging" - and run with "UCX_LOG_LEVEL=data": [log.txt.gz](https://github.com/openucx/ucx/files/4318791/log.txt.gz)

**Comment by yosefe** [comment]
@mkre can you pls try running
`mpirun -np 2 -mca btl self ./a.out`

**Comment by mkre** [comment]
@yosefe, same issue when running with `-mca btl self`. The warning do not appear when running with `-mca btl ^uct`. But I'm not sure if disabling BTL/uct is a viable option.

**Comment by hoopoepg** [comment]
hi @mkre 
could you try to reproduce this issue using UCX master branch or v1.8.x branch?
we made some optimization since release 1.7 which may resolve issue

thank you

**Comment by mkre** [comment]
@hoopoepg I am still seeing the warning message when using UCX 1.8.0-rc1 at run time. However, we are still building Open MPI against UCX 1.7.0. Do I also need to build Open MPI against UCX 1.8.0-rc1 in order to see this resolved?

**Comment by hoopoepg** [comment]
@mkre 
yes, please...
BTW, how you replace UCX built with OMPI by UCX 1.8?

**Comment by mkre** [comment]
@hoopoepg, same issue when building Open MPI against UCX 1.8.0-rc1. We are building our own Open MPI distribution, so we can choose freely which versions of other libraries we are building against...

**Comment by hoopoepg** [comment]
@mkre thank you
does launch parameter ```--mca opal_common_ucx_opal_mem_hooks 1``` resolves issue?

**Comment by mkre** [comment]
Yes, it does. But does this setting have any negative effects on performance? We are a bit hesitant to override the default settings....

**Comment by hoopoepg** [comment]
it forces use some remory registration optimizations which improve performance.
by default PML UCX is trying to identify situation when such optimization is required using some heuristic algorithm, but it seems in your case it failed due to possible conflict with BTL UCT.

so, I see 2 options to resolve issue:
1. update your command line to add switch ```--mca opal_common_ucx_opal_mem_hooks 1``` or ```-mca btl ^uct```
2. updated your build script to add configure parameter ```--enable-mca-no-build=btl-uct``` - it excludes BTL UCT from build

**Comment by mkre** [comment]
What do I need BTL/uct for? We are using PML/ucx for InfiniBand systems, but our Open MPI distribution should also work well on all other kinds of systems (TCP, OmniPath, you name it). Can we safely disable BTL/uct without any negative effects?

**Comment by hoopoepg** [comment]
BTL UCT is alternative transport based on subset of UCX (UCT is one of modules in UCX), in case if you use PML UCX - it is not needed

**Comment by mkre** [comment]
Thanks, @hoopoepg. In that case we will just add `-mca btl ^uct` to the command line but keep building BTL/uct into our Open MPI distribution. That way, we can still enable it explicitly on the command line if that ever becomes necessary.

**Comment by yosefe** [comment]
@mkre can we close the issue?

**Comment by mkre** [comment]
@yosefe, yes, I'll close it. Thanks for your help everyone! 

The exact reasons and coherencies (I have investigated with different configurations a bit more on my side) are still a bit obscure to me, but disabling BTL/uct seems to be a reasonable workaround, and something which doesn't look like it hurts anyway...

**Comment by mkre** [comment]
I need to reopen this issue, as it is still haunting me... As proposed previously, I now have an Open MPI distribution built without BTL/uct (`--enable-mca-no-build=btl-uct`). This avoids the warning, **as long as we do not specify any BTL-related MCA parameters**. For example, we want to disable BTL/openib in some instances, which brings back the warning messages despite non-existing BTL/uct. So, it seems like the message is not only related to BTL/uct.

* Open MPI 4.0.3
  * configured  with `--enable-mca-no-build=btl-uct`
  * built against UCX 1.6.0 (which itself is built against MOFED 1.5)
  * (same issue when using Open MPI 4.0.2)
* UCX 1.7.0 used at run time
  * built against MOFED 4.0 
  * (same issue when using UCX 1.7.0 built against MOFED 1.5)
  * (same issue when using UCX 1.8.0-rc1 built against MOFED 1.5/4.0)

| Command line | Result |
| --- | --- |
| `mpirun -np 2 ./a.out` | :heavy_check_mark: (no warning) |
| `mpirun -np 2 ./a.out -btl ^openib` | :x: `VM_UNMAP` warning |
| `mpirun -np 2 ./a.out -btl self` | :x: `VM_UNMAP` warning |

This is getting really strange, so any help is greatly appreciated.

**Comment by hoopoepg** [comment]
hi @mkre 
as I can see you build OMPI excluded btl-uct, right?

we can't reproduce your issue. so, could you provide build command lines for all modules you built, command line to run, and output for commands ```ompi_info -v``` and ```ucx_info -v``` used in your test. we will try to reproduce same environment

thank you

**Comment by mkre** [comment]
> as I can see you build OMPI excluded btl-uct, right?

Yes, that is correct. 

I just learned another thing: When requesting PML/ucx explicitly, the warning does not appear. So I can update my table posted above:

| Command line | Result |
| --- | --- |
| `mpirun -np 2 ./a.out` | :heavy_check_mark: (no warning) |
| `mpirun -np 2 ./a.out -btl ^openib` | :x: `VM_UNMAP` warning |
| `mpirun -np 2 ./a.out -btl self` | :x: `VM_UNMAP` warning |
| `mpirun -np 2 ./a.out -btl ^openib -mca pml ucx` | :heavy_check_mark: (no warning) |

Here are the build command lines for all modules we built:

- UCX 1.6.0 (this is what we are building Open MPI against in the step below)
  ```
  > ucx_info -v
  # UCT version=1.6.0 revision 24d3af9
  # configured with: --prefix=/usr/local/jenkins/workspace/ucx-linux/build/1.6.0/install --disable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --with-verbs=/home/test/.gradle/caches/cda/tpls/mofed-1.5-linux-x86_64/usr --with-rdmacm=/home/test/.gradle/caches/cda/tpls/mofed-1.5-linux-x86_64/usr --with-knem=/home/test/.gradle/caches/cda/tpls/mofed-1.5-linux-x86_64/opt/knem-0.9.7mlnx1 --without-java
  ```

- Open MPI 4.0.3 
  ```
  > ompi_info | grep "Configure command"
  Configure command line: '--prefix=/usr/local/jenkins/workspace/openmpi-linux/build/4.0.3/install' '--with-usnic' '--enable-mpi-fortran=none' '--disable-oshmem' '--with-package-string=Simcenter STAR-CCM+ Open MPI distribution' '--disable-show-load-errors-by-default' '--with-psm=/home/test/.gradle/caches/cda/tpls/mofed-2.1-linux-x86_64/usr' '--with-psm2=/home/test/.gradle/caches/cda/tpls/intel_opa-10.2-linux-x86_64' '--with-psm2-libdir=/home/test/.gradle/caches/cda/tpls/intel_opa-10.2-linux-x86_64/lib64' '--with-ucx=/home/test/.gradle/caches/cda/tpls/ucx-1.6.0-mofed-1.5-linux-x86_64-Release-libc2_12-gnu7_1_0' '--with-mxm=/home/test/.gradle/caches/cda/tpls/mofed-2.1-linux-x86_64/opt/mellanox/mxm/' '--with-knem=/home/test/.gradle/caches/cda/tpls/mofed-2.1-linux-x86_64/opt/knem-1.1.90mlnx2' '--with-ofi=/home/test/.gradle/caches/cda/tpls/libfabric-1.9.0-linux-x86_64-Release-libc2_12-gnu7_1_0' '--with-verbs=/home/test/.gradle/caches/cda/tpls/mofed-2.1-linux-x86_64/usr' '--enable-ipv6' '--with-tm=/home/test/.gradle/caches/cda/tpls/torque-4.2.10-linux-x86_64' '--with-singularity=/home/test/.gradle/caches/cda/tpls/singularity-2.6.1-linux-x86_64' '--with-slurm' '--with-sge' '--with-lsf=/home/test/.gradle/caches/cda/tpls/lsf-10.1-linux-x86_64' '--with-lustre=/home/test/.gradle/caches/cda/tpls/lustre-2.8-linux-x86_64' '--with-pvfs2=/home/test/.gradle/caches/cda/tpls/orangefs-2.8.4-linux-x86_64' '--enable-mca-no-build=btl-uct'
  ```
  ```
  > ompi_info -V
  Open MPI v4.0.3
  ```
- UCX 1.8.0-rc1 (this is what we are using for Open MPI at run time)
  ```
  > ucx_info -v
  # UCT version=1.8.0 revision d087d56
  # configured with: --prefix=/usr/local/jenkins/workspace/ucx-linux/build/1.8.0-rc1/install --disable-optimizations --enable-logging --disable-debug --disable-assertions --disable-params-check --with-verbs=/home/test/.gradle/caches/cda/tpls/mofed-4.0-linux-x86_64/usr --with-rdmacm=/home/test/.gradle/caches/cda/tpls/mofed-4.0-linux-x86_64/usr --with-knem=/home/test/.gradle/caches/cda/tpls/mofed-4.0-linux-x86_64/opt/knem-1.1.2.90mlnx2 --without-java --with-rc --with-ud --with-dc --with-cm --with-mlx5-dv --with-dm --enable-cma
  ```
  - The same issue appears when using UCX 1.6.0 as it comes with MOFED 4.6 instead of a self-compiled UCX 1.7.0.
  - This might show that it is a problem which is appearing at **build time**, but I wanted to make sure that it persists with 1.8.0-rc1 as well.

To reproduce the issue, we can use a very simple program which does some sort of MPI communication, e.g., the attached MPI_Bcast mini application: [mpi_bcast.c.txt](https://github.com/openucx/ucx/files/4386363/mpi_bcast.c.txt). We need to run it over two nodes with the additional flags as posted in the table above.

Let me know if you need anything else.

Thanks,
Moritz

**Comment by yosefe** [comment]
@mkre in addition, can you pls run one of the cases which shows VM_UNMAP warning with `-mca btl_base_verbose 999` and attach the output?

**Comment by mkre** [comment]
@yosefe, here you go: [btl_verbose.txt](https://github.com/openucx/ucx/files/4386563/btl_verbose.txt) (obtained with `-mca btl_base_verbose 999 -mca btl ^openib`)

**Comment by yosefe** [comment]
@mkre can you pls try `-mca btl_base_verbose 999 -mca btl ^openib,vader` ?

**Comment by mkre** [comment]
Looks pretty similar: [btl_verbose2.txt](https://github.com/openucx/ucx/files/4386615/btl_verbose2.txt)

**Comment by yosefe** [comment]
@mkre can you pls try `-mca btl_base_verbose 999 -mca btl ^openib,vader -mca pml ^mxm`

**Comment by mkre** [comment]
@yosefe, I suppose you meant `-mca pml ^yalla`. That seems to do the trick 👍 : 
[btl_verbose3.txt](https://github.com/openucx/ucx/files/4386852/btl_verbose3.txt)

We include Yalla/MXM support in our Open MPI distribution mainly for debugging/compatibility reasons. But of course we are using UCX by default on all Mellanox IB systems. Seems like our path forward will be to disable Yalla by default, and only let a user request it explicitly. 

By the way, it also works if we are only requesting PML/yalla.

| Command line | Result |
| --- | --- |
| `mpirun -np 2 ./a.out` | :heavy_check_mark: (no warning) |
| `mpirun -np 2 ./a.out -btl ^openib` | :x: `VM_UNMAP` warning |
| `mpirun -np 2 ./a.out -btl self` | :x: `VM_UNMAP` warning |
| `mpirun -np 2 ./a.out -btl ^openib -mca pml ucx` | :heavy_check_mark: (no warning) |
| `mpirun -np 2 ./a.out -btl ^openib -mca pml ^yalla` | :heavy_check_mark: (no warning) |
| `mpirun -np 2 ./a.out -btl ^openib -mca pml yalla` | :heavy_check_mark: (no warning) |

There seems to be some sort of conflict between PML/ucx and PML/yalla, but _only if we specify some BTL MCA parameter_.

**Comment by yosefe** [comment]
@mkre i could not reproduce the same issue with btl params on may machine..
can you pls attach the output for 
```
mpirun -np 2 -mca btl self -mca btl_base_verbose 99 -mca rcache_base_verbose 99 -mca pml_base_verbose 99 ./a.out
```

**Comment by mkre** [comment]
@yosefe, here you go: 
[out_1.txt](https://github.com/openucx/ucx/files/4401109/out_1.txt)

**Comment by yosefe** [comment]
@mkre i see that "yalla" is opened which is probably causing the warning..
can you pls upload same log for :
`mpirun -np 2 -mca btl_base_verbose 99 -mca rcache_base_verbose 99 -mca pml_base_verbose 99 ./a.out` - to see why if btl is not specified, yalla is not opened

**Comment by mkre** [comment]
@yosefe: [out_2.txt](https://github.com/openucx/ucx/files/4402298/out_2.txt)

**Comment by yosefe** [comment]
@mkre i've finally been able to reproduce the problem, by changing the order of mca_pml_yalla.so and mca_osc_ucx.so files in lib/ompi directory, to have the same component load order as you have.

So, pml_yalla triggers the problem when it's unloaded during MPI_Init (because it's unselected). It causes patcher component to be closed (by closing opal_memory_base_framework), which "restores" malloc hooks to their original state, which also reverts UCX's memory hooks.
When no "btl" parameter is specified, openib component is also loaded. It creates a registration cache which adds another "reference" to patcher component from rcache component. This prevents patcher from being unloaded and restoring the memory hooks.

The recommendation stays the same : disable yalla component by default.

**Comment by mkre** [comment]
Awesome, thanks for being so persistent, @yosefe! 

One last question: How can I change the load order of these libraries? I'd like to test this locally, because this warning message started appearing at some seemingly random point with our Open MPI distribution, without changing anything obvious to it. I have two versions of `lib/openmpi` directories here with exactly the same contents (same md5sum of all files), and only with one of them, we get the warning.

**Comment by yosefe** [comment]
@mkre the load order is according to the order of SO files in lib/ompi directory (as you would see with unsorted file list - `ls -U`). I changed the order by creating a new directory, copying lib/ompi/*.* files to it in the order i wanted to "force", and eventually replacing the lib/ompi directory itself by the new one.

**Comment by mkre** [comment]
That's something I totally wasn't ware of, thanks a lot for the explanation! Learning never stops :-).

**Comment by yosefe** [comment]
@mkre np, can we close this issue then?

**Comment by mkre** [comment]
Sure, thanks again!

**Comment by Andre235** [comment]
> @mkre thank you does launch parameter `--mca opal_common_ucx_opal_mem_hooks 1` resolves issue?

Where is this parameter added?

**Comment by mkre** [comment]
@Andre235 to the `mpirun` command line.

**Comment by Andre235** [comment]
> by changing the order of mca_pml_yalla.so and mca_osc_ucx.so files in lib/ompi directory,
 
Hi, I also encountered the same problem in this issue. When I tried to change the order of so files, I found that there is no mca_pml_yalla.so file in lib/ompi directory, only mca_osc_ucx.so file. And other directories also don't have mca_pml_yalla.so file

**Comment by Andre235** [comment]
Hi, I also encountered the same problem in this issue. When I tried to change the order of so files, I found that there is no `mca_pml_yalla.so ` file in `lib/ompi` directory, only `mca_osc_ucx.so` file. And other directories also don't have `mca_pml_yalla.so` file.

```shell
# ucx_info -v
# UCT version=1.12.1 revision dc92435
# configured with: --disable-assertions --disable-params-check --enable-mt --without-go --without-java --prefix=/home/lucas/daos/install/prereq/release/ucx --libdir=/home/lucas/daos/install/prereq/release/ucx/lib64 --enable-cma --without-cuda --without-gdrcopy --with-verbs --without-knem --without-rocm --enable-mca-no-build=btl-uct --without-xpmem --without-fuse3 --without-ugni --disable-debug --disable-logging
```

```shell
# ompi_info -V
Open MPI v3.1.0
http://www.open-mpi.org/community/help/
```
