### ISSUE TITLE
UCP: stream_send fails to correctly send messages of certain sizes using IB

### ISSUE THREAD

**Issue by HndrkMkt** [openucx/ucx#4876]
### Describe the bug
When sending messages of 57 or more bytes via IB, ucp_stream_send_nb fails to do so correctly with 
`stream_send.c:195  Assertion 'req->send.length > length' failed.`

### Steps to Reproduce

This issue can be reproduced using the [ucp_client_server.c](https://github.com/openucx/ucx/blob/master/test/examples/ucp_client_server.c) example.

- Replace [test_message](https://github.com/openucx/ucx/blob/master/test/examples/ucp_client_server.c#L46) by a string of >56 bytes (`"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234"`).

### Setup and versions
- Ubuntu 16.04.6 LTS 
- Linux cloud-43 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- MLNX_OFED_LINUX-4.6-1.0.1.1

- UCT version=1.7.0 revision 9d06c3a
    - configured with: --enable-gtest --enable-examples --with-valgrind --enable-profiling --enable-frame-pointer --enable-stats --enable-memtrack --enable-fault-injection --enable-debug-data --enable-mt --prefix=/home.../ucx/install-debug --enable-logging

**Comment by HndrkMkt** [comment]
After spending some time debugging this, it seems to be race condition within the code.

**Comment by evgeny-leksikov** [comment]
> After spending some time debugging this, it seems to be race condition within the code.

kind of but not exactly, if client-server connection is not established, EP is not completely configured then first pending request is configured incorrectly. this causes protocol mismatch when EP is configured and tries to send pending request.

**Comment by HndrkMkt** [comment]
What's the best way to solve this? Is there a way to make sure the client-server connection is established before sending the first request or should I first send a small intro message to ensure the configuration for any following requests?

**Comment by evgeny-leksikov** [comment]
> should I first send a small intro message to ensure the configuration for any following requests?

this should work as workaround, also need to recv small message from the peer to make sure the client-server connection is established since small message send will be buffered and completed immediately. bidirectional message exchange will guarantee that connection establishment is finished.

**Comment by HndrkMkt** [comment]
@evgeny-leksikov Thanks a lot, this does the trick for me. Would it make sense to integrate the EP configuration/waiting for its success into the general connection establishment instead of relying on a workaround? If provided some guidance, I could try to create a PR for this.

**Comment by evgeny-leksikov** [comment]
@HndrkMkt  we can't do it the same way inside UCP because UCP API should stay non-blocking.
the easiest way to fix it is to create such dummy EP configuration as its thresholds would be compliant with all available transports for the simplest available protocol like am-bcopy-single.

the wrong configuration is created here https://github.com/openucx/ucx/blob/f97ae3b1978d42abccd207919e6228d9e76a6004/src/ucp/core/ucp_ep.c#L310
but probably this is not the only place.

**Comment by yosefe** [comment]
fixed by #4955
