### ISSUE TITLE
Configure does not check for presence of g++

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#4884]
### Describe the bug
Configure supposed to check if g++ is available. Seems like the check does not work.
```
make[3]: Entering directory '/ucx/build/src/tools/perf/lib'
  CC       libucxperf_la-libperf.lo
  CXX      libucxperf_la-uct_tests.lo
  CXX      libucxperf_la-ucp_tests.lo
../../../../libtool: line 1762: g++: command not found
../../../../libtool: line 1762: g++: command not found
```

### Steps to Reproduce
- install os with gcc but no g++
- ../contrib/configure-devel && make
- master

### Setup and versions
- Ubuntu 19.04 with no g++ installed

**Comment by shamisp** [comment]
Ouch, autoconf is busted ! 
http://gnu-autoconf.7623.n7.nabble.com/AC-PROG-CXX-should-have-a-way-to-not-fall-back-to-g-td21034.html

**Comment by yosefe** [comment]
@shamisp can we close this? do we need it in v1.8?

**Comment by shamisp** [comment]
fixed
