### ISSUE TITLE
Compile error on ThunderX2

### ISSUE THREAD

**Issue by tonycurtis** [openucx/ucx#4886]
### Describe the bug

Compile error on ThunderX2

### Steps to Reproduce

github master @ 62751a4bea975668d56e4ced0fb39743d07b6210

`make`

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
   - CentOS 7.5

### Additional information (depending on the issue)

```
  CC       event/libucm_la-event.lo
  CC       malloc/libucm_la-malloc_hook.lo
  CC       mmap/libucm_la-install.lo
  CC       util/libucm_la-replace.lo
In file included from /users/arcurtis/src/ucx/build/../ucx-git/src/ucs/arch/cpu.h:93:0,
                 from ../../../ucx-git/src/ucm/event/event.c:16:
/users/arcurtis/src/ucx/build/../ucx-git/src/ucs/arch/aarch64/cpu.h: In function 'ucs_memcpy_relaxed':
/users/arcurtis/src/ucx/build/../ucx-git/src/ucs/arch/aarch64/cpu.h:204:5: error: nested extern declaration of '__memcpy_thunderx2' [-Werror=nested-externs]
     extern void *__memcpy_thunderx2(void *, const void *, size_t);
     ^
/users/arcurtis/src/ucx/build/../ucx-git/src/ucs/arch/aarch64/cpu.h: In function 'ucs_memcpy_nontemporal':
/users/arcurtis/src/ucx/build/../ucx-git/src/ucs/arch/aarch64/cpu.h:215:5: error: nested extern declaration of '__memcpy_thunderx2' [-Werror=nested-externs]
     extern void *__memcpy_thunderx2(void *, const void *, size_t);
     ^
cc1: all warnings being treated as errors
```

**Comment by yosefe** [comment]
@hoopoepg can you pls take a look

**Comment by shamisp** [comment]
@yosefe any idea why we didn't catch this in CI ?

**Comment by yosefe** [comment]
@shamisp currently we don't have ThunderX 2 in CI..

**Comment by shamisp** [comment]
@yosefe ouch, my understanding that you used to have. Do you have any other Arm in CI ?

**Comment by yosefe** [comment]
yes, we have TX1 and Huawei 1616 ARM today

**Comment by shamisp** [comment]
This is good but my guess that most of Arm + UCX deployments out there are TX2 based. So we shell figure out how to cover this gap.

**Comment by shamisp** [comment]
@tonycurtis do you have some TX2 that you can hookup to Azp CI. They have headless client for Arm. I have not tried it yet but this is the way to go if we want expand CI.

**Comment by tonycurtis** [comment]
> On Mar 15, 2020, at 2:20 PM, Pavel Shamis (Pasha) <notifications@github.com> wrote:
> 
> 
> @tonycurtis <https://github.com/tonycurtis> do you have some TX2 that you can hookup to Azp CI. They have headless client for Arm. I have not tried it yet but this is the way to go if we want expand CI.
> 

I’m using machines at LANL and ORNL at present.  I don’t expect to have any thunder nodes I can direct the use of.

Tony

**Comment by shamisp** [comment]
@tonycurtis got it. thanks
