### ISSUE TITLE
UCX_TLS=rc 

### ISSUE THREAD

**Issue by JuliaRS** [openucx/ucx#4941]
In your documentation mentioned that when i set UCX_TLS=rc it means thst will select rc and ud.
How exactly rc or ud is chosen? 
Based on what is this or that transport selected?

**Comment by yosefe** [comment]
ud is used for bootstrap and rc is used for real data communication

**Comment by JuliaRS** [comment]
Ok, what happens if i set UCX_TLS=rc,ud?
Do you have priority in list of transport?

**Comment by yosefe** [comment]
in this case, rc would be selected for small scale, and ud for large scale
in both cases ucx provides a reliable layer: for ud, there is internal reliability mechanism, parallel to TCP

**Comment by JuliaRS** [comment]
@yosefe, thanks a lot.
