### ISSUE TITLE
make sure whether ucx use cuda_ipc and shared memory to communicate inter-node or not.

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [openucx/ucx#5022]
My project want to use shared memory and cuda ipc technology to the limit of NIC that don't support communicate of processes inter-node. And what I first recall is ucx, so I use `ucx_perftest` to have a simple test. The `ucx_perftest` can run well, but I can't make sure whether ucx use cuda ipc or shared memory to communicate, so I paste the cmdline and log output, see below.
client cmd:
```
CUDA_VISIBLE_DEVICES=1 UCX_NET_DEVICES=eth0 UCX_NET_DEVICES=rdma2 UCX_TLS=sm,cuda_copy,cuda_ipc ./ucx_perftest 172.16.0.166  -m cuda -t tag_bw
```
server cmd:
```
CUDA_VISIBLE_DEVICES=0 UCX_NET_DEVICES=eth0 UCX_NET_DEVICE=rdma2 UCX_TLS=sm,cuda_copy,cuda_ipc ./ucx_perftest -m cuda -t tag_bw
```
client and server run at the same GPU server.
log of client see:
https://paste.ubuntu.com/p/524k66zZpt/
log of server see:
https://paste.ubuntu.com/p/Ycd4dPsx7S/

Can you help me to make sure it?

**Comment by dmitrygx** [comment]
As far I can see from your logs, CUDA_IPC is used for TAG/RNDV protocol:
```
[1586754829.145642] [usnic1:96374:0]         wireup.c:880  UCX  DEBUG ep 0x7f08592ab048: lane[0]:  0:posix/memory md[0] <proxy>  -> addr[0].md[0]/posix    am am_bw#0
[1586754829.145653] [usnic1:96374:0]         wireup.c:880  UCX  DEBUG ep 0x7f08592ab048: lane[1]:  5:cma/memory md[5]            -> addr[4].md[5]/cma      rma_bw#1
[1586754829.145662] [usnic1:96374:0]         wireup.c:880  UCX  DEBUG ep 0x7f08592ab048: lane[2]:  4:cuda_ipc/cuda md[4]         -> addr[3].md[4]/cuda_ipc rma_bw#0
```
You could check when RNDV protocol will be used by running:
```
$ UCX_TLS=sm,cuda_copy,cuda_ipc ucx_info -e -u t -D shm
```
where `-e` shows EP configuration, `-u t`  means requesting `UCP_FEATURE_TAG` feature, `-D shm` emulates intranode communication.
for more information, pls, check
```
$ ucx_info -h
```
Also, you could try to play with `UCX_RNDV_THRESH` environment variable to find the best RNDV limit. But, pls, note this will affect IB and other TLs.

**Comment by dmitrygx** [comment]
Also, you could try different message sizes with `ucx_perftest`:
```
ucx_perftest 127.0.0.1 -m cuda -t tag_bw -m <msg_size>
```

**Comment by Keepmoving-ZXY** [comment]
ok, I will have a try, and does tag_bw support host memory?

**Comment by dmitrygx** [comment]
> does tag_bw support host memory?

sure, you could set the required memory type for send/recv buffers:
```
-m <send mem type>[,<recv mem type>]
```
e.g. `-m host:host` or `-m host:cuda` or `-m cuda-managed:host` or etc

**Comment by Keepmoving-ZXY** [comment]
ok, I already have a try, all seems good.

**Comment by Keepmoving-ZXY** [comment]
@dmitrygx Can you provide me a example of ucp stream api?

**Comment by dmitrygx** [comment]
> @dmitrygx Can you provide me a example of ucp stream api?

@evgeny-leksikov if I'm not mistaken we don't have a small example for UCP Stram API, right?
@Keepmoving-ZXY you can try to check UCX perftest code - e.g. https://github.com/openucx/ucx/blob/d07461e54dfaaa9c40823cfae08511847a2656af/src/tools/perf/lib/ucp_tests.cc#L180
there we have UCP stream implementation for perftest

**Comment by Keepmoving-ZXY** [comment]
ok，thank you.

**Comment by evgeny-leksikov** [comment]
https://github.com/openucx/ucx/blob/d07461e54dfaaa9c40823cfae08511847a2656af/test/examples/ucp_client_server.c#L276
