### ISSUE TITLE
Endpoint failures are treated as fatal by mlx5

### ISSUE THREAD

**Issue by pentschev** [openucx/ucx#5027]
### Describe the bug
Endpoint failures are treated as fatal by mlx5, even if `UCX_FAILURE` (or inherited variables) are set to a different level.

### Steps to Reproduce
- UCX version 1.8
- Environment variables: `CUDA_VISIBLE_DEVICES=0 UCX_NET_DEVICES=mlx5_0:1 UCX_FAILURE=WARN UCX_TLS=rc,tcp,sockcm,cuda_copy UCX_SOCKADDR_TLS_PRIORITY=sockcm`
- Run `ucx_perftest -m cuda -t tag_bw -n 100 -s 100000000` server and client, as client starts printing iteration status, `kill -9` the server

### Probable source
The fatal log level is hardcoded in https://github.com/openucx/ucx/blob/6786e7e8e1ef5aba35c06b63727f9cd800fb9628/src/uct/ib/rc/accel/rc_mlx5_iface.c#L210, and https://github.com/openucx/ucx/blob/6786e7e8e1ef5aba35c06b63727f9cd800fb9628/src/uct/ib/rc/accel/rc_mlx5_iface.c#L228-L230 is supposed to use the level set by `UCX_RC_MLX5_FAILURE` but it seems not to happen. I'm not sure whether this is indeed a bug or endpoint errors are meant to be handled in a different manner.

### Reason
In UCX-Py we need to be more resilient to failures. Today, if a UCX process crashes for whatever reason and a different process is transferring data over mlx5, that process will also raise a fatal error. In a cluster like Dask this can create a chain-effect, as workers can start crashing as sends start to timeout, for example.

We are also open to alternative suggestions on how to handle this, but it seems that we will need at least to avoid UCX from raising a fatal error upon timeout.

**Comment by yosefe** [comment]
@pentschev need to create UCP endpoint with ERR handling mode PEER and install an error callback
https://github.com/openucx/ucx/blob/master/src/ucp/api/ucp_def.h#L585
pls reopen if this does not help

**Comment by pentschev** [comment]
Thanks for the clarification @yosefe . I'll try that and reopen if it doesn't work.

**Comment by pentschev** [comment]
@yosefe this seems to work for `ucp_ep_create`, I'm having some trouble in figuring how to do the same for endpoints created via `ucp_listener_create`. It seems that one alternative is to modify parameters with `ucp_ep_modify_nb`, but it seems for that I would have to pass modify the `ucp_conn_request_h->sa_data->err_mode` in the listener callback function. However, both `ucp_conn_request_t` and `ucp_wireup_sockaddr_data_t` are not exposed by the API, which means I can't dereference them within the callback function in UCX-Py. I can't seem to find any helper functions to deal with that either, but I may totally have missed something. Would you mind pointing me to the correct way of doing that?

**Comment by yosefe** [comment]
https://github.com/openucx/ucx/blob/master/test/examples/ucp_client_server.c#L567

**Comment by pentschev** [comment]
Just wanted to thank you @yosefe for the help here, I finally got it all working!
