### ISSUE TITLE
use JUCX in HDFS but NativeLibs have problem

### ISSUE THREAD

**Issue by JinBoZi** [openucx/ucx#5087]
### Describe the bug
Caused by: java.lang.NullPointerException
	at org.openucx.jucx.NativeLibs.extractUCTLibs(NativeLibs.java:85)
	at org.openucx.jucx.NativeLibs.<clinit>(NativeLibs.java:30)

NativeLibs.java:85 is 
URI uri = NativeLibs.class.getClassLoader().getResource("ucx").toURI();

### Steps to Reproduce
use JUCX(1.8.0) in HDFS

### Setup and versions
- Ubuntu 16.04.5 LTS + x86_64

### Additional information (depending on the issue)
- openjdk version "1.8.0_222"

**Comment by petro-rudenko** [comment]
Hi, need to add path to ucx install to classpath. How do you run jucx with hdfs?

**Comment by JinBoZi** [comment]
Thanks your reply

I just add jucx-1.8.0.jar to pom file and use maven make hdfs.
then add jucx-1.8.0.jar to ${HADOOP_HOME}/share/hadoop/hdfs/lib
but I find there is no "uxc" folder in jucx-1.8.0

change "hadoop-2.9.0-src/hadoop-hdfs-project/hadoop-hdfs/pom.xml" like this.
<dependency>
        <groupId>jucx</groupId>
        <artifactId>jucx</artifactId>
        <version>1.8.0</version>
        <scope>system</scope>
        <systemPath>${project.basedir}/src/main/lib/jucx-1.8.0.jar</systemPath>
</dependency>

![image](https://user-images.githubusercontent.com/35587765/80331248-1e106500-887a-11ea-8b6c-fbe690bd831c.png)

**Comment by petro-rudenko** [comment]
Hi, in jucx we include only libjucx.so (JNI wrapper). You have to install and build UCX on every node in the cluster. Then you need to add path to `UCX_INSTALL/lib` to the classpath for your java application. 
We're working on to load UCX from `LD_LIBRARY_PATH` not from classpath.

Do you plan to accelerate HDFS with UCX?

**Comment by JinBoZi** [comment]
Thanks for your help! HDFS cant't load the CLASSPATH of system,so I add it to `$HADOOP_HOME/libexec/hadoop-config.sh`

Now,I can use it. But I found it's too slower than 1.7.0, I don't know the reason.Maybe is my code have some problem. 

We plan to accelerate HDFS with JUCX(RDMA),datanode read data from client by RDMA.

**Comment by JinBoZi** [comment]
The problem is in my code. 1.8.0 is same as 1.7.0 in my code.I will continue debugging and optimization.

**Comment by petro-rudenko** [comment]
#5105 will allow to load ucx from `-Djava.library.path` or `LD_LIBRARY_PATH`
