### ISSUE TITLE
Does tag match operation support the same tag value but used in different endpoint?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [openucx/ucx#5175]
![ucx_tag_match](https://user-images.githubusercontent.com/19542656/82118264-9ba80080-97a8-11ea-9fa1-4bcc5b06e419.png)

In my project, there is a special case that a process create two ucp endpoints to another two different process which are in the same server, and must use ucx tag match operation  with the same tag value  to finish communicate,  and the picture above show the special case.
In the picture, process 1 in Server 2 create two ucp endpoint with process 1 in Server 1 and process 2 in Server 1.  And sometimes process 1 in Server 2 will start tag match operation with different ucp endpoint to communicate with two different process in Server 2, and at the same time the tag match operation to different process in Server 1 may use the same tag value. So my question is that can ucx distinguish which tag match operation should deliver to which process in my very special case? and tag value is for a ucx endpoint or for a RDMA NIC?  thank you.

**Comment by Keepmoving-ZXY** [comment]
I am very excited that github's issue support picture.

**Comment by shamisp** [comment]
The tag_receive operation is posted on a worker and not endpoint. So it is associated with a "nic", but it is a bit more complicated, since we also handle multi-nic, etc: https://github.com/openucx/ucx/blob/master/src/ucp/api/ucp.h#L2818

As for detection of sender, you can allocate certain bit on the tag, to identify the sender of the message. It is very similar to what MPI is doing here: 
https://github.com/open-mpi/ompi/blob/b61bf9a00afae110d4aedbf2fc91c0170e3cc781/ompi/mca/pml/ucx/pml_ucx_request.h#L27

**Comment by Keepmoving-ZXY** [comment]
so the tag recv operation with tag value 0x11 do not distinguish the matched messages should be delivered to which process even if there are multiple messages with tag value 0x11, and when a application issue tag recv operation with tag value 0x11, all messages can match even when some of them should be delivered to another application in theory.

**Comment by mike-dubman** [comment]
@Keepmoving-ZXY - the effect that you are after can be achieved with help of Active Messaging API which is WIP. Also, we plan to introduce feature which will enable definition of tag scope (per client or global). btw, what integration are you working with UCX? @yosefe

**Comment by Keepmoving-ZXY** [comment]
ok, I will have a try

**Comment by yosefe** [comment]
@Keepmoving-ZXY when tag receive operation is posted, it will match with the oldest incoming message with same tag. The message can be matched with any of the connections (either process1 or process2, in the drawing). In will not be just "any" application - only applications which connected previously by "ucp_ep_create()". 
In order to distinguish between process1 and process2, can add process number to the tag, for example `tag = 0x11 | (process_id << 32)`

**Comment by Keepmoving-ZXY** [comment]
In my picture, job id of process 1 in Server 1 is 2, and job id of process 2 in Server 1 is 4, and job id of process 1 in Server 1 is 0, so I decide add job id of sender and job id of receiver to tag value to help distinguish which tag belong to which process. I am writing a demo as picture shows, thank you for help.

**Comment by yosefe** [comment]
@Keepmoving-ZXY probably, receive job id is not needed: the tag will always be received on the worker to which ucp_ep_h is connected to.
See more example code in : https://github.com/openucx/ucx/blob/master/test/apps/iodemo/ucx_wrapper.cc#L501

**Comment by Keepmoving-ZXY** [comment]
ok, I will skip receive job id.

**Comment by Keepmoving-ZXY** [comment]
Does ucx support multithreading tag match on a single  ucp_worker and each thread use different tag value with a mask of all bit is 1 ?

**Comment by brminich** [comment]
yes, you will have to build UCX with multi-thread support and create UCP worker with multi-thread mode  enabled. You can use any tags then.

**Comment by Keepmoving-ZXY** [comment]
ok, thank you.

**Comment by Keepmoving-ZXY** [comment]
When a ucp worker is created,  I can get the ucp worker's address and length of the address, and I want to use ucp_put to directly write address content to peer, and this claim that peer must prepare a memory chunk. So the problem is that  peer don't know the length of address of this side's ucp_worker, so does the address of ucp_worker have the max length, such as 1k or 10k ?

**Comment by brminich** [comment]
For calling `ucp_put_nb` you need to have endpoint corresponding to the peer. To create that endpoint you need to exchange worker addresses using some out of band mechanism (e.g. TCP). Then create endpoint with `ucp_ep_create`

**Comment by Keepmoving-ZXY** [comment]
The peer's address comes from gRPC request, so the main problem is length of ucp address.

**Comment by shamisp** [comment]
You can query worker address: https://github.com/openucx/ucx/blob/master/src/ucp/api/ucp.h#L885

Here is an example how address is exchanged in Open MPI using their modes out of band service https://github.com/open-mpi/ompi/blob/b61bf9a00afae110d4aedbf2fc91c0170e3cc781/ompi/mca/pml/ucx/pml_ucx.c#L106

Here is similar example in UCX perf test:
https://github.com/openucx/ucx/blob/755be4911a9894995fefedc742bc2b79306861a8/src/tools/perf/lib/libperf.c#L1303

**Comment by Keepmoving-ZXY** [comment]
ok, thank you.
