### ISSUE TITLE
UCX  ERROR cuMemGetAddressRange_v2

### ISSUE THREAD

**Issue by angainor** [openucx/ucx#5181]
I am trying to use UCX 1.8 compiled with CUDA and multi-threading for GPU-GPU transfers over NVlink. This is a Power9 based system, in which pairs of GPUs are connected with 3 NVlink channels.

I have a custom application, which simply tests tagged send/recv between two ranks. I allocate the buffers on two different GPUs (each rank has it's own device) using `cudaMalloc` and submit them to UCX. When each rank has 1 thread, all works fine. When I use more than 1 thread per rank, I get the following error:

```
[1589810464.832794] [bluemaster01:106250:0] cuda_ipc_cache.c:218  UCX  ERROR dest:106251: failed to insert region:0x19dd6d20 [0x0..0x0] size:0 :Invalid parameter
[1589810464.832909] [bluemaster01:106250:1] cuda_ipc_cache.c:218  UCX  ERROR dest:106251: failed to insert region:0x7fff742fae30 [0x0..0x0] size:0 :Invalid parameter
[1589810464.831437] [bluemaster01:106251:0]    cuda_ipc_md.c:208  UCX  ERROR cuMemGetAddressRange_v2(&(key->d_bptr), &(key->b_len), (CUdeviceptr) addr) is failed. ret:named symbol not found
[1589810464.831725] [bluemaster01:106251:1]    cuda_ipc_md.c:208  UCX  ERROR cuMemGetAddressRange_v2(&(key->d_bptr), &(key->b_len), (CUdeviceptr) addr) is failed. ret:named symbol not found
```
I'm not sure what that could be. The application works well with CPU memory, with IB and shared memory transfers, but fails with GPU-GPU transfers. 

Do you have any ideas where I should look? 

Thanks!

**Comment by bureddy** [comment]
@angainor is it possible to share a repro?

**Comment by angainor** [comment]
@bureddy Yes, but it is technically a bit complicated to compile/debug. The application is written in C++, so the entire UCX layer is wrapped in (quite) a few classes. Example user code is [here](https://github.com/angainor/GHEX/blob/cuda/benchmarks/transport/ghex_p2p_bi_ft_wait_mt.cpp). The interesting part is the loop in lines 146-173, which submits the send/recv requests. The error pops up in the `wait()` function, which is essentially a loop of calls to `ucp_worker_progress`. I guess I could compile it for you, so that you can run it with some debug version of UCX, if that is useful?

**Comment by bureddy** [comment]
From error it looks like it it cuda context issue in the on of the calling thread. 
In a single thread case, there is an implicit association of the cuda context used for the cuda allocation with the calling thread.  In multi-thread case, both threads need to have valid cuda context before calling any cuda api if both threads calling into UCX.  is it possible to thread not have a valid context when calling into UCX?

**Comment by angainor** [comment]
@bureddy I ran `cudaSetDevice(rank);` before the parallel region. When I moved it into the parallel region, the error is gone :) Do you think this is the correct way to do this?

**Comment by bureddy** [comment]
yes. I'm assuming all threads in the process are using the same GPU based on the rank info. correct?
BTW, is rank is MPI rank or node-local rank? make sure rank is valid GPU index

**Comment by angainor** [comment]
@bureddy yea, that's a simple run with 2 ranks on the same node with 4 GPUs, so rank/gpu mapping is OK. Thanks for your help, I guess that's closed :)
