### ISSUE TITLE
[mtt] OSU hang with osc-ucx = off

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#5205]
Description:
```
hang with `osu_get_acc_latency` test and with `-mca osc ^ucx`
```

Configuration
```
Nodes: jazz x2 (ppn=28(x2), nodelist=jazz[01,16])
Module: hpcx-gcc (2020-05-26)
OFED: MLNX_OFED_LINUX-5.0-1.0.0.0
MPI: 4.0.4rc2
```
 
Cmd:
`/hpc/local/benchmarks/daily/next/2020-05-26/hpcx-gcc-redhat7.6/ompi/bin/mpirun -np 2 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt -x UCX_IB_PCI_RELAXED_ORDERING=off --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -mca osc '^ucx' -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc_x,self,sm -x UCX_DC_MLX5_TX_POLICY=dcs_quota -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 -x UCX_IB_NUM_PATHS=4 -x UCX_MAX_EAGER_LANES=4 -x UCX_MAX_RNDV_LANES=4 --map-by node /hpc/local/benchmarks/daily/next/2020-05-26/hpcx-gcc-redhat7.6/ompi/tests/osu-micro-benchmarks-5.6.2/osu_get_acc_latency`
 
Output:
```sh
Wed May 27 09:26:50 2020[1,0]<stdout>:# OSU MPI_Get_accumulate latency Test v5.6.2
Wed May 27 09:26:50 2020[1,0]<stdout>:# Window creation: MPI_Win_create
Wed May 27 09:26:50 2020[1,0]<stdout>:# Synchronization: MPI_Win_lock/unlock
Wed May 27 09:26:50 2020[1,0]<stdout>:# Size          Latency (us)
```

**Comment by yosefe** [comment]
`-mca osc '^ucx'` is not supported
