### ISSUE TITLE
Performance of multiple thread tag match with one ucp worker and multiple ucp workers.

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [openucx/ucx#5226]
These days I spend some work time to complete a communicate demo with ucx tag match feature, and there are three threads in my demo: ```one for tag match recv```, ```one for ucp worker address tag match recv```, and ```one for tag send```.  And my demo has two version: three threads use __the same ucp worker(single ucp worker version)__,  and three threads use __different ucp worker(multiple ucp worker version)__. 
I run a simple performance test, which record the time of finishing 1000 times transfer each of which send and recv 100 bytes. And I think the performance of __multiple ucp worker version__ should be better than __single ucp worker version__, because multiple ucp worker don't need any synchronize between threads (so ucx multiple thread support is disabled during compile), but opposite.
The chart shows performance result:
|  version | round 1 | round 2 | round 3|
|  ----  | ----  | ----  | ----  |
| single ucp worker | 0.006234 sec| 0.006700 sec| 0.006474 sec|
| multiple ucp worker |0.027773 sec|0.027160 sec|0.025305 sec|

I am very confused about this result,  can anyone provide the best practise of tag match feature or just explain the reason why performance result is opposite to my though ? My demo can be found [here](https://github.com/Keepmoving-ZXY/TagMatch_UCX/tree/multiple_ucp_worker), __single ucp worker version__ can be found in __master__ branch, and __multiple ucp worker version__ can be found in __multiple_ucp_worker__ branch.

**Comment by shamisp** [comment]
@Keepmoving-ZXY can you please share details about your setup ? Do you know if hardware offload was used for tag matching ?

**Comment by yosefe** [comment]
@Keepmoving-ZXY can you pls try more iterations, for example 1,000,000 ?

**Comment by Keepmoving-ZXY** [comment]
In my demo, there will be two process in two different workstation, and each process will run tag send or tag recv simulately (during my run, I only let one process run tag send and another process run tag recv).  Below is what my single ucp worker version demo do during run:
1.create a ucp worker, and all operation below use the this ucp worker;
2.create a thread to run tag match recv operation, code likes below:
```
start_tag_recv:
do {
   ucp_worker_progress(ucp_worker_);
   msg_tag = ucp_tag_probe_nb(ucp_worker_, context->tag_value,
                              context->tag_mask, 1, &info_tag);
} while (!exit_signal_ && msg_tag == NULL);

request = reinterpret_cast<tag_context_t *>(ucp_tag_msg_recv_nb(
        ucp_worker_, msg, info_tag.length, ucp_dt_make_contig(1), msg_tag, f));

if (UCS_PTR_IS_ERR(request)) {
   TAG_ERROR_LOG("%s", "unable to receive tag messages.");
   free(msg);
   continue;
 } else {
   assert(UCS_PTR_IS_PTR(request));
   WaitRequestFinish(request);

   request->completed = 0;
   ucp_request_release(request);
 }
 goto start_tag_recv;
```
3. in main thread, run tag send 1000 times, code like below:
```
while (n--) {
   int ret = worker->TagSendToPeer(*ip_numeric, port, msg, send_size);
   if (ret) {
     TAG_ERROR_LOG("%s", "send msg with tag match failed.");
     break;
   }
}
```
And my multiple ucp worker version act the same as single ucp worker version, but tag match recv thread and tag send thread use different ucp worker.

**Comment by Keepmoving-ZXY** [comment]
@shamisp  I don't know how to check my NIC is support hardware tag match, below is output of `ibdev2netdev -v`:
```
0000:60:00.0 mlx5_0 (MT4119 - MCX516A-CCAT) CX516A - ConnectX-5 QSFP28 fw 16.25.1020 port 1 (ACTIVE) ==> rdma2 (Up)
```
The datasheet of  `MCX516A-CCAT`' can be seen at [here](https://www.mellanox.com/related-docs/prod_adapter_cards/PB_ConnectX-5_EN_Card.pdf), and I find `MPI Tag Matching` in `Enhanced Features` in datasheet.

**Comment by Keepmoving-ZXY** [comment]
@yosefe  the chart shows performance result of 1,000,000 transfer each of which is 100 bytes:
|  version | round 1 | round 2 | round 3|
|  ----  | ----  | ----  | ----  |
| single ucp worker | 5.516429 sec| 5.566268 sec| 5.034538 sec|
| multiple ucp worker |0.882731 sec| 0.884603 sec|1.040820 sec|

**Comment by Keepmoving-ZXY** [comment]
multiple ucp worker version is so fast when run 1,000,000 transfer each of which is 100 bytes.
