### ISSUE TITLE
what does UCX_TCP_MAX_BCOPY means?

### ISSUE THREAD

**Issue by lytofd** [openucx/ucx#5374]
l have founded that this env affects  tranfer rate while specifing UCX_TLS=tcp , what does it means, how can l assign  appropriate value?
thks.

**Comment by yosefe** [comment]
adding @dmitrygx 
UCX_TCP_MAX_BCOPY controls the buffer size of TCP transfers
@lytofd can you pls share what settings for UCX_TCP_MAX_BCOPY gave best performance?

**Comment by shamisp** [comment]
BCOPY - Buffered copy.
