### ISSUE TITLE
`ucp_init` should not be defined in the header

### ISSUE THREAD

**Issue by vchuravy** [openucx/ucx#5404]
Header functions like are unfriendly to users who dynamically load `libucp.so`. The usual reason for a header function is speed and I don't think that applies for a function that is infrequently called like `ucp_init`.

https://github.com/openucx/ucx/blob/0e37370648f857e23d5775a0c5b3aa609044e43c/src/ucp/api/ucp.h#L1446-L1452

**Comment by Keno** [comment]
This kind of definition is a common trick to hardcode the API version into the calling binary to maintain ABI compatibility. I think if your client is not written in C, it's best to just call ucp_init_version with a hardcoded version directly.
