### ISSUE TITLE
[mtt] Hang mpi-small-tests/misc/comms test

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#5412]
Configuration
```
OMPI: 4.0.4rc3
MOFED: MLNX_OFED_LINUX-5.0-1.0.0.0
Module: hpcx-gcc (2020-07-12)
Test module: mtt-tests/hpcx-gcc
Nodes: jazz x3 (ppn=28(x3), nodelist=jazz[03-04,22])
```
 
MTT log:
`http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20200712_221140_187617_34590_jazz03.swx.labs.mlnx/html/test_stdout_bI3DZe.txt`
 
Cmd:
`/hpc/local/benchmarks/daily/next/2020-07-12/hpcx-gcc-redhat7.6/ompi/bin/mpirun -np 84 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt -x UCX_IB_PCI_RELAXED_ORDERING=off --bind-to core -x UCX_NET_DEVICES=mlx5_3:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=ud_x,self,sm -x UCX_UD_TIMEOUT=10m -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 -x UCX_IB_NUM_PATHS=4 -x UCX_MAX_EAGER_LANES=4 -x UCX_MAX_RNDV_LANES=4 --map-by node /hpc/local/benchmarks/daily/next/2020-07-12/mtt-tests-gcc/installs/eI8a/tests/mpi-small-tests/mtt-tests.git/mpi-small-tests/misc/comms`
 
Output:
```sh
 =============================================================Sun Jul 12 23:16:05 2020[1,0]<stdout>:making comm of size 35: 43 25 41 63 33 37 17 70 32 5 20 31 2 30 47 80 29 52 62 18 67 12 1 42 60 64 7 39 74 14 34 36 48 75 10
Sun Jul 12 23:16:06 2020[1,0]<stdout>:making comm of size 10: 60 58 35 81 7 38 27 50 34 59
Sun Jul 12 23:16:06 2020[1,0]<stdout>:making comm of size 47: 13 78 82 27 79 36 3 56 42 39 46 58 68 76 15 57 6 7 1 35 66 60 71 63 67 26 12 34 62 69 49 77 59 45 20 54 8 23 32 44 64 0 22 48 80 33 24

 > hang (wait more 3h, default timeout 90m)                                                      
```

**Comment by yosefe** [comment]
smaller repro on 3 nodes:
```
mpirun -np 7 -mca coll '^hcoll' -x UCX_NET_DEVICES=mlx5_3:1 -x UCX_TLS=rc_x,self,sm -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 -x UCX_IB_NUM_PATHS=2 -x UCX_MAX_EAGER_LANES=2 -x UCX_MAX_RNDV_LANES=4 --map-by node /hpc/local/benchmarks/daily/next/2020-07-12/mtt-tests-gcc/installs/eI8a/tests/mpi-small-tests/mtt-tests.git/mpi-small-tests/misc/comms
making comm of size 5: 3 1 4 5 0
making comm of size 2: 1 3
(hang)
```

**Comment by yosefe** [comment]
rdma-core is calling rand() during ibv_create_ah() and creating inconsistent rand state
https://github.com/linux-rdma/rdma-core/blob/master/providers/mlx5/verbs.c#L2885

**Comment by eric-haibin-lin** [comment]
@yosefe thanks for the comment. What does the env var `UCX_IB_NUM_PATHS ` do?

**Comment by yosefe** [comment]
> @yosefe thanks for the comment. What does the env var `UCX_IB_NUM_PATHS ` do?

This variable forces creating multiple connections between same pair of processes, which creates multiple (2) address handles by ibv_create_ah() , so the libmlx5 driver calls rand() from ibv_create_ah() to generate the value of udp.src_port.

**Comment by yosefe** [comment]
fixed in https://github.com/linux-rdma/rdma-core/pull/849
