### ISSUE TITLE
does ucx support wait for a request finish in a block way ?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [openucx/ucx#5441]
In the `ucp_hello_world.c`, I notices that there is a loop waiting for a request to finish, such as:
```
    request = ucp_tag_send_nb(client_ep, msg, msg_len,
                              ucp_dt_make_contig(1), tag,
                              send_handler);
    if (UCS_PTR_IS_ERR(request)) {
        fprintf(stderr, "unable to send UCX data message\n");
        ret = -1;
        goto err_free_mem_type_msg;
    } else if (UCS_PTR_IS_PTR(request)) {
        printf("UCX data message was scheduled for send\n");
        wait(ucp_worker, request);
        request->completed = 0;
        ucp_request_release(request);
    }
```
The function `wait` is a loop that check whether the request is finish or not in a unblock way, but in the case that cpu resource is not enough,  the loop maybe cause other thread has few opportunity to run, so is there any way to achieve wait the request to finish in a block way?

**Comment by yosefe** [comment]
@Keepmoving-ZXY Yes, it's possible, pls see https://github.com/openucx/ucx/blob/master/src/ucp/api/ucp.h#L1854

**Comment by Keepmoving-ZXY** [comment]
@yosefe  in the `ucp_hello_world.c`, the `ucp_worker_arm` is used at receive side, but you means that `ucp_worker_arm` can be used at send side, does this okay?

**Comment by yosefe** [comment]
yes, it can be used on both sides

**Comment by Keepmoving-ZXY** [comment]
ok, thank you,  I will have a try.

**Comment by Keepmoving-ZXY** [comment]
@yosefe  if compile ucx with cuda support, can ucx's tag match API achieve GPUDirectRDMA if I load nv_peer_memory module to kernel?

**Comment by yosefe** [comment]
> @yosefe if compile ucx with cuda support, can ucx's tag match API achieve GPUDirectRDMA if I load nv_peer_memory module to kernel?

yes

**Comment by Keepmoving-ZXY** [comment]
ok, thank you.
