### ISSUE TITLE
Cannot pass transport and device through the command line.

### ISSUE THREAD

**Issue by planetA** [openucx/ucx#5466]
### Describe the bug

Cannot pass transport and device through the command line. Although, passing the same variable through the flags works.

### Steps to Reproduce

I set the following variables on the both nodes

```
$ ucx_info -c | grep 'UCX_\(TLS\|NET_DEV\|LOG_LEVEL=\)'
UCX_LOG_LEVEL=INFO
UCX_NET_DEVICES=rxe0:1
UCX_TLS=rc
```

Then I launch ucx_perftest:

Node1

```
ucx_perftest -t am_bw -x rc  -d rxe0:1
```

Node2

```
ucx_perftest -t am_bw -x rc -d rxe0:1 172.16.1.3
```

If I remove -x and -d flags, I get the following error message (on the both nodes):

```
ucx_perftest -t am_bw 172.16.1.3
...
[1595520770.965036] [rank2:379  :0]        libperf.c:1244 UCX  ERROR Cannot use transport <none> on device <none>
[1595520770.965062] [rank2:379  :0]       perftest.c:1481 UCX  ERROR Failed to run test: No such device
```

Version info

```
ucx_info -v
# UCT version=1.6.1 revision 19a00c6
# configured with: --with-rc --with-ud=yes --with-dc=no --with-mlx5-dv=no --with-dm=no --with-ib-hw-tm=no --with-rdmacm=no --enable-cma=no
```

I guess this is not a bug, but rather a confusion regarding passing parameters. My actual need is to pass these parameters to OpenMPI through "-x" flag, which is also ignored.

**Comment by yosefe** [comment]
ucx_perftest uses env vars UCX_TLS/UCX_NET_DEVICES for "UCP" tests and command line args "-x rc  -d rxe0:1" for "UCT" tests
am_bw is a "UCT" test (pls see full list in ucx_perftest -h)

**Comment by planetA** [comment]
Thank you. That explains the discrepancy. I learned that openmpi actually was capturing the parameters.
