### ISSUE TITLE
UCX CQ failure report during initialization (Power)

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#551]
The following error reported during UCX initialization on power.

```
--------------------------------------------------------------------------
Failed to create a completion queue (CQ):

Hostname: XXXX
Requested CQE: 16384
Error:    Cannot allocate memory

Check the CQE attribute.
--------------------------------------------------------------------------
```

**Comment by yosefe** [comment]
This does not seem like UCX error message. Where is this coming from?

**Comment by shamisp** [comment]
I would guess - verbs driver ?

**Comment by yosefe** [comment]
no

**Comment by shamisp** [comment]
hmmm…

**Comment by shamisp** [comment]
Ok, this is a bug in OpenMPI. 
They set CQE size without query and as a result it may not work on a certain platforms:
https://github.com/open-mpi/ompi/blob/master/orte/mca/oob/ud/oob_ud_qp.c#L53

**Comment by shamisp** [comment]
I reported the issue to OMPI: 
https://github.com/open-mpi/ompi/issues/1301
