### ISSUE TITLE
RFC: use `PRIu64` instead of `%lld` format.

### ISSUE THREAD

**Issue by hiroyuki-sato** [openucx/ucx#5514]
Hello, developers.

1. What do you think to use `PRIx64` instead of `%llx`? (Use `PRIu64` in decimal) for `uint64_t` datatype?
2. The current code uses `%zu` format string for `uint64_t` datatype. What do you think to change `%lld` instead of `%zu`? As I describe above, It will use `PRIu64`.

If the idea is good, I'll create a PR.

## Use `PRIx64` instead of `%llx`
  
I'm porting OpenUCX to macOS. And I'm trying to fix the following error.

```
make: *** [tag/libucp_la-tag_recv.lo] Error 1
  CC       tag/libucp_la-tag_send.lo
tag/tag_send.c:49:44: error: format specifies type 'unsigned long' but the argument has type
      'ucp_datatype_t' (aka 'unsigned long long') [-Werror,-Wformat]
        ucs_error("Invalid data type %lx", req->send.datatype);
                                     ~~~   ^~~~~~~~~~~~~~~~~~
                                     %llx
```

There are many different definition between macOS and Linux.

I think it is portable solution to use `PRIx64` format.
`PRIxXX` syntax already used in some codes.

ie. `ucs/stats/client_server.c`

```C
339:    ucs_debug("From %s:%d - timestamp %"PRIu64", %zu..%zu / %zu",
401:        ucs_debug("timestamp %"PRIu64" fully assembled", entity->timestamp);
```

Ref: https://github.com/hiroyuki-sato/ucx/issues/30

## `%zu` to `%llx`

The following codes use `%zu` for `ucs_conn_sn_t` datatype.
But ucs_conn_sn_t datatype is `uint64_t`. As far as I know, `%zu` is the format string for `size_t`. not `uint64_t`
So, It 

src/ucs/datastruct/conn_match.h

```C
/**
 * Connection sequence number
 */
typedef uint64_t ucs_conn_sn_t;
```

src/ucs/datastruct/conn_match.c

```C
void ucs_conn_match_insert(ucs_conn_match_ctx_t *conn_match_ctx,
                           const void *address, ucs_conn_sn_t conn_sn,
                           ucs_conn_match_elem_t *conn_match,
                           ucs_conn_match_queue_type_t conn_queue_type)
{
    ucs_conn_match_peer_t *peer = ucs_conn_match_get_conn(conn_match_ctx,
                                                          address);
    ucs_hlist_head_t *head      = &peer->conn_q[conn_queue_type];
    char UCS_V_UNUSED address_str[UCS_CONN_MATCH_ADDRESS_STR_MAX];

    ucs_hlist_add_tail(head, &conn_match->list);
    ucs_trace("match_ctx %p: conn_match %p added as %s address %s conn_sn %zu",
              conn_match_ctx, conn_match,
              ucs_conn_match_queue_title[conn_queue_type],
              conn_match_ctx->ops.address_str(conn_match_ctx,
                                              address, address_str,
                                              UCS_CONN_MATCH_ADDRESS_STR_MAX),
              conn_sn);
}
```

Best regards.

**Comment by shamisp** [comment]
PRIx64 is C99 standard and this is what we should use.

**Comment by yosefe** [comment]
should use PRIu64 (not %lld) for uint64_t

**Comment by shamisp** [comment]
Indeed, the same stands for PRIu64.

**Comment by hiroyuki-sato** [comment]
Hello, @shamisp and @yosefe. Thank you for your comment. I'll create a PR later.
