### ISSUE TITLE
Compile: AOCC/clang-10 linker error

### ISSUE THREAD

**Issue by wyphan** [openucx/ucx#5545]
### Describe the bug
Compiling 1.8.1 release version fails on x86_64 using AMD AOCC (based on LLVM)

### Steps to Reproduce
- Command line
```shell
$ ./autogen.sh
$ ./contrib/configure-release-mt CC=clang CXX=clang++ \
    --disable-cma \
    --prefix=/opt/mpi/aocc-2.2.0/ucx-1.8.1 \
    --with-cuda=/usr/local/cuda-11.0 --with-gdrcopy=/usr
$ make -j 12 > build-aocc2.2.0+cuda11.0 2>&1
```
- UCX version used (from github branch XX or release YY) + UCX configure flags (can be checked by `ucx_info -v`)
Release 1.8.1
- **Any UCX environment variables used**
none

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
   - `cat /etc/issue` or `cat /etc/redhat-release` + `uname -a`
```
Ubuntu 20.04.1 LTS \n \l
Linux basecamp 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Compiler version
```shell
$ clang --version
AMD clang version 10.0.0 (CLANG: AOCC_2.2.0-Build#93 2020_06_25) (based on LLVM Mirror.Version.10.0.0)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/AMD/aocc-compiler-2.2.0/bin
```

- For GPU related issues:
  - GPU type
GeForce GTX 1060 6GB
  - Cuda:
```
$ dpkg -s cuda
Package: cuda
Status: install ok installed
Priority: optional
Section: multiverse/devel
Installed-Size: 7
Maintainer: cudatools <cudatools@nvidia.com>
Architecture: amd64
Version: 11.0.3-1
Depends: cuda-11-0 (>= 11.0.3)
Description: CUDA meta-package
 Meta-package containing all the available packages required for native CUDA
 development. Contains the toolkit, samples, driver and documentation.
```
  - Drivers version
```
$ dpkg -l nvidia-driver-*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version            Architecture Description
+++-====================-==================-============-=================================
ii  nvidia-driver-450    450.51.06-0ubuntu1 amd64        NVIDIA driver metapackage
un  nvidia-driver-binary <none>             <none>       (no description available)
```
  - Check if peer-direct is loaded: `lsmod|grep nv_peer_mem` and/or gdrcopy: `lsmod|grep gdrdrv`
```
$ lsmod|grep gdrdrv
gdrdrv                 20480  0
nvidia              19681280  172 nvidia_uvm,gdrdrv,nvidia_modeset
```

### Additional information (depending on the issue)
- Error message
```
make[3]: Entering directory '/home/wyp/compile/ucx-1.8.1/src/tools/perf'
  CC       ucx_perftest-perftest.o
  CCLD     ucx_perftest
ld.lld: error: unknown argument '-dynamic-list-data'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [Makefile:632: ucx_perftest] Error 1
```
edit: Fix typo

**Comment by shamisp** [comment]
This may help: https://github.com/openucx/ucx/issues/4549

**Comment by wyphan** [comment]
@shamisp I can confirm the "fix" proposed by @spikebike in #4549 works. The affected files are:
- `test/gtest/Makefile.in`
- `src/tools/perf/Makefile.in`

**Comment by shamisp** [comment]
So, it seems like some versions of clang do not support `-dynamic-list-data` ?

**Comment by shamisp** [comment]
The detection of linker is done by libtool.m4 which is part of libtool. I suspect something is off in the build environment since libtool gets confused.

**Comment by wyphan** [comment]
> So, it seems like some versions of clang do not support `-dynamic-list-data` ?

I can confirm that with the clang-10 version packaged in AOCC 2.2.0, and I believe @spikebike was using clang-9 from AOCC 2.1.0.

> The detection of linker is done by libtool.m4 which is part of libtool. I suspect something is off in the build environment since libtool gets confused.

I think the linker here is the LLVM `lld` linker. [Here](https://gist.github.com/wyphan/1c0bc850f8ca16fa817cfb5c1200156c) is the full `config.log` generated by `configure`.
I use [Lmod](https://lmod.readthedocs.io/en/latest/) to manage my environment variables, so I can simply `module load aocc` in the shell before compiling. [Here](https://gist.github.com/wyphan/8aaf0392e465043d06515e162c7ad223) is the contents of my `aocc` module file.

**Comment by wyphan** [comment]
Looks like if I force it to use `lld`, the build fails at linking `ucx_info` because `libtool` didn't generate shared libraries. For now, I added `--with-gnu-ld` to the configure line to force it to use GNU `ld`. Now the build completes, so probably AOCC's `lld` is at fault here.

**Comment by shamisp** [comment]
Thanks for an update. I will close this for now but if you have an update feel free to post here.

**Comment by lcebaman** [comment]
So, how can this be bypassed then? 
With AOCC3.1.0 and AOCC3.1.1 I get:

`CC=clang CXX=clang++ FC=flang  ./configure --prefix=$UCX_DIR --with-rocm=/opt/rocm-4.5.0 --without-knem --without-cuda --enable-gtest --enable-examples --enable-devel-headers --enable-optimizations`
