### ISSUE TITLE
UCX packages don't install in ubuntu 18.04

### ISSUE THREAD

**Issue by abellina** [openucx/ucx#5596]
```
The following packages have unmet dependencies:
 ucx : Depends: cuda-compat-10-1 but it is not installable
       Depends: ibverbs-providers (>= 22) but it is not going to be installed
       Depends: libibverbs1 (>= 28) but it is not going to be installed
       Depends: librdmacm1 (>= 23) but it is not going to be installed
```
While trying to install the 18.04 deb package we ran into issues where we needed `ibverbs-providers`, `libibverbs1`, `rdmacm1` and `cuda-compat-10-1`. We didn't have IB/RDMA hardware and the machine already had `cuda-10-1` installed. The ibverbs and rdmacm packages that are available for ubuntu 18.04 are too old, so we can't meet this dependency. Do they have to come from the `MLNX_OFED` installation?

Could there be a separate .deb and .rpm that doesn't have the IB/RDMA dependencies? Or could they somehow be optional (I am not an expert at packaging, but this would help reduce the number of .deb and .rpm files that need to be maintained)

One issue is that some environment (e.g. cloud) may not provide ssh access to machines, and so users may not be able to install `MLNX_OFED` for example. Also having them install `MLNX_OFED`, when they don't plan on using anything about it, seems like an unnecessary requirement.

Additionally, `cuda-compat-10-1` should not be required if we already have `cuda-10-1` installed. I believe that there is a way to specify alternatives, so this seems like a candidate for that. Again, not an expert, but an extra step that we hope can be avoided.

**Comment by yosefe** [comment]
currently there are separate packages with rpm but not with deb

**Comment by abellina** [comment]
As a workaround (in the interim) we discussed trying with force or ignore dependencies, I'll try this out and see if it works. Note this is an issue with _all_ ubuntu versions.

**Comment by abellina** [comment]
With `--force-depends` I was able to install the package. With this we ignore the package defined dependencies so it's just a hack while we get a package that has dependencies with alternates (for the cuda-compat case) and where the IB/RDMA components can be split off and be optional, or part of a different .deb that depends on MOFED.

**Comment by abellina** [comment]
@yosefe there is a major problem with `--force-depens`. After doing so, the package database appears to be in a corrupted state, so the user can't install any further packages in their machines: 

```
sudo apt install [my other package]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 ucx : Depends: cuda-compat-10-1 but it is not installable
       Depends: cuda-cudart-10-1 but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

So I don't think we want people to try `--force-depends`, it seems we should prioritize this issue as it "installs" but then they need to figure out how to fix the dependencies.

**Comment by mike-dubman** [comment]
maybe can remove this line: https://github.com/openucx/ucx/blob/master/debian/control.in#L17 meanwhile and regenerate package
since UCX uses dlopen anyway to resolve deps, we may not need explicit deps.

**Comment by abellina** [comment]
that would be better for sure in the interim @mike-dubman

**Comment by artemry-mlnx** [comment]
Fixed within https://github.com/openucx/ucx/pull/5776
Verified with UCX deb building on a host with MLNX_OFED and installing it (via `apt install -y`) on a host w and w/ MLNX_OFED.
