### ISSUE TITLE
UCX mailing list does not accept subscriptions

### ISSUE THREAD

**Issue by gnuoyd** [openucx/ucx#5723]
My colleague and I have sent at least a couple of subscription requests at https://elist.ornl.gov/mailman/listinfo/ucx-group . No answer.

**Comment by shamisp** [comment]
@gnuoyd I have seen few subscriptions coming through the last night. Can you please send me a note to pasharesearch@arm.com and I will check.

**Comment by shamisp** [comment]
@gnuoyd I would like to check if the mailing list problem was resolved ?

**Comment by gnuoyd** [comment]
On Tue, Sep 29, 2020 at 06:50:20AM -0700, Pavel Shamis (Pasha) wrote:
> @gnuoyd I would like to check if the mailing list problem was resolved ? 

It was!  Thank you.

Dave

-- 
David Young
dyoung@pobox.com    Urbana, IL    (217) 721-9981
