### ISSUE TITLE
Performance regression with UCX 1.9.0 and UD

### ISSUE THREAD

**Issue by mkre** [openucx/ucx#5740]
### Describe the bug
We are seeing performance regressions with UCX 1.9.0 and the UD transport. We are explicitly selecting UD because our testing has shown that it gives the best overall package in terms of performance and memory efficiency. We are not seeing similar regressions for RC and DC. 

The following table shows the average elapsed time for some test case run over two nodes (40 cores each) of our ConnectX-6 cluster. Similar regressions can be seen for other cases and core counts.

| | `UCX_TLS=ud,self,sm`  | `UCX_TLS=rc,self,sm` | `UCX_TLS=dc,self,sm` |
| ------- | ------------- | ------------- | ------- |
| UCX 1.8.0  | 0.7 s | 0.7 s | 0.7 s |
| UCX 1.9.0  | 1.3 s | 0.7 s | 0.7 s |

### Steps to Reproduce
- UCX 1.8.0 `ucx_info -v`:
```
# UCT version=1.8.0 revision c30b7da
# configured with: --prefix=/usr/local/hudson/workspace/ucx-linux-glibc2.17/build/1.8.0/install --disable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --disable-static --with-verbs=/home/test/.gradle/caches/cda/extLib/mofed-4.0-linux-x86_64/usr --with-rdmacm=/home/test/.gradle/caches/cda/extLib/mofed-4.0-linux-x86_64/usr --with-knem=/home/test/.gradle/caches/cda/extLib/mofed-4.0-linux-x86_64/opt/knem-1.1.2.90mlnx2 --without-java
```

- UCX 1.9.0 `ucx_info -v`:
```
# UCT version=1.9.0 revision cd9efd3
# configured with: --prefix=/usr/local/hudson/workspace/ucx-linux-glibc2.17/build/1.9.0/install --disable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --disable-static --with-verbs=/home/test/.gradle/caches/cda/extLib/mofed-4.0-linux-x86_64/usr --with-rdmacm=/home/test/.gradle/caches/cda/extLib/mofed-4.0-linux-x86_64/usr --with-knem=/home/test/.gradle/caches/cda/extLib/mofed-4.0-linux-x86_64/opt/knem-1.1.2.90mlnx2 --without-java
```

### Setup and versions
- CentOS 7.6
- 2x Intel Xeon Cascade Lake per node
- MLNX_OFED_LINUX-4.6-1.0.1.1
- `ibstat`:
```
CA 'mlx5_0'
        CA type: MT4123
        Number of ports: 1
        Firmware version: 20.25.6000
        Hardware version: 0
        Node GUID: 0xb8599f030000a310
        System image GUID: 0xb8599f030000a310
        Port 1:
                State: Active
                Physical state: LinkUp
                Rate: 100
                Base lid: 21
                LMC: 0
                SM lid: 2
                Capability mask: 0x2651e848
                Port GUID: 0xb8599f030000a310
                Link layer: InfiniBand
```

### Additional information
- OpenMPI version: 4.0.3
- UCX 1.8.0 `ucx_info -d`: [ucx_info_d_1.8.0.txt](https://github.com/openucx/ucx/files/5282365/ucx_info_d_1.8.0.txt)
- UCX 1.9.0 `ucx_info -d`: [ucx_info_d_1.9.0.txt](https://github.com/openucx/ucx/files/5282366/ucx_info_d_1.9.0.txt)
- UCX 1.9.0 log with `UCX_TLS=ud,self,sm UCX_LOG_LEVEL=data`: [ucx_log_data.txt.xz.gz](https://github.com/openucx/ucx/files/5282416/ucx_log_data.txt.xz.gz) (had to `xz` the log to get under 25 MB and then `gzip` the `xz` archive because Github wouldn't accept the `xz` file)

**Comment by mkre** [comment]
Hi @brminich,

Is there anything I can do to help investigating this issue?

**Comment by mkre** [comment]
I just tested with UCX master and the problem still persists. It seems like it has even gotten a bit worse. We won't be able to upgrade to UCX >1.8 while this regression is present, as the UD transport has the best memory efficiency of all and we cannot use RC or DC under all circumstances.


Extending my table from the first comment:

| | `UCX_TLS=ud,self,sm`  | `UCX_TLS=rc,self,sm` | `UCX_TLS=dc,self,sm` |
| ------- | ------------- | ------------- | ------- |
| UCX 1.8.0  | 0.7 s | 0.7 s | 0.7 s |
| UCX 1.9.0  | **1.3 s** | 0.7 s | 0.7 s |
| UCX master | **2.2 s** | 0.7 s | 0.7 s |

**Comment by brminich** [comment]
@yosefe

**Comment by mkre** [comment]
I just checked again with UCX 1.10.0-rc1 and the numbers are the same as with UCX 1.9.0, i.e., the regression with the UD transport still exists.

@rakhmets @yosefe Do you think that there is a chance that this gets addressed at some point, or are you maybe not considering this a bug?

**Comment by yosefe** [comment]
@mkre is it possible to use DC transport instead of UD?

**Comment by mkre** [comment]
@yosefe, unfortunately, that's not always possible.

1. We are sometimes short of memory, and UD shows the best memory efficiency of all transports.
2. On pre-ConnectX-4 systems, DC will not be available.

**Comment by yosefe** [comment]
@mkre , i see. there are currently no short-term plans for additional optimizations in UD transport. Is it possible to use 1.8.0 in the meantime?

**Comment by mkre** [comment]
Okay, I guess that also means that fixing UD regressions is probably not very high on your priority list. Is this correct? In that case, we will have to think about how to treat high-memory runs on all interconnects and ConnectX-3 in general in the future...

**Comment by yosefe** [comment]
@mkre do you have a simple reproducer (test+command line) for the performance issue which can be shared?

**Comment by mkre** [comment]
@yosefe I can also see the regression using the Intel MPI Benchmarks (IMB) with Open MPI 4.0.3. For example, using `./IMB-MPI1 -npmin 80 allreduce` (reported is `t_avg[usec]` at `4194304` bytes, so lower is better):

| | `UCX_TLS=ud,self,sm`  | `UCX_TLS=rc,self,sm` | `UCX_TLS=dc,self,sm` |
| ------- | ------------- | ------------- | ------- |
| UCX 1.8.0  | 11595.30 | 11548.84 | 11501.31 |
| UCX 1.10.0-rc1  | **12458.16** | 11477.22 | 11460.22 |

Granted, the regression is not on the same level as for our full application, but maybe other factors are coming into play there which make the effect worse.

**Comment by Artemy-Mellanox** [comment]
@mkre could you plz rerun STAR-CCM+ test with "-x UCX_UD_TIMER_TICK=100ms" and new ucx

**Comment by mkre** [comment]
Bingo @Artemy-Mellanox! This parameter does the trick:

| `UCX_TLS=ud,self,sm` |  | `UCX_UD_TIMER_TICK=100ms` | `200ms` | `500ms` | `1000ms` |
| ------- | ------------- | ------------- | ------- |------- |------- |
| UCX 1.8.0  | 0.71 s | | |
| UCX 1.10.0-rc1 | 2.1 s | 0.83 s | 0.78 s | 0.72 s | 0.72 s |

Many thanks for the suggestion!

Do you plan to address the default behavior in UCX master or should we rather plan to apply this fix manually on our end with future UCX versions?

**Comment by mkre** [comment]
Just for the sake of completeness, we are still seeing the same behavior with 1.10.0-rc2 (no idea if you intend to fix this): significant regression with `UCX_TLS=ud,self,sm` which can be alleviated with `UCX_UD_TIMER_TICK=1000ms`.

**Comment by yosefe** [comment]
@mkre https://github.com/openucx/ucx/pull/6231 which is part of 1.10-rc2 was supposed to fix mist of the regression.
can you pls double check the version?
also, how does the performance compare to v1.9 ?

**Comment by mkre** [comment]
> can you pls double check the version?

Good that you're asking! I made a stupid mistake while downloading/extracting and ended up testing RC1 again. Sorry for the confusion!

I can confirm that the regression has gotten much smaller with RC2 compared to 1.8.0:

|| 1.8.0 || 1.9.0 || 1.10.0-rc2 ||
| 0.77 s || 2.15 s | 0.79 s || 

Thanks for addressing this for 1.10.0.

**Comment by Artemy-Mellanox** [comment]
@mkre just to make sure - what is `UCX_UD_TIMER_TICK` setting in latest result?

**Comment by mkre** [comment]
I didn't change it, so it is set to the default value.

**Comment by Artemy-Mellanox** [comment]
@mkre Can we close the issue or there is something more to investigate?

**Comment by mkre** [comment]
Fine with me to close. Thanks again for addressing this before the final release of 1.10.0!
