### ISSUE TITLE
slow shmem_init

### ISSUE THREAD

**Issue by mikedoo3** [openucx/ucx#5750]
With Mellanox HPC-X 2.6 we see very slow shmem_init() times.  HPC-X 2.6 uses UCX 1.8.0.  HPC-X 2.4.1 uses UCX 1.6.0 and does not have the issue.

To duplicate it I ran a basic program that just does a shmem_init() on 128 nodes using 40 tasks per node (5120 tasks total)
We are using UCX_TLS=dc_x,mm

I traced through it and I think the problem is as follows:
-All 40 tasks on each node are calling ucs_sys_get_ns(IPC) alot which does a stat call on /proc/self/ns/ipc.  
Through the following code path:
src/uct/sm/base/sm_iface.c
uct_sm_iface_is_reachable()
   uct_sm_iface_get_device_address()

uct_sm_iface_get_device_address()
   ucs_sys_ns_is_default()

ucs_sys_ns_is_default()
   ucs_sys_get_ns()

ucs_sys_get_ns()
    stat("/proc/self/ns/ipc")

The stat function calls slow down because 40 tasks are calling it on one node.  This causes the shmem_init to slow down dramatically.
With HPC-X 2.4.1 using UCX 1.6.0, I get an average time of .00006 seconds for each 'activate iface' in the debug log.
With HPC-X 2.6.0 using UCX 1.8.0, I get an average time of .00098 seconds
.00006 * 5120 = ~.3 seconds
.00098 * 5120 = 5 seconds

On an idle node, calling stat on /proc/self/ns/ipc is fast but when 40 processes on one node are doing it at the same time, it slows down.  That appears to be the problem here.

**Comment by hoopoepg** [comment]
Hi @mikedoo3 

Thank you for bug report.
Do you use any kind of Linux containers, like docker? Or your environment is regular compute node without any level of virtualization?

Thank you

**Comment by hoopoepg** [comment]
@mikedoo3 
We prepared PR https://github.com/openucx/ucx/pull/5755 where implemented some caching of file system operations.
Could you check if this fix works for you?

thank you
