### ISSUE TITLE
package sun.nio.ch does not exist

### ISSUE THREAD

**Issue by xkszltl** [openucx/ucx#5811]
### Describe the bug

version: latest release tag (v1.9.0)

https://github.com/openucx/ucx/blob/24889d115aef230203ce750b9ac856a85edaa3fb/bindings/java/src/main/java/org/openucx/jucx/UcxUtils.java#L40
This line does not work on Ubuntu 18.04 (default jdk is openjdk11):
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/5203025/96358047-865b4780-1135-11eb-88a6-db678fbed34f.png">

I also tried it on CentOS 7 (javac 1.8.0_262), that works fine.

**Comment by shamisp** [comment]
FYI @petro-rudenko
