### ISSUE TITLE
update wiki with UCX_DEVICES -> UCX_{NET|ACC|SHM}_DEVICES

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#584]

**Comment by alinask** [comment]
https://github.com/openucx/ucx/wiki/UCX-environment-parameters

**Comment by alinask** [comment]
@shamisp I updated the wiki with the info you requested.

**Comment by alinask** [comment]
@yosefe @shamisp @miked-mellanox can this be closed?

**Comment by yosefe** [comment]
fixed in #568
