### ISSUE TITLE
Compatible version of gdrcopy

### ISSUE THREAD

**Issue by hyviquel** [openucx/ucx#5860]
I am contributing to the UCX package on Spack by updating the version of gdrcopy: https://github.com/spack/spack/pull/19606 . As you can see in the PR, Spack's developers would like to configure the version of gdrcopy according to the version of UCX. I am asking directly since I haven't found much information about it: only that release note of ucx v1.6.0rc2 has been tested with gdrcopy 1.3.2

**Comment by shamisp** [comment]
@bureddy should be able to answer

**Comment by bureddy** [comment]
@hyviquel UCX supports both gdrcopy 1.3 and 2.0 APIs.  Jenkins is currently testing with 2.0 (https://github.com/openucx/ucx/blob/master/contrib/test_jenkins.sh#L30).  we will update testing to version 2.1 (no API change) for the next release

**Comment by hyviquel** [comment]
@bureddy nice but do you know starting from what version of ucx the support of gdrcopy v2.0 has been added?

**Comment by bureddy** [comment]
@hyviquel  it supported since v1.7.x  (https://github.com/openucx/ucx/blob/v1.7.x/config/m4/gdrcopy.m4#L42)

**Comment by hyviquel** [comment]
Thanks @bureddy
