### ISSUE TITLE
Possible memory leak when sending small messages

### ISSUE THREAD

**Issue by angainor** [openucx/ucx#5871]
I am seeing a memory leak when running the attached simple MPI program on
our EDR system (RH 7.7). I tried with OpenMPI versions starting from 3.1.4
to 4.0.5, and with UCX versions from HPCX 2.6, HPCX 2.7, and the new UCX 1.9.0.
In all cases the program quickly allocates the memory (~1GB every few seconds) 
until it fails with a lot of UCX error messages:

```
[1604396696.346053] [c38-2:76180:1]          mpool.c:191  UCX  ERROR Failed to allocate memory pool (name=rc_recv_desc) chunk: Out of memory
```

The program is a multi-threaded MPI send/recv test. 
Each thread keeps a constant number of private onging send/recv messages in-flight. 
The threads test the requests, and as soon as one of them is finished, they submit
a new one in it's place. Essentially:

```
	while(true){

	    MPI_Testany(inflight, rreq, &j, &flag, MPI_STATUS_IGNORE);
	    if(flag) {
	        MPI_Irecv(rbuffers[j], buff_size, MPI_BYTE, peer_rank, thrid*inflight+j, mpi_comm, &rreq[j]);
	    }

            MPI_Testany(inflight, sreq, &j, &flag, MPI_STATUS_IGNORE);
            if(flag) {
                MPI_Isend(sbuffers[j], buff_size, MPI_BYTE, peer_rank, thrid*inflight+j, mpi_comm, &sreq[j]);
            }
	}
```

I compile the program with

```
mpicxx test.cpp -fopenmp -O3 -Wall -Wpedantic -o test
```

and run it as

```
mpirun -map-by node -np 2 -x OMP_NUM_THREADS=4 -bind-to socket -mca coll_hcoll_enable 0 ./test 1 10
```

The first argument of the program is the message size. The second argument is the number
of messages in flight. Not all configurations result in a memory leak. From my tests
I see that the number of messages in-flight should be small (~10) and the messages
must be below 8198 bytes. Sometimes (different UCX/OpenMPI version) I need 2 threads, 
but 4 threads seem to work OK. Sometimes 8 threads are needed to reproduce the problem. 
Hence this looks like some thread race.

Do you have any ideas what this behavior could be caused by?

[test.zip](https://github.com/openucx/ucx/files/5480713/test.zip)

**Comment by yosefe** [comment]
this test creates an unlimited amount of "unexpected" messages, since the sender can send with any backpressure from the receiver

**Comment by angainor** [comment]
Thanks, @yosefe. So you're saying I should limit the sender somehow? Say, I would demand that it keeps up with local recv, e.g.

```
        int lsent=0, lrecv=0;
	while(true){

	    MPI_Testany(inflight, rreq, &j, &flag, MPI_STATUS_IGNORE);
	    if(flag) {
	        MPI_Irecv(rbuffers[j], buff_size, MPI_BYTE, peer_rank, thrid*inflight+j, mpi_comm, &rreq[j]);
                lrecv++;
	    }
            
            if(lsent<lrecv+inflight){
                MPI_Testany(inflight, sreq, &j, &flag, MPI_STATUS_IGNORE);
                if(flag) {
                    MPI_Isend(sbuffers[j], buff_size, MPI_BYTE, peer_rank, thrid*inflight+j, mpi_comm, &sreq[j]);
                    lsent++;
                }
            }
	}
```

**Comment by yosefe** [comment]
yes, something like that

**Comment by angainor** [comment]
@yosefe Thanks a lot! this solves my issue :)
