### ISSUE TITLE
segmentation fault in ucs_ptr_array_set()

### ISSUE THREAD

**Issue by chenyidu** [openucx/ucx#5879]
Init phase
```
ptr_array->size = 0;
ptr_array->start = NULL;
```
when `element_index` is 0, it will not go to " ptr_array grow" branch.
https://github.com/openucx/ucx/blob/4f03615e8f1627d50310343b47f83f5957e465fc/src/ucs/datastruct/ptr_array.c#L212
It will use `ptr_array->start[0]` which causes a segmentation fault.
https://github.com/openucx/ucx/blob/4f03615e8f1627d50310343b47f83f5957e465fc/src/ucs/datastruct/ptr_array.c#L215

The condition should be `element_index >= ptr_array->size`

**Comment by yosefe** [comment]
it should be >=
@alex--m

**Comment by alex--m** [comment]
#5787

**Comment by chenyidu** [comment]
#5787 already merged, close this issue
