### ISSUE TITLE
Performance issues with internode GPU tag_lat test

### ISSUE THREAD

**Issue by Yiltan** [openucx/ucx#5893]
### Describe the bug

I have noticed poor performance with inter-node pt2pt communication using GPU buffers with Open MPI. The issue is still present when doing performance tests with UCX.

With UCX for a 4MB I have a latency of 760us. According to this paper ([Fig 12b](https://www.researchgate.net/publication/337684803_Performance_Evaluation_of_MPI_Libraries_on_GPU-Enabled_OpenPOWER_Architectures_Early_Experiences)), on this platform I should have around 250us when using UCX. Regardless of message size the max bandwidth is around 5000MB/s. I have verified the platform with other MPI implementations and I am able to achieve 425us for a 4MB message which is less than the paper.

I was wondering if anyone could comment on if there is an issue with my setup and if my results seem reasonable. 

### Steps to Reproduce
- **Any UCX environment variables used**
   - `export UCX_RNDV_SCHEME=get_zcopy`
   - `export UCX_TLS=all`
   - `export UCX_NET_DEVICES=all`
- Command line
   - Node 0: `ucx_perftest -c 0 -w 100 -n 1000 -m cuda,cuda -s $(4 * 1024 * 1024) > /dev/null & `
   - Node 1: `ucx_perftest $REMOTE_NODE -t tag_lat -c 1 -w 100 -n 1000 -m cuda,cuda -s $(4 * 1024 * 1024) `

- Output:
```
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
          1000     0.000   760.423   760.423    5260.23    5260.23        1315        1315
```

- UCX version used
```
# UCT version=1.8.0 revision c76471d
# configured with: --prefix=/opt/ucx/ --disable-assertions --disable-debug --disable-logging --disable-params-check --enable-devel-headers --enable-mt --enable-backtrace-detail --with-cuda=/opt/cuda/10.2.89 --without-java --with-gdrcopy --with-knem=/opt/knem-1.1.3.90mlnx1
```

### Setup and versions
This machine is a an IBM® Power® System AC922 - (Same machine as Sierra)

- OS version + CPU architecture (ppc64le)
   - Red Hat Enterprise Linux Server release 7.6 (Maipo)

- For RDMA/IB/RoCE related issues:
    - Driver version:
        - MLNX_OFED version: 4.5
   - HW information (ConnectX-5)
- For GPU related issues:
  - GPU type V100-SMX2
  - Cuda: 
      -  Driver Version: 440.33.01    
      - CUDA Version: 10.2
      - Check if peer-direct is loaded: `lsmod|grep nv_peer_mem` and/or gdrcopy: `lsmod|grep gdrdrv`
          ```nv_peer_mem             7394  0 
                  nvidia              23537874  55 nv_peer_mem,gdrdrv,nvidia_modeset,nvidia_uvm
                  ib_core               386900  11 ib_cm,rdma_cm,ib_umad,nv_peer_mem,ib_uverbs,ib_ipoib,iw_cm,mlx5_ib,ib_ucm,rdma_ucm,mlx4_ib```

**Comment by bureddy** [comment]
@Yiltan can you attach "`nvidia-smi topo -m`" output?

**Comment by Yiltan** [comment]
Hi @bureddy, this is the output. Both nodes have the same topology.

```
	GPU0	GPU1	GPU2	GPU3	mlx5_0	mlx5_1	mlx5_2	mlx5_3	CPU Affinity
GPU0	 X 	NV3	SYS	SYS	NODE	NODE	SYS	SYS	0-63
GPU1	NV3	 X 	SYS	SYS	NODE	NODE	SYS	SYS	0-63
GPU2	SYS	SYS	 X 	NV3	SYS	SYS	NODE	NODE	64-127
GPU3	SYS	SYS	NV3	 X 	SYS	SYS	NODE	NODE	64-127
mlx5_0	NODE	NODE	SYS	SYS	 X 	PIX	SYS	SYS	
mlx5_1	NODE	NODE	SYS	SYS	PIX	 X 	SYS	SYS	
mlx5_2	SYS	SYS	NODE	NODE	SYS	SYS	 X 	PIX	
mlx5_3	SYS	SYS	NODE	NODE	SYS	SYS	PIX	 X 	

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by bureddy** [comment]
Can you try with UCX_NET_DEVICES=mlx5_0:1,mlx5_3:1 ? 
this is Socket-Direct configuration. need to pick the correct interfaces to get the peak.
I tried it on Summit and got the expected latency

```
UCX_NET_DEVICES=mlx5_0:1,mlx5_3:1 UCX_RNDV_SCHEME=get_zcopy install/bin/ucx_perftest  -t tag_lat -c 1 -w 100 -n 1000 -m cuda,cuda  -s 4194304 h31n14
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
          1000     0.000   260.043   260.043   15382.07   15382.07        3846        3846

```

**Comment by Yiltan** [comment]
I ran it with `UCX_NET_DEVICES=mlx5_0:1,mlx5_3:1` and got the following warning:

```
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
[1605131501.458403] [mist042:121972:0]    ucp_context.c:690  UCX  WARN  network device 'mlx5_3:1' is not available, please use one or more of: 'enP5p1s0f0'(tcp), 'ib0'(tcp), 'mlx5_0:1'(ib), 'mlx5_2:1'(ib)
           667     0.000  1500.047  1500.047    2666.58    2666.58         667         667
          1000     0.000  1502.114  1500.735    2662.91    2665.36         666         666
```

So I used `UCX_NET_DEVICES=mlx5_0:1,mlx5_2:1` as stated by the warning. 

```
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
          1000     0.000   758.241   758.241    5264.32    5264.32        1317        1317
```

This is fairly similar to my measurement with `UCX_NET_DEVICES=all`

**Comment by bureddy** [comment]
250us latency on Summit/Sierra with dual IB cards. It looks like one HCA (2 ports: mlx5_1, mlx5_3)  on your setup is not active/up. 
mlx5_0 and mlx5_2 are socket-Direct ports ofsame HCA connected to different NUMA.  
can you check UCX_NET_DEVICES=mlx5_0:1 and UCX_NET_DEVICES=mlx5_2:1 indivisually?

**Comment by Yiltan** [comment]
After discussing with the sysadmins, this machine only has one of the cards connected. So I suspect that my latency should be around double what you see on Summit/Sierra. With MVAPICH2-GDR I able to get a latency of 480us for the 4MB message which is around double your results. I am only achieving 760us with UCX.

As requested here are the tests that you requested. 
Test 1: `UCX_NET_DEVICES=mlx5_0:1`
```
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
           665     0.000  1505.429  1505.429    2657.05    2657.05         664         664
          1000     0.000  1509.036  1506.637    2650.70    2654.92         663         664
```

Test 2: `UCX_NET_DEVICES=mlx5_2:1`
```
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
           663     0.000  1509.665  1509.665    2649.59    2649.59         662         662
          1000     0.000  1515.549  1511.648    2639.31    2646.12         660         662
```

**Comment by bureddy** [comment]
can you try with "`-x UCX_IB_GPU_DIRECT_RDMA=no`"

**Comment by Yiltan** [comment]
Thank you, that worked perfectly. I'm now getting around 460us for the 4MB message.

**Comment by bureddy** [comment]
It looks like this setup is not tuned well for GPUDirectRDMA.  maybe you can check with sysadmins.

**Comment by Yiltan** [comment]
@bureddy  Do you have any suggestions on what to check on this setup? Talking with the admins they are telling me that they have the packages installed and the kernel modules loaded.

**Comment by bureddy** [comment]
do they have both `nv_peer_mem` and `nv_rsync_mem` ?
https://www.ibm.com/support/knowledgecenter/SSZTET_10.2/install/smpi01_gpu_install.html
