### ISSUE TITLE
Some questions about multi thread mode in UCX

### ISSUE THREAD

**Issue by zhangwp** [openucx/ucx#5947]
UCX supports multi threads or thread safety. How do I understand it?
It means UCX will create multi threads in UCX itself? Or application using ucx creates multi threads?
Who will guarantee the thread safety?

**Comment by yosefe** [comment]
UCX does not create multiple threads on its own. It can only guarantee safety if UCX API functions are used from multiple threads (assuming correct thread support flags passed to ucp_init() and ucp_worker_init() )

**Comment by zhangwp** [comment]
> UCX does not create multiple threads on its own. It can only guarantee safety if UCX API functions are used from multiple threads (assuming correct thread support flags passed to ucp_init() and ucp_worker_init() )

But, I see that ucs/async/thread.c(ucs_async_thread_start function) will use pthread_create to process async event.

**Comment by zhangwp** [comment]
> > UCX does not create multiple threads on its own. It can only guarantee safety if UCX API functions are used from multiple threads (assuming correct thread support flags passed to ucp_init() and ucp_worker_init() )
> 
> But, I see that ucs/async/thread.c(ucs_async_thread_start function) uses pthread_create to process async event.

**Comment by shamisp** [comment]
@zhangwp UCX has internal threads that are used for asynchronous progress of communication.

**Comment by yosefe** [comment]
> @zhangwp UCX has internal threads that are used for asynchronous progress of communication.

Actually, it progresses only asynchronous events (such as connect/disconnet/error), the actual communication happens only in the context of ucp_worker_progress(), which must be called explicitly from application thread(s)

**Comment by shamisp** [comment]
@yosefe is not UD RNDV also progress asynchronously in the thread ?

**Comment by yosefe** [comment]
> @yosefe is not UD RNDV also progress asynchronously in the thread ?

No, it doesn't

**Comment by shamisp** [comment]
So, no asynchronous progress for UD  ?

**Comment by yosefe** [comment]
> So, no asynchronous progress for UD ?

Only for retransmissions but not for actual protocols
