### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by JaeseungYeom** [openucx/ucx#5971]
### Describe the bug
Compilation error
src/uct/rocm/gdr/rocm_gdr_ep.c: In function 'uct_rocm_gdr_ep_put_short':
../../../../../src/uct/rocm/gdr/rocm_gdr_ep.c:47:15: error: implicit declaration of function 'gdr_copy_to_bar'; did you mean 'gdr_copy_to_mapping'? [-Werror=implicit-function-declaration]
         ret = gdr_copy_to_bar((void *)remote_addr, buffer, length);
               ^~~~~~~~~~~~~~~
               gdr_copy_to_mapping
../../../../../src/uct/rocm/gdr/rocm_gdr_ep.c:47:15: error: nested extern declaration of 'gdr_copy_to_bar' [-Werror=nested-externs]

### Steps to Reproduce
- ./autogen.sh; mkdir build; cd build; ../configure --prefix=<install-path>; make -j 4
- Just pulled from github. (HEAD #5963 36ed22886fea1cffddee9eb76f1f9ff3b6b292f9)

### Setup and versions
- OS version (Linux 3.10.0) + CPU architecture x86_64
- For RDMA/IB/RoCE related issues:
   - HW information from `ibstat`
  	Number of ports: 1
	Firmware version: 1.27.0
	Hardware version: 11

- For GPU related issues:
  - GPU type: NO GPU

**Comment by hoopoepg** [comment]
same as https://github.com/openucx/ucx/issues/4489?

**Comment by JaeseungYeom** [comment]
Looks similar. I will close this issue.

**Comment by JaeseungYeom** [comment]
Just one question though. How can I configure with GPU-related features disabled? My platform does not have GPU, but the error is coming from compiling gdr-related code. I will have to check if the driver is present somewhere in the system.

**Comment by hoopoepg** [comment]
./configure --without-rocm --without-gdrcopy --without-cuda

**Comment by JaeseungYeom** [comment]
Thank you!
