### ISSUE TITLE
ud_verbs/uct_p2p_mix_test_alloc_methods.mix1000_multithreaded

### ISSUE THREAD

**Issue by rakhmets** [openucx/ucx#5988]
### Describe the bug
Test ud_verbs/uct_p2p_mix_test_alloc_methods.mix1000_multithreaded fails with segfault:
Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))

4  0x00007f323738ff1f in ucs_debug_handle_error_signal (signo=11, cause=0x7f32374554f4 "address not mapped to object", fmt=0x7f323745567d " at address %p") at debug/debug.c:1027
5  0x00007f3237390065 in ucs_error_signal_handler (signo=11, info=0x7f32378d4eb0, context=0x7f32378d4d80) at debug/debug.c:1049
6  <signal handler called>
7  0x0000000000000000 in ?? ()
8  0x00007f32365f1d94 in ibv_dereg_mr () from /lib64/libibverbs.so.1
9  0x00007f323682aec3 in uct_ib_mlx5_exp_dereg_atomic_key (ibmd=0x35a7ae0, ib_memh=0x35750d0) at mlx5/exp/ib_exp_md.c:494
10 0x00007f3236820fae in uct_ib_memh_dereg (md=0x35a7ae0, memh=0x35750d0) at base/ib_md.c:590
11 0x00007f3236822010 in uct_ib_rcache_mem_dereg_cb (context=0x35a7ae0, rcache=0x35a80e0, rregion=0x35750a0) at base/ib_md.c:1037
12 0x00007f3237396794 in ucs_mem_region_destroy_internal (rcache=0x35a80e0, region=0x35750a0) at memory/rcache.c:305
13 0x00007f3237396f08 in ucs_rcache_check_gc_list (rcache=0x35a80e0) at memory/rcache.c:441
14 0x00007f3237398d3c in ucs_rcache_t_cleanup (self=0x35a80e0) at memory/rcache.c:994
15 0x00007f32373a82de in ucs_class_call_cleanup_chain (cls=0x7f32376aa8c0 <ucs_rcache_t_class>, obj=0x35a80e0, limit=-1) at type/class.c:56
16 0x00007f3237398ed1 in ucs_rcache_destroy (self=0x35a80e0) at memory/rcache.c:1009
17 0x00007f3236822f41 in uct_ib_md_release_reg_method (md=0x35a7ae0) at base/ib_md.c:1363
18 0x00007f3236823f40 in uct_ib_md_close (uct_md=0x35a7ae0) at base/ib_md.c:1668
19 0x00007f32370f03e1 in uct_md_close (md=0x35a7ae0) at base/uct_md.c:64

### Steps to Reproduce
./test/gtest/gtest  --gtest_filter="ud_verbs/uct_p2p_mix_test_alloc_methods.mix1000_multithreaded*"
UCX from github branch master
UCT version=1.10.0 revision 272c246
configured with: --enable-gtest --enable-examples --with-valgrind --enable-profiling --enable-frame-pointer --enable-stats --enable-memtrack --enable-fault-injection --enable-debug-data --enable-mt --enable-debug --with-java=no

### Setup and versions
hostname: cascade1
Red Hat Enterprise Linux Server release 7.4 (Maipo)
Driver version: libibverbs-41mlnx1-OFED.4.6.0.4.1.46101.x86_64

**Comment by rakhmets** [comment]
the issue is no longer reproducible

**Comment by Jim2016713** [comment]
> the issue is no longer reproducible
How did you solve it
