### ISSUE TITLE
[Q]: UCX  ERROR ibv_open_device(mlx5_0) failed: Cannot allocate memory

### ISSUE THREAD

**Issue by angainor** [openucx/ucx#6049]
I'm running with HPCX 2.7 / OpenMPI 4.0.5 on Centos 7.7, two socket AMD system (128 cores / 256 hw threads). 
My application triggers the following errors when I run 256 ranks on one compute node:
```
[1608298882.555115] [b2294:54275:0]          ib_md.c:1678 UCX  ERROR ibv_open_device(mlx5_0) failed: Cannot allocate memory
```
`dmesg` shows this
```
[2605244.823409] mlx5_core 0000:61:00.0: mlx5_cmd_check:795:(pid 53945): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)
```
A simple mpi program doesn't trigger this, so it must be something the app does. Do you know what kind of limit do I trigger, and how I can fix this?

**Comment by yosefe** [comment]
@angainor pls see https://github.com/open-mpi/ompi/issues/6854#issuecomment-516341819

**Comment by angainor** [comment]
@yosefe that worked, thanks! Are there any potential side effects / performance implications of this setting?

**Comment by yosefe** [comment]
@angainor if the machine is able to boot and recognize the NIC, there should not be side effects.

**Comment by angainor** [comment]
@yosefe thanks for the info!
