### ISSUE TITLE
IODEMO: coredump

### ISSUE THREAD

**Issue by SummerRayPeipei** [openucx/ucx#6096]
### Describe the bug
i cannot change any code, just test the example of iodemo, 

### Steps to Reproduce
- server
 ./io_demo -b 512 -i 10000000 -d 512:524288 -w 256 -o read,write -p 10001

- client
./io_demo -p 10001  -b 256 -i 100 -d 512:524288 -w 256 -o read,write <server_addr>

error info:

[UCX] created context 0xb614a0
[UCX] created worker 0x7f7fb9525010
[UCX] started listener 0xbb2440 on 0.0.0.0:10001
[UCX] got new connection request 0x7f7fb00029f0
[UCX-connection #1 0.0.0.0:0] created new connection, total: 1
[UCX-connection #1 0.0.0.0:0] ucp_conn_request_query() failed: Unsupported operation
[UCX-connection #1 0.0.0.0:0] created endpoint 0x7f7fb7eec000, exchanging connection id
[TENCENT64:7130 :0:7130]      ucp_ep.c:720  Bug: pending request 0xbe19b8 on ep 0x7f7fb7eec000 should have been flushed

/.../ucx-1.9.0/build/src/ucp/../../../src/ucp/core/ucp_ep.c: [ ucp_destroyed_ep_pending_purge() ]
      ...
      717 static void ucp_destroyed_ep_pending_purge(uct_pending_req_t *self, void *arg)
      718 {
      719     ucs_bug("pending request %p on ep %p should have been flushed", self, arg);
==>   720 }
      721 
      722 void ucp_ep_destroy_internal(ucp_ep_h ep)
      723 {

==== backtrace (tid:   7130) ====
 0 0x0000000000052815 ucs_debug_print_backtrace()  /data/raylchen/ucx-1.9.0/build/src/ucs/../../../src/ucs/debug/debug.c:656
 1 0x000000000001929b ucp_destroyed_ep_pending_purge()  /data/raylchen/ucx-1.9.0/build/src/ucp/../../../src/ucp/core/ucp_ep.c:720
 2 0x0000000000061cf0 ucp_wireup_ep_pending_purge()  /data/raylchen/ucx-1.9.0/build/src/ucp/../../../src/ucp/wireup/wireup_ep.c:227
 3 0x0000000000061cf0 ucp_wireup_ep_pending_purge()  /data/raylchen/ucx-1.9.0/build/src/ucp/../../../src/ucp/wireup/wireup_ep.c:222
 4 0x000000000001a485 uct_ep_pending_purge()  /data/raylchen/ucx-1.9.0/build/../src/uct/api/uct.h:2732
 5 0x000000000001a485 ucp_ep_cleanup_lanes()  /data/raylchen/ucx-1.9.0/build/src/ucp/../../../src/ucp/core/ucp_ep.c:741
 6 0x0000000000065663 ucp_wireup_process_request()  /data/raylchen/ucx-1.9.0/build/src/ucp/../../../src/ucp/wireup/wireup.c:480
 7 0x00000000000665de ucp_wireup_msg_handler()  /data/raylchen/ucx-1.9.0/build/src/ucp/../../../src/ucp/wireup/wireup.c:670
 8 0x00000000000664b2 uct_iface_invoke_am()  /data/raylchen/ucx-1.9.0/build/../src/uct/base/uct_iface.h:635
 9 0x00000000000664b2 uct_ib_iface_invoke_am_desc()  /data/raylchen/ucx-1.9.0/build/../src/uct/ib/base/ib_iface.h:353
10 0x00000000000664b2 uct_ud_ep_process_rx()  /data/raylchen/ucx-1.9.0/build/src/uct/ib/../../../../src/uct/ib/ud/base/ud_ep.c:887
11 0x00000000000709b2 uct_ud_mlx5_iface_poll_rx()  /data/raylchen/ucx-1.9.0/build/src/uct/ib/../../../../src/uct/ib/ud/accel/ud_mlx5.c:468
12 0x00000000000709b2 uct_ud_mlx5_iface_progress()  /data/raylchen/ucx-1.9.0/build/src/uct/ib/../../../../src/uct/ib/ud/accel/ud_mlx5.c:517
13 0x000000000002a3ba ucs_callbackq_dispatch()  /data/raylchen/ucx-1.9.0/build/../src/ucs/datastruct/callbackq.h:211
14 0x000000000002a3ba uct_worker_progress()  /data/raylchen/ucx-1.9.0/build/../src/uct/api/uct.h:2346
15 0x000000000002a3ba ucp_worker_progress()  /data/raylchen/ucx-1.9.0/build/src/ucp/../../../src/ucp/core/ucp_worker.c:2040
16 0x000000000040ec8f UcxContext::wait_completion()  ???:0
17 0x000000000040fbd8 UcxConnection::connect_common()  ???:0
18 0x000000000040f43f UcxConnection::accept()  ???:0
19 0x000000000040e941 UcxContext::progress_conn_requests()  ???:0
20 0x000000000040e552 UcxContext::progress()  ???:0
21 0x000000000040446f DemoServer::run()  ???:0
22 0x00000000004033d6 do_server()  io_demo.cc:0
23 0x0000000000403641 main()  ???:0
24 0x0000000000021c05 __libc_start_main()  ???:0
25 0x0000000000402719 _start()  ???:0

- UCX version used (from github branch  release 1.9.0) + UCX configure flags (can be checked by `ucx_info -v`)
UCT version=1.9.0 revision a306b90
configured with: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --enable-cma --without-cuda --without-gdrcopy --with-verbs --with-cm --with-knem --with-rdmacm --without-rocm --without-xpmem --without-ugni --without-java

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
   - `cat /etc/issue` or `cat /etc/redhat-release` + `uname -a`
- For RDMA/IB/RoCE related issues:
    - Driver version:
        - `rpm -q rdma-core` or `rpm -q libibverbs`
        - or: MLNX_OFED version `ofed_info -s`
           MLNX_OFED_LINUX-4.6-1.0.1.1
   - HW information from `ibstat` or `ibv_devinfo -vv` command
   CA 'mlx5_bond_0'
        CA type: MT4117
        Number of ports: 1
        Firmware version: 14.22.1002
        Hardware version: 0
        Node GUID: 0x0c42a103006428a4
        System image GUID: 0x0c42a103006428a4
        Port 1:
                State: Active
                Physical state: LinkUp
                Rate: 25
                Base lid: 0
                LMC: 0
                SM lid: 0
                Capability mask: 0x00010000
                Port GUID: 0x0e42a1fffe6428a4
                Link layer: Ethernet

**Comment by alinask** [comment]
@SummerRayPeipei Since you are using UCX v1.9, can you please set the following environment parameter on both sides?
`UCX_SOCKADDR_CM_ENABLE=y`

**Comment by SummerRayPeipei** [comment]
Is there a function call to do this? I don't know what function to call to do this

**Comment by alinask** [comment]
@SummerRayPeipei you can do it like this:

- server

`UCX_SOCKADDR_CM_ENABLE=y ./io_demo -b 512 -i 10000000 -d 512:524288 -w 256 -o read,write -p 10001`

- client

`UCX_SOCKADDR_CM_ENABLE=y ./io_demo -p 10001 -b 256 -i 100 -d 512:524288 -w 256 -o read,write <server_addr>`

**Comment by SummerRayPeipei** [comment]
when I run "UCX_SOCKADDR_CM_ENABLE=y ./io_demo -b 512 -i 10000000 -d 512:524288 -w 256 -o read,write -p 10001" cmd, The progress is not running

**Comment by alinask** [comment]
can you share the output please from client and server?

**Comment by SummerRayPeipei** [comment]
Now the progress is both running, but on the side of client, print the result:
DEMO] random seed: 1610012742
[UCX] created context 0xdbbec0
[UCX] created worker 0x7fa5e22e5010
[UCX-connection #1 0.0.0.0:0] created new connection, total: 1
[UCX-connection #1 9.228.242.23:1337] created endpoint 0x7fa5e0ce9000, exchanging connection id
[UCX-connection #1 9.228.242.23:1337] detected error: Operation rejected by remote peer
[UCX-connection #1 9.228.242.23:1337] failed to send remote connection id
[UCX-connection #1 9.228.242.23:1337] closing ep 0x7fa5e0ce9000 mode force
[UCX-connection #1 9.228.242.23:1337] released
[DEMO] retry 1/9223372036854775807 in 1 seconds
[UCX-connection #2 0.0.0.0:0] created new connection, total: 1
[UCX-connection #2 9.228.242.23:1337] created endpoint 0x7fa5e0ce9000, exchanging connection id
[UCX-connection #2 9.228.242.23:1337] detected error: Operation rejected by remote peer
[UCX-connection #2 9.228.242.23:1337] failed to send remote connection id
[UCX-connection #2 9.228.242.23:1337] closing ep 0x7fa5e0ce9000 mode force
[UCX-connection #2 9.228.242.23:1337] released
[DEMO] retry 2/9223372036854775807 in 1 seconds
[UCX-connection #3 0.0.0.0:0] created new connection, total: 1
[UCX-connection #3 9.228.242.23:1337] created endpoint 0x7fa5e0ce9000, exchanging connection id
@alinask

**Comment by alinask** [comment]
can you please share the output of the server side, output of `ifconfig` and output of `ibdev2netdev`?

**Comment by SummerRayPeipei** [comment]
ifconfig
bond1: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 1500
        inet 9.228.242.23  netmask 255.255.255.192  broadcast 9.228.242.63
        inet6 2402:4e00:2200:c604::3  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::e42:a1ff:fe64:28a4  prefixlen 64  scopeid 0x20<link>
        ether 0c:42:a1:64:28:a4  txqueuelen 1000  (Ethernet)
        RX packets 31835087  bytes 2422500190 (2.2 GiB)
        RX errors 0  dropped 41291  overruns 0  frame 0
        TX packets 4159080  bytes 605066740 (577.0 MiB)
        TX errors 0  dropped 3 overruns 0  carrier 0  collisions 0

eth0: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        ether 0c:42:a1:64:28:a4  txqueuelen 1000  (Ethernet)
        RX packets 16123413  bytes 1216367620 (1.1 GiB)
        RX errors 0  dropped 41291  overruns 0  frame 0
        TX packets 2179548  bytes 300387367 (286.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        ether 0c:42:a1:64:28:a4  txqueuelen 1000  (Ethernet)
        RX packets 15711674  bytes 1206132570 (1.1 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1979539  bytes 304680639 (290.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 22522  bytes 9465491 (9.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 22522  bytes 9465491 (9.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
ibdev2netdev
mlx5_bond_0 port 1 ==> eth0 (Up)
@alinask

**Comment by alinask** [comment]
can you please add the server's output and the <server_addr> you are using in the command line?

**Comment by SummerRayPeipei** [comment]
- client
UCX_SOCKADDR_CM_ENABLE=y ./io_demo 9.228.242.23  -b 256 -i 1 -d 512:524288 -w 256 -o read,write 
outputs:
[UCX-connection #8 9.228.242.23:1337] detected error: Operation rejected by remote peer
[UCX-connection #8 9.228.242.23:1337] failed to send remote connection id
[UCX-connection #8 9.228.242.23:1337] closing ep 0x7ff8a418b000 mode force
[UCX-connection #8 9.228.242.23:1337] released
[DEMO] retry 8/9223372036854775807 in 1 seconds
[UCX-connection #9 0.0.0.0:0] created new connection, total: 1
[UCX-connection #9 9.228.242.23:1337] created endpoint 0x7ff8a418b000, exchanging connection id
[UCX-connection #9 9.228.242.23:1337] detected error: Operation rejected by remote peer
[UCX-connection #9 9.228.242.23:1337] failed to send remote connection id
[UCX-connection #9 9.228.242.23:1337] closing ep 0x7ff8a418b000 mode force
[UCX-connection #9 9.228.242.23:1337] released
[DEMO] retry 9/9223372036854775807 in 1 seconds
[UCX-connection #10 0.0.0.0:0] created new connection, total: 1
[UCX-connection #10 9.228.242.23:1337] created endpoint 0x7ff8a418b000, exchanging connection id
- server
UCX_SOCKADDR_CM_ENABLE=y ./io_demo -b 512 -i 10000000 -d 512:524288 -w 256 -o read,write -p 10001
outputs:
[UCX] created context 0xbc54f0
[UCX] created worker 0x7f8488ab4010
[UCX] started listener 0xc13800 on 0.0.0.0:10001
@alinask

**Comment by SummerRayPeipei** [comment]
i know the reason of this question,  thank you very much

**Comment by alinask** [comment]
@SummerRayPeipei do you still see a problem?
If yes, please share the output,
According to the output above, you are trying to reach bond1 (9.228.242.23) but eth0 is the interface of mlx5_bond_0 port 1.

**Comment by SummerRayPeipei** [comment]
these is no problem, thanks @alinask

**Comment by alinask** [comment]
great! 👍 
i'm closing this ticket then...
