### ISSUE TITLE
Several questions about UCX protocol and API

### ISSUE THREAD

**Issue by haihai-00** [openucx/ucx#6103]
As a beginner of UCX, I'm confused about the protocol concept in UCX
1. UCX can choose "transport" automatically according to the H/W environment. transport here means transport methods such as shm, reliable connection.... And this operatiron is done by protocol_selection in the code. Am I right?
2. UCX support protocols such as active message, tag match, RMA put/get and AMO. These protocols are supported through the UCP APIs, and any transports above-mentioned can be used for any protocols. Am I right?
3. Since UCX provides many APIs for uses, so how should user choose an appropriate API for application? Or what kind of scenarios are suitable for these protocols( active message, tag match, RMA put/get and AMO)?

By the way, I noticed that the 2020 UCX conference is held on Dec. 2020. Is there any chance that the conference materials can be shared like 2019?
Thank you very much ^^

**Comment by yosefe** [comment]
Hi @haihai-00 ,
1. Yes that is right
2. Mostly yes, except some transports may not implement AMO/RMA natively (for example ,TCP), so UCP will emulate it over active messages
3. The API to use is according to the application, so if you could please describe the use case, it would be possible to recommend something specific. That being said, active messages API is the most generic one, so I would recommend start with it.
4. please see here: https://www.openucx.org/presentations/

**Comment by haihai-00** [comment]
Hi, @yosefe 
Thank you very much for your quick response!
There's no presentations of 2020 in https://www.openucx.org/presentations/, so will it be updated? 

> 
> 
> Hi @haihai-00 ,
> 
>     1. Yes that is right
> 
>     2. Mostly yes, except some transports may not implement AMO/RMA natively (for example ,TCP), so UCP will emulate it over active messages
> 
>     3. The API to use is according to the application, so if you could please describe the use case, it would be possible to recommend something specific. That being said, active messages API is the most generic one, so I would recommend start with it.
> 
>     4. please see here: https://www.openucx.org/presentations/

**Comment by yosefe** [comment]
hi @haihai-00 ,
yes, we expect 2020 slides will be added as well.
adding @shamisp

**Comment by shamisp** [comment]
I'm working with our web team to get all the content online. We will be sharing the slides and video. I think we will have all materials uploaded by end of the January.

**Comment by haihai-00** [comment]
Thank you very much ^^
