### ISSUE TITLE
JDK 11 and JDK 8 CI for JUCX

### ISSUE THREAD

**Issue by abellina** [openucx/ucx#6172]
Since JUCX could be used using a JDK11 or JDK8 JVM, this ticket is to add both CI pipelines. We should run whatever tests executed for JDK8 against JDK11.

On building JUCX, it seems building it with JDK11 but for JDK8 support is the way to go. We probably don't want to have two JARs, one built with JDK11 and one built with JDK8. Having CI test with both JDK versions at runtime should help uncover potential issues.

**Comment by sameerz** [comment]
This is primarily a testing (not building) request.  We want to ensure JUCX is tested and validated with both JDK 8 and JDK 11.
