### ISSUE TITLE
What's the difference between ucp_stream_send_nb and ucp_tag_send_nb?

### ISSUE THREAD

**Issue by haipeng31** [openucx/ucx#6193]
ucp_stream_send_nb similar with tcp socket，ucp_tag_send_nb similar with rpc？
What situation should I use ucp_stream_send_nb rather than ucp_tag_send_nb?
How do I figure out which devices I am using, Roce device or Ethernet device? and does ucp_stream_send_nb and ucp_tag_send_nb will use different devices?

**Comment by haipeng31** [comment]
Dose ucp support some api like readv and writev. not found in upc api doc

**Comment by evgeny-leksikov** [comment]
@haipeng31 you are right `ucp_stream_send_nb` similar with tcp socket. this is stream oriented API which allows to send stream of bytes on sender and receive stream of bytes on receiver, this means that point-to-point channel guarantees data ordering. For example number of send operations can be different form receive operations for the same amount of bytes, in other words you can do 1 send of 1000 bytes and 1000 receives of 1 bytes.
tag-matching API is message oriented API. this means that every send has to be matched to receive call, please note that receive context of TAG receive is worker, so posted recv operation to worker can be matched to send form any endpoint connected to this worker according to tag and tagmask.
> Dose ucp support some api like readv and writev. not found in upc api doc

both TAG and STREAM APIs support UCP_DATATYPE_IOV
http://openucx.github.io/ucx/api/v1.9/html/group___u_c_p___d_a_t_a_t_y_p_e.html#ga8ff6e9f933b306e777d24491ec251d7a

**Comment by haipeng31** [comment]
> @haipeng31 you are right `ucp_stream_send_nb` similar with tcp socket. this is stream oriented API which allows to send stream of bytes on sender and receive stream of bytes on receiver, this means that point-to-point channel guarantees data ordering. For example number of send operations can be different form receive operations for the same amount of bytes, in other words you can do 1 send of 1000 bytes and 1000 receives of 1 bytes.
> tag-matching API is message oriented API. this means that every send has to be matched to receive call, please note that receive context of TAG receive is worker, so posted recv operation to worker can be matched to send form any endpoint connected to this worker according to tag and tagmask.
> 
> > Dose ucp support some api like readv and writev. not found in upc api doc
> 
> both TAG and STREAM APIs support UCP_DATATYPE_IOV
> http://openucx.github.io/ucx/api/v1.9/html/group___u_c_p___d_a_t_a_t_y_p_e.html#ga8ff6e9f933b306e777d24491ec251d7a

@evgeny-leksikov many thanks, your reply helps a lot.
