### ISSUE TITLE
Drop in 3-stage pipeline performance when use of GPUDirectRDMA is disabled

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [openucx/ucx#6206]
### Describe the bug
- Seeing a big drop in D->H perf when GDR is disabled
- Peak local D->H and H->D cudaMemcpy perf on DGX-A100 is 24 GB/s so it should be possible to have 24 GB/s end-to-end for D->D when GDR is disabled but peak seen is 16.7 GB/s (peak H->H end-to-end bandwidth on the system is 24 GB/s as well)

Edit:
- Also, gdr_copy is not disabled when UCX_IB_GPU_DIRECT_RDMA=n but we would need an equivalent disable knob.

Traces indicate that am_bcopy pipeline is being forced with 8k transfers over pageable host bounce buffers. It maybe the case that the optimized pipeline is being dropped because some conditions are not met in the rndv decision logic.

### Steps to Reproduce
- osu_bw with and without UCX_IB_GPU_DIRECT_RDMA=n

### Setup and versions
 - OMB 5.7
 - 2 DGX-A100 nodes
 - ucx main branch at `e01f83c94`
 - ompi 4.1.x

### Perf details

D->H | GDR-on | GDR-off | GDR-off, gdr_copy off
-- | -- | -- | --
1 | 0.8 | 0.37 | 0.08
2 | 1.61 | 0.49 | 0.15
4 | 3.2 | 0.97 | 0.31
8 | 6.45 | 1.96 | 0.62
16 | 12.83 | 5.95 | 1.23
32 | 25.86 | 11.81 | 2.4
64 | 51 | 23.09 | 4.86
128 | 102.12 | 47.55 | 9.71
256 | 206.16 | 53.52 | 19.36
512 | 411.86 | 76.94 | 38.63
1024 | 459.78 | 66.2 | 70.93
2048 | 923.73 | 63.72 | 141.22
4096 | 2016.97 | 60.54 | 276.43
8192 | 4077.63 | 60.1 | 537.13
16384 | 8098.62 | 48.37 | 577.55
32768 | 14715.16 | 58.46 | 595.5
65536 | 20535.22 | 59.09 | 603.84
131072 | 22982.25 | 58.38 | 605.65
262144 | 23771.62 | 59.87 | 606.59
524288 | 24009.36 | 61.23 | 606.27
1048576 | 24456.18 | 61.14 | 607.93
2097152 | 24491.57 | 60.92 | 610.43
4194304 | 24548.16 | 60.95 | 618.31

H->D | GDR-on | GDR-off
-- | -- | --
1 | 0.89 | 0.89
2 | 1.85 | 1.84
4 | 3.69 | 3.65
8 | 7.39 | 7.36
16 | 14.81 | 14.69
32 | 27.67 | 27.46
64 | 55.32 | 54.74
128 | 109.02 | 108.09
256 | 214.79 | 212.77
512 | 401.79 | 395.73
1024 | 456.7 | 145.38
2048 | 914.8 | 292.63
4096 | 1827.41 | 596.27
8192 | 3649.03 | 1265.08
16384 | 7275.56 | 2459.9
32768 | 13330.78 | 4308.6
65536 | 15688.5 | 6173.12
131072 | 17255.71 | 7861.05
262144 | 18974.66 | 9113.75
524288 | 22534.91 | 9930.52
1048576 | 22927.85 | 10022.45
2097152 | 23092.96 | 10117.49
4194304 | 23948.9 | 10963.04

D->D | GDR-on | GDR-off
-- | -- | --
1 | 0.79 | 0.36
2 | 1.58 | 0.48
4 | 3.19 | 0.96
8 | 6.41 | 1.93
16 | 12.76 | 5.73
32 | 25.1 | 11.48
64 | 50.36 | 22.68
128 | 101.15 | 46.15
256 | 196.61 | 53.56
512 | 393.21 | 80.66
1024 | 454.89 | 87.47
2048 | 909.7 | 175.24
4096 | 1815.37 | 352.26
8192 | 3640.83 | 740.2
16384 | 7250.61 | 1539.04
32768 | 14282.99 | 2996.62
65536 | 20190.03 | 5084.14
131072 | 22729.61 | 8246.43
262144 | 23720.46 | 11431.41
524288 | 24147.96 | 16154.14
1048576 | 24439.15 | 16503.83
2097152 | 24559.56 | 16278.93
4194304 | 24623.2 | 16687.72

![am-bcopy-bw](https://user-images.githubusercontent.com/3201794/105890782-a320da00-5fc4-11eb-8c4c-72c49612e658.png)
![am-bcopy-cpu-usage](https://user-images.githubusercontent.com/3201794/105890786-a4ea9d80-5fc4-11eb-8701-655604b89092.png)

**Comment by Akshay-Venkatesh** [comment]
cc @yosefe @bureddy @abellina

**Comment by bureddy** [comment]
@Akshay-Venkatesh  can you try https://github.com/openucx/ucx/pull/6208

**Comment by bureddy** [comment]
another WA is `-x UCX_RNDV_PIPELINE_SEND_THRESH=0`

**Comment by bureddy** [comment]
@Akshay-Venkatesh can you try #6208  confirm if this resolves the issue?

**Comment by Akshay-Venkatesh** [comment]
@bureddy The message range between 1k and 2MB is much better with #6208 but 4MB (with osu_bw D H) seems to hang (tried with -x 0 -i 1 to run just one iteration where it still hangs).
