### ISSUE TITLE
Latency not expected when using ucx？

### ISSUE THREAD

**Issue by haipeng31** [openucx/ucx#6242]
I write a test code using ucx which just send req and receive response, and see the latency，In my test machines，The result is about 60us，This is not expected，The test result i use ib_send_lat is less than 10us。

my test code is here: [https://github.com/haipeng31/rdma_test/blob/main/main.cpp](test code)

UCX_NET_DEVICES=mlx5_bond_0:1
UCX_TLS=all

ib_send_lat:
---------------------------------------------------------------------------------------
                    Send Latency Test
 Dual-port       : OFF		Device         : mlx5_bond_0
 Number of qps   : 1		Transport type : IB
 Connection type : RC		Using SRQ      : OFF
 RX depth        : 512
 Mtu             : 1024[B]
 Link type       : Ethernet
 GID index       : 3
 Max inline data : 236[B]
 rdma_cm QPs	 : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
 #bytes #iterations    t_min[usec]    t_max[usec]  t_typical[usec]    t_avg[usec]    t_stdev[usec]   99% percentile[usec]   99.9% percentile[usec] 
Conflicting CPU frequency values detected: 2428.573000 != 3004.218000. CPU Frequency is not max.
Conflicting CPU frequency values detected: 1648.383000 != 2166.102000. CPU Frequency is not max.
 2       1000          5.43           7.90         5.84     	       5.83        	0.14   		6.12    		7.90   
---------------------------------------------------------------------------------------

My problems is how i make sure which transport i am using when using ucx？And How can I make sure where the 60us latency use?

**Comment by yosefe** [comment]
@haipeng can you try measuring with "ucx_perftest -t tag_lat" ? see more details in https://github.com/openucx/ucx/wiki/Performance-measurement
Or, modify your example code to run multiple iterations? Since it's expected that the first iteration could be somewhat slower due to warmup and lazy initialization

**Comment by haipeng31** [comment]
> @haipeng can you try measuring with "ucx_perftest -t tag_lat" ? see more details in https://github.com/openucx/ucx/wiki/Performance-measurement
> Or, modify your example code to run multiple iterations? Since it's expected that the first iteration could be somewhat slower due to warmup and lazy initialization

ucx_perftets -t tag_lat result is about 5us，this latency include send and receive?

**Comment by yosefe** [comment]
- ucx_perftest tag_lat shows half round trip time
- can check the difference between your code and perftest by `perf top -p <pid>` monitoring command

**Comment by haipeng31** [comment]
> * ucx_perftest tag_lat shows half round trip time
> * can check the difference between your code and perftest by `perf top -p <pid>` monitoring command

@yosefe thanks for you answers, they helps a lot
