### ISSUE TITLE
Differences between short, bcopy, zcopy?

### ISSUE THREAD

**Issue by haipeng31** [openucx/ucx#6293]
No concrete descriptions about these three types of memory in documents, can anyone compare them in details, and when using, which one should I use, give some examples?

**Comment by brminich** [comment]
@haipeng31, there is some decription in https://github.com/openucx/ucx/blob/master/docs/source/faq.md
```
In terms of communication APIs, UCT defines interfaces for immediate (short), buffered copy-and-send (bcopy), and zero- copy
(zcopy) communication operations. The short operations are optimized for small messages that can be posted and completed in
place. The bcopy operations are optimized for medium size messages that are typically sent through a so- called bouncing-
buffer. Finally, the zcopy operations expose zero-copy memory-to-memory communication semantics.
```

**Comment by haipeng31** [comment]
> @haipeng31, there is some decription in https://github.com/openucx/ucx/blob/master/docs/source/faq.md
> 
> ```
> In terms of communication APIs, UCT defines interfaces for immediate (short), buffered copy-and-send (bcopy), and zero- copy
> (zcopy) communication operations. The short operations are optimized for small messages that can be posted and completed in
> place. The bcopy operations are optimized for medium size messages that are typically sent through a so- called bouncing-
> buffer. Finally, the zcopy operations expose zero-copy memory-to-memory communication semantics.
> ```

@brminich already seen these， but still can't understand。bcopy, copy the thing want to send to a buffer, and then send the buffer？zcopy，directly send without copy，short, don't know what does it mean。In my opinion，zcopy is with best performance because it doesn't do copy，then In what situation should I use bcopy rather than zcopy，And what does short really mean, can give some examples?

**Comment by shamisp** [comment]
@haipeng31 before you investigate send protocols it is important to understand completion semantic that UCX and many other networking libraries use. Send or put operation is completed when the the source buffer is re-usable. For very small buffers it is efficient to use short send which in the most optimal case will copy the data from the source buffer to the buffer on the NIC. Bcopy will copy to internal pre-pregistered (specially prepared buffers for interception with NIC), and the bcopy has to register and send the data directly.  There are multiple publication on the subject, like this once that provides overview of some of the protocols http://mvapich.cse.ohio-state.edu/static/media/publications/abstract/liuj.pdf . The protocols that UCX is uses are similar but a bit more sophisticated due various low level optimizations, etc.

**Comment by shamisp** [comment]
@haipeng31 Can we close this one ? thanks !

**Comment by haipeng31** [comment]
> @haipeng31 Can we close this one ? thanks !

sorry forget about it.
