### ISSUE TITLE
ucx rpmbuild failed with error of invalid rpath 

### ISSUE THREAD

**Issue by Di0gen** [openucx/ucx#637]
Hi,
The rpmbuild of ucx project failed.
Reproducing:  run contrib/test_jenkins.sh in your working directory.

Error:
make[1]: Leaving directory `/.autodirect/mtrswgwork/eugene/ucx/build-test/ucx-1.0.1254'
- mkdir -p /labhome/eugene/workspace/ucx/build-test/_rpm/etc/ld.so.conf.d/
- echo /opt/ucx/lib
- mkdir -p /labhome/eugene/workspace/ucx/build-test/_rpm/usr/lib64/pkgconfig
- cp ucx.pc /labhome/eugene/workspace/ucx/build-test/_rpm/usr/lib64/pkgconfig
- /usr/lib/rpm/check-rpaths /usr/lib/rpm/check-buildroot
  *******************************************************************************
  *
- WARNING: 'check-rpaths' detected a broken RPATH and will cause 'rpmbuild'
-          to fail. To ignore these errors, you can set the '$QA_RPATHS'
-          environment variable which is a bitmask allowing the values
-          below. The current value of QA_RPATHS is 0x0000.
  *
-    0x0001 ... standard RPATHs (e.g. /usr/lib); such RPATHs are a minor
-               issue but are introducing redundant searchpaths without
-               providing a benefit. They can also cause errors in multilib
-               environments.
-    0x0002 ... invalid RPATHs; these are RPATHs which are neither absolute
-               nor relative filenames and can therefore be a SECURITY risk
-    0x0004 ... insecure RPATHs; these are relative RPATHs which are a
-               SECURITY risk
-    0x0008 ... the special '$ORIGIN' RPATHs are appearing after other
-               RPATHs; this is just a minor issue but usually unwanted
-    0x0010 ... the RPATH is empty; there is no reason for such RPATHs
-               and they cause unneeded work while loading libraries
-    0x0020 ... an RPATH references '..' of an absolute path; this will break
-               the functionality when the path before '..' is a symlink
  *
  *
- Examples:
- \- to ignore standard and empty RPATHs, execute 'rpmbuild' like
-   $ QA_RPATHS=$[ 0x0001|0x0010 ] rpmbuild my-package.src.rpm
- \- to check existing files, set $RPM_BUILD_ROOT and execute check-rpaths like
-   $ RPM_BUILD_ROOT=<top-dir> /usr/lib/rpm/check-rpaths
  *
  *******************************************************************************
  ERROR   0002: file '/opt/ucx/lib/libucs.so.2.0.1' contains an invalid rpath '/opt/ucx/lib' in [/opt/ucx/lib]
  ERROR   0002: file '/opt/ucx/lib/libuct.so.2.0.1' contains an invalid rpath '/opt/ucx/lib' in [/opt/ucx/lib]
  ERROR   0002: file '/opt/ucx/lib/libucp.so.2.0.1' contains an invalid rpath '/opt/ucx/lib' in [/opt/ucx/lib]
  ERROR   0002: file '/opt/ucx/bin/ucx_info' contains an invalid rpath '/opt/ucx/lib' in [/opt/ucx/lib]
  ERROR   0002: file '/opt/ucx/bin/ucx_perftest' contains an invalid rpath '/opt/ucx/lib' in [/opt/ucx/lib]
  error: Bad exit status from /var/tmp/rpm-tmp.sXyG2h (%install)

**Comment by igor-ivanov** [comment]
@Di0gen 
Checked on 
`e3b0c18 Merge pull request #661 from hppritcha/topic/progress_gni_properly`
launched
`contrib/test_jenkins.sh` from source code location
no issues were observed
```
make[1]: Leaving directory `/hpc/home/USERS/ivanovi/prj/ii-ucx/build-test/ucx-1.0.1400'
+ mkdir -p /hpc/home/USERS/ivanovi/prj/ii-ucx/build-test/_rpm/etc/ld.so.conf.d/
+ echo /opt/ucx/lib
+ mkdir -p /hpc/home/USERS/ivanovi/prj/ii-ucx/build-test/_rpm/usr/lib64/pkgconfig
+ cp ucx.pc /hpc/home/USERS/ivanovi/prj/ii-ucx/build-test/_rpm/usr/lib64/pkgconfig
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-python-bytecompile
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: ucx-1.0.1400-1.x86_64
Finding  Provides: /usr/lib/rpm/redhat/find-provides
Finding  Requires: /hpc/home/USERS/ivanovi/prj/ii-ucx/build-test/ucx-1.0.1400/find-requires.sh
Provides: ucx libucm.so.0()(64bit) libucp.so.2()(64bit) libucs.so.2()(64bit) libuct.so.2()(64bit) pkgconfig(ucx) = 1.0
Requires(interp): /bin/sh /bin/sh
Requires(rpmlib): rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(VersionedDependencies) <= 3.0.3-1
```

**Comment by shssf** [comment]
@Di0gen , @yosefe 
I got the same test-jenkins.sh issue last time and found workaround for this:
rm ~/.rpmmacros
After this, the test passed well.
