### ISSUE TITLE
A few questions about ucp_tag_send_nb

### ISSUE THREAD

**Issue by haipeng31** [openucx/ucx#6370]
1. does I need to register the buffer(secod argument of ucp_tag_send_nb ) before I invoke ucp_tag_send_nb, if not, Is ucx do it for me?
2. If I invoke two upc_tag_send_nb on same ep one by one，Will these two send requests will be completed in the invoke order？Does it matter with whether I use RC or not?
3. if the message is large, ucx will use rdnv mode, this will lead to larger latency because it contains two send, one for control, one for data，my questions in why ucx use rdnv mode？

**Comment by yosefe** [comment]
1. No, ucx will do it internally
2. They may be completed in a different order, but will be matched in the same order on receiver
3. yes, for large messages the latency of the control message is outweighed by the benefit of using zero-copy on the receiver

**Comment by shamisp** [comment]
adding to 3. We measure end to end (memory to memory latency). With RNDV you send additional messages on wire but avoid memory copy. The latency of memory copy is >> wire latency for the large messages. As a result RNDV protocol has better latency even with multiple messages on the wire.

**Comment by haipeng31** [comment]
> adding to 3. We measure end to end (memory to memory latency). With RNDV you send additional messages on wire but avoid memory copy. The latency of memory copy is >> wire latency for the large messages. As a result RNDV protocol has better latency even with multiple messages on the wire.

@shamisp 
1. Does the extra memory copy you mean is come from send/receive mode compared to rdma write(send/receive mode has one more memory copy than rdma write on the receive side)，and is there any article give the concrete performance data?
2. if message size larger than zcopy_thresh, ucp will use zcopy rather than bcopy，The difference between bcopy and zcopy is that bcopy copy the data to a preregister buffer from memory pool and send that buffer，zcopy doesn't do the copy, and send the data with multiple ibv_sge, Is that because send with buffer list is slower than just one buffer, and the same some performance data?

**Comment by haipeng31** [comment]
> 1. No, ucx will do it internally
> 2. They may be completed in a different order, but will be matched in the same order on receiver
> 3. yes, for large messages the latency of the control message is outweighed by the benefit of using zero-copy on the receiver

@yosefe for the second question, I see in RoceV2 wiki：
the RoCEv2 specification requires that packets with the same UDP source port and the same destination address must not be reordered

Which say packet order will be same with send order, but ucx ucp_tag_send_nb may be completed in different order, is this because a ucp_tag_send_nb may be implemented with multiple low level sends in hardware(for example rdnv mode?)

**Comment by yosefe** [comment]
> Which say packet order will be same with send order, but ucx ucp_tag_send_nb may be completed in different order, is this because a ucp_tag_send_nb may be implemented with multiple low level sends in hardware(for example rdnv mode?)

Yes, that is right

**Comment by shamisp** [comment]
> > adding to 3. We measure end to end (memory to memory latency). With RNDV you send additional messages on wire but avoid memory copy. The latency of memory copy is >> wire latency for the large messages. As a result RNDV protocol has better latency even with multiple messages on the wire.
> 
> @shamisp
> 
> 1. Does the extra memory copy you mean is come from send/receive mode compared to rdma write(send/receive mode has one more memory copy than rdma write on the receive side)，and is there any article give the concrete performance data?
> 2. if message size larger than zcopy_thresh, ucp will use zcopy rather than bcopy，The difference between bcopy and zcopy is that bcopy copy the data to a preregister buffer from memory pool and send that buffer，zcopy doesn't do the copy, and send the data with multiple ibv_sge, Is that because send with buffer list is slower than just one buffer, and the same some performance data?

1. Depends on you system. You actually can run ucx_perftest and measure the tradeoffs (BW/LAT) for various message sizes and protocols. There are tons of publications from MPI community in this space, for example:
 *  http://nbcl.cse.ohio-state.edu/static/media/publications/abstract/koop-ipdps08.pdf
2. There are many tradeoff in these protocols that we consider. bcopy has extra memory copy but it does not have to register memory, so the send operation completed locally the moment user buffer is copied to the buffer. Zero copy has to register the memory first, which has its own cost (we have many optimizations there are well) but does not do memory copy. It also has to wait for network completion to signal local completion of the operation.

**Comment by haipeng31** [comment]
> > > adding to 3. We measure end to end (memory to memory latency). With RNDV you send additional messages on wire but avoid memory copy. The latency of memory copy is >> wire latency for the large messages. As a result RNDV protocol has better latency even with multiple messages on the wire.
> > 
> > 
> > @shamisp
> > 
> > 1. Does the extra memory copy you mean is come from send/receive mode compared to rdma write(send/receive mode has one more memory copy than rdma write on the receive side)，and is there any article give the concrete performance data?
> > 2. if message size larger than zcopy_thresh, ucp will use zcopy rather than bcopy，The difference between bcopy and zcopy is that bcopy copy the data to a preregister buffer from memory pool and send that buffer，zcopy doesn't do the copy, and send the data with multiple ibv_sge, Is that because send with buffer list is slower than just one buffer, and the same some performance data?
> 
> 1. Depends on you system. You actually can run ucx_perftest and measure the tradeoffs (BW/LAT) for various message sizes and protocols. There are tons of publications from MPI community in this space, for example:
> 
> * http://nbcl.cse.ohio-state.edu/static/media/publications/abstract/koop-ipdps08.pdf
> 
> 1. There are many tradeoff in these protocols that we consider. bcopy has extra memory copy but it does not have to register memory, so the send operation completed locally the moment user buffer is copied to the buffer. Zero copy has to register the memory first, which has its own cost (we have many optimizations there are well) but does not do memory copy. It also has to wait for network completion to signal local completion of the operation.

@shamisp thanks for your reply。
another question, if created endpoint is rc, and i invoke ucp_tag_send_nb to send a message, however, the data I just send may be received by not the corresponding endpoint(If i sent tag to 0, and receive request with tag 0)，why It's designed like this?

**Comment by yosefe** [comment]
@haipeng31 the tag matching semantics are designed according to [MPI specification](https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf)
According to UCX semantics, the receive is per worker (not per endpoint), and the receiver tag/mask has to match the sender tag. As long as it doesn't match, the received message will be queued internally.

**Comment by haipeng31** [comment]
> @haipeng31 the tag matching semantics are designed according to [MPI specification](https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf)
> According to UCX semantics, the receive is per worker (not per endpoint), and the receiver tag/mask has to match the sender tag. As long as it doesn't match, the received message will be queued internally.

I got it, thanks a lot.
