### ISSUE TITLE
[mtt] fail sum_short on ucx-emulation

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#6547]
Configuration
```
OMPI: 4.1.1rc1
MOFED: MLNX_OFED_LINUX-5.1-2.5.8.0
Module: hpcx-gcc (2021-03-23)
Test module: none
Nodes: jazz x10 (ppn=28(x10), nodelist=jazz[10-11,17-20,24-25,27-28])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/shmem/20210323_220343_519_30875_jazz10.swx.labs.mlnx/html/test_stdout_DfxhXN.txt
 
Cmd:
`/hpc/local/benchmarks/daily/next/2021-03-23/hpcx-gcc-redhat7.6/ompi/bin/oshrun -np 280 --display-map --bind-to core -mca oshmem_proc_group_cache_size 10000 -mca sshmem ucx -mca atomic ucx -mca coll '^hcoll' -mca coll_hcoll_enable 0 -mca spml ucx -mca pml ucx -x UCX_HANDLE_ERRORS=bt -x UCX_TLS=ud_x -x UCX_UD_TIMEOUT=10m -x UCX_NET_DEVICES=mlx5_2:1 -x UCX_UNIFIED_MODE=y --map-by node --mca scoll_basic_barrier_alg 2 --mca scoll_basic_broadcast_alg 1 --mca scoll_basic_collect_alg 0 --mca scoll_basic_reduce_alg 4 -x SHMEM_SYMMETRIC_HEAP_SIZE=128M /hpc/mtr_scrap/users/mtt/scratch/shmem/20210323_220343_519_30875_jazz10.swx.labs.mlnx/installs/kact/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour -o5 --task=reduce`
 
Output:
```sh
[trace] tc..: #00 ...TC: sum_short TI #6 result: FAIL
FAIL   reduce     sum_short      shmem_short_sum_to_all(): Calculates SUM on symmetric arrays of 'short' datatype over the active set of PEs.
[trace] te..: #00 Memory Usage (MB):	before: 706 resident: 255	after: 706 resident: 255	difference: +0 resident: +0

```

**Comment by brminich** [comment]
can repro with 
```
oshrun -np 257  --bind-to core  -mca sshmem ucx -mca atomic ucx -mca coll '^hcoll'  -mca spml ucx -mca pml ucx  -x UCX_NET_DEVICES=mlx5_2:1 --map-by node -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M   /.autodirect/mtrswgwork/mikhailb/git/oshmem_verifier/verifier/oshmem_test exec --no-colour -o5 --task=reduce:tc27
```

**Comment by brminich** [comment]
the problem is short values overflow in `shmem_short_sum_to_all`
