### ISSUE TITLE
 How to choose UCP context features?

### ISSUE THREAD

**Issue by Adahai** [openucx/ucx#6556]
hi:
   I have got that there are four kinds of feature， such as  'a': atomic operations, 'r' : remote memory access, 't' : tag matching, 'w' :    wakeup. and i want to  Find out more about how they work?

  Looking forward to your answer
   best wishes!

**Comment by shamisp** [comment]
@Adahai This enum defines the features that you can pass as a parameter during context creation https://github.com/openucx/ucx/blob/b72fec8df4ac1ab14e5a3392183215164c7f07cf/src/ucp/api/ucp.h#L140

**Comment by Adahai** [comment]
@shamisp That help me a lot ,  thank you very much.

**Comment by Adahai** [comment]
@shamisp   It helped me a lot to understand how these enums work. Thank you!
So, I want to go a little bit further to look at each of these ENUMs and what is their general function in UCX data transfer?   What are the similarities and differences between these features?

**Comment by Adahai** [comment]
@shamisp   It helped me a lot to understand how these enums work. Thank you!
So,  I want to go a little bit further to look at each of these ENUMs and what is their general function in UCX data transfer?   What are the similarities and differences between these features?

**Comment by shamisp** [comment]
@Adahai each one of the enum values represents a group of communication operations. Each one of the groups has different communication semantics. The semantics is documented as part of our API documentation which can be found here: https://openucx.github.io/ucx/api/v1.10/html/group___u_c_p___c_o_m_m.html

**Comment by Adahai** [comment]
@shamisp thank you very much!

**Comment by shamisp** [comment]
Closing for now. Feel free reopen if you have additional questions on the subject.
