### ISSUE TITLE
UCX_ZCOPY_THRESH Doesn't Work On MLX5 Interfaces

### ISSUE THREAD

**Issue by Seth5141** [openucx/ucx#6592]
### Describe the bug
When setting UCX_ZCOPY_THRESH=0, one would expect it to work for both put and get operations, however, at least on mlx5_rc endpoints, this is not the case. It seems there is some kind of optimization in place to take advantage of inline data in puts and gets.

This is important for applications attempting to use CUDA memory with mlx5 but without cuda_copy. The bcopy operations cause an insufficient privileges error.

My hope is that there is a way to configure UCX_ZCOPY_THRESH to be 0 on both puts and gets on MLX5.

### Steps to Reproduce
set UCX_ZCOPY_THRESH=0
Perform any gets < 64 bytes
See them get pushed through bcopy.

### Setup and versions
ucx 1.10

### Additional information (depending on the issue)
This appears to be caused by a configuration value in the ib_iface struct 'min_zcopy'.
iface_attr->cap.get.min_zcopy = iface->super.config.max_inl_cqe[UCT_IB_DIR_TX] + 1;
which in turn is set by 'inl':
iface->config.max_inl_cqe[dir] = (inl > 0) ? (dv_attr.cqe_size / 2) : 0;
'inl' seems to be controllable through a uct interface configuration:
  {"TX_INLINE_RESP", "0",
   "Bytes to reserve in send WQE for inline response. Responses which are small\n"
   "enough, such as of atomic operations and small reads, will be received inline.",
   ucs_offsetof(uct_ib_iface_config_t, inl[UCT_IB_DIR_TX]), UCS_CONFIG_TYPE_MEMUNITS},

However, as you can see here, the default value is 0, and I can't find anywhere else in the source where this value is changed to something else.

Mostly, I would like to know if there is a specific reason for the min_zcopy rule, and if there is a way to decrease the inl argument to 0 to avoid that limitation for NVSHMEM and other applications hoping to do small rma operations on GPU memory without enabling the cuda_copy transport.

Thanks in advance for any info,

Seth

**Comment by Seth5141** [comment]
@yosefe Perfect, thanks! Setting UCX_RX_TX_INLINE_RESP directly through the environment worked like a charm.

One follow up question. We are using the ucp APIs in our transport. Is it possible to query and modify the uct interface configuration while using UCP APIs, or is it necessary to rely on the environment to set that variable in this case?

It's not a big deal either way, I can push setting this environment variable to some of our other code, but I'd like to use ucx native APIs if possible.

Either way, closing this bug as you have provided the workaround.

Thanks,

Seth

**Comment by yosefe** [comment]
Unfortunately, at present, the UCP API does not support forwarding configuration to UCT layer, but it's something that makes sense to add.
