### ISSUE TITLE
Question regarding the ucp_client_server example

### ISSUE THREAD

**Issue by huangvincent170** [openucx/ucx#6632]
I see in the [ucx quick start guide](https://www.openucx.org/documentation/) it says the client_server example should use a local IPoIB interface. Does the example also work with remote connections?

I have two devices on the same network, but attempting to run the server on one and the client on another fails with the following message:

server:
```
$ ifconfig
ib0       Link encap:UNSPEC  HWaddr A0-00-02-20-FE-80-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.12.62  Bcast:192.168.12.255  Mask:255.255.255.0
          inet6 addr: fe80::225:90ff:ff1c:8cb1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:2044  Metric:1
          RX packets:200 errors:0 dropped:0 overruns:0 frame:0
          TX packets:114 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:256
          RX bytes:13300 (13.3 KB)  TX bytes:8656 (8.6 KB)
$ ./ucp_client_server
server is listening on IP 0.0.0.0 port 13337
Waiting for connection...
```

client:
```
$ ./ucp_client_server -a 192.168.12.62 -p 13337
error handling callback was invoked with status -6 (Destination is unreachable)
unable to send UCX message (Destination is unreachable)
client failed on iteration #1
```

I can ping the server just fine using ibping.

Apologies if this is a rather basic question, as I am new to using ucx.

**Comment by yosefe** [comment]
In general, the usage is correct. However it's possible the IPoIB is not setup correctly.
Does "ping 192.168.12.62 " work from client's machine?

**Comment by huangvincent170** [comment]
Thank you for the response!

Yes, ping seems to work from the client's machine.

```
$ ping 192.168.12.62
PING 192.168.12.62 (192.168.12.62) 56(84) bytes of data.
64 bytes from 192.168.12.62: icmp_seq=1 ttl=64 time=0.290 ms
64 bytes from 192.168.12.62: icmp_seq=2 ttl=64 time=0.174 ms
64 bytes from 192.168.12.62: icmp_seq=3 ttl=64 time=0.173 ms
64 bytes from 192.168.12.62: icmp_seq=4 ttl=64 time=0.171 ms
64 bytes from 192.168.12.62: icmp_seq=5 ttl=64 time=0.167 ms
64 bytes from 192.168.12.62: icmp_seq=6 ttl=64 time=0.170 ms
64 bytes from 192.168.12.62: icmp_seq=7 ttl=64 time=0.170 ms
^C
--- 192.168.12.62 ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 5999ms
rtt min/avg/max/mdev = 0.167/0.187/0.290/0.045 ms
```

**Comment by alinask** [comment]
Hi @huangvincent170 ,
Do you have MLNX_OFED installed?
Does ib_write_bw work between your client and server?
Can you please send the output of ibdev2netdev on both sides and ifconfig of the client as well?
Also, since you are using the default port that the server is using, no need to specify it in the client's command line.

**Comment by huangvincent170** [comment]
1. Yes, I believe I have MLNX_OFED installed on both the server and the client.
```
$ ofed_info -s
MLNX_OFED_LINUX-3.4-2.0.0.0:
```

2. ib_write_bw seems to not be working
server:
```
$ ib_write_bw

************************************
* Waiting for client to connect... *
************************************
```
client:
```
$ ib_write_bw 192.168.12.62
Couldn't connect to 192.168.12.62:18515
Unable to open file descriptor for socket connection Unable to init the socket connection
```

server ibdev2netdev
```
$ ibdev2netdev
mlx4_0 port 1 ==> ib0 (Up)
```

client ibdev2netdev
```
$ ibdev2netdev
mlx4_0 port 1 ==> ib0 (Up)
```

ifconfig of client:
```
$ ifconfig
ib0       Link encap:UNSPEC  HWaddr A0-00-02-20-FE-80-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.12.63  Bcast:192.168.12.255  Mask:255.255.255.0
          inet6 addr: fe80::225:90ff:ff1c:8db1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:2044  Metric:1
          RX packets:154 errors:0 dropped:0 overruns:0 frame:0
          TX packets:288 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:256
          RX bytes:11564 (11.5 KB)  TX bytes:20884 (20.8 KB)
```

**Comment by alinask** [comment]
Thanks for the info!
ib_write_bw should be working before attempting to use UCX.
Seems like something is misconfigured in your setup. I will consult with our dev-ops to check what could be the problem.
Btw, your MLNX_OFED is of an old version. Would you consider to upgrade?

**Comment by huangvincent170** [comment]
Thank you so much for the help!

**Comment by alinask** [comment]
I see. ib_write_bw doesn't work without -z or -R ?
Which UCX version are you using and where is it from?
Did you compile it? If so, what was your configure command line?

**Comment by huangvincent170** [comment]
I am using ucx version 1.10.0, which I got from
```
wget https://github.com/openucx/ucx/releases/download/v1.10.0/ucx-1.10.0.tar.gz
```
I also tried directly cloning this repo and following the build instructions listed in the readme.

Sorry, I'm not too sure what you mean by configure command line.
I used the configure-release script, if that's is what you're asking.
```
./contrib/configure-release --prefix=$PWD/install
```

**Comment by alinask** [comment]
Can you please add UCX_LOG_LEVEL=diag on each side (client and server) when running ucp_client_server and attach the logs?
```
UCX_LOG_LEVEL=diag ./ucp_client_server
UCX_LOG_LEVEL=diag ./ucp_client_server -a 192.168.12.62
```

ib_write_bw doesn't work without -z or -R ?

**Comment by huangvincent170** [comment]
Yes, ib_write_bw does not work when I do not include either the -z or -R flag.

server:
```
$ UCX_LOG_LEVEL=diag ./ucp_client_server
[1618142081.225075] [jedi062:10278:0]         uct_cm.c:236  UCX  DIAG  configure value 2147483647 is greater than the max_value 128. using max_value
server is listening on IP 0.0.0.0 port 13337
Waiting for connection...
```

client:
```
$ UCX_LOG_LEVEL=diag ./ucp_client_server -a 192.168.12.62
error handling callback was invoked with status -6 (Destination is unreachable)
unable to send UCX message (Destination is unreachable)
client failed on iteration #1
```

One interesting thing I found was that ucp_client_server does seem to work in version ucx 1.9.0





```

**Comment by alinask** [comment]
What is the value you have set in `/proc/sys/net/core/somaxconn` ?
If it's 128 can you please increase to 15000 on both sides and retest?

Also, what do you have set in `/proc/sys/net/rdma_ucm/max_backlog` ?

**Comment by huangvincent170** [comment]
The initial value of somaxconn was indeed 128, so I changed it to 15000
Server
```
$ cat /proc/sys/net/rdma_ucm/max_backlog
1024
$ cat /proc/sys/net/core/somaxconn
15000
$ UCX_LOG_LEVEL=diag ./ucp_client_server
[1618144430.390850] [jedi062:10457:0]         uct_cm.c:236  UCX  DIAG  configure value 2147483647 is greater than the max_value 15000. using max_value
server is listening on IP 0.0.0.0 port 13337
Waiting for connection...
```
client:
```
$ cat /proc/sys/net/core/somaxconn
15000
$ cat /proc/sys/net/rdma_ucm/max_backlog
1024
$ UCX_LOG_LEVEL=diag ./ucp_client_server -a 192.168.12.62
error handling callback was invoked with status -6 (Destination is unreachable)
unable to send UCX message (Destination is unreachable)
client failed on iteration #1
```

**Comment by yosefe** [comment]
@huangvincent170 can you please run "show_gids" command on each of the machines and post the output?

**Comment by huangvincent170** [comment]
server:
```
$ show_gids
DEV     PORT    INDEX   GID                                     IPv4            VER     DEV
---     ----    -----   ---                                     ------------    ---     ---
mlx4_0  1       0       fe80:0000:0000:0000:0025:90ff:ff1c:8cb1
n_gids_found=1
```

client:
```
$ show_gids
DEV     PORT    INDEX   GID                                     IPv4            VER     DEV
---     ----    -----   ---                                     ------------    ---     ---
mlx4_0  1       0       fe80:0000:0000:0000:0025:90ff:ff1c:8db1
n_gids_found=1
```

**Comment by alinask** [comment]
@huangvincent170 since your MLNX_OFED is pretty old, would you be able to upgrade to MLNX_OFED 4.9 please and retest this?

**Comment by huangvincent170** [comment]
Hello,

After upgrading to MLNX_OFED 4.9, the client_server is still failing with the same error messages.

**Comment by alinask** [comment]
Does ib_write_bw pass? without -z or -R

**Comment by huangvincent170** [comment]
It is still failing with the same error if I do not use -z or -R

**Comment by alinask** [comment]
@huangvincent170 Can you please try running iperf?
Does it work?

On the server side:
```
iperf -s
```

On the client side:
```
iperf -t 1000 -i 5  -c 192.168.12.62 
```

Can install iperf with 'yum install iperf'

**Comment by alinask** [comment]
@huangvincent170 seems that your setup is misconfigured. iperf is not related to MLNX_OFED or to UCX and when there is correct connectivity among the hosts, it should pass.
Can you please contact your network administrator for this?

**Comment by huangvincent170** [comment]
Resolved

**Comment by alinask** [comment]
@huangvincent170 Could you please share what was the problem?
