### ISSUE TITLE
What is the (current) relationship to libfabric?

### ISSUE THREAD

**Issue by ingomueller-net** [openucx/ucx#6647]
The [FAQ](http://openucx.github.io/ucx/faq.html) and various copies of it suggest that UCX uses libfabric:

> UCX [...] relies on vendors provided user level drivers including [...] libfabrics

> UCT relies on low-level drivers provided by vendors such as [...] libfabrics, etc.

> UCX [is] performance portable because a single implementation (in Open MPI or OpenSHMEM) will work efficiently on multiple interconnects. (e.g. uGNI, Verbs, libfabrics, etc).

However, libfabric does not seem to be a dependency, the source code does not include `ofi.h` anywhere, and a [reply to a previous issue](https://github.com/openucx/ucx/issues/5927#issuecomment-730525289) was answered with the following:

> There is no relation between the two project[s] [libfabric and UTC]. UCX community works in close collaboration with rdma-core community and we are complementary API to the low-level Verbs API developed by rdma core.

What is correct? I suppose that libfabric is not used by UCX (anymore?), in which case the FAQ should be updated/clarified.

**Comment by shamisp** [comment]
Indeed the FAQ is a bit outdated. BTW, our up to date FAQ hosted here https://openucx.readthedocs.io/en/master/faq.html but it has the same question/answer. 

For NICs with network offload capabilities we use Linux RDMA subsystem ([rdma-core](https://github.com/linux-rdma/rdma-core)) directly. We closely collaborate rdma-core community on interface requirements, etc.  Vendors that work with our community expose their network devices with RDMA subsystem so we have never had the need to implement OFI transport layer. Nevertheless, users and developers are more than welcome to contribute additional transport layers to UCX. For example ugni and xpmem transports was contributed back in the day by ORNL :)

**Comment by ingomueller-net** [comment]
Thanks, @shamisp, for confirming my impression. What is the up-to-date relationship between UCX and libfabric, then? Is it fair to say the UCX, or at least UCT, have similar goals in that they offer a low-level but hardware-agnostic interface for point-to-point communication (whereas rdma-core is even lower-level and RDMA-specific)?

**Comment by shamisp** [comment]
@ingomueller-net I also cannot comment about 3rd party project goals, you would have to check it with their community.  

Nevertheless, I can comment about UCT - unified communication transport API.  UCT is a relatively thin layer that abstracts a very simple set of basic operations (send/receive, one-sided, atomics, etc.). Typically, implementation of UCT implements a one-to-one mapping from UCT API to device driver (verbs, tcp, CUDA, ROCM, shared memory, etc.). If some operation is not available in HW, it is not implemented in UCT. The assumption here that the upper layer (for example UCP) will implement operation emulation or will use some other algorithm if the operation is not available.  The term  "hardware-agnostic" is not well defined and  very often misused.  I define "hardware-agnostic" as an interface that you can use without making assumptions about the underlying hardware. For example, if my code has to query what features are supported in hardware and based on this decide to execute certain operations/algorithms or not is NOT considered a hardware-agnostic interface. In this sense, UCT is not a hardware-agnostic API - it is a very simple and lightweight abstraction that is used by UCP for construction network protocols. UCT also greatly simplifies the integration of new transport - I implement the initial revision of XPMEM shared memory just in a few hours.  I think UGNI UCT took us about a week. In the early days of UCT, we used to have user-space driver components in UCT. We worked with rdma-core community to address our need and eventually the drives specific logic moved there. UCT is also used by 3rd party libraries that need a convenient abstraction for the implementation of their own custom network protocols. One such example is the Huawei UGC group communication library. There other projects that use UCT directly.

UCP is a hardware-agnostic layer - the application can invoke any of the API function and there is no need to query if the hardware supports it or where the memory resided (CPU or GPU) - the library does it best effort to auto-detect the hardware and select best possible channel (or channels) and protocols for communication. The library takes into account node hierarchy, PCIe layout, etc.

**Comment by ingomueller-net** [comment]
@shamisp Thank you so much, that was really helpful!

My specific questions are now answered. I am leaving the issue open as a reminder that the FAQs should be updated.

**Comment by shamisp** [comment]
Closing. Fixed in #6700
