### ISSUE TITLE
UCX ERROR failed to unpack remote key from remote 

### ISSUE THREAD

**Issue by Blopeur** [openucx/ucx#6651]
### Describe the bug
getting SIGSEV with UCX error failed to unpack remote key
Any idea what would be the reason for it? 

### Steps to Reproduce
![image (4)](https://user-images.githubusercontent.com/494959/114547772-c3247900-9c56-11eb-92bf-10e4023ddade.png)
 
Server : loop : get direct buffer, register memory, get rkey , send key + address + size
Client : get rkey + size + address, unpack rkey , remote get .. , when success we send a message to deregister the memory to the remote side

At some point ( always same data slot) we get the error 

- **Any UCX environment variables used**

### Setup and versions
OS: ubuntu 19.04
UCX: 1.9 

### Additional information (depending on the issue)

Core dump : 

[hs_err_pid810 (1).log](https://github.com/openucx/ucx/files/6303468/hs_err_pid810.1.log)

**Comment by petro-rudenko** [comment]
Does it reproduce with ucx-1.10 or master? Can you please check with master and `UCX_TLS=^posix` to see whether it's a posix transport issue. Meanwhile, i'll try to reproduce this scenario with our tests.

**Comment by petro-rudenko** [comment]
Do you set something as `UCX_POSIX_DIR` ?

**Comment by Blopeur** [comment]
we recompiled the following flag and the error disappeared .... .

./contrib/configure-devel --without-rdmacm --with-java --enable-mt --disable-numa --prefix=$PWD/install
