### ISSUE TITLE
JUCX 1.11 says it's not compatible with UCX 1.10

### ISSUE THREAD

**Issue by abellina** [openucx/ucx#6694]
I've noticed this in the logs. I know it is a warning, but the way it's stated makes me believe I am doing something wrong, where JUCX 1.11 and UCX 1.10 are actually compatible.

```
 ucp_context.c:1585 UCX  WARN  UCP version is incompatible, required: 1.11, actual: 1.10 (release 0 /usr/lib/libucp.so.0.0.0)
```

Filing this mostly for visibility, it's not a functional issue. Just trying to figure out if it's best to change the wording, or to perhaps widen the check so that JUCX 1.11+ can be flagged as compatible against different versions of the native library.

@petro-rudenko fyi

**Comment by petro-rudenko** [comment]
So JUCX is backward compatible. You can run jucx, built with ucx-1.11 with UCX-1.10. This warning is useful sometimes, when we miss with ucx path and it uses some system path.

**Comment by yosefe** [comment]
i would recommend using such a combination (jucx v1.11+ucx v1.10) only for testing purposes in a controlled environment, and ignore this warning. For general use it would be safer to use v1.11 snapshort+jucx v1.11
@abellina do you think I would help to have ucx snapshots (say, src/binary rpm) same as we have for Java?

**Comment by abellina** [comment]
> @abellina do you think I would help to have ucx snapshots (say, src/binary rpm) same as we have for Java?

Do you mean publishing to a repository deb/rpms `SNAPSHOT` a nightly that is in-sync with `jucx-[foo]-SNAPSHOT`? Or something that is published with calendar versioning (each night publish something?) I am not sure they would help with this particular issue, but...

In the past we've used something like this for cuDF to triage issues. I.e. it works with the SNAPSHOT 1 month ago, but not with the one 15 days ago, etc., provided that they are published with some sort of minor version and are stored for a period of time. This can be done with building manually, but if there are specific build options that go into the package that could influence the end result, so it's nice to be able to point at artifacts that are failing. 

I could also imagine that CI could use these latest packages, so we are testing with latest and greatest, and with official packaging. So I can see benefits with this.

**Comment by abellina** [comment]
For now, we've added a note to our documentation to say to disregard the WARN on startup. Just FYI. I think this one can be closed then, although not sure if @yosefe wants to keep it open for his other question.
