### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by bkmgit** [openucx/ucx#6714]
### Describe the bug
The website http://www.openucx.org/ seems not to be available

### Steps to Reproduce

Try to view http://www.openucx.org/ in a web browser

### Setup and versions
Not applicable
### Additional information (depending on the issue)
Consider linking to https://openucx.github.io/ucx/  instead

**Comment by yosefe** [comment]
@bkmgit thanks for the report! it's a known issue and being taken care of

**Comment by bkmgit** [comment]
@yosefe Great

**Comment by shamisp** [comment]
@yosefe we shell remove https://openucx.github.io/ucx/.

**Comment by yosefe** [comment]
> @yosefe we shell remove https://openucx.github.io/ucx/.

yes, it's no longer relevant
i suggest replace it by link/redirect to read-the-docs

**Comment by shamisp** [comment]
I think the URL still host the doxygen API, right ?

**Comment by bkmgit** [comment]
Having the site hosted in a git repository makes contributing easy. Please leave the information available until the main site  http://www.openucx.org/ is back up again.

**Comment by shamisp** [comment]
@bkmgit the same website is available here https://openucx.readthedocs.io/en/master/ and can be updated here https://github.com/openucx/ucx/tree/master/docs/source

We will update git website to redirect to  https://openucx.readthedocs.io

**Comment by bkmgit** [comment]
Thanks. Is a contributor agreement still required?

**Comment by shamisp** [comment]
@bkmgit - correct, we require if for any commits to the repo.

**Comment by bkmgit** [comment]
Where can it be found?

**Comment by shamisp** [comment]
@bkmgit on openucx.org which is down now. Once the web server is back I will post the link here. Apologies for inconvenience.

**Comment by shamisp** [comment]
@bkmgit - here we go https://www.openucx.org/license/ .

**Comment by shamisp** [comment]
Website is back !

**Comment by bkmgit** [comment]
Thanks for the prompt response.
