### ISSUE TITLE
Segmentation fault when calling ucp_listener_create using IB-enabled library on non-IB machine

### ISSUE THREAD

**Issue by krakowski** [openucx/ucx#6755]
### Describe the bug

Calling `ucp_listener_create` with a IB-enabled library on a **machine without InfiniBand adapters** leads to a segmentation fault due to a null pointer dereference in [`uct_listener_create`](https://github.com/openucx/ucx/blob/v1.10.0/src/uct/base/uct_cm.c#L210) (`cm` is null here). Debugging this issue I found out that this happens because the [Worker's Connection Manager array contains a null pointer](https://github.com/openucx/ucx/blob/v1.10.0/src/ucp/core/ucp_listener.c#L266-L270).

Disabling all IB-related features during configuration fixes this problem.

```
--with-verbs=no \
--with-rc=no \
--with-ud=no \
--with-dc=no \
--with-mlx5-dv=no \
--with-ib-hw-tm=no \
--with-dm=no \
--with-cm=no \
--with-rdmacm=no \
```

### Steps to Reproduce
- UCX version 1.10.0
- Configured with `contrib/configure-release`

### Setup and versions
- `Linux 5.4.85-1-MANJARO` (x86_64)
- `rdma-core 30.0`

**Comment by krakowski** [comment]
This may also be the cause of issue #6244

**Comment by alinask** [comment]
Hi @krakowski ,
can you please try setting the following environment parameter on both sides (client and server) to see it helps?
UCX_SOCKADDR_TLS_PRIORITY=tcp
(given that you are not setting any other UCX environment parameters)

**Comment by krakowski** [comment]
Hi @alinask,

yes, I can confirm that it works by setting `UCX_SOCKADDR_TLS_PRIORITY=tcp`.

**Comment by alinask** [comment]
Can you please use this environment parameter for UCX v1.10?
We will fix this issue for the next UCX release.
Thanks!

**Comment by abellina** [comment]
I just hit this also, and was about to file an issue @alinask thanks for jumping on it. `UCX_SOCKADDR_TLS_PRIORITY=tcp` also fixes it for me.

**Comment by abellina** [comment]
@alinask @yosefe do you think it's possible to get this into 1.10.1?

@petro-rudenko fyi.

**Comment by alinask** [comment]
> @alinask @yosefe do you think it's possible to get this into 1.10.1?
> 
> @petro-rudenko fyi.

@abellina The fix was merged into the UCX v1.10.x branch.

**Comment by alinask** [comment]
@krakowski @abellina Following the fix in the UCX v1.10.x branch, can we close this ticket?

**Comment by krakowski** [comment]
From my side it can be closed. Thanks for the quick fix! :slightly_smiling_face:

**Comment by abellina** [comment]
Same for me. Thanks @alinask
