### ISSUE TITLE
[mtt][ucx-cuda] ERROR in MPI_Sendrecv_replace: incorrect data

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#6770]
Configuration
```
OMPI: 4.1.1rc1
MOFED: MLNX_OFED_LINUX-5.2-2.2.0.0
Module: hpcx-gcc (2021-05-06)
Test module: none
Nodes: vulcan x2 (ppn=24(x2), nodelist=vulcan[03-04])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210506_180449_17101_10487_vulcan03.swx.labs.mlnx/html/test_stdout_S8i_l3.txt
 
Cmd:
`/hpc/local/benchmarks/daily/next/2021-05-06/hpcx-gcc-redhat7.6/ompi/bin/mpirun -np 48 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt -x UCX_IB_PCI_RELAXED_ORDERING=off --bind-to core -x UCX_NET_DEVICES=mlx5_0:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_UD_TIMEOUT=10m -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210506_180449_17101_10487_vulcan03.swx.labs.mlnx/installs/EXad/tests/ibm-tests/ompi-tests/ibm/pt2pt/sendrecv_rep_big2`
 
Output:
```sh
 =============================================================Thu May  6 20:31:37 2021[1,0]<stderr>:buffer[256] = 0, expected 1
Thu May  6 20:31:37 2021[1,0]<stderr>:[**ERROR**]: MPI_COMM_WORLD rank 0, file sendrecv_rep_big2.c:48:
Thu May  6 20:31:37 2021[1,0]<stderr>:ERROR in MPI_Sendrecv_replace: incorrect data
Thu May  6 20:31:37 2021[1,1]<stderr>:buffer[256] = 1, expected 0
Thu May  6 20:31:37 2021[1,1]<stderr>:[**ERROR**]: MPI_COMM_WORLD rank 1, file sendrecv_rep_big2.c:48:
Thu May  6 20:31:37 2021[1,1]<stderr>:ERROR in MPI_Sendrecv_replace: incorrect data--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.
```

**Comment by brminich** [comment]
fixed by open-mpi/ompi#8897
