### ISSUE TITLE
How to build ucp_client_server in directory examples ?

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#6844]
1、After I run cmds below, ucp_client_server is not compiled.
$ ./autogen.sh
$ ./contrib/configure-release --prefix=/where/to/install
$ make -j8
$ make install
2、When I run make in path example, it tell me as figure below.
![image](https://user-images.githubusercontent.com/58133919/119355762-3995ab80-bcd8-11eb-9488-280611cd0dbe.png)

How can I compile it ?

Any reply will be appreciated.

**Comment by yosefe** [comment]
please do `./contrib/configure-release --enable-examples`

**Comment by h2cw2l** [comment]
> please do `./contrib/configure-release --enable-examples`

Thanks.
