### ISSUE TITLE
When I test am_lat by ucx_perftest, what transport type should be when I want to use verbs ?

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#6853]
Hello,

My dev is shown as below, I want to test am_lat.
I have tried "-x verbs", "-x dc_mlx5", "-x rc_verbs", "-x rc_mlx5". It always tell me this is can not use.
**Which transport type should follow after "-x" ?**
![图片](https://user-images.githubusercontent.com/58133919/119596192-4c5fcb80-be11-11eb-9da5-ccac4d6546e1.png)

![图片](https://user-images.githubusercontent.com/58133919/119596258-68636d00-be11-11eb-83b0-b1593c2ff5c1.png)

Any reply will be appreciated.

**Comment by dmitrygx** [comment]
Hello @h2cw2l,

You can't use dc_mlx5/rc_mlx5/rc_verbs transports over `eth0` which is IP interface. IB transports (dc/rc/ud) require to run only over `device:port` pair specified in `ibv_devinfo` output.
Please, change `-d eth0` to `-d mlx5_0:1`.

JFYI, `-d eth0` could be used along with `-t tcp`, i.e. TCP transport requires setting IP interface as a device input.

**Comment by h2cw2l** [comment]
> Hello @h2cw2l,
> 
> You can't use dc_mlx5/rc_mlx5/rc_verbs transports over `eth0` which is IP interface. IB transports (dc/rc/ud) require to run only over `device:port` pair specified in `ibv_devinfo` output.
> Please, change `-d eth0` to `-d mlx5_0:1`.
> 
> JFYI, `-d eth0` could be used along with `-t tcp`, i.e. TCP transport requires setting IP interface as a device input.

Thanks for reply.

What should follow -x ?
![image](https://user-images.githubusercontent.com/58133919/120468031-5e260d80-c3d3-11eb-96a5-aaca302f0296.png)

**Comment by shamisp** [comment]
You can use `ucx_info -d | grep Transport` to get list of transports supported on your platform. Also please take a look at https://openucx.readthedocs.io/en/master/faq.html#selecting-networks-and-transports.

**Comment by dmitrygx** [comment]
> What should follow -x ?

`-x <transport>`, e.g. rc_verbs, rc_mlx5, tcp and etc

**Comment by h2cw2l** [comment]
@shamisp @dmitrygx 

Thanks.
