### ISSUE TITLE
Call back function: What is the request ? Is it a struct ? Where is its definition ?

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#6894]
![image](https://user-images.githubusercontent.com/58133919/120646582-3e164d00-c4ac-11eb-92ea-71938bf3a24d.png)

**Comment by hoopoepg** [comment]
@h2cw2l request from user's perspective is opaque object without any specific features. it is used to track operation progress and results (success/fail). internally this is wide structure declared in src/ucp/core/ucp_request.h. but note that location of request structure is not same as pointer: request pointer "points" to user's data, request structure located on memory buffer "before" of user's data.

**Comment by h2cw2l** [comment]
> opaque

Thanks for reply.

But I still can not understand you clearly.
1、Is struct ucp_request in src/ucp/core/ucp_request.h the definition of the first input parameter "void *request" ?
2、“request pointer "points" to user's data”，as I understand, the last  input parameter points to the user's data, what do you mean by "request pointer", it also points to user's data ?
3、What do you mean by "user's data", the data user want to send oe recv ?

**Comment by hoopoepg** [comment]
the common request layout is like this:
```
|----------|-------------------|
 request_t   user data/payload
           /\
           |
       pointer - first argument of callback function
``` 
look at the description of ucp_tag_send_nbr routine for details
size of payload is configured in ucp_params_t::request_size value of ucp_init routine

**Comment by h2cw2l** [comment]
> ucp_tag_send_nbr

As far as I know, the send/recv buffer is malloced by user, how can we place the request before the the user buffer ?

**Comment by h2cw2l** [comment]
> the common request layout is like this:
> 
> ```
> |----------|-------------------|
>  request_t   user data/payload
>            /\
>            |
>        pointer - first argument of callback function
> ```
> 
> look at the description of ucp_tag_send_nbr routine for details
> size of payload is configured in ucp_params_t::request_size value of ucp_init routine

As far as I know, the send/recv buffer is malloced by user, how can we place the request before the the user buffer ?

**Comment by hoopoepg** [comment]
user data here is not send/recv data. user may use request to store any operation context, for example in OMPI it used to store OMPI request.
good example of usage is in test/examples/ucp_hello_world.c

**Comment by h2cw2l** [comment]
> example

Yes, I have read test/examples/ucp_hello_world.c. 

My application scenario is to encapsulate some functions similar to socket apis based on ucx apis.
I will abstract an id similar to socket fd to represent a connection.
When recv or send a packet，the data buff is offerred by user.

**Every time before I call recv or send, I want to remember the id and buff address  in request_t, so that when the call  back function are called，I can get fd and buff address and return it to user.**

**Now, I do not know how to set the reques_t every time before I recv/send a packet, do you know hwo to do this ?**

**Comment by h2cw2l** [comment]
> 
> 
> user data here is not send/recv data. user may use request to store any operation context, for example in OMPI it used to store OMPI request.
> good example of usage is in test/examples/ucp_hello_world.c

Yes, I have read test/examples/ucp_hello_world.c.

My application scenario is to encapsulate some functions similar to socket apis based on ucx apis.
I will abstract an id similar to socket fd to represent a connection.
When recv or send a packet，the data buff is offerred by user.

**Every time before I call recv or send, I want to remember the id and buff address in request_t, so that when the call back function are called，I can get fd and buff address and return it to user.

Now, I do not know how to set the reques_t every time before I recv/send a packet, do you know hwo to do this ?**

**Comment by hoopoepg** [comment]
hmm, you definitely may use ucp_tag_send_nbx/ucp_tag_recv_nbx functions, it allow to use own request which may be partially initialized prior to send/recv operation

**Comment by h2cw2l** [comment]
> ucp_tag_send_nbx

Now, I use ucp_stream_recv_nbx/ucp_stream_send_nbx, because they are similar to TCP.
Can I use request_t for each packet in this scenario ?

**Comment by hoopoepg** [comment]
no, you can't use it directly.
the right way to use own request is:
1. get UCX request size using ucp_context_query function
2. allocate buffer length request size + your custom data size
3. initialize pointer to buffer+request size - it will points into your custom data
4. initialize your custom data using pointer from previous item
5. use this pointer as user request in send/recv_nbx calls

in description of ucp_tag_send_nbr  routine there is good example how user request may be created and used, this way is common for all such requests
