### ISSUE TITLE
ERROR feature flags UCP_FEATURE_TAG were not set for ucp_init()

### ISSUE THREAD

**Issue by pentschev** [openucx/ucx#6895]
Not enabling `UCP_FEATURE_TAG` prints error messages upon `ucp.init()`. I believe this shouldn't happen for cases where TAG isn't used (e.g., when relying on AM only). The complete error message is seen below:

```
[1622724381.798912] [dgx15:56728:0]           probe.c:30   UCX  ERROR feature flags UCP_FEATURE_TAG were not set for ucp_init()
```

This is reproducible with https://github.com/openucx/ucx/commit/74552f660066a1a7b7468901a34937724f221873 and a non-release build.

**Comment by brminich** [comment]
this message comes from `ucp_tag_probe_nb` which is TAG API call. It is illegal to invoke this func, if `UCP_FEATURE_TAG` is not specified in `ucp_init`

**Comment by pentschev** [comment]
Ah yes, you're right, I could confirm that on my end. The error message got me confused thinking it was happening _during_ `ucp_init()`. Anyway, sorry for the false alarm.
