### ISSUE TITLE
Where is definition of ucp_address_t ?

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#6902]

**Comment by chenyidu** [comment]
https://github.com/openucx/ucx/blob/74552f660066a1a7b7468901a34937724f221873/src/ucp/api/ucp_def.h#L112

Because only `ucp_address_t*` and `ucp_address_t**` , the definition of `struct ucp_address` is not required.

**Comment by h2cw2l** [comment]
> 
> 
> https://github.com/openucx/ucx/blob/74552f660066a1a7b7468901a34937724f221873/src/ucp/api/ucp_def.h#L112
> 
> Because only `ucp_address_t*` and `ucp_address_t**` , the definition of `struct ucp_address` is not required.

It is difficult to understand the definition of struct ucp_address is not required, why ?

**Comment by chenyidu** [comment]
> > https://github.com/openucx/ucx/blob/74552f660066a1a7b7468901a34937724f221873/src/ucp/api/ucp_def.h#L112
> > 
> > Because only `ucp_address_t*` and `ucp_address_t**` , the definition of `struct ucp_address` is not required.
> 
> It is difficult to understand the definition of struct ucp_address is not required, why ?

Size of pointer type is fixed, so pointer types can be used with only forward declaration. If you take a closer look at where `ucp_address_t` is used, you can find that it is treated as void type. `struct ucp_address` is just a more readable name, `typedef void ucp_address_t` is ok too. Here is the basic knowledge of C language.

**Comment by yosefe** [comment]
the ucp_address_t should be treated as void and the actual address size is returned from ucp_worker_query(). It's not possible to know the real address size in compile-time, but only in run time, since it depends on available communication hardware on the machine.

**Comment by h2cw2l** [comment]
Thanks.
