### ISSUE TITLE
If ucp_stream_send_nbx completed immediately, will the send_cb be called ? 

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#6903]
I see the cb of ucp_stream_send_nb will not be called if completed immediately. 
But the description of ucp_stream_send_nbx does not say this, if it completed immediately, will its cb be called ?
Is the same condition exists in recv side ?
![图片](https://user-images.githubusercontent.com/58133919/120785378-a7a36380-c55f-11eb-90d5-3d0161072803.png)
![图片](https://user-images.githubusercontent.com/58133919/120785584-d7526b80-c55f-11eb-850b-7566f24b3f12.png)

**Comment by hoopoepg** [comment]
there is same behavior across all _nbx calls

**Comment by h2cw2l** [comment]
> there is same behavior across all _nbx calls

Thanks for reply.

Is the same condition exists in the recv side ?
That means, if ucp_stream_send_nbx/ucp_stream_recv_nbx complete immediately, the call back function will not be called ?

**Comment by hoopoepg** [comment]
right. for this purpose there is recv_info value in ucp_request_param_t structure to get received data info

**Comment by h2cw2l** [comment]
> right. for this purpose there is recv_info value in ucp_request_param_t structure to get received data info

Thanks.
