### ISSUE TITLE
About ucp_stream_send_nbx/ucp_stream_recv_nbx ?

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#6913]
When ucp_stream_send_nbx completes, the len of data sent is equal to the input param count ?
When ucp_stream_recv_nbx completes, the len of data recvd is  0 < length <= count ?

**Is my understand right ?**

ucp_stream_send_nbx(ucp_ep_h ep, const void *buffer, size_t count,
                                     const ucp_request_param_t *param);
ucp_stream_recv_nbx(ucp_ep_h ep, void *buffer, size_t count,
                                     size_t *length,
                                     const ucp_request_param_t *param);

**Comment by hoopoepg** [comment]
for sender side it is true: after **operation** is completed, not only call of send routine, send buffer may be reused.
for receiver side you should use flag UCP_STREAM_RECV_FLAG_WAITALL to force receiving of whole message

**Comment by h2cw2l** [comment]
> message

Thanks for reply.
For the receiver side, I do not use flag UCP_STREAM_RECV_FLAG_WAITALL, if ucp_stream_recv_nbx  is completed immediately and returns UCS_OK, **is the length between 0 and count ?**

ucp_stream_recv_nbx(ucp_ep_h ep, void *buffer, size_t **count**,
size_t ***length**, const ucp_request_param_t *param);

**Comment by hoopoepg** [comment]
right, any value between 0 and length

**Comment by h2cw2l** [comment]
> 
> 
> right, any value between 0 and length

Thanks.
