### ISSUE TITLE
Do you have customers whose application is developed by golang ?

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#6960]
Hello, ucx team,

Do you have customers whose application is developed by golang ?
How is the performance about latency and throughput ?

**Comment by shamisp** [comment]
@petro-rudenko is leading the work on golang

**Comment by petro-rudenko** [comment]
Hi, we just started to implement go bindings. Soon should be functionality for endpoint, so you can measure latency/bandwidth. Let us know your use case, meanwhile, you can watch this folder: https://github.com/openucx/ucx/tree/master/bindings/go
