### ISSUE TITLE
Doubt about iodemo.

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#6997]
After create ep why call connect_tag() ?
This code not exists in ucp_client_server.

void UcxConnection::connect_common(ucp_ep_params_t &ep_params,
                                   UcxCallback *callback)
{
    _establish_cb = callback;

    // create endpoint
    ep_params.field_mask      |= UCP_EP_PARAM_FIELD_ERR_HANDLER |
                                 UCP_EP_PARAM_FIELD_ERR_HANDLING_MODE;
    ep_params.err_mode         = UCP_ERR_HANDLING_MODE_PEER;
    ep_params.err_handler.cb   = error_callback;
    ep_params.err_handler.arg  = reinterpret_cast<void*>(this);

    ucs_status_t status = ucp_ep_create(_context.worker(), &ep_params, &_ep);
    if (status != UCS_OK) {
        assert(_ep == NULL);
        UCX_LOG << "ucp_ep_create() failed: " << ucs_status_string(status);
        handle_connection_error(status);
        return;
    }

    UCX_CONN_LOG << "created endpoint " << _ep << ", connection id "
                 << _conn_id;

    if (_use_am) {
        connect_am(callback);
    } else {
        **connect_tag(callback);**
    }

    _context.add_connection(this);
}

**Comment by evgeny-leksikov** [comment]
it goes from TAG API semantic: send context is endpoint but receive context is worker,  so to identify "reply" endpoint we have to exchange IDs as part of connection establishment and use it on data path as part of tag

**Comment by h2cw2l** [comment]
> context

I see STREAM also do this ？

**Comment by evgeny-leksikov** [comment]
stream API does receive on endpoint, so it matches send and receive (reply) endpoints, this is why we use it to exchange IDs for usage in TAG API

**Comment by h2cw2l** [comment]
> 
> 
> stream API does receive on endpoint, so it matches send and receive (reply) endpoints, this is why we use it to exchange IDs for usage in TAG API

Thanks。
