### ISSUE TITLE
Doubt about request(ep close request, send/recv request, connection request) process

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#7005]
Hello, ucx team,

1、I have learned the iodemo code. I see it processes requests(ep close request, send/recv request, connection request) very carefully.

2、I also see, there are some ucx functions can cleanup the unprocessed request automatically. 
ucs_callbackq_cleanup(), ucs_callbackq_remove_if(), ucp_request_complete_stream_recv()

3、I have test locally, before I destroy the ep/listener/worker/context，I deliberately make a recv request and do not process it，
the resoueces can still be freed successfully.

**### My doubt is whether I must process the requests before I freee resources ?**

**Comment by evgeny-leksikov** [comment]
assuming that you are using UCP, (2) - these are internal functions called from UCP to clean up UCP resources
> I deliberately make a recv request and do not process it，the resoueces can still be freed successfully.

 - in case of stream request it will be completed with status UCS_ERR_CANCEL
 - TAG request - you have to cancel it with ucp_request_cancel (see https://openucx.github.io/ucx/api/v1.10/html/group___u_c_p___c_o_m_m.html#ga3553f89a61d6b40af4633a2e7c84fc1d for details)
 - not "accepted" connect request can be rejected by `ucp_listener_reject`  https://openucx.github.io/ucx/api/v1.10/html/group___u_c_p___w_o_r_k_e_r.html#ga1f1620fdbae11ea076875fd6ac644241
 - all endpoints, listeners and requests have to be released before destroying parent worker

**Comment by h2cw2l** [comment]
>     * and requests have to be released before destroying parent worker

all endpoints, listeners and requests have to be released before destroying parent worker

I want to ask is that if recv/send requests can be processed automatically by ucx and user do not need to care this ?

**Comment by evgeny-leksikov** [comment]
> I want to ask is that if recv/send requests can be processed automatically by ucx and user do not need to care this ?

sure you can release or free request rigth after send/recv operation with `ucp_request_release`/`ucp_request_free`
> In case of stream request, user no need to care send/recv request ?

in any case it's user responsibility to release requests back to UCP library
