### ISSUE TITLE
Question about request and call_back_q

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#7007]
ucs_status_ptr_t request = ucp_stream_recv_nbx();

Let us consider this condition:
After call ucp_stream_recv_nbx(), it return an request and it will add an event to the call back queue after the recv completed.

Can I cancel the request before the call back event be processed ?
If I do this, will the call back function be called ? It the call back function be called, the request is NULL ?

**Comment by evgeny-leksikov** [comment]
> Can I cancel the request before the call back event be processed ?

ucp_request_cancel works like "best effort" to cancel the operation without any guerantees and implemted only for TAG API

> It the call back function be called, the request is NULL ? 

it depends on `ucp_stream_recv_nbx` parameters
