### ISSUE TITLE
Listing available UCX transports is taking a long time

### ISSUE THREAD

**Issue by mkre** [openucx/ucx#7066]
### Describe the bug
We need to find out the supported UCX transports, but listing them via the suggested `ucx_info -d` takes almost 30 seconds on our InfiniBand cluster. The output hangs for some seconds at
```
...
#      Transport: dc_mlx5
#         Device: mlx5_0:1
#  System device: 0000:86:00.0 (0)
```
before continuing with
```
#
#      capabilities:
#            bandwidth: 6961.86/ppn + 0.00 MB/sec
#              latency: 660 nsec
#             overhead: 40 nsec
...
```
So, I suspect the delay might have to do with the performance tests being run. Can we somehow speed up the listing of supported transports (e.g., by skipping the performance tests)? 
This is a critical issue to us since we need to query the transports in order to tune our Open MPI + UCX toolchain during application startup, so we would like to prevent any kind of noticeable delay.

### Steps to Reproduce
- Command line
```
ucx_info -d
```
- UCX version used (from github branch XX or release YY) + UCX configure flags (can be checked by `ucx_info -v`)
Tested with 1.8.0 and 1.10.0
- **Any UCX environment variables used**
None

### Setup and versions
CentOS Linux release 7.6.1810 (Core)
MLNX_OFED_LINUX-4.6-1.0.1.1

### Additional information (depending on the issue)
- Output of `ucx_info -d` to show transports and devices recognized by UCX: [ucx_info-d.txt](https://github.com/openucx/ucx/files/6778572/ucx_info-d.txt)

Thanks,
Moritz

**Comment by yosefe** [comment]
@mkre no performance tests are run but potentially some HW related operation is taking a while.
Is it possible to compile UCX [with logging enabled](https://github.com/openucx/ucx/wiki/Logging) and run the command with UCX_LOG_LEVEL=trace?

**Comment by mkre** [comment]
Please find the log file with tracing attached: [ucx_info-d_trace.txt](https://github.com/openucx/ucx/files/6781930/ucx_info-d_trace.txt)
The delay happens between the lines
```
[1625724487.016910] [wvhpc02v01:320650:0]          mpool.c:205  UCX  DEBUG mpool rcache_mp: allocated chunk 0x2aaab0e6f008 of 151544 bytes with 1052 elements
[1625724513.287550] [wvhpc02v01:320650:0]          ib_md.c:775  UCX  DEBUG registered memory 0x2aaaaea00000..0x2aaab0e00000 on mlx5_0 lkey 0x16211 rkey 0x16211 access 0xf flags 0x3e4
```

**Comment by yosefe** [comment]
maybe there was not enough free physical memory on the system and memory registration forced buffer cache eviction

**Comment by mkre** [comment]
Yeah, that might be the reason. Thanks for providing some background information. I will close this ticket and check the system status (and possibly reopen) should I see similar behavior again.
