### ISSUE TITLE
Qusetion about the *data of am_recv_callback() in iodemo.

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#7074]
As far as I know, if in the eager mode, the  recved data is stored in *data.This buffer of *data is managed by ucx.
**What I want to know is how can I config the buffer size and buff num and what its default value ?**

ucs_status_t UcxContext::am_recv_callback(void *arg, const void *header,
                                          size_t header_length,
                                          void ***data**, size_t length,
                                          const ucp_am_recv_param_t *param)
{
    UcxContext *self = reinterpret_cast<UcxContext*>(arg);

    assert(param->recv_attr & UCP_AM_RECV_ATTR_FIELD_REPLY_EP);
    assert(self->_use_am);

    uint64_t conn_id = reinterpret_cast<uint64_t>(param->reply_ep);
    conn_map_t::iterator iter = self->_conns.find(conn_id);
    if (iter == self->_conns.end()) {
        // TODO: change this to assert when data dropping is implemented in AM
        UCX_LOG << "could not find connection with ep " << param->reply_ep
                << "(" << conn_id << ")";
        return UCS_OK;
    }

    UcxConnection *conn = iter->second;

    UcxAmDesc data_desc(data, param);

    self->dispatch_am_message(conn, header, header_length, data_desc);

    return UCS_OK;
}

**Comment by brminich** [comment]
In the eager mode, you get `length` parameter which defines the size of `data`. You will always receive all the data in one buffer. We are considering adding support for receiving data by chunks in eager mode, but it is not implemented yet.
What do you mean by default values for these buffers?
