### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by gggh000** [openucx/ucx#7127]
### Describe the bug
Build is failing with log below:

```
nonroot@nonroot-Standard-PC-i440FX-PIIX-1996:~/git.co/ucx$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf
configure.ac:79: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
nonroot@nonroot-Standard-PC-i440FX-PIIX-1996:~/git.co/ucx$ git branch -r
  origin/HEAD -> origin/master
  origin/gh-pages
  origin/master
  origin/revert-7023-release_ci
  origin/topic/iodemo-assert-servers
  origin/v1.10.x
  origin/v1.11.x
  origin/v1.2.x
  origin/v1.3.x
  origin/v1.4.x
  origin/v1.5.x
  origin/v1.6.x
  origin/v1.7.x
  origin/v1.8.x
  origin/v1.9.x
nonroot@nonroot-Standard-PC-i440FX-PIIX-1996:~/git.co/ucx$ git checkout v1.11.x
Branch 'v1.11.x' set up to track remote branch 'v1.11.x' from 'origin'.
Switched to a new branch 'v1.11.x'
nonroot@nonroot-Standard-PC-i440FX-PIIX-1996:~/git.co/ucx$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf
configure.ac:79: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
nonroot@nonroot-Standard-PC-i440FX-PIIX-1996:~/git.co/ucx

```
### Steps to Reproduce
On ubuntu machine (18.04), just simply checkout and follow the first instruction: . ./autogen.sh caused this.
- UCX version used (from github branch XX or release YY) + UCX configure flags (can be checked by `ucx_info -v`)
master branch and v1.11

- **Any UCX environment variables used**
No that i know of
### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...): Ubuntu 1804:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
nonroot@nonroot-Standard-PC-i440FX-PIIX-1996:~/git.co/ucx$ uname -r
5.4.0-42-generic
nonroot@nonroot-Standard-PC-i440FX-PIIX-1996:~/git.co/ucx$

``` 
   - `cat /etc/issue` or `cat /etc/redhat-release` + `uname -a`
   - For Nvidia Bluefield SmartNIC include `cat /etc/mlnx-release` (the string identifies software and firmware setup)
- For RDMA/IB/RoCE related issues:
    - Driver version:
        - `rpm -q rdma-core` or `rpm -q libibverbs`
        - or: MLNX_OFED version `ofed_info -s`
   - HW information from `ibstat` or `ibv_devinfo -vv` command
- For GPU related issues:
  - GPU type
  - Cuda: 
      - Drivers version
      - Check if peer-direct is loaded: `lsmod|grep nv_peer_mem` and/or gdrcopy: `lsmod|grep gdrdrv`

### Additional information (depending on the issue)
- OpenMPI version
- Output of `ucx_info -d` to show transports and devices recognized by UCX
- Configure result - config.log
- Log file - configure UCX with "--enable-logging" - and run with "UCX_LOG_LEVEL=data"
N/A

**Comment by gggh000** [comment]
After installing libtool, it worked. It may be good idea to add libtool installation as requirement.

**Comment by shamisp** [comment]
@gggh000 AC_PROG_LIBTOOL is a "autotools" way to configure libtool. Checking for the presence of libtool binary with `which libtool`  is not a very robust way of checking the functionality of libtool installation since other parts of the tool can be missing. Executing the macro is a relatively reliable way to verify functionality of the tool.

**Comment by shamisp** [comment]
I'm closing for now. If you have an idea how libtool detection can be implemented in a robust way, please let us know.
