### ISSUE TITLE
In posix shared memory, on linux, pass /proc/<pid>/fd/<fd> instead of path

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#718]
In order to avoid stale shared mmeory files, in case of process premature exit, we can do following:
* open posix file
* immediately unlink it (but keep it open)
* mmap the file
* let the other processes open /proc/<pid>/fd/<fd> in order to access the shared memory
* in case of exit, the file will be automatically deleted, because no directory entry points to it

Reference: http://unix.stackexchange.com/questions/92816/can-a-file-be-retrieved-by-its-inode

**Comment by shamisp** [comment]
how do you unlink the file before sharing it with other perrs

**Comment by yosefe** [comment]
Unlinking the file does not delete it as long as there is a reference to if (open file descriptor)
And there is still a “default” link to it from /proc which another process can open

**Comment by shamisp** [comment]
Is there an issue way to find it in /proc ?
I think in ompi it is unlinked once it is shared with the rest.

**Comment by yosefe** [comment]
Should not be an issue. And we can unlink the original file it even before sharing.
