### ISSUE TITLE
Segmentation fault after `UCM/BISTRO: Parse libcuda debug hooks`

### ISSUE THREAD

**Issue by pentschev** [openucx/ucx#7210]
### Describe the bug
After #7195 / #7197 several of UCX-Py tests are failing with a segmentation fault, as well as all UCX-based Dask tests, regardless of being TCP-only, including `cuda_ipc` or `rc` transports, but in all cases tested with `cuda_copy`.

### Steps to Reproduce
- Simplest way to reproduce is run UCX-Py test: `py.test --ignore-glob debug-tests --cache-clear -vs tests/test_custom_send_recv.py`
- UCX 1.11 https://github.com/openucx/ucx/commit/7057cb39e1228f1bace1756542083da389279620 and master https://github.com/openucx/ucx/commit/05dca02812b00f5e8ac2d0da18b816a0ff3e8b77

### Setup and versions
- DGX-1: `Linux dgx13 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- NVIDIA V100
- CUDA 11.2
  - Both `nv_peer_mem` and `gdrcopy` modules loaded

**Comment by yosefe** [comment]
@pentschev can you pls check with https://github.com/openucx/ucx/pull/7209? (on v1.11.x)

**Comment by pentschev** [comment]
Forgot to close this before, but https://github.com/openucx/ucx/pull/7209 fixed this issue.
