### ISSUE TITLE
Crash in multi-thread scenarios

### ISSUE THREAD

**Issue by chenyidu** [openucx/ucx#7227]
### Describe the bug
#6265 removed the following code so that `ucp_tag_probe_nb()` is no longer multithread safe, even if I configured `--enable-mt`.
![image](https://user-images.githubusercontent.com/69713632/129211975-0252c215-925e-4126-ae96-cbf957c06399.png)

In my case, there are multiple threads calling `ucp_worker_progress()`, and there is another thread executing `ucp_tag_probe_nb()`. Sometimes, `ucp_tag_probe_nb()` can not probe the incoming tag message. And sometimes, it just crashes.

In my opinion, this is a bug, and I don't quite understand why these two lines of code were deleted.

**Comment by chenyidu** [comment]
@brminich Can you tell me why these codes were deleted?

**Comment by brminich** [comment]
#7228
