### ISSUE TITLE
ucx_info: symbol lookup error: ucx_info: undefined symbol: ucs_topo_sys_device_bdf_name

### ISSUE THREAD

**Issue by LazyCoder15** [openucx/ucx#7232]
I'm installing UCX on Ubuntu 20.04.1 inside a container. Although ucx installation ucx-1.11 and ucx-1.10 succeeds, ucx_info -b gives this error. The same installation works on ubuntu 18.04.

I use the following steps for installation:
$tar zxf ucx-1.11.0.tar.gz
$cd ucx-1.11.0
$./contrib/configure-prof --prefix=/usr --enable-examples --with-java=no --with-cuda=/usr/local/cuda
$make -j4 install

#ucx_info -b
ucx_info: symbol lookup error: ucx_info: undefined symbol: ucs_topo_sys_device_bdf_name

Is this a known problem? How to fix it?

**Comment by LazyCoder15** [comment]
So, I installed mellanox ofed driver before installing ucx. I believe that also installs ucx? How can I remove other versions and reinstall?

**Comment by yosefe** [comment]
try `sudo apt remove ucx` or similar

**Comment by LazyCoder15** [comment]
Still see the same issue.

**Comment by yosefe** [comment]
what is the output of `ldd $(which ucx_info)`?
need to make sure UCX libraries, in particular libucs.so, is really loaded from /usr/lib

**Comment by LazyCoder15** [comment]
You are right. It's not loaded from /usr/lib
 
ldd $(which ucx_info)
        linux-vdso.so.1 (0x00007ffea4c85000)
        /usr/lib/x86_64-linux-gnu/libgstbadvideo-1.0.so.0 (0x00007f963af14000)
        libucp.so.0 => /usr/local/ucx/lib/libucp.so.0 (0x00007f963ae53000)
        libuct.so.0 => /usr/local/ucx/lib/libuct.so.0 (0x00007f963ae0f000)
        libucs.so.0 => /usr/local/ucx/lib/libucs.so.0 (0x00007f963adb7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f963ad94000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f963aba0000)
        libgstvideo-1.0.so.0 => /lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x00007f963aaef000)
        libgstbase-1.0.so.0 => /lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x00007f963aa71000)
        libgstreamer-1.0.so.0 => /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007f963a92a000)
        libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f963a8ca000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f963a7a1000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f963a794000)
        libnuma.so.1 => /lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f963a787000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f963a638000)
        libucm.so.0 => /usr/local/ucx/lib/libucm.so.0 (0x00007f963a61a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f963a614000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f963b138000)
        liborc-0.4.so.0 => /lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007f963a58f000)
        libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f963a589000)
        libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007f963a57d000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f963a50a000)
