### ISSUE TITLE
segfault in MPI_Init with OpenMPI+UCX 1.10.0

### ISSUE THREAD

**Issue by angainor** [openucx/ucx#7239]
I am getting a segfault in MPI_Init with OpenMPI 4.0.5 and OpenMPI 4.1.1 compiled against UCX 1.10.0 and 1.10.1. When I load UCX 1.11.1 with the same binary and MPI, things work. This happens on our compute nodes, but not on the login node, so it might be something related to OS config. I guess something so basic would pop up earlier, but I didn't find any posts about it. Is this a know issue? This is the stack:

```
[marcink@b1101.BETZY ~]$ mpirun -np 1 ./mpihello
[b1101:176811:0:176811] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x98)
==== backtrace (tid: 176811) ====
 0 0x0000000000028663 ucs_debug_print_backtrace()  /cluster/home/marcink/src/ucx-1.10.0/src/ucs/debug/debug.c:656
 1 0x000000000000bbb6 _dl_relocate_object()  :0
 2 0x000000000001463c dl_open_worker()  dl-open.c:0
 3 0x000000000000f7a4 _dl_catch_error()  :0
 4 0x0000000000013b5b _dl_open()  :0
 5 0x0000000000000fab dlopen_doit()  dlopen.c:0
 6 0x000000000000f7a4 _dl_catch_error()  :0
 7 0x00000000000015ad _dlerror_run()  :0
 8 0x0000000000001041 __dlopen_check()  :0
 9 0x000000000000de00 ucm_prevent_dl_unload()  /cluster/home/marcink/src/ucx-1.10.0/src/ucm/util/sys.c:311
10 0x0000000000006d77 ucm_event_install()  /cluster/home/marcink/src/ucx-1.10.0/src/ucm/event/event.c:491
11 0x0000000000006d77 ucm_set_event_handler()  /cluster/home/marcink/src/ucx-1.10.0/src/ucm/event/event.c:558
12 0x000000000002fb1a ucs_rcache_t_init()  /cluster/home/marcink/src/ucx-1.10.0/src/ucs/memory/rcache.c:956
13 0x000000000002fb1a ucs_rcache_create()  /cluster/home/marcink/src/ucx-1.10.0/src/ucs/memory/rcache.c:1006
14 0x00000000000038d8 uct_knem_md_open()  /cluster/home/marcink/src/ucx-1.10.0/src/uct/sm/scopy/knem/knem_md.c:364
15 0x00000000000127e4 uct_md_open()  /cluster/home/marcink/src/ucx-1.10.0/src/uct/base/uct_md.c:52
16 0x0000000000015564 ucp_fill_tl_md()  /cluster/home/marcink/src/ucx-1.10.0/src/ucp/core/ucp_context.c:887
17 0x0000000000015564 ucp_add_component_resources()  /cluster/home/marcink/src/ucx-1.10.0/src/ucp/core/ucp_context.c:1155
18 0x0000000000016a6b ucp_fill_resources()  /cluster/home/marcink/src/ucx-1.10.0/src/ucp/core/ucp_context.c:1294
19 0x0000000000016a6b ucp_init_version()  /cluster/home/marcink/src/ucx-1.10.0/src/ucp/core/ucp_context.c:1609
20 0x00000000000066c8 ucp_init()  /cluster/home/marcink/software/ucx/1.10.0/include/ucp/api/ucp.h:1650
21 0x0000000000051c4f open_components()  /cluster/home/marcink/src/openmpi-4.0.5/opal/mca/base/mca_base_components_open.c:125
22 0x0000000000051c4f mca_base_framework_components_open()  /cluster/home/marcink/src/openmpi-4.0.5/opal/mca/base/mca_base_components_open.c:68
23 0x00000000000b3a07 mca_pml_base_open()  /cluster/home/marcink/src/openmpi-4.0.5/ompi/mca/pml/base/pml_base_frame.c:184
24 0x000000000005bc91 mca_base_framework_open()  /cluster/home/marcink/src/openmpi-4.0.5/opal/mca/base/mca_base_framework.c:176
25 0x00000000000bd165 ompi_mpi_init()  /cluster/home/marcink/src/openmpi-4.0.5/ompi/runtime/ompi_mpi_init.c:617
26 0x0000000000074b7f PMPI_Init()  /cluster/home/marcink/src/openmpi-4.0.5/ompi/mpi/c/profile/pinit.c:67
27 0x0000000000400764 main()  ???:0
28 0x0000000000022545 __libc_start_main()  ???:0
29 0x0000000000400699 _start()  ???:0
=================================
```

**Comment by angainor** [comment]
And `mpihello` source code is

```
#include <mpi.h>
int main(int argc, char **argv)
{
  MPI_Init(&argc, &argv);
  MPI_Finalize();
}
```

**Comment by hoopoepg** [comment]
hi @angainor 
thank you for bug report.

it looks like known issue in system module loader.

could you try to run your application with environment variable
```
UCX_MEM_MODULE_UNLOAD_PREVENT_MODE=now
```
or
```
UCX_MEM_MODULE_UNLOAD_PREVENT_MODE=none
```

thank you

**Comment by angainor** [comment]
@hoopoepg Thanks for the hint! `UCX_MEM_MODULE_UNLOAD_PREVENT_MODE=none` did help, mode `now` did not.

**Comment by yosefe** [comment]
@angainor can you please provide more details on the system where this issue happens?

**Comment by angainor** [comment]
@yosefe This is a BullSequana XH2000 system with AMD EPYC 7742 64-Core Processor, running on Red Hat Enterprise Linux Server 7.7. The login nodes run the same OS as the compute nodes, but the problem is not observed there. One obvious difference is the fact that `/` is mounted `ro` on the compute nodes, and `rw` on the frontend nodes. 

Let me know if you would like more specific in formation.

**Comment by yosefe** [comment]
@angainor to make sure, is v1.11 resolving this segfault issue?
one change we made between v1.10 and v1.11 is to do the dlopen() above in library init instead of during ucp_init()

**Comment by angainor** [comment]
@yosefe yes, 1.11 works without the envar, but it's more complicated. The workaround is also not needed in 1.10 if I compile it on my compute node, as opposed to my login node. I've updated more logs in #7245

**Comment by angainor** [comment]
@yosefe do you think this can be closed, or do you want to keep this open? It seems that this error only occurred in my case when I was compiling for a different OFED (5) than I was in fact running on (4). I understand that you also observed such behavior, but maybe my case is not so useful in that regard?

**Comment by yosefe** [comment]
since this code path is also changed in v1.11 I think we can close it
