### ISSUE TITLE
Low IB bandwidth with UCX 1.10 and 1.11 

### ISSUE THREAD

**Issue by angainor** [openucx/ucx#7245]
I get very low OSU bandwidth results with the newest UCX versions on our BullSequana XH2000 system with AMD EPYC 7742 64-Core Processor and MT28908 ConnectX-6, running on Red Hat Enterprise Linux Server 7.7. Here are the results with HPCX 2.7 (UCX 1.9):

```
# OSU MPI Bi-Directional Bandwidth Test v5.7
# Size      Bandwidth (MB/s)
1                       5.95
2                      12.49
4                      24.88
8                      52.27
16                    100.73
32                    204.02
64                    311.07
128                   612.31
256                   817.46
512                  1787.83
1024                 3316.37
2048                 5218.08
4096                 8722.35
8192                13899.90
16384               18056.62
32768               21316.22
65536               22851.18
131072              23690.87
262144              24128.47
524288              24381.31
1048576             24509.98
2097152             24575.19
4194304             24609.96
```
I guess the above is as expected. This is what I get with HPCX 2.8 (UCX 1.10):

```
# OSU MPI Bi-Directional Bandwidth Test v5.7
# Size      Bandwidth (MB/s)
1                       1.52
2                       3.35
4                       7.05
8                      14.34
16                     26.59
32                     42.46
64                    132.15
128                   187.52
256                   299.63
512                   686.10
1024                 1496.68
2048                 1543.28
4096                 2725.40
8192                 4939.90
16384                5834.66
32768                5411.06
65536                5290.45
131072               4792.16
262144               4634.00
524288               4656.26
1048576              4649.79
2097152              4176.99
4194304              4519.10
```
And here are results obtained with manually compiled UCX 1.11.1:
```
# OSU MPI Bi-Directional Bandwidth Test v5.7
# Size      Bandwidth (MB/s)
1                       1.89
2                       3.87
4                       8.16
8                      14.78
16                     29.77
32                     42.70
64                     94.01
128                   276.79
256                   500.75
512                   921.56
1024                 1500.79
2048                 2138.20
4096                 2380.90
8192                 3534.07
16384                3890.16
32768                4043.58
65536                3982.09
131072               4150.06
262144               4026.88
524288               3951.54
1048576              3937.32
2097152              3926.45
4194304              4000.02
```
Do you have any ideas what this might be caused by?

**Comment by angainor** [comment]
It seems that IB is not recognized on this system with HPCX 2.8, or UCX 1.10 and above. This is `ucx_info -p -e -u t` with HPCX 2.8, and with manually compiled UCX 1.10.1

```
#
# UCP context
#
#     component 0  :  posix
#     component 1  :  sysv
#     component 2  :  self
#     component 3  :  tcp
#     component 4  :  sockcm
#     component 5  :  cma
#     component 6  :  knem
#
#            md 0  :  component 0  posix 
#            md 1  :  component 1  sysv 
#            md 2  :  component 2  self 
#            md 3  :  component 3  tcp 
#            md 4  :  component 4  sockcm 
#            md 5  :  component 5  cma 
#            md 6  :  component 6  knem 
#
#      resource 0  :  md 0  dev 0  flags -- posix/memory
#      resource 1  :  md 1  dev 0  flags -- sysv/memory
#      resource 2  :  md 2  dev 0  flags -- self/memory
#      resource 3  :  md 3  dev 1  flags -- tcp/ib0
#      resource 4  :  md 3  dev 2  flags -- tcp/enp225s0f0
#      resource 5  :  md 4  dev 3  flags -s sockcm/sockaddr
#      resource 6  :  md 5  dev 0  flags -- cma/memory
#      resource 7  :  md 6  dev 0  flags -- knem/memory
#
# memory: 0.42MB, file descriptors: 1
# create time: 9.996 ms
#
#
# UCP endpoint
#
#               peer: <no debug data>
#                 lane[0]:  2:self/memory.0 md[2]           -> md[2]/self     am am_bw#0
#                 lane[1]:  7:knem/memory.0 md[6]           -> md[6]/knem     rma_bw#0
#
#                tag_send: 0..<egr/short>..8185..<egr/bcopy>..8192..<rndv>..(inf)
#            tag_send_nbr: 0..<egr/short>..8185..<egr/bcopy>..262144..<rndv>..(inf)
#           tag_send_sync: 0..<egr/short>..8185..<egr/bcopy>..8192..<rndv>..(inf)
#
#                  rma_bw: mds [6] rndv_rkey_size 26
#
```
And this is what I get with HPCX 2.7:
```
#
# UCP context
#
#     component 0  :  posix
#     component 1  :  sysv
#     component 2  :  self
#     component 3  :  tcp
#     component 4  :  sockcm
#     component 5  :  ib
#     component 6  :  rdmacm
#     component 7  :  cma
#     component 8  :  knem
#
#            md 0  :  component 0  posix 
#            md 1  :  component 1  sysv 
#            md 2  :  component 2  self 
#            md 3  :  component 3  tcp 
#            md 4  :  component 4  sockcm 
#            md 5  :  component 5  mlx5_0 
#            md 6  :  component 6  rdmacm 
#            md 7  :  component 7  cma 
#            md 8  :  component 8  knem 
#
#      resource 0  :  md 0  dev 0  flags -- posix/memory
#      resource 1  :  md 1  dev 0  flags -- sysv/memory
#      resource 2  :  md 2  dev 0  flags -- self/memory
#      resource 3  :  md 3  dev 1  flags -- tcp/ib0
#      resource 4  :  md 3  dev 2  flags -- tcp/enp225s0f0
#      resource 5  :  md 4  dev 3  flags -s sockcm/sockaddr
#      resource 6  :  md 5  dev 4  flags -- rc_verbs/mlx5_0:1
#      resource 7  :  md 5  dev 4  flags -- rc_mlx5/mlx5_0:1
#      resource 8  :  md 5  dev 4  flags -- dc_mlx5/mlx5_0:1
#      resource 9  :  md 5  dev 4  flags -- ud_verbs/mlx5_0:1
#      resource 10 :  md 5  dev 4  flags -- ud_mlx5/mlx5_0:1
#      resource 11 :  md 5  dev 4  flags -- cm/mlx5_0:1
#      resource 12 :  md 6  dev 3  flags -s rdmacm/sockaddr
#      resource 13 :  md 7  dev 0  flags -- cma/memory
#      resource 14 :  md 8  dev 0  flags -- knem/memory
#
# memory: 1.25MB, file descriptors: 3
# create time: 11.746 ms
#
[1629111829.116478] [b1101:63084:0]         parser.c:1629 UCX  WARN  unused env variable: UCX_MEM_MODULE_UNLOAD_PREVENT_MODE (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
#
# UCP endpoint
#
#               peer: <no debug data>
#                 lane[0]:  2:self/memory.0 md[2]           -> md[2]/self     am am_bw#0
#                 lane[1]:  7:rc_mlx5/mlx5_0:1.0 md[5]      -> md[5]/ib       rma_bw#0 wireup{ud_mlx5/mlx5_0:1}
#                 lane[2]: 14:knem/memory.0 md[8]           -> md[8]/knem     rma_bw#1
#
#                tag_send: 0..<egr/short>..8185..<egr/bcopy>..8192..<rndv>..(inf)
#            tag_send_nbr: 0..<egr/short>..8185..<egr/bcopy>..262144..<rndv>..(inf)
#           tag_send_sync: 0..<egr/short>..8185..<egr/bcopy>..8192..<rndv>..(inf)
#
#                  rma_bw: mds [5] [8] rndv_rkey_size 35
```
I'd appreciate any suggestions.

**Comment by angainor** [comment]
Another observation is that the output of `ucx_info` is as expected on the front-end nodes. Only the compute nodes have this problem. Somehow this feels related to #7239, where I also see the same asymmetry.

**Comment by yosefe** [comment]
@angainor can you pls run the ucx_info from v1.11 version with `UCX_LOG_LEVEL=trace`, on the compute node, and upload the log file - to figure out why IB does not initialize?

**Comment by angainor** [comment]
@yosefe I've done more testing. There is a difference whether I compile UCX on the login node, or whether I compile it on the compute node. When I compile on compute node, UCX 1.10 and 1.11 both find the `mlx5_0` interface, and 1.10 doesn't need the workaround discussed in #7239. When I compile on the login node and run `ucx_info` on the compute nodes, `mlx5_0` is not found, and UCX 1.10 additionally needs the dl workaround.

I've attached some logs. `_login` suffix means that UCX has been compiled on the login node, `_node` means that UCX has been compiled on the compute node, `_hpcx28` is the output obtained from UCX distributed with HPCX 2.8.

There are two sets of logs:

- output of `UCX_LOG_LEVEL=trace ucx_info -d`
```
ucx_info.dev_hpcx28
ucx_info.dev_login
ucx_info.dev_node
```
- output of `ucx_info -b`
```
ucx_info.build_hpcx28
ucx_info.build_login
ucx_info.build_node
```

It seems that the build configuration seen on my compute nodes is signifficantly different than what I get with HPCX 2.8 and with UCX compiled on my login node. Might this be due to some RPM / OS differences?

[ucx.tar.gz](https://github.com/openucx/ucx/files/6993810/ucx.tar.gz)

**Comment by angainor** [comment]
@yosefe I've done more testing. There is a difference whether I compile UCX on the login node, or whether I compile it on the compute node. When I compile on compute node, UCX 1.10 and 1.11 both find the `mlx5_0` interface, and 1.10 doesn't need the workaround discussed in #7239. When I compile on the login node and run `ucx_info` on the compute nodes, `mlx5_0` is not found, and UCX 1.10 additionally needs the dl workaround.

I've attached some logs. `_login` suffix means that UCX has been compiled on the login node, `_node` means that UCX has been compiled on the compute node, `_hpcx28` is the output obtained from UCX distributed with HPCX 2.8.

There are two sets of logs:

- output of `UCX_LOG_LEVEL=trace ucx_info -d`
```
ucx_info.dev_hpcx28
ucx_info.dev_login
ucx_info.dev_node
```
- output of `ucx_info -b`
```
ucx_info.build_hpcx28
ucx_info.build_login
ucx_info.build_node
```

It seems that the build configuration seen on my compute nodes is signifficantly different than what I get with HPCX 2.8 and with UCX compiled on my login node. Might this be due to some RPM / OS differences?

[ucx.tar.gz](https://github.com/openucx/ucx/files/6993815/ucx.tar.gz)

**Comment by yosefe** [comment]
@angainor is there a difference in rdma-core on MLNX_OFED libraries between login and compute nodes?

**Comment by yosefe** [comment]
It seems like the compute node has MLNX_OFED 4.x and login node is MLNX_OFED is MLNX_OFED 5.x

**Comment by angainor** [comment]
@yosefe hmm. `ofed_info` shows this on both nodes:
```
$ ofed_info | head
MLNX_OFED_LINUX-5.0-2.1.8.0 (OFED-5.0-2.1.8):
```

**Comment by angainor** [comment]
@yosefe you're right - things are not consistent. Compute node:
```
[marcink@b1101.BETZY ~/src/ucx-1.11.1]$ rpm -qa | grep rdma
librdmacm-devel-41mlnx1-OFED.4.7.3.0.6.50218.x86_64
librdmacm-utils-41mlnx1-OFED.4.7.3.0.6.50218.x86_64
ucx-rdmacm-1.8.0-1.50218.x86_64
librdmacm-41mlnx1-OFED.4.7.3.0.6.50218.x86_64
```
and login node
```
ucx-rdmacm-1.8.0-1.50218.x86_64
rdma-core-devel-50mlnx1-1.50218.x86_64
librdmacm-utils-50mlnx1-1.50218.x86_64
rdma-core-50mlnx1-1.50218.x86_64
librdmacm-50mlnx1-1.50218.x86_64
```
How come `ofed_info` shows the same version 5??

**Comment by angainor** [comment]
@yosefe thanks a lot for spotting this. I guess this explains then the difference. I guess your advise would be to upgrade compute nodes to OFED 5?

**Comment by yosefe** [comment]
maybe an incomplete/partial installation.. I'd recommend to upgrade to OFED 5.0 .

**Comment by angainor** [comment]
@yosefe This is strange. `ofed_info` on both nodes reports roughly the same stuff (attached). For example, 

```
librdmacm:
/sw/release/mlnx_ofed/IBHPC/MLNX_OFED_LINUX-5.0-1.0.0.0/SRPMS/librdmacm-41mlnx1-OFED.4.7.3.0.6.50100.0.src.rpm
```
So although it`s `MLNX_OFED_LINUX-5.0-2.1.8.0`, it says it uses `librdmacm-41mlnx1`. While the actual RPM installed is `librdmacm-50mlnx1-1.50218.x86_64`.

Maybe also the dl problem is due to the fact that I'm trying to use HPCX compiled for MOFED 5 (since I thought that's what I have), but I'm actually running something else. 

Could you have a look at the output of `ofed_info` and see, if you think it's correct? Thanks a lot!

[ofed_info.login.gz](https://github.com/openucx/ucx/files/6994048/ofed_info.login.gz)

**Comment by yosefe** [comment]
@angainor possible there is some issue with MLNX_OFED installation on the nodes
I'd recommend to install MLNX_OFED 5.0 (without special flags) and/or contact Nvidia NBU support if there is an issue with the installation.
