### ISSUE TITLE
Question about ucp_request_free()

### ISSUE THREAD

**Issue by chenyidu** [openucx/ucx#7290]
### Describe the bug
My project needs to have a timeout feature. When a timeout occurs, I call `ucp_request_free()` to release the request returned by `ucp_tag_recv_nbx()` and free receive buffer. However, when the message arrives, UCP does not check the request flag(UCP_REQUEST_FLAG_RELEASED) and still uses the buffer in the request to receive data.
https://github.com/openucx/ucx/blob/7dd8a0638a88e34fad9b884c0bed60a7bb84922f/src/ucp/tag/eager_rcv.c#L100-L104

According to the comment of `ucp_request_free()`, if the upper layer will never get any notifications after this function is called, it is reasonable for the upper layer to free the receive buffer. So I'd like to ask what is the proper use of `ucp_request_free()`. Is this scenario not supported? 

Thanks in advance.

> When using eager protocol, it's easy to add the check, but it seems can not be fixed under RNDV protocol.

**Comment by yosefe** [comment]
in order to implement a timeout feature, need to use ucp_request_cancel(), and then wait for the request callback to be called. it would either be completed successfully or fully canceled.

**Comment by chenyidu** [comment]
@yosefe Thank you for your reply, we noticed the function. Looks like it's just a matter of usage, I'll close this issuse.
