### ISSUE TITLE
What's the meaning of lane ? Is there any docs can help me understand it ?

### ISSUE THREAD

**Issue by zabara123** [openucx/ucx#7495]
Hello, ucx team:

I have referenced 'VERBS_RDMA_Aware_Programming_user_manual.pdf' and 'ucx-v1.10.pdf', but I still don't understand what does lane[x] mean.
What's the relationship between lane and ep ?  lane and worker ? lane and md ?

![image](https://user-images.githubusercontent.com/91873501/135814652-b5953558-1779-457e-bb45-7266dcf15de4.png)

**Comment by yosefe** [comment]
ucp endpoint contains one or more lanes . each lane is a uct endpoint owned by this ucp endpoint. 
a uct endpoint is just one transport/device, but ucp endpoint can use multiple transports and devices.

**Comment by zabara123** [comment]
> ucp endpoint contains one or more lanes . each lane is a uct endpoint owned by this ucp endpoint. a uct endpoint is just one transport/device, but ucp endpoint can use multiple transports and devices.

Thanks very much.
