### ISSUE TITLE
support omnipath's max_inline_data == 0 feature

### ISSUE THREAD

**Issue by hppritcha** [openucx/ucx#750]
Currently ucx doesn't work on omnipath.  One issue that needs to be addressed is the max_inline_data usage, which currently is unconditional in ucx.  On omnipath make gtest fails with

```
    ud_iface.c:274  Assertion `qp_init_attr.cap.max_inline_data >= UCT_UD_MIN_INLINE' failed
```

**Comment by yosefe** [comment]
done
