### ISSUE TITLE
ucp_config_modify doesn't return UCS_ERR_NO_ELEM anymore

### ISSUE THREAD

**Issue by pentschev** [openucx/ucx#7519]
### Describe the bug
After the UCT caching changes in `ucp_config_modify` from https://github.com/openucx/ucx/pull/7019, it's not possible anymore to check whether a wrong/mistyped option was set. In UCX-Py we use `UCS_ERR_NO_ELEM` return status to identify a wrong user-specified option, but now all we get is a warning that doesn't really reflect the actual issue:

```
[1633640648.678052] [dgx13:79435:0]      ucp_worker.c:1972 UCX  WARN  unused cached uct configuration: UNKOWN_OPTION
```

### Steps to Reproduce
- Call `ucp_config_modify` with any non-existing variable name;
- UCX master at https://github.com/openucx/ucx/commit/b6197c8e5af598f5682165ea16915f126a798702 or newer.

**Comment by yosefe** [comment]
How about:
"[1633640648.678052] [dgx13:79435:0]      ucp_worker.c:1972 UCX  WARN  Invalid configuration: UNKOWN_OPTION=VALUE"

**Comment by pentschev** [comment]
That's a better error message. Would be also useful if there's a UCP API we can use to validate whether a configuration option is valid, is there something like that we could use today?

**Comment by changchengx** [comment]
@pentschev
Currently, there's no such API. As being said by Yossi, ```it's not possible to validate the values during ucp_config_modify() because it happens before UCT transports are loaded```.
For the ```reword the above warning message```, it's WIP: https://github.com/openucx/ucx/pull/7605

**Comment by pentschev** [comment]
Can we use the output from `ucp_config_print` to validate those options that exist? Or is there some situation where existing options do not show up there?

**Comment by changchengx** [comment]
@pentschev  As being said by Yossi ```it's not possible to validate the values during ucp_config_modify() because it happens before UCT transports are loaded```

**Comment by changchengx** [comment]
To validate configurations in ```ucp_config_print```, it also requires to load UCT transports.

**Comment by pentschev** [comment]
@changchengx Can you explain how we're supposed to interpret the output of `ucp_config_print` then? We have it implemented in UCX-Py that we parse its output to show the current UCP configurations, for example:

```python
In [1]: import ucp

In [2]: ucp.get_ucx_version()
Out[2]: (1, 12, 0)

In [3]: ucp.get_config()
Out[3]:
{'NET_DEVICES': 'all',
 'SHM_DEVICES': 'all',
 'ACC_DEVICES': 'all',
 'SELF_DEVICES': 'all',
 'TLS': 'all',
 'PROTOS': 'all',
 'ALLOC_PRIO': 'md:sysv,md:posix,huge,thp,md:*,mmap,heap',
 'SOCKADDR_TLS_PRIORITY': 'rdmacm,tcp,sockcm',
 'SOCKADDR_AUX_TLS': 'ud',
 'SELECT_DISTANCE_MD': 'cuda_cpy',
 'MEMTYPE_REG_WHOLE_ALLOC_TYPES': 'cuda',
 'WARN_INVALID_CONFIG': 'y',
 'BCOPY_THRESH': 'auto',
 'RNDV_THRESH': '8K',
 'RNDV_SEND_NBR_THRESH': '256K',
 'RNDV_THRESH_FALLBACK': 'inf',
 'RNDV_PERF_DIFF': '1.000',
 'MULTI_LANE_MAX_RATIO': '4.000',
 'MAX_EAGER_RAILS': '1',
 'MAX_RNDV_RAILS': '2',
 'RNDV_SCHEME': 'get_zcopy',
 'RKEY_PTR_SEG_SIZE': '512K',
 'ZCOPY_THRESH': 'auto',
 'BCOPY_BW': 'auto',
 'ATOMIC_MODE': 'guess',
 'ADDRESS_DEBUG_INFO': 'n',
 'MAX_WORKER_ADDRESS_NAME': '32',
 'USE_MT_MUTEX': 'n',
 'ADAPTIVE_PROGRESS': 'y',
 'SEG_SIZE': '8K',
 'TM_THRESH': '1K',
 'TM_MAX_BB_SIZE': '1K',
 'TM_FORCE_THRESH': '8K',
 'TM_SW_RNDV': 'n',
 'NUM_EPS': 'auto',
 'NUM_PPN': 'auto',
 'RNDV_FRAG_SIZE': 'host:512K,cuda:4M',
 'RNDV_FRAG_ALLOC_COUNT': 'host:128,cuda:128',
 'RNDV_PIPELINE_SEND_THRESH': 'inf',
 'FLUSH_WORKER_EPS': 'y',
 'UNIFIED_MODE': 'n',
 'CM_USE_ALL_DEVICES': 'y',
 'LISTENER_BACKLOG': 'auto',
 'PROTO_ENABLE': 'n',
 'KEEPALIVE_INTERVAL': '20000000.00us',
 'KEEPALIVE_NUM_EPS': '128',
 'PROTO_INDIRECT_ID': 'auto',
 'RNDV_PUT_FORCE_FLUSH': 'n',
 'SA_DATA_VERSION': 'v1',
 'RKEY_MPOOL_MAX_MD': '2'}
```

If an option isn't there, for example `[UCX_]UNKNOWN_OPTION`, can we assume it's an invalid UCP option?

**Comment by changchengx** [comment]
@pentschev I didn't understand the question well. Could you explain the question with more information?

**Comment by pentschev** [comment]
Assume I'm only interested at UCP configurations at this point. When calling `ucp_config_print` it should print some UCP configurations. For example, because `UCX_TLS` is a valid UCP configuration it's printed there, and therefore I know `UCX_TLS` is a valid configuration option for UCP. However, if I'm trying to figure our whether some arbitrary option, say `UCX_UNKNOWN_OPTION`, can I assume it isn't valid because it's not in that list, or is there a chance that it's still a valid UCP option but doesn't show up because some UCT transport isn't loaded yet?

**Comment by pentschev** [comment]
Or to put it more simply: will `ucp_config_print` _ ALWAYS_ print _ALL_ existing _UCP_ configs, or are there situations where even UCP configs will be omitted from it?

**Comment by yosefe** [comment]
ucp_config_print will always print all supported UCP configs

**Comment by pentschev** [comment]
I understand now, thanks both for help understanding!

**Comment by pentschev** [comment]
This has been addressed in https://github.com/openucx/ucx/issues/7519 and https://github.com/rapidsai/ucx-py/pull/804 . Thanks @yosefe and @changchengx for the help here. Closing.
