### ISSUE TITLE
Handle network failures

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#755]
TODO:

- [x] add a test with failing of 'zcopy' message (PR https://github.com/openucx/ucx/pull/1574)
- [x] add a test with failing of 'zcopy_multi' message with pending segment (PR https://github.com/openucx/ucx/pull/1653)
- [x] dcx and rcx counting completions after QP reset (PR https://github.com/openucx/ucx/pull/1700)
- [x] Pass error handling mode thru wireup (PR https://github.com/openucx/ucx/pull/1731)
- [x] test when some operations are successful and others have failed
- [x] test different operations on UCP 
- [x] Print error message only once and with all available info if it's unhandled

**Comment by evgeny-leksikov** [comment]
TODO:

- [ ] add a test with failing of 'zcopy' message.
- [ ] dcx and rcx counting completions after QP reset
- [ ] Reconfiguration of existing endpoint (wireup)
- [ ] test when some operations are successful and others have failed
- [ ] test different operations on UCP

**Comment by yosefe** [comment]
@evgeny-leksikov can we close this?

**Comment by evgeny-leksikov** [comment]
@yosefe there are several TODOs but anyway i'm traking this. up to you.

**Comment by yosefe** [comment]
ok, lets keep it

**Comment by evgeny-leksikov** [comment]
btw, if you move this list to the description GitHub will show the progress bar :)
