### ISSUE TITLE
./autogen.sh errors "Can't locate Autom4te/ChannelDefs.pm in @INC"

### ISSUE THREAD

**Issue by zhmlcg** [openucx/ucx#7627]
### Describe the bug
When I run `./autogen.sh`, it errors:

> Can't locate Autom4te/ChannelDefs.pm in @INC (you may need to install the Autom4te::ChannelDefs module) (@INC contains: /usr/share/autoconf /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.3 /usr/local/share/perl/5.30.3 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl) at /my/user/space/usr/bin/autoreconf line 39.
> BEGIN failed--compilation aborted at /my/user/space/usr/bin/autoreconf line 39.

I'm not a root user. Can I install `ucx` in my user space? In the past, I can run `./configure` directly, but now this file is removed and I am forced to run `./autogen.sh`. But it can do nothing but error. Is there a single-line (less than 10 lines is also ok) command that I can run to make `./autogen.sh` happy and working?

PS, what is the latest version of `ucx` that contains `./configure`?

### Steps to Reproduce
1. Installed `autoconf` package 2.69 my user space
2. run `./autogen.sh`
- UCX version used: Latest v1.11.2

### Setup and versions
- A remote ubuntu, I'm not a root user.

**Comment by yosefe** [comment]
1. There is probably an issue with autotools installation so that ./autogen.sh does not work on that system
2. UCX source .tar.gz always contains `./configure `, for example : https://github.com/openucx/ucx/releases/download/v1.11.2/ucx-1.11.2.tar.gz

**Comment by zhmlcg** [comment]
I got it. Thank you, yosefe.

**Comment by yosefe** [comment]
@zhmlcg ok to close the issue?

**Comment by zhmlcg** [comment]
ok.
