### ISSUE TITLE
support mapping policies from processes to devices/ports

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#763]
Allow the user to specify which device/s to use during the run according to a certain policy - nearest device to the used CPU / first device / do a round-robin between the devices etc.

**Comment by shamisp** [comment]
I guess first we have to integrate hwloc

**Comment by miked-mellanox** [comment]
IMO better use sysfs info (HCA provides distance to cpu in sysfs)

**Comment by shamisp** [comment]
I still think that for consistent reading / setting affinity we will end up using Hwloc. I would guess that this Sysfs feature is relatively new. Also we would need similar functionality for sm.
