### ISSUE TITLE
UCX error in cudaEventRecord, and in rndv.c

### ISSUE THREAD

**Issue by BKitor** [openucx/ucx#7635]
### Describe the bug
I'm trying to run an MPI application called Horovod with UCX and UCC, but it's crashing at runtime within UCX. I was hoping to get some pointers on debugging it. 

I'm getting a ucx error 
`[1636407160.851549] [ng30802:671180:0]    cuda_copy_ep.c:82   UCX  ERROR cudaEventRecord(cuda_event->event, iface->stream[id])() failed: invalid resource handle`
But it's also failing on an assert statement in in `/ucx-1.11.2/src/ucp/rndv/rndv.c: [ ucp_rndv_recv_frag_put_completion() ]`

See the full output:
https://gist.github.com/BKitor/0cd2a914dc63fd17d6a555db0623b870 

### Steps to Reproduce
```
mpirun -n 8 \
  --map-by ppr:4:node \
  --display bind \
  python tensorflow2_synthetic_benchmark.py
```
```
UCT version=1.11.2 revision ef2bbcf
configured with: --prefix=/home/bkitor/ucx-1.11.2/build --enable-mt --with-gdrcopy --with-verbs --with-cuda
```
- **Any UCX environment variables used**
```
export UCX_IB_FORK_INIT=yes
export IBV_FORK_SAFE=1
export OMPI_MCA_coll_ucc_enable=1
export OMPI_MCA_coll_ucc_priority=33
```

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
   - `Rocky Linux release 8.4 (Green Obsidian)`
- For RDMA/IB/RoCE related issues:
    - Driver version:
        - libibverbs-32.0-4.el8.x86_64
   - HW information from `ibstat` or `ibv_devinfo -vv` command: https://gist.github.com/BKitor/0a226acbf6877c96b0f9430e8a366f8f
- For GPU related issues:
  - GPU type - A100
  - Cuda: 11.4
      - Drivers version: 470.57.02
```
[bkitor@ng30801 ~]$ lsmod|grep gdrdrv
gdrdrv                 24576  0
nvidia              35266560  87 nvidia_uvm,gdrdrv,nvidia_modeset
[bkitor@ng30801 ~]$ lsmod|grep nv_peer_mem
[bkitor@ng30801 ~]$
```

- OpenMPI version - 5.0.0rc2
- UCC version=1.0.602 revision e77f002
- Output of `ucx_info -d` to show transports and devices recognized by UCX : https://gist.github.com/BKitor/0a226acbf6877c96b0f9430e8a366f8f

**Comment by bureddy** [comment]
```
[bkitor@ng30801 ~]$ lsmod|grep nv_peer_mem
[bkitor@ng30801 ~]$
```
any reason why GPU Direct RDMA is not enabled on the setup?

**Comment by BKitor** [comment]
I don't have admin access to the cluster. 
Is there some way I can load drivers in userspace?

**Comment by BKitor** [comment]
Got it working, but it's still kinda wonky. 
UCX-1.11.2 is failing in MPI_Bcast (on GPU buffers I think), for both mca_coll_tuned mca_coll_ucc. 
I can get my application to run if I: 1. Disable broadcast in UCC, 2. Disable pml_ucx in OMPI. 

Here's a gist with my workaround:
https://gist.github.com/BKitor/04f18f8a075641c2d3a0409be975821a
