### ISSUE TITLE
Gtest build failure on Fedora 35 with inbox gcc

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#7705]
### Describe the bug
Gtest build failure on Fedora 35 with inbox gcc
```
 CXX      ucp/gtest-test_ucp_stream.o
../../../test/gtest/uct/uct_test.cc: In member function ‘bool uct_test::async_event_ctx::wait_for_event(uct_test::entity&, double)’:
../../../test/gtest/uct/uct_test.cc:1514:26: error: ‘int poll(pollfd*, nfds_t, int)’ writing 8 bytes into a region of size 4 overflows the destination [-Werror=stringop-overflow=]
 1514 |     int ret        = poll(&wakeup_fd, 1, timeout_ms);
      |                      ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/poll.h:1,
                 from ../../../test/gtest/uct/uct_test.h:15,
                 from ../../../test/gtest/uct/uct_test.cc:7:
/usr/include/sys/poll.h:38:9: note: destination object ‘pollfd::fd’ of size 4
   38 |     int fd;                     /* File descriptor to poll.  */
      |         ^~
/usr/include/sys/poll.h:38:9: note: destination object ‘pollfd::fd’ of size 4
/usr/include/sys/poll.h:54:12: note: in a call to function ‘int poll(pollfd*, nfds_t, int)’ declared with attribute ‘access (write_only, 1, 2)’
   54 | extern int poll (struct pollfd *__fds, nfds_t __nfds, int __timeout)
      |            ^~~~
  CXX      ucp/gtest-test_ucp_peer_failure.o

```

### Steps to Reproduce
- ``../configure --enable-gtest --enable-examples --with-valgrind --enable-profiling --enable-frame-pointer --enable-stats --enable-memtrack --enable-fault-injection --enable-debug-data --enable-mt --with-xpmem=/home/pavsha01/work/xpmem-install/ --prefix=/home/xxx/xxx/ucx-install/ --with-ugni PKG_CONFIG_PATH=:/home/xxx/xxx/ucx/build/../contrib/cray-ugni-mock PKG_CONFIG_TOP_BUILD_DIR=/home/xxx/xxx/ucx/build/..``

- Reproducible on master and v1.12.x branch

### Setup and versions
- Fedora release 35 (Thirty Five) , aarch64
- No rdma-core drivers/hardware
- gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)

**Comment by shamisp** [comment]
I don't see the same issue with inbox clang. @yosefe  do we have F35 in CI ?

**Comment by hoopoepg** [comment]
it seems this is compiler bug: ```struct pollfd``` is declared as
```
struct pollfd
  {
    int fd;
    short int events;
    short int revents;
  };
```
which is 8 bytes length, but compiler lost ```events``` and ```revents``` values

**Comment by shamisp** [comment]
@hoopoepg Agree with you point but we still have to figure out how to deal with this.

**Comment by yosefe** [comment]
Seems like bug in GCC thinking that wakeup_fd only contains "fd" .
I think it can be solved by moving wakeup_fd to be a local variable instead of class member
