### ISSUE TITLE
Why disable RNDV when err_mode is UCP_ERR_HANDLING_MODE_PEER ?

### ISSUE THREAD

**Issue by chenyidu** [openucx/ucx#7746]
```c
int ucp_ep_config_test_rndv_support(const ucp_ep_config_t *config)
{
    return (config->key.err_mode == UCP_ERR_HANDLING_MODE_NONE) ||
           (config->key.cm_lane  != UCP_NULL_LANE);
}
```
When a ucp ep is created by client/server mode, `UCP_ERR_HANDLING_MODE_PEER` is usually specified (such as `example/ucp_client_server`). In this case, cm_lane is not UCP_NULL_LANE, so RNDV is enabled. It seems that `UCP_ERR_HANDLING_MODE_PEER` has nothing to do with RNDV, so why disable RNDV when specify `UCP_ERR_HANDLING_MODE_PEER`.

**Comment by chenyidu** [comment]
@evgeny-leksikov I see that you have added `config->key.cm_lane  != UCP_NULL_LANE` in #4702. Do you know the reason?

**Comment by evgeny-leksikov** [comment]
@chenyidu what's the UCX version you are exploring? This check was deleted recently in https://github.com/openucx/ucx/pull/7530. It was actual when keep alive was not implemented and RDNV protocol could stuck waiting for ACK from failed peer, but CM lane is able to notify remote failure.

**Comment by chenyidu** [comment]
I'm using the latest v1.11.x code, maybe I should move on to the updated code☺.
I've thought about the reason, but what puzzles me is that when err_mode is `UCP_ERR_HANDLING_MODE_NONE`, It just means not detecting remote failure, RDNV may still suck waiting for ACK if an error occurs, but RNDV is enabled.

**Comment by chenyidu** [comment]
My intuition is that RNDV can be turned on only when  err_mode is `UCP_ERR_HANDLING_MODE_PEER` or CM lane is not NULL, so that the remote failure can be sensed when it occurs and the RNDV can be ended properly.

**Comment by evgeny-leksikov** [comment]
> It just means not detecting remote failure, RDNV may still suck waiting for ACK if an error occurs, but RNDV is enabled.

right, if err handling is disabled we guarantee nothing in case of peer or network failure, RNDV is enabled and can be selected as most performing protocol

> My intuition is that RNDV can be turned on only when err_mode is UCP_ERR_HANDLING_MODE_PEER or CM lane is not NULL

Actually wise versa, without keep alive we cannot guarantee completion of requests (this is requirement of UCP_ERR_HANDLING_MODE_PEER - to complete requests in finite time) which is waiting for ACK because remote side can become unucessible or even dead at the moment between received RTS and sending ACK. So, we had disabled RNDV if err handling is enabled. This limitation is gone with KA.

**Comment by chenyidu** [comment]
I understand why RNDV is enabled for `UCP_ERR_HANDLING_MODE_NONE`, it's user's choice, and we don't guarantee anything. In the new version, the RNDV is always enabled, and if the problem occurs because the user disables the KA, it's also user's choice. So we don't need to check whether KA is enabled when set RNDV thresh, just a diag message.

Maybe I misunderstood what `UCP_ERR_HANDLING_MODE_PEER` does. It seems to me that `UCP_ERR_HANDLING_MODE_PEER` and KA are similar, both can detect peer exceptions. The difference is that the UCT EP that supports UCP_ERR_HANDLING_MODE_PEER detects exceptions passively, while the KA detects exceptions proactively. Whether there is this assumption? In passive mode, some remote failure may not be detected, but in active mode, all remote failure can be detected, so the RNDV will never stuck forever. Am I right about that?

**Comment by evgeny-leksikov** [comment]
yes, you are right. By default setting of `UCP_ERR_HANDLING_MODE_PEER` enables KA configuration, if all EPs are created with `UCP_ERR_HANDLING_MODE_NONE` KA can be disabled for performance reason, so err handling is an part of API to define EP dehavior, KA is a one from many possible mechanisms to detect error

**Comment by chenyidu** [comment]
Thank you @evgeny-leksikov
