### ISSUE TITLE
Incorrect datatype setting in ucp_tag_send_nbx

### ISSUE THREAD

**Issue by raffenet** [openucx/ucx#7754]
### Describe the bug

https://github.com/openucx/ucx/blob/c2fc7bd5654f0cd2c252f719b7e71ba39067ea82/src/ucp/tag/tag_send.c#L251-L270

If the user sets both the datatype flag and no immediate completion flag, the else branch in this conditional incorrectly assumes that the data is contiguous.

**Comment by yosefe** [comment]
nice :)
i guess line 259 should be changed from == to &. does such change fix the issue for you?

**Comment by raffenet** [comment]
> nice :) i guess line 259 should be changed from == to &. does such change fix the issue for you?

It does, but we also never supply a contig datatype parameter. I think using `&` could cause the no immediate parameter to be ignored if the datatype is contiguous. Line 261 in the snippet above.

**Comment by yosefe** [comment]
guess need another branch :(

```c
    if (ucs_likely(attr_mask == 0)) {
        status = UCS_PROFILE_CALL(ucp_tag_send_inline, ep, buffer, count, tag);
        ucp_request_send_check_status(status, ret, goto out);
        datatype      = ucp_dt_make_contig(1);
        contig_length = count;
    } else if (attr_mask & UCP_OP_ATTR_FIELD_DATATYPE) {
        datatype = param->datatype;
        if (ucs_likely(UCP_DT_IS_CONTIG(datatype))) {
            contig_length = ucp_contig_dt_length(datatype, count);
            if (!(attr_mask & UCP_OP_ATTR_FLAG_NO_IMM_CMPL)) {
                status = UCS_PROFILE_CALL(ucp_tag_send_inline, ep, buffer,
                                          contig_length, tag);
                ucp_request_send_check_status(status, ret, goto out);
            }
        }
    } else {
        datatype      = ucp_dt_make_contig(1);
        contig_length = count;
    }
```

**Comment by raffenet** [comment]
If you want to keep the first 2 branches the same, this could also work:
```
diff --git a/src/ucp/tag/tag_send.c b/src/ucp/tag/tag_send.c
index 35752a9b..0c06bfd3 100644
--- a/src/ucp/tag/tag_send.c
+++ b/src/ucp/tag/tag_send.c
@@ -265,8 +265,8 @@ UCS_PROFILE_FUNC(ucs_status_ptr_t, ucp_tag_send_nbx,
             ucp_request_send_check_status(status, ret, goto out);
         }
     } else {
-        datatype      = ucp_dt_make_contig(1);
-        contig_length = count;
+        datatype      = ucp_request_param_datatype(param)
+        contig_length = ucp_contig_dt_length(datatype, count);
     }

     if (ucs_unlikely(param->op_attr_mask & UCP_OP_ATTR_FLAG_FORCE_IMM_CMPL)) {
```

**Comment by raffenet** [comment]
> ```c
> +        contig_length = ucp_contig_dt_length(datatype, count);
> ```

Actually this line crashes with a non-contig datatype, so I guess there needs to be some more logic to handle everything correctly.
