### ISSUE TITLE
v1.13 ABI break

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#7822]
PR #7623 breaks UCX ABI because the new field `local_sockaddr` was added to the middle of `ucp_ep_params_t` struct. Need to move it to the end.
It will ABI-break any application that uses `conn_request` or `name` fields (so pretty much any client/server application)

cc @leibin2014 @shamisp @tonycurtis @brminich 

Update: The PR was merged after v1.12.x branch-off so it doesn't affect v1.12 series

**Comment by shamisp** [comment]
@yosefe ouch ... we need some unit testing for this
