### ISSUE TITLE
openmpi-4.1.2 with ucx-1.13.0  got Segmentation fault: invalid permissions for mapped object 

### ISSUE THREAD

**Issue by tomeybest** [openucx/ucx#7845]
### Describe the bug

run mpi job as follows
```
hosts=gpu-8:8,gpu-3:8
MLX5_DEVICES=mlx5_0:1,mlx5_1:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_7:1,mlx5_10:1,mlx5_11:1
 /opt/openmpi/bin/mpirun --allow-run-as-root  --report-bindings -np 16 -host $hosts  -npernode 8   -mca coll_hcoll_enable 0 -mca pml ucx  -mca osc ucx -x UCX_TLS=ib  -x UCX_LOG_LEVEL=info -x PATH -x LD_LIBRARY_PATH -x UCX_NET_DEVICES=$MLX5_DEVICES  /opt/bin/vasp_std_ucx 
```

got Segmentation fault after normally run a few minutes ：

> [gpu-8:165331:0:165331] Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x7fc073c00000)
> [gpu-3:51593:0:51593] Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x7fc234a02016)

backtrace:

>  0 0x000000000014cc75 __memcpy_ssse3()  :0
>  1 0x000000000003ea99 ucp_dt_pack()  /opt/ucx-source/src/ucp/dt/dt.c:120
>  2 0x0000000000063eb2 ucp_tag_pack_eager_common()  /opt/ucx-source/src/ucp/tag/eager_snd.c:31
>  3 0x00000000000337a2 uct_rc_mlx5_ep_am_bcopy()  /opt/ucx-source/src/uct/ib/rc/accel/rc_mlx5_ep.c:337
>  4 0x00000000000337a2 uct_rc_mlx5_ep_am_bcopy()  /opt/ucx-source/src/uct/ib/rc/accel/rc_mlx5_ep.c:341
>  5 0x00000000000653ea uct_ep_am_bcopy()  /opt/ucx-source/src/uct/api/uct.h:2852
>  6 0x00000000000653ea ucp_tag_eager_bcopy_multi()  /opt/ucx-source/src/ucp/tag/eager_snd.c:141
>  7 0x000000000006c3d0 ucp_request_try_send()  /opt/ucx-source/src/ucp/core/ucp_request.inl:334
>  8 0x000000000006c3d0 ucp_request_send()  /opt/ucx-source/src/ucp/core/ucp_request.inl:357
>  9 0x000000000006c3d0 ucp_tag_send_req()  /opt/ucx-source/src/ucp/tag/tag_send.c:116
> 10 0x000000000006c3d0 ucp_tag_send_nbx()  /opt/ucx-source/src/ucp/tag/tag_send.c:298
> 11 0x000000000000632e mca_pml_ucx_send_nbr()  /opt/openmpi-4.1.2/build/ompi/mca/pml/ucx/../../../../../ompi/mca/pml/ucx/pml_ucx.c:904
> 12 0x0000000000004b92 mca_pml_ucx_send()  /opt/openmpi-4.1.2/build/ompi/mca/pml/ucx/../../../../../ompi/mca/pml/ucx/pml_ucx.c:944
> 13 0x00000000000e9760 ompi_coll_base_sendrecv_actual()  /opt/openmpi-4.1.2/build/ompi/mca/coll/../../../../ompi/mca/coll/base/coll_base_util.c:58
> 14 0x00000000000e95c2 ompi_coll_base_sendrecv()  /opt/openmpi-4.1.2/build/ompi/mca/coll/../../../../ompi/mca/coll/base/coll_base_util.h:133
> 15 0x00000000000e892a ompi_coll_base_allgatherv_intra_bruck()  /opt/openmpi-4.1.2/build/ompi/mca/coll/../../../../ompi/mca/coll/base/coll_base_allgatherv.c:181
> 16 0x000000000000b5f4 ompi_coll_tuned_allgatherv_intra_do_this()  /opt/openmpi-4.1.2/build/ompi/mca/coll/tuned/../../../../../ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c:148
> 17 0x0000000000007360 ompi_coll_tuned_allgatherv_intra_dec_fixed()  /opt/openmpi-4.1.2/build/ompi/mca/coll/tuned/../../../../../ompi/mca/coll/tuned/coll_tuned_decision_fixed.c:1363
> 18 0x0000000000063bc5 PMPI_Allgatherv()  /opt/openmpi-4.1.2/build/ompi/mpi/c/profile/pallgatherv.c:146
> 19 0x0000000000045a94 mpi_allgatherv_()  /opt/openmpi-4.1.2/build/ompi/mpi/fortran/mpif-h/profile/pallgatherv_f.c:92
> 20 0x000000000065802b dfast_parallel_ggemm_()  /data1/qlab/vasp.6.2.1-ucx/build/std/dfast.f90:365
> 21 0x0000000000d172ef rot_roteta_()  /data1/qlab/vasp.6.2.1-ucx/build/std/rot.f90:2585
> 22 0x0000000000d03f0f rot_edwav_()  /data1/qlab/vasp.6.2.1-ucx/build/std/rot.f90:1494
> 23 0x0000000000d1b205 elmin_all_()  /data1/qlab/vasp.6.2.1-ucx/build/std/electron_all.f90:435
> 24 0x00000000014c4b3a vamp_electronic_optimization()  /data1/qlab/vasp.6.2.1-ucx/build/std/main.f90:5228
> 25 0x00000000014a6957 MAIN_()  /data1/qlab/vasp.6.2.1-ucx/build/std/main.f90:3027
> 26 0x00000000004115f3 main()  ???:0
> 27 0x0000000000022555 __libc_start_main()  ???:0
> 28 0x000000000040f1e9 _start()  ???:0

### Steps to Reproduce
ucx information:

> UCT version=1.13.0 revision 35c58b0
> configured with: --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/opt/ucx

openmpi compiled by pgi , detail infromation :
ompi-info 
>                  Package: Open MPI root@gpu-8 Distribution
>                 Open MPI: 4.1.2
>   Open MPI repo revision: v4.1.2
>    Open MPI release date: Nov 24, 2021
>                 Open RTE: 4.1.2
>   Open RTE repo revision: v4.1.2
>    Open RTE release date: Nov 24, 2021
>                     OPAL: 4.1.2
>       OPAL repo revision: v4.1.2
>        OPAL release date: Nov 24, 2021
>                  MPI API: 3.1.0
>             Ident string: 4.1.2
>                   Prefix: /opt/openmpi
>  Configured architecture: x86_64-pc-linux-gnu
>           Configure host: gpu-8
>            Configured by: root
>            Configured on: Fri Jan  7 03:38:30 UTC 2022
>           Configure host: gpu-8
>   Configure command line: '--prefix=/opt/openmpi' '--disable-debug'
>                           '--disable-getpwuid' '--disable-mem-debug'
>                           '--disable-mem-profile' '--disable-memchecker'
>                           '--disable-static' '--enable-mca-no-build=btl-uct'
>                           '--enable-mpi1-compatibility' '--enable-oshmem'
>                           '--with-cuda=/usr/local/cuda' '--with-ucx=/opt/ucx'
>                           '--enable-mca-no-build=op-avx' 'CPP=cpp' 'CC=nvc'
>                           'CFLAGS=-DNDEBUG -O1 -nomp -fPIC
>                           -fno-strict-aliasing -tp=haswell' 'CXX=nvc++'
>                           'CXXFLAGS=-DNDEBUG -O1 -nomp -fPIC
>                           -finline-functions -tp=haswell' 'F77=nvfortran'
>                           'F90=nvfortran' 'FC=nvfortran' 'FCFLAGS=-O1 -nomp
>                           -fPIC -tp=haswell' 'FFLAGS=-fast -Mipa=fast,inline
>                           -tp=haswell' 'LDFLAGS=-Wl,--as-needed'
>                 Built by: root
>                 Built on: Fri Jan  7 03:45:24 UTC 2022
>               Built host: gpu-8
>               C bindings: yes
>             C++ bindings: no
>              Fort mpif.h: yes (all)
>             Fort use mpi: yes (full: ignore TKR)
>        Fort use mpi size: deprecated-ompi-info-value
>         Fort use mpi_f08: yes
>  Fort mpi_f08 compliance: The mpi_f08 module is available, but due to
>                           limitations in the nvfortran compiler and/or Open
>                           MPI, does not support the following: array
>                           subsections, direct passthru (where possible) to
>                           underlying Open MPI's C functionality
>   Fort mpi_f08 subarrays: no
>            Java bindings: no
>   Wrapper compiler rpath: runpath
>               C compiler: nvc
>      C compiler absolute: /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/compilers/bin/nvc
>   C compiler family name: PGI
>       C compiler version: 21.11-0
>             C++ compiler: nvc++
>    C++ compiler absolute: /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/compilers/bin/nvc++
>            Fort compiler: nvfortran
>        Fort compiler abs: /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/compilers/bin/nvfortran
>          Fort ignore TKR: yes (!DIR$ IGNORE_TKR)
>    Fort 08 assumed shape: no
>       Fort optional args: yes
>           Fort INTERFACE: yes
>     Fort ISO_FORTRAN_ENV: yes
>        Fort STORAGE_SIZE: yes
>       Fort BIND(C) (all): yes
>       Fort ISO_C_BINDING: yes
>  Fort SUBROUTINE BIND(C): yes
>        Fort TYPE,BIND(C): yes
>  Fort T,BIND(C,name="a"): yes
>             Fort PRIVATE: yes
>           Fort PROTECTED: yes
>            Fort ABSTRACT: yes
>        Fort ASYNCHRONOUS: yes
>           Fort PROCEDURE: yes
>          Fort USE...ONLY: yes
>            Fort C_FUNLOC: yes
>  Fort f08 using wrappers: yes
>          Fort MPI_SIZEOF: yes
>              C profiling: yes
>            C++ profiling: no
>    Fort mpif.h profiling: yes
>   Fort use mpi profiling: yes
>    Fort use mpi_f08 prof: yes
>           C++ exceptions: no
>           Thread support: posix (MPI_THREAD_MULTIPLE: yes, OPAL support: yes,
>                           OMPI progress: no, ORTE progress: yes, Event lib:
>                           yes)
>            Sparse Groups: no
>   Internal debug support: no
>   MPI interface warnings: yes
>      MPI parameter check: runtime
> Memory profiling support: no
> Memory debugging support: no
>               dl support: yes
>    Heterogeneous support: no
>  mpirun default --prefix: no
>        MPI_WTIME support: native
>      Symbol vis. support: yes
>    Host topology support: yes
>             IPv6 support: no
>       MPI1 compatibility: yes
>           MPI extensions: affinity, cuda, pcollreq
>    FT Checkpoint support: no (checkpoint thread: no)
>    C/R Enabled Debugging: no

### Setup and versions
- OS version centos7+x86_64
- For RDMA/IB/RoCE related issues:
    - Driver version: MLNX_OFED_LINUX-5.4-1.0.3.0
   - HW information 8 * ConnectX6 200Gb/s HCA per node
- For GPU related issues:
  - Nvidia Delta A100 40GB
  - Cuda 11.4

**Comment by yosefe** [comment]
Pls try remove UCX_TLS from the command line

**Comment by tomeybest** [comment]
> Pls try remove UCX_TLS from the command line
Hi,
Removing UCX_TLS from the command line leads to  the same segmentation fault as above. Any other comments about this problem?
Thanks!

**Comment by brminich** [comment]
with what UCX version did it pass? Was UCX built with CUDA support?

**Comment by yosefe** [comment]
@tomeybest can you pls provide the output of "ucx_info -bd" ?

**Comment by tomeybest** [comment]
> @tomeybest can you pls provide the output of "ucx_info -bd" ?
[ucx_info_bd_output.txt](https://github.com/openucx/ucx/files/7874783/ucx_info_bd_output.txt)
Thanks!

**Comment by tomeybest** [comment]
> with what UCX version did it pass? Was UCX built with CUDA support?

Try uxc 1.10 1.11. 1.12  1.13, all fail.

**Comment by yosefe** [comment]
Seems UCX was built without Cuda support.
Can you pls pass "--with-cuda=<path-to-cuda-install>" to ./configure when building UCX?

**Comment by tomeybest** [comment]
> Seems UCX was built without Cuda support. Can you pls pass "--with-cuda=" to ./configure when building UCX?
Rebuild ucx with cuda support and it really works. Thanks for your help and also thanks @yosefe.
