### ISSUE TITLE
Architecture.pdf has several spelling typo

### ISSUE THREAD

**Issue by shssf** [openucx/ucx#799]
I found several spelling typo in the file ${UCX}/doc/doxygen/Architecture.pdf

**Comment by yosefe** [comment]
@shamisp can you fix it and/or add the source to UCX ?

**Comment by shamisp** [comment]
@shssf Can you please pin-point the typos ?

**Comment by shssf** [comment]
@shamisp  Yes, please:
"High Level APITransport"
"cross-transrport multi-rail"
"Domain:tag matching, randevouze"
"Accelerator Memory communucation"
"Data stractures"

**Comment by shamisp** [comment]
Once I have my Mac up, i will fix it.

**Comment by shssf** [comment]
@shamisp Friendly reminder.
Also, do you think it is better to have HTML generated documentation in Wiki?

**Comment by shamisp** [comment]
@shssf forgot about it.
We want to have both and with doxygen we can generate HTML and PDF.
The idea was to maintain a script somewhere that will re-fresh the HTML every night.

**Comment by shssf** [comment]
@shamisp Friendly reminder.

**Comment by shamisp** [comment]
I forgot about this one. But it is important to fix it before release. The problem is that the original files are on my computer at home.

**Comment by shssf** [comment]
@shamisp Could you please upload "original files" to the repository as well?

**Comment by shamisp** [comment]
Sure, this is the plan.
