### ISSUE TITLE
installation fails in ucxperftest when no mpi available

### ISSUE THREAD

**Issue by thomasgillis** [openucx/ucx#8079]
Dear UCX team,

I am trying to build UCX (1.12.1) in order to build openMPI right after (I have no mpi available at the moment).
However, the installation fails when compiling `ucx_perftest`:

``` bash
CC       ucx_perftest-perftest.o
CC       ucx_perftest-perftest_run.o
CC       ucx_perftest-perftest_params.o
/bin/mpicc: No such file or directory
```

I tried to disable the perftests with
```
./contrib/configure-release --disable-mpi
```
but it still tries to build them.

What is the correct way of not building the perftest? 

Thanks for your help!

**Comment by yosefe** [comment]
pls try "--without-mpi"
```
$ ./configure --help|grep -w mpi
  --with-mpi[=MPIHOME]    Compile MPI tests (default is NO)
```

**Comment by thomasgillis** [comment]
Thanks for your answer, I have just tried both `--with-mpi=no` and --without-mpi` but the configuration still produces
```
configure:            MPI tests:   enabled
```
Is there anything that you have in mind and that could prevent the command line to be correctly processed?

**Comment by yosefe** [comment]
can you pls upload the full output of configure command, and also config.log?

**Comment by yosefe** [comment]
BTW, maybe MPICC or MPIRUN environment variables are set?

**Comment by thomasgillis** [comment]
> MPICC



> BTW, maybe MPICC or MPIRUN environment variables are set?

Ha yes, indeed!
Let me fix that and try again

**Comment by shamisp** [comment]
> BTW, maybe MPICC or MPIRUN environment variables are set?

@yosefe if a user explicitly requests through the configure not to use MPI, we probably should not pickup the environment variables.
