### ISSUE TITLE
io_demo fails: /usr/bin/ld: ../../../src/ucs/.libs/libucs.so: undefined reference to `ucm_set_global_opts'

### ISSUE THREAD

**Issue by jeffhammond** [openucx/ucx#8178]
### Describe the bug

```
make[3]: Entering directory '/local/home/jehammond/MPI/ucx/build/test/apps/iodemo'
  CXXLD    io_demo
/usr/bin/ld: ../../../src/ucs/.libs/libucs.so: undefined reference to `ucm_set_global_opts'
/usr/bin/ld: ../../../src/ucs/.libs/libucs.so: undefined reference to `ucm_mmap_hook_modes'
collect2: error: ld returned 1 exit status
```

### Steps to Reproduce
- Command line

```
../configure --with-cuda --with-mcpu=neoverse-n1 CPPFLAGS=-I/usr/local/cuda-11.6/targets/sbsa-linux/include  --prefix=$HOME/ucx-cuda-11.6 && make -j40
````

- UCX version used (from github branch XX or release YY) + UCX configure flags (can be checked by `ucx_info -v`)

a2f342be0ff0940a6996296241a5d9327b0d2b04

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)

AArch64, Ubuntu 20.04.4 LTS, 5.4.0-109-generic, Ampere Altra Q80.  No NIC.

**Comment by hoopoepg** [comment]
hi @jeffhammond 

thank you for bug report
could you test this PR: https://github.com/openucx/ucx/pull/8179
it seems Ubuntu autotools have bit different behavior from RH
