### ISSUE TITLE
AM: UCP_AM_RECV_ATTR_FLAG_DATA not set for small message sizes

### ISSUE THREAD

**Issue by ironMann** [openucx/ucx#8237]
### Describe the bug
I send AM messages of various sizes (up to 500 kB) using the `UCP_AM_SEND_FLAG_EAGER` flag. On the receiver side, in the `ucp_am_data_cb` I assert the following`(param->recv_attr & UCP_AM_RECV_ATTR_FLAG_DATA)`.

If the message size is small, ~50 Bytes, the `UCP_AM_RECV_ATTR_FLAG_DATA` flag is not set (`param->recv_attr` is `0`).
The data length and the content is still valid. 

### Steps to Reproduce
- Command line: custom application...
- UCX version used: v1.12.1

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
- CentOS 8.5 Linux  4.18.0-348.7.1.el8_5.x86_64
- For RDMA/IB/RoCE related issues:
    - Driver version:
        - rdma-core-35.0-1.el8.x86_64

### Additional information (depending on the issue)
UCT version=1.12.1 
```bash
 configured with: --disable-logging --disable-debug --disable-assertions --disable-params-check --enable-mt --prefix=/cc8_x86-64/ucx/v1.12.1 --with-verbs --with-rdmacm --with-ib-hw-tm --with-mlx5-dv --with-rc --with-ud --with-dc --with-dm --with-avx --with-sse41 --with-sse42 --without-java --without-go --without-fuse3 --without-cuda --without-rocm
```

**Comment by brminich** [comment]
This flag is not guaranteed to be set. If it is not set, this means that the data pointer can't be used outside the callback and must be copied by the user if needed. Please check some comments here:
https://github.com/openucx/ucx/blob/master/src/ucp/api/ucp.h#L715
https://github.com/openucx/ucx/blob/master/src/ucp/api/ucp_def.h#L651

If you want this flag to be always set for AM eager messages, please set the AM callback with the corresponding flag:
https://github.com/openucx/ucx/blob/master/src/ucp/api/ucp.h#L568

**Comment by ironMann** [comment]
Hi @brminich, 
thanks a lot for the quick feedback. I do not need to keep the data outside the callback, so I can just drop the assert of `UCP_AM_RECV_ATTR_FLAG_DATA` flag. 
But, I now realize that I probably want to set `UCP_AM_FLAG_WHOLE_MSG`. 
Sorry for the noise, I'll close this now.
