### ISSUE TITLE
failed in build when adding `--with-rdmacm`

### ISSUE THREAD

**Issue by chrjxj** [openucx/ucx#8324]
Try to build UCX inside a docker container (`nvcr.io/nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04`)

```bash 
wget -q -nc --no-check-certificate -P /var/tmp https://github.com/openucx/ucx/releases/download/v1.7.0-rc1/ucx-1.7.0.tar.gz 
tar -x -f /var/tmp/ucx-1.7.0.tar.gz -C /var/tmp -z
cd /var/tmp/ucx-1.7.0
./configure --prefix=/usr/local/ucx --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --disable-doxygen-doc --with-cuda=/usr/local/cuda --with-gdrcopy=/usr/local/gdrcopy/ --with-verbs --with-rdmacm
```
at config step, when adding `--with-rdmacm` flag, it reports
```
configure: error: RDMACM requested but required file (rdma/rdma_cma.h) could not be found in /usr
```

any suggestion to fix this? thanks!

**Comment by changchengx** [comment]
What's the reason of using the verfy old version? https://github.com/openucx/ucx/releases/

To simplify, you can follow below link to install ofed which will install rdma-core library automatically.
https://network.nvidia.com/products/infiniband-drivers/linux/mlnx_ofed/
If you confirm that OFED has been installed, you need to check whether rdma-core package is installed in the docker environment.

**Comment by chrjxj** [comment]
thank you, Jerry. It works after adding some packages on top of the docker container.

`apt install -y libnuma-dev  libibverbs-dev rdma-core`
