### ISSUE TITLE
OpenMPI-4.1.2+UCX-1.12.0 Fail to create QP: Cannot allocate memory

### ISSUE THREAD

**Issue by razor1991** [openucx/ucx#8336]
#### case1
When I run osu_init in 2 nodes with 256 processes per node, it is reported like:

> `ib_iface.c:988  UCX  ERROR iface=0x224c8a10: failed to create UD QP TX wr:256 sge:6 inl:64 resp:0 RX wr:4096 sge:1 resp:0: Cannot allocate memory`

These Firmware version of CX5 is `Firmware version: 16.31.2006`, `OFED Version: MLNX_OFED_LINUX-5.4-3.0.3.0:`

#### case2
I found other 2 nodes, only the firmware version is different(`Firmware version: 16.27.1016`, OFED version is same).
And the osu_init is OK.

### Steps to Reproduce
- Command line

> mpirun -N 256 --hostfile ./2hf -x UCX_TLS=sm,rc -x UCX_NET_DEVICES=mlx5_0:1 --oversubscribe ./osu_init

- UCX version used (from github branch XX or release YY) + UCX configure flags (can be checked by `ucx_info -v`)

> UCX-1.12.0

>  UCT version=1.12.0 revision d367332
>  configured with: --disable-logging --disable-debug --disable-assertions --disable-params-check --enable-optimizations --prefix=/home/panxiaogang/install/ucx --without-java

- **Any UCX environment variables used**

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
   - `CentOS Linux release 7.6.1810 (AltArch)` + `Linux 6426-node181 4.14.0-115.el7a.0.1.aarch64 #1 SMP Sun Nov 25 20:54:21 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux ` + `Kunpeng 920 64Cores * 2` 
- For RDMA/IB/RoCE related issues:
    - Driver version:
        - MLNX_OFED version `MLNX_OFED_LINUX-5.4-3.0.3.0:`
   - `CA 'mlx5_0'
        CA type: MT4121
        Number of ports: 1
        Firmware version: 16.31.2006
        Hardware version: 0
        Node GUID: 0x0c42a103004f0fa2
        System image GUID: 0x0c42a103004f0fa2
        Port 1:
                State: Active
                Physical state: LinkUp
                Rate: 100
                Base lid: 53
                LMC: 0
                SM lid: 157
                Capability mask: 0x2651e848
                Port GUID: 0x0c42a103004f0fa2
                Link layer: InfiniBand
` 
   - `CA 'mlx5_0'
        CA type: MT4121
        Number of ports: 1
        Firmware version: 16.27.1016
        Hardware version: 0
        Node GUID: 0x98039b03006db0f0
        System image GUID: 0x98039b03006db0f0
        Port 1:
                State: Active
                Physical state: LinkUp
                Rate: 100
                Base lid: 79
                LMC: 0
                SM lid: 157
                Capability mask: 0x2651e848
                Port GUID: 0x98039b03006db0f0
                Link layer: InfiniBand
`

**Comment by yosefe** [comment]
@razor1991 
1. is there any error in dmesg?
2. what is the output of "ulimit -l"?

**Comment by razor1991** [comment]
@yosefe 
1.dmesg:

> [81909.039684] mlx5_cmd_check: 129 callbacks suppressed
> [81909.039690] mlx5_core 0000:01:00.0: mlx5_cmd_check:816:(pid 9828): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)
> [81909.039814] mlx5_core 0000:01:00.0: mlx5_cmd_check:816:(pid 9981): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)
> [81909.040656] mlx5_core 0000:01:00.0: mlx5_cmd_check:816:(pid 9982): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)
> [81909.044997] mlx5_core 0000:01:00.0: mlx5_cmd_check:816:(pid 9981): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)
> [81909.045099] mlx5_core 0000:01:00.0: mlx5_cmd_check:816:(pid 9993): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)
> [81909.048344] mlx5_core 0000:01:00.0: mlx5_cmd_check:816:(pid 9935): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)
> [81909.049544] mlx5_core 0000:01:00.0: mlx5_cmd_check:816:(pid 9993): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)
> [81909.051662] mlx5_core 0000:01:00.0: mlx5_cmd_check:816:(pid 9935): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)
> [81909.052343] mlx5_core 0000:01:00.0: mlx5_cmd_check:816:(pid 9990): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)
> [81909.053552] mlx5_core 0000:01:00.0: mlx5_cmd_check:816:(pid 10002): ALLOC_UAR(0x802) op_mod(0x0) failed, status limits exceeded(0x8), syndrome (0x5a7939)

2.ulimit -l output:

> unlimited

**Comment by razor1991** [comment]
@yosefe 
I also try to decrease ppn, when I decrease to 250 ppn, osu_init is OK.

> mpirun -N 250 --hostfile ./2hf -x UCX_TLS=sm,rc -x UCX_NET_DEVICES=mlx5_0:1 -mca btl ^vader,tcp,uct,openib --oversubscribe ./osu_init

> OSU MPI Init Test v5.9
> nprocs: 500, min: 1781 ms, max: 3586 ms, avg: 2663 ms

Is there anything I forgot to set?

**Comment by yosefe** [comment]
@razor1991 can you pls increase PF_LOG_BAR_SIZE, as described in https://github.com/open-mpi/ompi/issues/6854?

**Comment by razor1991** [comment]
@yosefe thanks very much. it solved my problem.
