### ISSUE TITLE
Initialization segfault

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#847]
On a system where the IB port is not ACTIVE, UCX fails with segfault:
Command line
```
mpirun -np 1 -H node  --mca spml ucx  -x UCX_TLS=rc_mlx5,ud -x MLX5_CQE_SIZE=64  ./app
```

```
/home/ubuntu/ucx/contrib/../src/ucp/core/ucp_context.c: [ ucp_cleanup() ]
      ...
      674 
      675 void ucp_cleanup(ucp_context_h context)
      676 {
==>   677     ucp_free_resources(context);
      678     ucp_free_config(context);
      679     ucs_free(context);
      680 }
```

**Comment by yosefe** [comment]
This is a bug in ompi spm/ikrit which is calling ucp_cleanup() from mca_spml_ucx_component_close() despite ucp_init() failed.

**Comment by shamisp** [comment]
@yosefe  do I have to open a corresponding bug in ompi

**Comment by yosefe** [comment]
yes

**Comment by shamisp** [comment]
Can you please do it ?

**Comment by shamisp** [comment]
I would prefer to keep it open and  we will close it once ompi issue is addressed

**Comment by yosefe** [comment]
fixed in https://github.com/open-mpi/ompi/pull/2218
