### ISSUE TITLE
Follow priority when choosing a device to use

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#851]
Currently ucx will choose a device for usage according to a score - the device with the highest score will be chosen. If two devices have the same score, the first one checked will be chosen.

Need to add a mechanism which will set a priority per device so that if several devices have the same score, the chosen one will be the one with the highest priority and not the one that appeared first on the device list. 
For example - posix and sysv have the same score but if we want sysv to be chosen, need to set its priority to a higher value than posix, since posix appears first. Same for HCAs.

**Comment by yosefe** [comment]
Let's make this task part of training for now.

**Comment by yosefe** [comment]
fixed in #893
