### ISSUE TITLE
OSHMEM segfault

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#854]
It seems that OSHMEM dynamic proc flow is completely broken when it is user with ucx.

In order to reproduce:
```
 mpirun -np 4 -npernode 2 -H node-1,node-2  --mca spml ucx  -x UCX_TLS=rc_mlx5,ud -x MLX5_CQE_SIZE=64  APP
```
Note: It works fine if IB is disabled.

Temporary workaround:

```
 mpirun -np 4 -npernode 2 -H node-1,node-2  --mca spml ucx -x   -x UCX_TLS=rc_mlx5,ud -x OMPI_MCA_mpi_add_procs_cutoff=10000000 -x MLX5_CQE_SIZE=64  APP
```

**Comment by shamisp** [comment]
The same code is passing with yoda spml and dynamic proc.

**Comment by yosefe** [comment]
@alex-mikheev can we close this now?

**Comment by yosefe** [comment]
closing this since ucx works with ompi master
