### ISSUE TITLE
error in shm/test_ucp_wireup_tag.stress_connect2/0

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#856]
```
 [ RUN      ] shm/test_ucp_wireup_tag.stress_connect2/0
 [1467126126.737807] [jenkins01:17301:4]       mm_posix.c:369  UCX  ERROR Error returned from shm_open/open in attach. No such file or directory. File name is: /ucx_posix_mm__jenkins01_2941e407d02eade9
 [1467126126.737823] [jenkins01:17301:4]          mm_ep.c:76   UCX  ERROR failed to connect to remote peer with mm. remote mm_id: 11891631804999448486
 [jenkins01:17301:5] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
 ./contrib/test_jenkins.sh: line 222: 16863 User defined signal 1   $AFFINITY $TIMEOUT make -C test/gtest test UCS_HANDLE_ERRORS=bt
 
 /var/lib/jenkins/jobs/gh-ucx-pr/workspace-2/contrib/../src/ucp/core/ucp_ep.c: [ ucp_ep_destory_uct_eps() ]
       ...
       176 
       177     for (lane = 0; lane < ucp_ep_num_lanes(ep); ++lane) {
       178         uct_ep = ep->uct_eps[lane];
 ==>   179         uct_ep_pending_purge(uct_ep, ucp_request_release_pending_send, NULL);
       180         ucs_debug("destroy ep %p lane %d uct_ep %p", ep, lane, uct_ep);
       181         uct_ep_destroy(uct_ep);
       182     }
```
Might be fixed with the WIP disconnect flow.

**Comment by yosefe** [comment]
@alinask can you please check why shm file name is in / directory?
`File name is: /ucx_posix_mm__jenkins01_2941e407d02eade9`

**Comment by alinask** [comment]
@yosefe it's only the printing of the name of the file. it's not really in the / directory. 
it's because the error is printed after shm_open or open fails, but we dont check which one it was that failed to make the code simpler and shorter.
https://github.com/openucx/ucx/blob/master/src/uct/sm/mm/mm_posix.c#L369 
you think a separate check is required?

**Comment by yosefe** [comment]
@alinask can we print the correct directory, or not print the / at all? currently the error is misleading

**Comment by alinask** [comment]
@yosefe printing the directory means to add an 'if' to check if open or shm_open was used. 
/ is part of the file's name. but i can print the name starting the second char.

**Comment by yosefe** [comment]
let's add the if - it is useful for debug

**Comment by yosefe** [comment]
happens because one side gets WIREUP_REQUEST from a context which is already destroyed.
solution should be as part of disconnect flow, to make sure all messages are flushed before destroying.
