### ISSUE TITLE
CAS over network ?

### ISSUE THREAD

**Issue by g302ge** [openucx/ucx#8626]
I found that the ucx has the api `ucp_mem_map` but if there is a possiblity to use atomic CAS over the memory which mmap from remote node to this node ?

**Comment by yosefe** [comment]
yes, with https://github.com/openucx/ucx/blob/c5d5b0ca9b77aace33bf90eec42743084e91941b/src/ucp/api/ucp.h#L3775

**Comment by g302ge** [comment]
> yes, with
> 
> https://github.com/openucx/ucx/blob/c5d5b0ca9b77aace33bf90eec42743084e91941b/src/ucp/api/ucp.h#L3775

well, thx for ur reply
