### ISSUE TITLE
Does this lib support RoCE-v2?

### ISSUE THREAD

**Issue by dragon-zhang** [openucx/ucx#8633]
Does this lib support RoCE-v2? Also, I want to ask that does it support soft-RoCE ?

**Comment by shamisp** [comment]
ROCE-v2  - yes, it is tested on ROCE. 
soft-ROCE - in theory yes but it has not been tested. When I have tried soft-ROCE a  year ago, the kernel module was not stable to pass all the unit tests.

**Comment by dragon-zhang** [comment]
Thanks !
