### ISSUE TITLE
AMO emulation functions

### ISSUE THREAD

**Issue by MattBBaker** [openucx/ucx#864]
A "Works on Titan thing". I was asked to provide this for a more complete inspection. It adds a src/ucp/amo/emulated_amo.{c,h}" file, rigs basic_amo.c to hardware the emulated amos, and short circuits select.c in the wireup logic to over look missing AMOs. On titan this allows all the AMO functions in UCP to work over Gemini in spite of the lack of hardware support.

Branch is here:
https://github.com/MattBBaker/ucx/tree/topic/soft-amo-functions

**Comment by yosefe** [comment]
done
