### ISSUE TITLE
Does `ucp_config_modify` allow setting UCT configurations?

### ISSUE THREAD

**Issue by pentschev** [openucx/ucx#8649]
In the past there were changes that prevented us from validating non-UCP configurations, but as mentioned by @yosefe in https://github.com/openucx/ucx/issues/7519#issuecomment-953704767, we should be allowed to specify UCT configurations as well. However, I'm seeing warnings when trying to set some of those options, for example:

```python
In [1]: import ucp

In [2]: ucp.init({"RNDV_SCHEME": "get_zcopy", "TCP_RX_SEG_SIZE": "8K"})
[1666266334.366280] [dgx13:78547:0]      ucp_worker.c:2146 UCX  WARN  invalid configuration: TCP_RX_SEG_SIZE=8K
```

`ucp.init()` is a function from UCX-Py that will take the options to pass to `ucp_config_modify` and then create a context. Clearly, `UCX_RNDV_SCHEME` was accepted, but `UCX_TCP_RX_SEG_SIZE` was reject which should be a UCT-layer config. Is this supposed to work?

**Comment by changchengx** [comment]
> [1666266334.366280] [dgx13:78547:0]      ucp_worker.c:2146 UCX  WARN  invalid configuration: TCP_RX_SEG_SIZE=8K
@pentschev Please try to use ```RX_SEG_SIZE``` without the leading ```TCP_```

**Comment by pentschev** [comment]
Thanks @changchengx , that indeed works. But won't that result in `RX_SEG_SIZE` changing for all transports? And why does the leading `TCP_` not work if that's listed in `ucx_info -f`?

**Comment by changchengx** [comment]
@pentschev 
>
> But won't that result in RX_SEG_SIZE changing for all transports?
Currently, no

>
> And why does the leading TCP_ not work
It's related with parsing rules. We don't want to complex the code of parsing & applying the rules.

**Comment by pentschev** [comment]
Understood, thanks @changchengx for clarifying those questions!

**Comment by pentschev** [comment]
Actually, I forgot one last question, we are allowed to pass UCP and UCT options to `ucp_config_modify`, but not UCM (for example), is that right? For example, it seems we are unable to specify `MEM_LOG_LEVEL`:

```python
In [1]: import ucp

In [2]: ucp.init({"MEM_LOG_LEVEL": "TRACE"})
[1666348186.663626] [dgx13:72810:0]      ucp_worker.c:2175 UCX  WARN  invalid configuration: MEM_LOG_LEVEL=TRACE
```

Could you confirm if that's the case @changchengx ? Just want to understand what are the limitations of `ucp_config_modify`.

**Comment by changchengx** [comment]
@pentschev should be ucp & uct

**Comment by pentschev** [comment]
Thanks @changchengx !
