### ISSUE TITLE
[UCX/1.10.2] Too many ep configuration

### ISSUE THREAD

**Issue by vitduck** [openucx/ucx#8730]
When performing HPL benchmarks with more than 200 GPUs, we encounter the following error: 
 ```
 ucp_worker.c:1836 UCX  ERROR too many ep configurations: 16 (max: 16)
``` 
The NGC container, provided by NVIDIA, was built with Open MPI and UCX/1.10.2. 

Going through the release note, it seems that the limit was raised to 64 since UCX/1.11.0: 
```
Increased UCP_WORKER_MAX_EP_CONFIG to 64
```
We think that it corresponds to number of GPUs, but it would be  far too restricted for any large-scale run. 

So what exactly constitutes an end point (ep) ? 
For better performance, do we need to tune this parameter ? 

Thanks.

**Comment by yosefe** [comment]
The number of configurations depends on how many different combinations of remote/local configurations exist on a specific worker. It does not depend on the number of machines in the job (as long as these machines have same configuration).
Anyway, 64 should be more than enough, is it possible to switch to latest UCX version?

**Comment by vitduck** [comment]
Thanks for clarification. 

Our situation is somewhat unique where a mixture of V100/A100 nodes with different topologies are used. 
Below are the debug message obtained via ```UCX_LOG_LEVEL=info```
- gpu16: 4 V100, i.e 0.25 port per GPU (non-NVLINK)
```
[gpu16:17663:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[0]: tag(cuda_copy/cuda); rma(gdr_copy/cuda);
[gpu16:17663:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[1]: tag(cuda_copy/cuda); rma(cuda_copy/cuda);
[gpu16:17663:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[2]: tag(self/memory0 cma/memory rc_mlx5/mlx5_0:1 cuda_copy/cuda);
[gpu16:17663:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[3]: tag(posix/memory cma/memory rc_mlx5/mlx5_0:1 cuda_ipc/cuda);
[gpu16:17663:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[4]: tag(rc_mlx5/mlx5_0:1);
[gpu16:17663:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[5]: tag(rc_mlx5/mlx5_0:1);
...
```
- gpu31: 8 A100, i.e 0.5 port per GPU (HGX-1/NVLINK)
```
[gpu31:50180:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[0]: tag(cuda_copy/cuda); rma(gdr_copy/cuda);
[gpu31:50180:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[1]: tag(cuda_copy/cuda); rma(cuda_copy/cuda);
[gpu31:50180:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[2]: tag(self/memory0 cma/memory rc_mlx5/mlx5_0:1 cuda_copy/cuda);
[gpu31:50180:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[3]: tag(posix/memory cma/memory rc_mlx5/mlx5_0:1 cuda_ipc/cuda);
[gpu31:50180:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[4]: tag(posix/memory cma/memory rc_mlx5/mlx5_2:1 cuda_ipc/cuda);
[gpu31:50180:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[5]: tag(rc_mlx5/mlx5_0:1 rc_mlx5/mlx5_2:1);
[gpu31:50180:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[6]: tag(rc_mlx5/mlx5_0:1 posix/memory cma/memory cuda_ipc/cuda); rma(rc_mlx5/mlx5_0:1 posix/memory sysv/memory);
[gpu31:50180:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[7]: tag(rc_mlx5/mlx5_0:1 posix/memory cma/memory cuda_ipc/cuda); rma(rc_mlx5/mlx5_0:1 posix/memory sysv/memory);
[gpu31:50180:0]      ucp_worker.c:1777 UCX  INFO    ep_cfg[8]: tag(rc_mlx5/mlx5_0:1 rc_mlx5/mlx5_2:1); rma(rc_mlx5/mlx5_0:1);
...
```
As you said, each end point (ep) corresponds to a UCX protocol combination: 
- 0: gdr_copy (local) 
- 1: cuda_copy (local) 
- 2: gdr_copy (remote via rc) 
- 3: cuda_copy (remote via rc) 
- \>4: remote via rc 

Our mixed partition actually contains nodes with 4 different configurations. 
Pair-wise connection between them introduces addition remote rc pairs, increasing total number of ep_cfg. 
Is this a correct understanding ? 

We have slated the container's UCX with 1.11.2 version. 
UCX already offers noticeable performance improvement out of the box with all default parameters. 
Do you perhaps have further suggestions for optimizing heterogenous case like this, such as tuing eager/rdnv/zcopy threshold ?

**Comment by yosefe** [comment]
Yes, this is a correct understanding. Heterogeneous cases have more endpoint "types" because of possible combinations.
The thresholds are auto-calculated, but you could try tuning `UCX_RNDV_THRESH` and `UCX_ZCOPY_THRESH` environment variables to squeeze more performance. For example `export UCX_RNDV_THRESH=1g` or `UCX_RNDV_THRESH=1k`

**Comment by vitduck** [comment]
Thanks for your advice. 

I would like to close this issue.
