### ISSUE TITLE
ODP cleanup broken?

### ISSUE THREAD

**Issue by alex--m** [openucx/ucx#8735]
I'm getting the following SEGV during cleanup:
```
...
#0    Object "/usr/lib/libuct_ib.so.0", at 0x7f9d25255433, in uct_ib_md_close
Segmentation fault (Address not mapped to object [0x11])
```

Looks like ODP cleanup is broken... According to GDB, `md->global_odp` is of type `uct_ib_mem_t*` (like `uct_ib_memh_dereg` expects) and not `uct_md_mem_dereg_params_t*` (like `uct_ib_memh_dereg` expects):
```
(gdb) p params
$9 = (const uct_md_mem_dereg_params_t *) 0x80003847f0
(gdb) p *params
$10 = {field_mask = 2256743321568383, flags = 0, memh = 0x1, comp = 0x800038e8b0}
(gdb) p *(uct_ib_mem_t*)params
$11 = {lkey = 525439, rkey = 525439, atomic_rkey = 0, indirect_rkey = 0, flags = 1}
(gdb) 
```
Should it be changed as follows?
```
diff --git a/src/uct/ib/base/ib_md.c b/src/uct/ib/base/ib_md.c
index c0afd5946..06d87d847 100644
--- a/src/uct/ib/base/ib_md.c
+++ b/src/uct/ib/base/ib_md.c
@@ -1459,7 +1459,7 @@ static void uct_ib_md_release_reg_method(uct_ib_md_t *md)
         ucs_rcache_destroy(md->rcache);
     }
     if (md->global_odp != NULL) {
-        uct_ib_mem_dereg(&md->super, md->global_odp);
+        uct_ib_memh_dereg(md, md->global_odp);
     }
 }
```

**Comment by gleon99** [comment]
@alex--m 
Can you elaborate please?
1. What scenario has lead to this situation?
2. Do you have the stack from the SEGFAULT?
3. The `(gdb) p params...` snippet - where does it come from?

Anyway, we are going to remove ODP soon as part of more general IB cleanup,

**Comment by alex--m** [comment]
Re. ODP - that's unfortunate, because I'm aware of some large organizations which rely on this feature and will likely stay with the last version supporting it.

Re. reproducer - I don't have it handy to run, so I'm relying on what I recorded when I encountered the problem (it was pretty clear so i didn't save too much detail):
1. I'm pretty sure any time you'd use `-x UCX_IB_REG_METHODS=odp` it should trigger this problem. If I'm right, than this line should never succeed.
2. Originally got this:
```
Stack trace (most recent call last):
#11   Object "/home/alexm/test", at 0x7f9d2832fb49, in 
#10   Object "/usr/lib/libmpi.so.40", at 0x7f9d27e259f4, in PMPI_Init
#9    Object "/usr/lib/libmpi.so.40", at 0x7f9d2805c438, in ompi_mpi_init
#8    Object "/usr/lib/libopen-pal.so.40", at 0x7f9d25ca11cf, in mca_base_framework_open
#7    Object "/usr/lib/libmpi.so.40", at 0x7f9d27feec69, in 
#6    Object "/usr/lib/libopen-pal.so.40", at 0x7f9d25c906af, in mca_base_framework_components_open
#5    Object "/usr/lib/libmpi.so.40", at 0x7f9d27ff8c49, in 
#4    Object "/usr/lib/libmpi.so.40", at 0x7f9d27ff52b8, in mca_pml_ucx_open
#3    Object "/usr/lib/libucp.so.0", at 0x7f9d259ab105, in ucp_init_version
#2    Object "/usr/lib/libucp.so.0", at 0x7f9d259acb75, in 
#1    Object "/usr/lib/libuct.so.0", at 0x7f9d258e43ba, in uct_md_close
#0    Object "/usr/lib/libuct_ib.so.0", at 0x7f9d25255433, in uct_ib_md_close
Segmentation fault (Address not mapped to object [0x11])
```
3. It's from GDB attached from `uct_ib_mem_global_odp_dereg()`, which is admittedly missing from the stack trace because it was not obtained through GDB but through UCX's built-in stack-trace-emitting functionality.

**Comment by gleon99** [comment]
Actually we also have plans to renovate and refactor the ODP support for the next UCX version. Anyway, at the first phase we will at least remove it, including the code mentioned in this issue, so I think we can close this one for now.

**Comment by alex--m** [comment]
Sure, I don't mind (I fixed it in my fork).
Thanks @gleon99
