### ISSUE TITLE
UCX testing procedure

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#874]
Please add a short text file to ucx/doc, or to ucx wiki, to describe the mandatory procedure for testing.
For example:
-   Every change should have a unit test
-   Which tests are running now (Jenkins, gtest, cov, valgrind,...)
-   When to test on IMB large scale
  o   E,g run a benchmark (IMB for example) on one host with ppn=16 with UCX_SHM_DEVICES=posix 
-   MTT

**Comment by alinask** [comment]
Added to the UCX wiki for a an easier maintenance:
https://github.com/openucx/ucx/wiki/UCX-Testing-Procedure
