### ISSUE TITLE
Build issue on Arch Linux

### ISSUE THREAD

**Issue by Ergus** [openucx/ucx#8753]
### Describe the bug

WIth gcc-12 I get this error when trying to compile following the instructions in the documentation:

```
debug/debug.c: In function 'load_file':
debug/debug.c:275:53: error: 'PTR' undeclared (first use in this function)
  275 |     symcount = bfd_read_minisymbols(file->abfd, 0, (PTR)&file->syms, &size);
      |                                                     ^~~
debug/debug.c:275:53: note: each undeclared identifier is reported only once for each function it appears in
```

### Steps to Reproduce
- Command line
```
wget https://github.com/openucx/ucx/releases/download/v1.13.1/ucx-1.13.1.tar.gz
tar xzf ucx-1.13.1.tar.gz
cd ucx-1.13.1
./contrib/configure-release --prefix=$PWD/install
make -j8 install
```
- UCX version used (from github branch XX or release YY) + UCX configure flags (can be checked by `ucx_info -v`)
- **Any UCX environment variables used**
None

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
   - `cat /etc/issue` or `cat /etc/redhat-release` + `uname -a`

   Arch Linux, 
   Linux Ergus 6.0.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 02 Dec 2022 17:25:31 +0000 x86_64 GNU/Linux
 
This issue is also mentioned here: https://aur.archlinux.org/packages/openucx

**Comment by raffenet** [comment]
https://github.com/openucx/ucx/pull/8450 addressed this in master.

**Comment by Ergus** [comment]
Got it
