### ISSUE TITLE
UCP/wireup/address zero length device_address is not supported

### ISSUE THREAD

**Issue by shssf** [openucx/ucx#878]
In function ucp_address_do_pack() expected [dev_addr_len](https://github.com/openucx/ucx/blob/master/src/ucp/wireup/address.c#L279) should be greater than zero. in case of dev_addr_len is zero the buffer contains no filed with the address.

In case of unpacking this buffer in ucp_address_unpack() the [dev_addr](https://github.com/openucx/ucx/blob/master/src/ucp/wireup/address.c#L484) will points to another fileds in the message (csum and iface_attr) if dev_addr_len is zero. Later, this dev_addr pointer passed to [uct_iface_is_reachable](https://github.com/openucx/ucx/blob/master/src/ucp/wireup/select.c#L118) with no changes as `ae->dev_addr`

I suspect this behaviour isn't good from fault tolerance perspective. At least, we have to do assert(dev_addr_len).

**Comment by yosefe** [comment]
but a transport which exposes zero-size device address should ignore the device_addr pointer in its implementation of `uct_iface_is_reachable`

**Comment by shssf** [comment]
Fixed in PR #882
