### ISSUE TITLE
ud/uct_flush_test.put_bcopy_flush_ep_no_comp hang

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#879]
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2132/console
```
12:21:29 [       OK ] ud/uct_flush_test.put_bcopy_flush_ep_no_comp/1 (98 ms)
12:21:29 [ RUN      ] ud/uct_flush_test.am_pending_flush_nb/1
13:26:29 make: *** [test] Terminated
```

**Comment by brminich** [comment]
The one which hangs is uct_flush_test.am_pending_flush_nb. 
For some reason ep can't resend a lost packet to its peer due to:
- its ep->tx.pending.elem.next is not NULL (thus it is not added to the group with ucs_arbiter_group_push_elem)
- in the meantime ep->tx.pending.group.tail is NULL which lead to pendings dispatch not being run.

**Comment by yosefe** [comment]
@alex-mikheev can it be related to the recent arbiter change?

**Comment by brminich** [comment]
@yosefe, the problem is reproduced with that change rolled back

**Comment by yosefe** [comment]
another failure:
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2140/consoleFull
```
20:02:53 [       OK ] ud/uct_flush_test.am_flush_ep_nb/0 (30 ms)
20:02:53 [ RUN      ] ud/uct_flush_test.am_pending_flush_nb/1
20:02:54 /var/lib/jenkins/jobs/gh-ucx-pr/workspace-4/contrib/../test/gtest/uct/test_flush.cc:357: Failure
20:02:54 Value of: flush_req.comp.count == 1
20:02:54   Actual: false
20:02:54 Expected: true
20:02:54 [  FAILED  ] ud/uct_flush_test.am_pending_flush_nb/1, where GetParam() = ud/mlx5_0:1 (1080 ms)
20:02:54 [ RUN      ] ud/uct_flush_test.am_zcopy_flush_iface_no_comp/0
```

**Comment by yosefe** [comment]
http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/2141/console
```
15:13:32 [ RUN      ] ud_mlx5/uct_flush_test.am_pending_flush_nb/0
16:25:13 make: *** [test] Terminated
16:25:13 Build step 'Execute shell' marked build as failure
```
