### ISSUE TITLE
self transport fixes

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#888]
- check what MPI and shmem spec says about overlapping source/receive buffers for "self"
- if we can, move 'self' under 'shm' and put common put/atomics inside shm/base

**Comment by abouteiller** [comment]
In MPI 3.1, chapter 11.3 line 44

> "the outcome of concurrent conflicting accesses to the same memory location s undefined [...] Exception to this rule; the same location  can be updated by several concurrent accumulate calls, the outcome is 'as if' updates occurred in some order.
> [...]
> For all RMA calls, the target process may be identical with the origin process, i.e. a process may use RMA to move data in its memory. 

It appears that it is legal to use accumulate on self with the same target and origin. It is not very clear that it is illegal to use overlapping target and source on self with PUT/GET, but I would tend to think it is.

**Comment by shssf** [comment]
@yosefe  if atomic/put/get put back into shm no source left in uct/uct_base_ep.c . Should I delete base_ep.c after this?
