### ISSUE TITLE
Q: How do many network adapters (into a single node) correlate with multi-rail concept?

### ISSUE THREAD

**Issue by vasslavich** [openucx/ucx#8922]
Hello, dear colleagues!
This isn't a bug. **I have some questions about UCX multi-rail future**.
I have two PCIe network adapters into each node in a cluster. That adapters allow build a network via PCIe like tcp and IB. Thus, server's topology has lanes x 2. Theoretical I can parallelize data transfers between 2 lanes.
I want to add an experimental multi-lanes PCIe support into UCX and bench it. 
**The questions are**: 

- suppose, I have `UCX_MAX_RNDV_RAILS=2`,
- UCX multi-rail means using two _iface_ objects `iface(PCIe)+iface(Ethernet)` for a parallelization of data transfers?,
- how should I design two PCIe devices into UCT level? - case A: two end-point per one iface `one iface(PCIe) + two end-points(ep0, ep1)` or case B: a one end-point per iface ` iface(PCIe0) + end-point` + `iface(PCIe1) + end-point`?
- but, is case A not a multi-rail then?
- what case is right?

Thanks a lot in advance!

**Comment by yosefe** [comment]
both cases are considered multi-rail.
the decision is based on whether these 2 endpoints are created on same device or not. according to "I have two PCIe network adapters into each node ", than each adapter would have a separate uct_iface_t object and there would be one endpoint on each uct_iface - caseB. UCT layer should advertise 2 devices from uct_md_query_tl_resources() API, then UCP layer would create 2 uct_iface objects on each of them and will split the data between the 2 devices in case of rndv protocol.

**Comment by vasslavich** [comment]
@yosefe , thank you for your attention! 
It seems, I understood this case:
- uct_md_query_tl_resources() have to return 2,
- UCP layer creates 2 uct_iface_t objects, 
- each adapter has a separate uct_iface_t object and there is one endpoint on each uct_iface_t, 
- UCP splits data between this two uct_iface_t objects. 
That's right?). 

And, what about another case: one uct_iface_t object with two endpoints, does this configuration make sense? What does uct_md_query_tl_resources() have to return?

**Comment by yosefe** [comment]
> That's right?).

Yes
 
> And, what about another case: one uct_iface_t object with two endpoints, does this configuration make sense? What does uct_md_query_tl_resources() have to return?

It's a case where 2 connections from one devices are needed to get higher BW than one connection, for example RoCE LAG, in this case uct_md_query_tl_resources has to return 2 and uct_iface_query must return num_paths=2 (instead of 1)

**Comment by vasslavich** [comment]
Hi, @yosefe ! Thank you, your answers really help me!
