### ISSUE TITLE
Unexpected assertion failure in ucs

### ISSUE THREAD

**Issue by KaimingOuyang** [openucx/ucx#9021]
### Describe the bug
Hi UCX experts,
I recently faced the following error:

> sys.c:258  Assertion `errno == 0' failed
> BFD: DWARF error: section .debug_info is larger than its filesize! (0x93ef57 vs 0x530ea0)
> BFD: DWARF error: section .debug_info is larger than its filesize! (0x93ef57 vs 0x530ea0)
> ==== backtrace (tid: 840809) ====
>  0 0x000000000006eae8 ucs_sysconf()  /build-result/src/hpcx-v2.14-gcc-MLNX_OFED_LINUX-5-ubuntu20.04-cuda11-gdrcopy2-nccl2.16-x86_64/ucx-5e8621f95002cf2ad7135987c2a7dc32d4fc72fb/src/ucs/sys/sys.c:258
>  1 0x0000000000009dd7 ucs_vfs_fuse_thread_reset_affinity()  /build-result/src/hpcx-v2.14-gcc-MLNX_OFED_LINUX-5-ubuntu20.04-cuda11-gdrcopy2-nccl2.16-x86_64/ucx-5e8621f95002cf2ad7135987c2a7dc32d4fc72fb/src/ucs/vfs/fuse/vfs_fuse.c:362
>  2 0x0000000000009dd7 ucs_vfs_fuse_thread_func()  /build-result/src/hpcx-v2.14-gcc-MLNX_OFED_LINUX-5-ubuntu20.04-cuda11-gdrcopy2-nccl2.16-x86_64/ucx-5e8621f95002cf2ad7135987c2a7dc32d4fc72fb/src/ucs/vfs/fuse/vfs_fuse.c:388
>  3 0x0000000000008609 start_thread()  /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477
>  4 0x000000000011f133 clone()  ???:0

The related code snippet is https://github.com/openucx/ucx/blob/81f407b1f1b933cd915c8e7745edd78d10c22145/src/ucs/sys/sys.c#L252-L261

It looks like a ucs bug since we should first check whether `rc == -1` and then check `errno` instead of checking `errno` only.

We write a simple program to call `sysconf(_SC_NPROCESSORS_CONF)`; it works without an issue.

### Setup and versions
- OS version Ubuntu 20.04.3 LTS + CPU architecture x86_64
- UCX version used (from github branch master commit 5e8621f95002cf2ad7135987c2a7dc32d4fc72fb)

**Comment by shamisp** [comment]
@KaimingOuyang pls fee to propose patch. FYI, UCX project requires signed CLA.
