### ISSUE TITLE
1.14.1 release?

### ISSUE THREAD

**Issue by jakirkham** [openucx/ucx#9070]
Was curious when the 1.14.1 release might come out. No worries if this isn't completely known yet. Just trying to get a rough idea. Thanks for your help! 🙏

**Comment by jakirkham** [comment]
Some prior related discussion here ( https://github.com/openucx/ucx/issues/8936#issuecomment-1468419592 )

**Comment by yosefe** [comment]
fixed by @shamisp 
https://github.com/openucx/ucx/releases/tag/v1.14.1

**Comment by jakirkham** [comment]
Thanks Pavel & Yossi! 🙏
