### ISSUE TITLE
Does ucx allow to invoke ucp_request_free() in recv callback ?

### ISSUE THREAD

**Issue by chenyidu** [openucx/ucx#9131]
## What
When `ucp_tag_recv_common()` goes to  the following code, it always returns `req+1`
https://github.com/openucx/ucx/blob/a4840a3be01fd124e8c6089a3729e8e22094b4fd/src/ucp/tag/tag_recv.c#L170-L179

But I found that it may complete the request and execute the user's callback function
`ucp_tag_recv_eager_multi() -> ucp_request_process_recv_data() `
https://github.com/openucx/ucx/blob/a4840a3be01fd124e8c6089a3729e8e22094b4fd/src/ucp/core/ucp_request.inl#L883-L887

The above two functions will call `ucp_request_complete()` and then enter to user callback,

If I call `ucp_request_free()` in callback，the returned `req + 1` seems invalid. But some ucx code do invoke `ucp_request_free()` in callback that makes me very confused.
https://github.com/openucx/ucx/blob/a4840a3be01fd124e8c6089a3729e8e22094b4fd/src/tools/perf/lib/ucp_tests.cc#L293-L299

Does ucx not allow such behavior or it's a bug ? Looking forward to an answer, thanks in advance !

**Comment by yosefe** [comment]
The code in ucp_tests.cc does not use the request pointer returned from ucp_tag_recv_nbx() so it works even though "req+1" is already an invalid pointer

**Comment by chenyidu** [comment]
@yosefe Thank you for your reply. At `ucp_tests.cc`, it only performs the following checks and does not dereference, so there will be no problem. 
https://github.com/openucx/ucx/blob/a4840a3be01fd124e8c6089a3729e8e22094b4fd/src/tools/perf/lib/ucp_tests.cc#L487-L491
But the actual situation is  more complex. If the returned request ptr is not UCS_OK or error, I will assume that request is still outstanding and try to use `ucp_request_check_ status()` or `ucp_request_ is_ completed ()` to check its status. Based on its status, i'll release some resources.  But the request and resources have already been released in the callback. 
So why not return UCS_OK when the request is completed ? It doesn't seem difficult to implement. Is there any special consideration?

**Comment by chenyidu** [comment]
I suddenly realized that when it returns UCS_OK, it also means that the callback has not been executed. Perhaps I shouldn't release the request in the callback
