### ISSUE TITLE
Question: Is there a way to know in ep_am_zcopy that the packet is last in this message?

### ISSUE THREAD

**Issue by vasslavich** [openucx/ucx#9144]
Hello, dear colleagues!

UCX v.1.12.1

I'm implementing a custom UCT module over shared memory and the size(shared memory) << size(message). I use `ep_am_zcopy` and I found the function `ucp_do_am_zcopy_multi` splits the source message into packets of `max_zcopy` length. Next, it loops for each package and calls `ep_am_copy`. I need to know about the last packet in function 'ep_am_zcopy' to sync. Unfortunately, this function doesn't have any special information about it. 
Perhaps, is there another way: 
- to know where is the package's location in the source message size?, or
- to implement passing of big messages with an additional information about a request to UCT level?

ep_am_zcopy is:
```
typedef ucs_status_t (*uct_ep_am_zcopy_func_t)(uct_ep_h ep,
                                               uint8_t id,
                                               const void *header,
                                               unsigned header_length,
                                               const uct_iov_t *iov,
                                               size_t iovcnt,
                                               unsigned flags,
                                               uct_completion_t *comp);
```

But, `uct_iov_t` doesn't contain that information too.

Thanks in advance for any ideas!

**Comment by brminich** [comment]
In UCP we use different headers for the first and other fragments of the message. This header contains offset of this chunk in the original message. So you could define some header format which would help you to assemble the message on the receiver

**Comment by vasslavich** [comment]
@brminich , I'm sorry, I was imprecise. Just I want to know, is there a way to figure out what is type packet (first,last), from parameters in `uct_ep_am_zcopy_func_t` on a sender side in UCT level?

```
.ep_am_zcopy = uct_my_am_zcopy(uct_ep_h ep,
                                               uint8_t id,
                                               const void *header,
                                               unsigned header_length,
                                               const uct_iov_t *iov,
                                               size_t iovcnt,
                                               unsigned flags,
                                               uct_completion_t *comp){

if( is_last_packet(ep, id, header, ...)){
    // do something...
    }
}
```
What should I check in `is_last_packet` or, it's impossible to find out?
Thank you, @brminich !

**Comment by brminich** [comment]
There is no message fragmentation concept on `UCT` level. Every UCT send operation is self-contained, thus it is up to `UCT` user to implement message fragmentation/assembly (like we do it in `UCP`)

**Comment by vasslavich** [comment]
I got it, thank you!
