### ISSUE TITLE
gdr_copy on mem type cuda seg faulting

### ISSUE THREAD

**Issue by shimmybalsam** [openucx/ucx#9190]
### Describe the bug
seg fault when running with memory type cuda. 
<img width="1257" alt="image" src="https://github.com/openucx/ucx/assets/38699071/05b2f2c1-a7e2-4a0d-86c8-4422ae297192">

### Steps to Reproduce

clone ucc
module load hpcx-gcc dev/cuda-latest
./authogen
mkdir build
cd build
../configure --prefix=$PWD/install --woth_ucx=$HPCX_UCX_DIR --with-mpi --enable_debug --enable-gtest --with-cuda=$CUDA_HOME
make -j install
cd test/gtest

- Command line:
UCX_ERROR_SIGNALS=ILL,SEGV,BUS,FPE,ABRT UCX_HANDLE_ERRORS=freeze UCC_TL_SHARP_TUNE=0 UCC_TL_NCCL_TUNE=0 UCX_IB_GPU_DIRECT_RDMA=n ./gtest --gtest_filter=test_alltoall_0.single_onesided/2

If add flag UCX_TLS=^gdr_copy then there is no error. 

- UCX version used from @HPCX_UCX_DIR in module hpcx-gcc
- UCC master

### Setup and versions
run on gpu swx-gdx01 from (but happens also in CI on swx-clx01)
cuda module: dev/cuda-latest

**Comment by yosefe** [comment]
according to the output, ucc passes NULL to uct_md_mem_reg which is illegal

**Comment by shimmybalsam** [comment]
@yosefe in ucc we never call uct, we call ucp_tag_send_nbx(ep, buffer, 1, ucp_tag, &req_param); 
and these are the values of the params that we call with (nothing is NULL):
<img width="1185" alt="image" src="https://github.com/openucx/ucx/assets/38699071/9fd46f0c-1c41-4f12-84a4-9caf65a4830a">

**Comment by shimmybalsam** [comment]
Issue was found to be inside ucc test, in which we allocate host buffer but tag is as mem type cuda. Closing this issue as it is not connected to ucx.
