### ISSUE TITLE
setting UCX_LOG_BUFFER=auto causes to segmentation fault

### ISSUE THREAD

**Issue by alexvm** [openucx/ucx#923]
Steps:
export UCX_LOG_LEVEL=trace/debug
export UCX_LOG_BUFFER=auto 
./ucp_hello_world -n IP
Segmentation fault (core dumped)

**Comment by alinask** [comment]
#
# Buffer size for a single log message.
#
# Syntax: memory units: <number>[b|kb|mb|gb], "inf", or "auto"
#
UCX_LOG_BUFFER=1024

'inf' and 'auto' aren't supported currently. 
(they are part of the print of the mem units config type)

**Comment by shamisp** [comment]
Still, it should not segfault.
