### ISSUE TITLE
Build with cuda fails on master

### ISSUE THREAD

**Issue by bathmatt** [openucx/ucx#9260]
### Describe the bug
Starting at the commit listed below one cannot compile ucx with cuda.  I have uploaded a docker file and command lines.
```
make[4]: Entering directory '/var/tmp/ucx/src/uct/cuda/gdr_copy'
  CC       libuct_cuda_gdrcopy_la-gdr_copy_md.lo
  CC       libuct_cuda_gdrcopy_la-gdr_copy_iface.lo
In file included from gdr_copy_md.c:22:
/var/tmp/ucx/src/uct/cuda/base/cuda_iface.h:13:10: fatal error: cuda_runtime.h: No such file or directory
   13 | #include <cuda_runtime.h>
      |          ^~~~~~~~~~~~~~~~
```

### Steps to Reproduce

On this version it started to happen

```
commit 0697b7cdd484c035dd4b1f7d99c034c05310434d (HEAD)
Author: Raul Akhmetshin <rakhmetshin@nvidia.com>
Date:   Mon Jul 24 18:59:34 2023 +0300

    UCT/CUDA/GDR_COPY: Cleaned up configure and makefile.
```

- Command line

./autogen.sh ; ./configure --prefix=/usr/local/ucx --disable-assertions --disable-backtrace-detail --disable-debug --disable-doxygen-doc --disable-logging --disable-params-check --disable-static --enable-mt --with-cuda=/usr/local/cuda --with-gdrcopy=/usr/local/gdrcopy --with-knem=/usr/local/knem ; make -j 45

### Setup and versions
Linux with nvidia container.

[Dockerfile.txt](https://github.com/openucx/ucx/files/12226786/Dockerfile.txt)

### Additional information (depending on the issue)
- OpenMPI version
- Output of `ucx_info -d` to show transports and devices recognized by UCX
- Configure result - config.log
- Log file - configure UCX with "--enable-logging" - and run with "UCX_LOG_LEVEL=data"

**Comment by rakhmets** [comment]
https://github.com/openucx/ucx/pull/9264 was merged.
Master branch should be fixed.
