### ISSUE TITLE
UCX_MEM_MMAP_HOOK_MODE=reloc assumes dynamic table is relocated

### ISSUE THREAD

**Issue by rbradford** [openucx/ucx#9283]
When using `UCX_MEM_MMAP_HOOK_MODE=reloc` (vs `=bistro`) the code for parsing the relocation tables assumes that the loader has relocated the entries in the dynamic table (`PT_DYNAMIC`) at runtime. Unfortunately depending on the C library or the architecture this is not the case.

The following test program (as derived from the UCX source code)
```C
#define _GNU_SOURCE
#include <link.h>
#include <stdlib.h>
#include <stdio.h>

#define UCS_PTR_BYTE_OFFSET(_ptr, _offset) \
        ((void *)((intptr_t)(_ptr) + (intptr_t)(_offset)))

static uintptr_t ucm_reloc_get_entry(ElfW(Addr) base, const ElfW(Phdr) *dphdr,
                                     ElfW(Sxword) tag)
{
        ElfW(Dyn) *entry;
        for (entry = (void *)(base + dphdr->p_vaddr); entry->d_tag != 0; ++entry) {
                if (entry->d_tag == tag) {
                        return entry->d_un.d_val;
                }
        }
        return 0;
}

static int callback(struct dl_phdr_info *info, size_t size, void *data)
{
        void *symtab, *strtab;
        ElfW(Phdr) *phdr, *dphdr;
        int found_pt_load;

        dphdr = NULL;
        found_pt_load = 0;
        for (int i = 0; i < info->dlpi_phnum; ++i) {
                phdr = UCS_PTR_BYTE_OFFSET(info->dlpi_phdr, sizeof(ElfW(Phdr)) * i);
                if (phdr->p_type == PT_LOAD) {
                        found_pt_load = 1;
                } else if (phdr->p_type == PT_DYNAMIC) {
                        dphdr = phdr;
                }
        }

        if (found_pt_load != 1) {
                return 0;
        }

        symtab = (void *)ucm_reloc_get_entry(info->dlpi_addr, dphdr, DT_SYMTAB);
        strtab = (void *)ucm_reloc_get_entry(info->dlpi_addr, dphdr, DT_STRTAB);
        printf("name=%s dlpi_addr=%p symtab=%p strtab=%p\n", info->dlpi_name, 
               (void *)info->dlpi_addr, symtab, strtab);
        return 0;
}

int main(int argc, char *argv[])
{
        dl_iterate_phdr(callback, NULL);
        exit(EXIT_SUCCESS);
}
```

Prints out the values for the symbol table (`symtab`) and string table (`strtab`) for the libraries that the program is running against.

Here is the result on x86-64 with glibc (Fedora 38):
```
name= dlpi_addr=(nil) symtab=0x4003e0 strtab=0x400470
name=linux-vdso.so.1 dlpi_addr=0x7ffdea5f7000 symtab=0x1c8 strtab=0x300
name=/lib64/libc.so.6 dlpi_addr=0x7f231c6d3000 symtab=0x7f231c6dba48 strtab=0x7f231c6ed700
name=/lib64/ld-linux-x86-64.so.2 dlpi_addr=0x7f231c8cd000 symtab=0x7f231c8cd5a8 strtab=0x7f231c8cd950
```

And here is the result from x86-64 with musl (Alpine running in a docker container):

```
name=/tmp/a.out dlpi_addr=0x5584c21e9000 symtab=0x360 strtab=0x480
name=/lib/ld-musl-x86_64.so.1 dlpi_addr=0x7f81d7c48000 symtab=0x5f90 strtab=0xff68
name= dlpi_addr=0x7ffd1374e000 symtab=0x1c8 strtab=0x300
```

As you can see the values for `strtab` & `symtab` are not virtual addresses but are offsets  when running under musl.

A similar result can be seen on RISC-V when running with glibc (Debian 12):

```
name= dlpi_addr=0xaaaaaabddd3000 symtab=0x300 strtab=0x3f0
name=linux-vdso.so.1 dlpi_addr=0xffffff90686000 symtab=0x198 strtab=0x270
name=/lib/riscv64-linux-gnu/libc.so.6 dlpi_addr=0xffffff9054b000 symtab=0x47e8 strtab=0x158b8
name=/lib/ld-linux-riscv64-lp64d.so.1 dlpi_addr=0xffffff90688000 symtab=0x388 strtab=0x748
```

I also tested with aarch64 on glibc (Debian) and there the values are addresses.

An explanation of why the entries in the dynamic table on RISC-V are not pointers but offsets can be found in the [glibc code](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/generic/ldsodefs.h;h=e8b7359b04a7b86625fb43f5c930c4a168d4bf93;hb=refs/heads/master#l82) and in particular the [RISC-V header](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/riscv/dl-relocate-ld.h;h=7d8704b3c44c88149aa64b59807df4c3786c9121;hb=refs/heads/master#l23). Unfortunately these are headers internal to glibc and so cannot be used to identify when the value is a pointer or offset so a heuristic will be necessary.

**Comment by tvegas1** [comment]
trying to avoid heuristics, apparently from the links provided, we have offsets instead of pointers when either:
- built for riscv, that could be a build flag
- for non riscv: section dynamic is read only applicable to apparently 7 dt_types, (`(ph->p_flags & PF_W) == 0`)

you could confirm (R or RW) on various libraries that you tested using `readelf -e`:
```
  DYNAMIC        0x0000000000045c50 0x0000000000245c50 0x0000000000245c50
                 0x0000000000000240 0x0000000000000240  RW     8
```

ref: https://sourceware.org/pipermail/glibc-cvs/2021q3/075053.html

Built:
```
diff --git a/src/ucm/util/reloc.c b/src/ucm/util/reloc.c
index 8b5b07ce9..2de234d11 100644
--- a/src/ucm/util/reloc.c
+++ b/src/ucm/util/reloc.c
@@ -343,6 +343,7 @@ static ucs_status_t ucm_reloc_dl_info_get(const struct dl_phdr_info *phdr_info,
             found_pt_load  = 1;
         } else if (phdr->p_type == PT_DYNAMIC) {
             /* Found dynamic section */
+            ucm_error(" DYNAMIC!  flag %x -> %x", phdr->p_flags, phdr->p_flags & PF_W);
             dphdr = phdr;
         }
     }
```

**Comment by rbradford** [comment]
Apologies for the delayed response - I've been away.

Unfortunately it looks like the linker for e.g. musl as used by Alpine, etc) marks the dynamic section as writable and still does not relocate the address. Here is the output from an enhanced version of the test program:

```
rockhopper:~/src/symtab-toy$ podman run --rm -v `pwd`:/tmp  frolvlad/alpine-gcc /tmp/a.out
Found dynamic section: writable = yes flags = 0x6
name=/tmp/a.out dlpi_addr=0x5568c668e000 symtab=0x360 strtab=0x480
Found dynamic section: writable = yes flags = 0x6
name=/lib/ld-musl-x86_64.so.1 dlpi_addr=0x7f5780dd5000 symtab=0x5f90 strtab=0xff68
Found dynamic section: writable = no flags = 0x4
name= dlpi_addr=0x7ffe13bdd000 symtab=0x1c8 strtab=0x300
```

This also can't be used for riscv with glibc either as they are also marked as writable and not relocated

```
Found dynamic section: writable = yes flags = 0x6
name= dlpi_addr=0xaaaaaaba499000 symtab=0x300 strtab=0x3f0
Found dynamic section: writable = no flags = 0x4
name=linux-vdso.so.1 dlpi_addr=0xffffffb76a6000 symtab=0x198 strtab=0x270
Found dynamic section: writable = yes flags = 0x6
name=/lib/riscv64-linux-gnu/libc.so.6 dlpi_addr=0xffffffb756b000 symtab=0x47e8 strtab=0x158b8
Found dynamic section: writable = yes flags = 0x6
name=/lib/ld-linux-riscv64-lp64d.so.1 dlpi_addr=0xffffffb76a8000 symtab=0x388 strtab=0x748
```

If you think that supporting non-glibc is out of scope then i'm happy to just update the PR in #9284 to just add the offset when running in RISC-V.

**Comment by tvegas1** [comment]
Seems musl loader might expect offsets regardless, from `decode_dyn()`:
`p->syms = laddr(p, dyn[DT_SYMTAB]);` and `#define laddr(p, v) (void *)((p)->base + (v))`.

So the behavior could be:
- glibc: if p_flags has RO, or if a riscv build: expect offsets for applicable `dt_types`. Else use pointers
- musl: seems to be using offsets

But I think your current proposed heuristic or even only a riscv build flag is more practical than implementing and testing detection scheme above.

**Comment by rbradford** [comment]
> Seems musl loader might expect offsets regardless, from `decode_dyn()`: `p->syms = laddr(p, dyn[DT_SYMTAB]);` and `#define laddr(p, v) (void *)((p)->base + (v))`.
> 
> So the behavior could be:
> 
>     * glibc: if p_flags has RO, or if a riscv build: expect offsets for applicable `dt_types`. Else use pointers
> 
>     * musl: seems to be using offsets
> 
> 
> But I think your current proposed heuristic or even only a riscv build flag is more practical than implementing and testing detection scheme above.

Thanks for your feedback @tvegas1 - in the end I went with a riscv conditional check - https://github.com/openucx/ucx/pull/9168/files#diff-02b0af96939bc77eb57647cbb8a9c14f0ef056bd1bde0767efaf63a60f62cc11R99-R104 and since it was RISC-V specific I pulled it into the general RISC-V PR. I will close #9284.
