### ISSUE TITLE
Clarification: does all ucx recv need to be completed or canceled before finalizing?

### ISSUE THREAD

**Issue by JiakunYan** [openucx/ucx#9323]
We are developing a UCX backend for our system. The communication pattern of the system is dynamic. For now, we just pre-post a bunch of receives. Those receives might or might not be consumed at the end of the program. Then we encountered the following error during the finalization phase:
```
ucp_ep.c:431  Assertion `req->flags & UCP_REQUEST_FLAG_RELEASED' failed
```

We suspected this is due to we did not cancel those pre-post receives before finalizing UCX. Is this a valid suspicion? Does UCX require all receives to be completed or canceled before finalizing?

We do not have a mini ucx program reproducing the error for now. We want to first understand the above questions conceptually before we decide our next steps.

cc @weixuanzh

**Comment by yosefe** [comment]
@JiakunYan yes, currently need to cancel uncompleted receive requests before destroying the worker.

**Comment by JiakunYan** [comment]
@yosefe Thanks! If I just disable the ucs_assert, will I run into other issues with unreleased requests?

**Comment by yosefe** [comment]
There should not be issues since the whole memory pool is released when the worker is released.

**Comment by JiakunYan** [comment]
Thanks! I will close this issue.
