### ISSUE TITLE
IB - Hang on Wakeup-wait after send/recv

### ISSUE THREAD

**Issue by alex--m** [openucx/ucx#934]
A (mellanox-internal) piece of code hangs on waiting for wakeup:

```
ucp_arm();
ucp_progress();
for (some_number_msgs) {
    ucp_probe_nb()
};
…..
epoll_wait() /* This is only be called if there are pending requests */

```

Either one of the following confs "solve" the problem (code doesn’t hang):

```
UCX_FC_ENABLE=N
UCX_RC_FC_WND_SIZE=10
UCX_RC_FC_WND_SIZE=10000
```

The following still cause the test to hang:

```
UCX_RC_FC_WND_SIZE=100
UCX_RC_FC_WND_SIZE=512 (default)
UCX_RC_FC_WND_SIZE=1000
```

One of the suspected sources for this problem were drained events from the completion queue, and draining the CQ happens in two places in UCX:
1.  uct_ud_iface_cq_event (triggered by UD async event handler)
2.  uct_ib_iface_wakeup_arm (called by user to set wakeup)
I tried printing out any (unnecessarily) drained events - none displayed.
Also, the order of calls in the code prevents this from being the potential source of the problem IMO.

**Comment by alex--m** [comment]
Currently I'm looking into this - can assign me.

**Comment by shssf** [comment]
Is `worker_arm()` called just before `epoll_wait()`?
As I understand, if we use UCX wakeup interface we have to use `wakeup_wait()` instead of direct call `epoll()`.
