### ISSUE TITLE
How do I test for RDMA completion on remote side?

### ISSUE THREAD

**Issue by krzikalla** [openucx/ucx#9361]
How can I test on the receiver side, if all the data sent by a `ucp_put_nbx` call has been received? 
To put it in other words: how can `shmem_put_signal_nbi` be implemented using UCX?

**Comment by yosefe** [comment]
could use ucp_put_nbx(data) + ucp_worker_fence + ucp_put_nbx(signal)

**Comment by krzikalla** [comment]
Taken from the docs: "Communication operations issued on a particular endpoint created on the worker prior to this call are guaranteed to be completed before any communication operations issued on the same endpoint after this call."
Thus "completed" means "completed on the remote side" too.

That said, IMHO the `put+fence+put` sequence is horribly inefficient, isn't it?

**Comment by yosefe** [comment]
Yes, there is no more efficient way in the current UCX API.

**Comment by krzikalla** [comment]
Thanks for the quick answer.
