### ISSUE TITLE
after close endpoint, Can I make sure one side operation rdma write can not access remote addr any more?

### ISSUE THREAD

**Issue by haipeng31** [openucx/ucx#9452]
Client and Server build an endpoint.
Server register a MR, and send MR rkey and remote_addr to client
If I Close endpoint at Server side, can I make sure Client side can not access remote addr on server using ucp_put_nb through the closed endpoint anymore?

**Comment by ivankochin** [comment]
Hi, thanks for the question.

Yes, but to achieve that you should set `UCP_EP_PARAM_FIELD_ERR_HANDLING_MODE` bit in `ucp_ep_params_t::field_mask` field and `UCP_ERR_HANDLING_MODE_PEER` to `ucp_ep_params_t::err_mode` field to enable memory invalidation feature.

In that case UCX would guarantee that after closing the endpoint peer wouldn't access the local memory.

**Comment by ivankochin** [comment]
Hi, thanks for the question.

Yes, but to achieve that you should set `UCP_EP_PARAM_FIELD_ERR_HANDLING_MODE` bit in `ucp_ep_params_t::field_mask` field and `UCP_ERR_HANDLING_MODE_PEER` to ` UCX guarantees that after closing the endpoint peer wouldn't access the local memory
