### ISSUE TITLE
scatter-gather list support

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#951]

**Comment by shssf** [comment]
* UCX needs to support sending and receiving several data buffers at one time (single WR)
* It should be implemented similar to `struct iovec` from `<sys/uio.h>`
* Interface of `zcopy` functions family should be changed at this time
Implementation plan:
- [ ] UCT API. High level UCT interface with minor changes in tests and UCP
- [ ] UCT SM/CMA
- [ ] UCT SM/KNEM
- [ ] UCT IB/RC
- [ ] UCT IB/DC
- [ ] UCT IB/UD
- [ ] UCT tests
- [ ] UCP API
- [ ] UCP tests

**Comment by shamisp** [comment]
@shssf - you have to talk with @MattBBaker about ugni. Please add it to the list, since somebody would have to handle this.
