### ISSUE TITLE
jucx 1.15.0 missing arm shared library

### ISSUE THREAD

**Issue by abellina** [openucx/ucx#9523]
@pxli from our team identified an issue in jucx 1.15.0 where the jucx shared library for arm isn't included:

https://github.com/NVIDIA/spark-rapids/issues/7116#issuecomment-1833235334

I am adding this issue to get some help as we'd love to be able to use 1.15.0.1 (?) with our 23.12 release so we can test arm.

@petro-rudenko @yosefe @Alexey-Rivkin

**Comment by artemry-nv** [comment]
For the reference https://github.com/openucx/ucx/pull/9538

**Comment by abellina** [comment]
With the 1.16.0-rc4 jar we see the required shared library and I have confirmed that our smoke tests pass in an arm64 box. Thank you!!!!
