### ISSUE TITLE
Is ucp_request_cancel only support recv request?

### ISSUE THREAD

**Issue by littleneko** [openucx/ucx#9584]
Hi,
I want to cancel a send request if the send not completed for a long time, but I found the cancel routine not take effect for a send request.

And i found the `ucp_request_cancel` only work when req flag `UCP_REQUEST_FLAG_RECV_TAG` has been set.
**So, Is there any way to cancel a send request or set a timeout for a send request?**

```c++
UCS_PROFILE_FUNC_VOID(ucp_request_cancel, (worker, request),
                      ucp_worker_h worker, void *request)
{
    ucp_request_t *req = (ucp_request_t*)request - 1;
    int removed;

    if (req->flags & UCP_REQUEST_FLAG_COMPLETED) {
        return;
    }

    if (req->flags & UCP_REQUEST_FLAG_RECV_TAG) {
        UCP_WORKER_THREAD_CS_ENTER_CONDITIONAL(worker);

        removed = ucp_tag_exp_remove(&worker->tm, req);
        /* If tag posted to the transport need to wait its completion */
        if (removed && !(req->flags & UCP_REQUEST_FLAG_OFFLOADED)) {
            ucp_request_complete_tag_recv(req, UCS_ERR_CANCELED);
        }

        UCP_WORKER_THREAD_CS_EXIT_CONDITIONAL(worker);
    }
}
```

**Comment by yosefe** [comment]
Currently only receive canceling is supported. While it's theoretically possible to cancel sends (for example, when using RNDV protocol, send a RNDV_CANCEL message) it has not been implemented currently. EAGER messages should be completed regardless of remote side progress.
