### ISSUE TITLE
failure with warnings on the hpcc_shmem test

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#961]
There is a failure with oshmem and ucx when running the hpcc_shmem test.
It reproduces on every run and there are warnings that are always printed in the end of the run.
Happens both with dc and rc.
Passes with spml ikrit.

$/hpc/mtr_scrap/users/mtt/scratch/shmem/20160909_014106_26461_100837_vegas25/installs/lKNx/install/bin/oshrun -np 2 -bind-to core -mca btl_openib_warn_default_gid_prefix 0 -report-bindings -display-map -x SHMEM_SYMMETRIC_HEAP_SIZE=128M -mca sshmem_verbs_hca_name mlx5_0:1 -mca btl_openib_if_include mlx5_0:1 -x MXM_RDMA_PORTS=mlx5_0:1 -x UCX_SHM_DEVICES=all -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_ACC_DEVICES=all -mca scoll_mpi_enable 0 -mca scoll basic,mpi -mca coll_hcoll_enable 0 -x HCOLL_POLLING_LEVEL=1 -mca spml ucx -mca pml ucx -x UCX_TLS=dc --map-by node /hpc/mtr_scrap/users/mtt/scratch/shmem/20160909_014106_26461_100837_vegas25/installs/lKNx/tests/hpcc_shmem/hpc_tests.git/hpcc_shmem/ra_shmem
```
 Data for JOB [30955,1] offset 0

 ========================   JOB MAP   ========================

 Data for node: vegas25	Num slots: 16	Max slots: 0	Num procs: 1
 	Process OMPI jobid: [30955,1] App: 0 Process rank: 0 Bound: socket 0[core 0[hwt 0]]:[B/././././././.][./././././././.]

 Data for node: vegas26	Num slots: 16	Max slots: 0	Num procs: 1
 	Process OMPI jobid: [30955,1] App: 0 Process rank: 1 Bound: socket 0[core 0[hwt 0]]:[B/././././././.][./././././././.]

 =============================================================
[vegas26:12597] MCW rank 1 bound to socket 0[core 0[hwt 0]]: [B/././././././.][./././././././.]
[vegas25:22457] MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././.][./././././././.]
Running on 2 processors (PowerofTwo)
Total Main table size = 2^15 = 32768 words
PE Main table size = 2^14 = 16384 words/PE
Default number of updates (RECOMMENDED) = 131072
Real time used = 0.562082 seconds
0.000233190 Billion(10^9) Updates    per second [GUP/s]
0.000116595 Billion(10^9) Updates/PE per second [GUP/s]
Verification:  Real time used = 0.001019 seconds
Found 28158 errors in 32768 locations (failed).
[1473576993.711580] [vegas26:12603:0]          async.c:409  UCX  WARN  async handler table is not empty during exit
[1473576993.711609] [vegas26:12603:0]         thread.c:321  UCX  WARN  async thread still running (use count 2)
[1473576993.711805] [vegas25:22463:0]          async.c:409  UCX  WARN  async handler table is not empty during exit
[1473576993.711818] [vegas25:22463:0]         thread.c:321  UCX  WARN  async thread still running (use count 2)
```

**Comment by yosefe** [comment]
data corruption - may be related to atomic cpu/hw correctness

**Comment by shamisp** [comment]
disable SM and check ? Should not be an issue if you run just with IB.

**Comment by alinask** [comment]
it's only dc in the command line: UCX_TLS=dc

**Comment by shamisp** [comment]
@alinask that it has nothing to do with CPU/HW AMOs

**Comment by alinask** [comment]
@shamisp you meant to try without shared memory?
if so, the failure happens without it.

**Comment by yosefe** [comment]
fixed in https://github.com/open-mpi/ompi/commit/6338ed03234e0f656c745018d70501a574eb766d
