### ISSUE TITLE
UCX 1.17.0RC1 gtest hang

### ISSUE THREAD

**Issue by edgargabriel** [openucx/ucx#9890]
### Describe the bug
While testing UCX 1.17.0RC1 we hit a problem with UCX gtest, which seems to end up in an endless loop during initialization and hangs.

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
  ubuntu 22.04, x86_64 AMD EPYC 7V12
- For RDMA/IB/RoCE related issues:
    - Driver version:
```
$ sudo dpkg -s rdma-core
Package: rdma-core
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 229
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 39.0-1

$ ibstat
CA 'rocep177s0'
        CA type: MT4117
        Number of ports: 1
        Firmware version: 14.25.8102
        Hardware version: 0
        Node GUID: 0xf46b8c6c2f580001
        System image GUID: 0xf46b8c6c2f580001
        Port 1:
                State: Active
                Physical state: LinkUp
                Rate: 40
                Base lid: 0
                LMC: 0
                SM lid: 0
                Capability mask: 0x00010000
                Port GUID: 0xf66b8cfffe6c2f58
                Link layer: Ethernet
```

### Additional information (depending on the issue)
- Output of `ucx_info -d`  attached to ticket

**Comment by edgargabriel** [comment]
[ucx_info.txt](https://github.com/openucx/ucx/files/15390891/ucx_info.txt)

**Comment by shasson5** [comment]
@edgargabriel can specify which gtest are you running? (with full command line)

**Comment by shasson5** [comment]
@evgeny-leksikov can check?

**Comment by edgargabriel** [comment]
Any command line argument will generate the issue on this platform, include just doing ```./gtest```

gtest gets stuck ```uct_test_base::enum_resources()``` (resp. ```uct_md_query_tl_resources``` invoked from there) for the ```gga_mlx5``` tl. For whatever reason the ```component->tl_list``` seems to be ill formed and the loop at https://github.com/openucx/ucx/blob/master/src/uct/base/uct_md.c#L93 never terminates. (I tried to count the number of entries in the tl_list by inserting a ```ucs_list_length()``` in the code, but ```ucs_list_length``` also doesn't return, so its really the list that has an issue)

What is confusing is that the same tl_list looks correct for ```gga_mlx5``` when invoked from ucx_info, so the question is what does gtest do differently than ucx_info when initializing the

**Comment by edgargabriel** [comment]
as an additional data point, running gtest through valgrind memchecker does not show any memory corruption

**Comment by evgeny-leksikov** [comment]
@edgargabriel could you pls share `config.log`?

**Comment by edgargabriel** [comment]
Sure, here it is: 

[config.log](https://github.com/openucx/ucx/files/15404973/config.log)

**Comment by evgeny-leksikov** [comment]
@edgargabriel unfortunally I cannot reproduce the hang on 2 different servers.
Could you please check that you have the same state of the list under gdb (see `// <- comments`):
```
gdb --args ./gtest
...
b uct_tl_register         // <- set break point
r
...
Breakpoint 1, uct_tl_register (component=0x7ffff7a30980 <uct_self_component>, tl=0x7ffff7a30de0 <uct_self_tl>) at ../../../src/uct/base/uct_iface.c:986
d        // <- delete break point
b uct_tl_register if component == &uct_gga_component // <- set conditional break point only for gga TL
r         // re-run to catch only gga related call
...
Breakpoint 2, uct_tl_register (component=0x7ffff713e920 <uct_gga_component>, tl=0x7ffff713ea60 <uct_gga_mlx5_tl>) at ../../../src/uct/base/uct_iface.c:986
986         ucs_list_add_tail(&ucs_config_global_list, &tl->config.list);
(gdb) n
987         ucs_list_add_tail(&component->tl_list, &tl->list);
(gdb) p component->tl_list         // <- here the list is empty
$1 = {
  prev = 0x7ffff713e9d8 <uct_gga_component+184>,
  next = 0x7ffff713e9d8 <uct_gga_component+184>
}
(gdb) p component->tl_list.next          // <- make sure that the list is empty :-)
$2 = (struct ucs_list_link *) 0x7ffff713e9d8 <uct_gga_component+184>
(gdb) n // <- step next to add TL to the list
988     }
(gdb) p component->tl_list
$3 = {
  prev = 0x7ffff713eab8 <uct_gga_mlx5_tl+88>,
  next = 0x7ffff713eab8 <uct_gga_mlx5_tl+88>
}
(gdb) p component->tl_list.next         // <- the entry is added
$4 = (struct ucs_list_link *) 0x7ffff713eab8 <uct_gga_mlx5_tl+88>
(gdb) p component->tl_list.next.next         // <- there is the only 1 entry in the list
$5 = (struct ucs_list_link *) 0x7ffff713e9d8 <uct_gga_component+184>
```
this is what I would expect, I have only one breakpoint hit and checked it on 2 different servers,
if you have the same state, at this point I think you can catch corruption by `watch` gdb command by `component->tl_list.next.next` address (https://sourceware.org/gdb/current/onlinedocs/gdb.html/Set-Watchpoints.html)

let me know if you need help with above, we could have a debug session

**Comment by edgargabriel** [comment]
I think I have multiple hits at that breakpoint, that might be the difference

```
$ gdb --args ./gtest
Reading symbols from ./gtest...
(gdb) break uct_tl_register
Function "uct_tl_register" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (uct_tl_register) pending.
(gdb) run
Starting program: /home/egabriel/ucx-1.17.0/build/test/gtest/gtest
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, uct_tl_register (component=0x7ffff7f2c9c0 <uct_self_component>, tl=0x7ffff7f2ce20 <uct_self_tl>) at ../../../src/uct/base/uct_iface.c:986
986         ucs_list_add_tail(&ucs_config_global_list, &tl->config.list);
(gdb) d 1
(gdb) break uct_tl_register if component == &uct_gga_component
Breakpoint 2 at 0x7ffff7eeb4b4: file ../../../src/uct/base/uct_iface.c, line 986.
(gdb) c
Continuing.

Breakpoint 2, uct_tl_register (component=0x7ffff7bfd940 <uct_gga_component>, tl=0x7ffff7bfda80 <uct_gga_mlx5_tl>) at ../../../src/uct/base/uct_iface.c:986
986         ucs_list_add_tail(&ucs_config_global_list, &tl->config.list);
(gdb) p component->tl_list
$1 = {prev = 0x7ffff7bfd9f8 <uct_gga_component+184>, next = 0x7ffff7bfd9f8 <uct_gga_component+184>}
(gdb) p component->tl_list.next
$2 = (struct ucs_list_link *) 0x7ffff7bfd9f8 <uct_gga_component+184>
(gdb) n
987         ucs_list_add_tail(&component->tl_list, &tl->list);
(gdb)
988     }
(gdb) p component->tl_list
$3 = {prev = 0x7ffff7bfdad8 <uct_gga_mlx5_tl+88>, next = 0x7ffff7bfdad8 <uct_gga_mlx5_tl+88>}
(gdb) p component->tl_list.next
$4 = (struct ucs_list_link *) 0x7ffff7bfdad8 <uct_gga_mlx5_tl+88>
(gdb) p component->tl_list.next.next
$5 = (struct ucs_list_link *) 0x7ffff7bfd9f8 <uct_gga_component+184>
(gdb)
$6 = (struct ucs_list_link *) 0x7ffff7bfd9f8 <uct_gga_component+184>
(gdb) c
Continuing.
[New Thread 0x7fffea5ff640 (LWP 506962)]
[New Thread 0x7fffe9dfe640 (LWP 506963)]
[Thread 0x7fffe9dfe640 (LWP 506963) exited]

Thread 1 "gtest" hit Breakpoint 2, uct_tl_register (component=0x7ffff7bfd940 <uct_gga_component>, tl=0x7ffff7bfda80 <uct_gga_mlx5_tl>) at ../../../src/uct/base/uct_iface.c:986
986         ucs_list_add_tail(&ucs_config_global_list, &tl->config.list);
(gdb) p component->tl_list
$7 = {prev = 0x7ffff7bfdad8 <uct_gga_mlx5_tl+88>, next = 0x7ffff7bfdad8 <uct_gga_mlx5_tl+88>}
(gdb) n
987         ucs_list_add_tail(&component->tl_list, &tl->list);
(gdb)
988     }
(gdb) p component->tl_list
$8 = {prev = 0x7ffff7bfdad8 <uct_gga_mlx5_tl+88>, next = 0x7ffff7bfdad8 <uct_gga_mlx5_tl+88>}
(gdb) p component->tl_list.next
$9 = (struct ucs_list_link *) 0x7ffff7bfdad8 <uct_gga_mlx5_tl+88>
(gdb) p component->tl_list.next.next
$10 = (struct ucs_list_link *) 0x7ffff7bfdad8 <uct_gga_mlx5_tl+88>
(gdb) p component->tl_list.next.next.next
$11 = (struct ucs_list_link *) 0x7ffff7bfdad8 <uct_gga_mlx5_tl+88>
```
I would be open for a joint debug session, lets sync up by email

**Comment by edgargabriel** [comment]
In fact, ```uct_tl_register`` is also invoked twice for uct_ib_component for each tl (uct_dc_mlx5_tl, uct_rc_verbs_tl, uct_rc_mlx5_tl, uct_ud_verbs_tl, uct_ud_mlx5_tl), so its not just uct_gga_component that seems to be registered twice.

Note that uct_tl_register is NOT invoked twice for tcp, self, and the shared memory components, just ib and gga.

**Comment by edgargabriel** [comment]
I will check on the other platform, but just to clarify, you would expect uct_ib_component to be registered twice with uct_dc_mlx5_tl, twice with uct_rc_verbs_tl, etc?

**Comment by evgeny-leksikov** [comment]
ah.. sorry, I missed that, the difference ib and gga components from others is they both placed in `libuct_ib.so` and loaded from lib constructor, probably by some reason it was loaded twice?

**Comment by evgeny-leksikov** [comment]
@edgargabriel I found the difference in our `config.log`:
on my system I have:
```
$ cat ./config.log | grep runpath
lt_cv_shlibpath_overrides_runpath=no
```
in your `config.log` I see:
```
lt_cv_shlibpath_overrides_runpath=yes
```
So, on your system `$LD_LIBRARY_PATH=<ucx_install_dir>` takes unexpected effect and loads `libuc<s|m|t|p>.so` from there and additionally `libuct_ib.so` from `<build>` directory since gtest has it in direct dependencies.
As a workaround you can add `LDFLAGS=-Wl,--disable-new-dtags` to `configure` command to force using `rpath` and disable  `runpath`

@yosefe I think we should disable `runpath` for gtest by default. From my understanding <rpath|runpath> defaults may depend on many factors like versions of libtool, gcc, OS, etc. Since we cannot control everything, gtest should always use `.so`'s which it's compiled with because we use many internals there for testing and avoid double loading of internal modules like `libuct_ib.so`
