### ISSUE TITLE
Condition "status == UCS_OK" is always true when reached.

### ISSUE THREAD

**Issue by maxim-banaev** [openucx/ucx#9945]
https://github.com/openucx/ucx/blob/ab1aa5102b0cdec8bf9ed05487db02282edd91f3/src/ucp/rma/amo_sw.c#L87C33-L87C49

**Comment by tvegas1** [comment]
If I get your report right, seems `ucp_rma_sw_do_am_bcopy()` can return < 0 as `uct_ep_send_bcopy()` returns a `ssize_t`. So `status == UCS_OK` is not true in that case.

**Comment by brminich** [comment]
afaiu, report says that this line:
`if ((status != UCS_OK) || ((status == UCS_OK) && !fetch)) {`
can be replaced by this one:
`if ((status != UCS_OK) ||  !fetch) {`

**Comment by maxim-banaev** [comment]
@tvegas1 thanks for your reply and sorry for lack of explanation. Indeed the `status` can different than `UCS_OK`. My concern over the condition itself. 

I see that condition `if ((status != UCS_OK) || ((status == UCS_OK) && !fetch))`. If I understand correctly the `!fetch` checked here only if `status` is `UCS_OK`. So the whole condition can be simplified to `if (status != UCS_OK ||  !fetch)` without loosing the logic.
