### ISSUE TITLE
mlx5 connect on mlx5_1 failed: Connection timed out

### ISSUE THREAD

**Issue by shinoharakazuya** [openucx/ucx#9970]
Hello

I'm running NGC's hpl benchmark test from Slurm. When I ran hpl in an hpl container on two servers with 8 GPUs per node, I encountered a UCX error. Someone please help me.

root@node1:~$ sbatch hpl.sh
root@node1:~$ less slurm-441.out
---
[log.txt](https://github.com/user-attachments/files/15942950/log.txt)

[1719157763.321281] [node2:19381:0]       ib_device.c:1163 UCX  ERROR   ibv_create_ah(dlid=49152 sl=0 port=1 src_path_bits=0 dgid=::ffff:172.16.0.2 flow_label=0xffffffff sgid_index=3 traffic_class=106) for UD mlx5 connect on mlx5_1 failed: Connection timed out
[node2:19381] pml_ucx.c:424  Error: ucp_ep_create(proc=2) failed: Endpoint timeout
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  PML add procs failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
[node2:19381] *** An error occurred in MPI_Init
[node2:19381] *** reported by process [3710458193,3]
[node2:19381] *** on a NULL communicator
[node2:19381] *** Unknown error
[node2:19381] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[node2:19381] ***    and potentially your MPI job)
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 441.0 ON node1 CANCELLED AT 2024-06-23T15:49:23 ***
[1719157762.357955] [node2:19369:0]        ib_iface.c:844  UCX  DEBUG   iface 0x56101c979230: ah_attr dlid=49152 sl=0 port=1 src_[1719157762.720648] [node1:22268:0]        ib_iface.c:844  UCX  DEBUG   iface 0x563c6778e1c0: ah_attr dlid=49152 sl=0 port=1 s[1719157762.720648] [node1:22280:0]        ib_iface.c:844  UCX  DEBUG   iface 0x55cfa6b1f250: ah_attr dlid=49152 sl=0 port=1 ssrun: error: node2: tasks 2-3: Killed
slurmstepd: error:  mpi/pmix_v5: _errhandler: node1 [0]: pmixp_client_v2.c:211: Error handler invoked: status = -61, source = [slurm.pmix.441.0:0]
srun: error: node1: tasks 0-1: Killed

**Comment by yosefe** [comment]
Can you pls post the full information in the bug report form https://github.com/openucx/ucx/issues/new?assignees=&labels=Bug&projects=&template=bug_report.md&title=
Plus the output of `show_gids` command?
It's possible need to set a specific GID index (by UCX_IB_GID_INDEX env var) on the given setup

**Comment by yosefe** [comment]
replaced by #9971
